[Core] Included files in json
KratosMultiphysics/Kratos pull request #10004
Opened 2022-07-07 10:42 UTC by AriadnaCortesDanes

**📝 Description**
Allows json files to include other json files using the keyword "@include_json" (issue #6815). The code adds a post-process to the original json data, and substitutes "@include_json" entries by the contents of the new json file especified. 

Just to illustrate. If we have a first json: 
`{
"data1" : "hello",
"@include_json" : "foo.json",
"data2" : 2.0
}`

and the file foo.json contains:
`{
"data3" :  3.0,
"data4" : 4.0
}`

the final processed data would be equivalent as if we had:  
`{
"data1" : "hello",
"data2" : 2.0,
"data3" :  3.0,
"data4" : 4.0
}`

Note that the function is recursive in the number of includes.

**🆕 Changelog**
- Added a function (and header) in order to read a json file
- Added a function (and header) in order to post-process the json data
- Added corresponding tests

2022-07-07 10:46 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> +#include <stack>
This is not external dependency, it goes in the upper one

2022-07-07 10:47 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> +nlohmann::json Parameters::ReadFile(std::string file_name) {
Input is always CammelCase
```suggestion
nlohmann::json Parameters::ReadFile(std::string FileName) {
```

2022-07-07 10:47 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> +void Parameters::SolveIncludes(nlohmann::json& rJson) {
```suggestion
void Parameters::SolveIncludes(nlohmann::json& rJson) 
{
```
Style

2022-07-07 10:48 UTC, loumalouomega commented on kratos/includes/kratos_parameters.h
> +    //aqui?
```suggestion
```
I assume it is a leftover

2022-07-07 10:48 UTC, loumalouomega requested changes
Some comments. Implementation simple and elegant

2022-07-07 10:49 UTC, loumalouomega commented on kratos/includes/kratos_parameters.h
> +    nlohmann::json ReadFile(std::string file_name);
```suggestion
    nlohmann::json ReadFile(std::string FileName);
```

2022-07-07 10:50 UTC, loumalouomega submitted a review, later dismissed

2022-07-07 12:13 UTC, loumalouomega approved these changes, later dismissed

2022-07-07 12:40 UTC, pooyan-dadvand commented
I think this needs the approval of the @KratosMultiphysics/technical-committee as a generic core feature

2022-07-07 14:36 UTC, loumalouomega commented
New test are failing

2022-07-07 14:36 UTC, loumalouomega requested changes
Blocking until @KratosMultiphysics/technical-committee agrees

2022-07-08 11:46 UTC, matekelemen commented
Should circular includes be checked or is this something we don't worry about?

2022-07-08 12:41 UTC, roigcarlo commented
> Should circular includes be checked or is this something we don't worry about?

We should totally check that if we do not

2022-07-09 12:54 UTC, matekelemen commented
> We should totally check that if we do not

I can do that but we should probably get the tests working first. I don't want to commit to this PR without approval so I'll use [another branch](https://github.com/KratosMultiphysics/Kratos/compare/core/included-files-in-json...core/acyclic-json-links?w=1) in the meantime.

> New test are failing

The problem is with the [path to the included json](https://github.com/KratosMultiphysics/Kratos/blob/77f365ce8184ef92b9fc50c0126cbffb9ca82ef2/kratos/tests/cpp_tests/sources/test_kratos_parameters.cpp#L274). Kratos implements tools for changing the working directory during testing for python scripts, so the filesystem can be safely navigated, but there's no such infrastructure for cpp tests.

I vaguely remember someone working on a unified test interface for cpp and python tests, which would be a good place to implement working directory manipulation. Does anyone know anything about the status of that project?

2022-07-10 14:15 UTC, roigcarlo commented
> I can do that but we should probably get the tests working first. I don't want to commit to this PR without approval so I'll use [another branch](https://github.com/KratosMultiphysics/Kratos/compare/core/included-files-in-json...core/acyclic-json-links?w=1) in the meantime.

👍 

>  Kratos implements tools for changing the working directory during testing for python scripts, so the filesystem can be safely navigated, but there's no such infrastructure for cpp tests

You should be able to use `Kratos::CurrentWorkingDirectory()` it should be a wrapper for `boost/std::filesystem::current_path` (https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/kratos_filesystem.h) and move from there. Its an external lib now but it will be part of c++17 when we move and we have an abstract interface for it so you will not notice any diference

2022-07-11 08:51 UTC, matekelemen commented
Ready for review.

(No idea what's happening on CentOS but I doubt it's related to this PR)

2022-07-22 07:30 UTC, roigcarlo commented
@KratosMultiphysics/technical-committee Agrees with the changes, but @pooyan-dadvand will make a final review before approving. Gj!

2022-08-12 09:18 UTC, ddiezrod commented
any advance on this?

2022-08-12 09:22 UTC, loumalouomega commented
> any advance on this?

I think we are waiting for @pooyan-dadvand final review

2022-09-06 10:11 UTC, pooyan-dadvand commented
@mpentek Why you store the `adjacency_list`? Why you are not only checking the stack to see if you have the same entry somewhere there?

2022-09-09 16:29 UTC, matekelemen commented
> Why you store the adjacency_list? Why you are not only checking the stack to see if you have the same entry somewhere there?

The stack's purpose is to help navigating the JSON structure, not to store ```@include_json``` entries. It stores nested json objects so it can't be used to check for included file names.

Moreover, having duplicate includes doesn't necessarily mean that there's a cycle in the include graph, which is part of the reason why we need a full graph representation of the include structure. That's what ```adjacency_list``` (or ```rAdjacencyMap```) is for.

2022-09-12 16:25 UTC, pooyan-dadvand commented
I understand that we can include the same file in different places but that should not appear in the stack twice. So still checking the filename in the stack should be valid. 

In other word, the stack of the calls would be the same as the adjacency map from the root to the given leaf. So I think we can use it to travers the map without really creating map.

2022-09-13 21:23 UTC, matekelemen commented
@pooyan-dadvand ok so you don't mean [this stack](https://github.com/KratosMultiphysics/Kratos/blob/c272bd3acd0e46aaf7ed9ce01ab62ce0831abc64/kratos/sources/kratos_parameters.cpp#L345), but rather your suggestion is to replace [the adjacency map](https://github.com/KratosMultiphysics/Kratos/blob/c272bd3acd0e46aaf7ed9ce01ab62ce0831abc64/kratos/sources/kratos_parameters.cpp#L236) with **a** stack that only contains the current sequence of included files? I can see that working.

2022-09-14 12:00 UTC, philbucher commented on kratos/includes/kratos_filesystem.h
> +std::string ResolveSymlinks(const std::string& rPath);
Can you please make a separate PR for this?
I have some comments

2022-09-28 10:38 UTC, pooyan-dadvand commented
@matekelemen thanks for the confirmation. I think stack would be a better choice. And also we can keep track of the include file paths in the same stack of the call. But if you prefer a separate stack I would not oppose it.

@AriadnaCortesDanes would you please proceed with this change?

2022-09-28 11:14 UTC, matekelemen commented
> I think stack would be a better choice. And also we can keep track of the include file paths in the same stack of the call.

I'm afraid I don't know how to do that :(

> But if you prefer a separate stack I would not oppose it.

@pooyan-dadvand it's already implemented via cbc87dba43ecc1e185641d6288178fa25fb89d1a.

2022-09-28 13:40 UTC, pooyan-dadvand commented on kratos/includes/kratos_parameters.h
> +#include <map>
Do we need this one?

2022-09-28 13:42 UTC, pooyan-dadvand approved these changes, later dismissed
I think the current stack implementation for the cyclic dependency is ok. So let's go with it!

2022-09-28 14:29 UTC, matekelemen commented on kratos/includes/kratos_parameters.h
> +#include <map>
Nope, good catch!

2022-09-29 07:19 UTC, philbucher reviewed
lets make use of C++17 since we now finally have it :tada:

2022-09-29 07:19 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +    void SolveIncludes(nlohmann::json& rJson, const std::string& rFileName, std::vector<std::string>& rIncludeSequence);
```suggestion
    void SolveIncludes(nlohmann::json& rJson, const std::filesystem::path& rFileName, std::vector<std::string>& rIncludeSequence);
```

2022-09-29 07:19 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +    nlohmann::json ReadFile(std::string FileName);
```suggestion
    nlohmann::json ReadFile(const std::filesystem::path& rFileName);
```

2022-09-30 09:52 UTC, pooyan-dadvand commented
Seems that windows didn't liked the file system. Maybe a merge from master is needed.

2022-09-30 10:01 UTC, loumalouomega commented
> Seems that windows didn't liked the file system. Maybe a merge from master is needed.

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include\iterator(151,27): error C2039: 'insert': is not a member of 'std::filesystem::path' [D:\a\Kratos\Kratos\build\Custom\kratos\KratosCore.vcxproj] 

Looks like this is the problem

2022-09-30 11:03 UTC, matekelemen commented
I'm not quite sure what the problem is but I'll only be able to take a look at it during the weekend. I'll let you know when I fixed it.

2022-09-30 16:42 UTC, matekelemen commented
@pooyan-dadvand ok looks like MSVC's satisfied too.

### Details

For anyone who later might fall into the same trap with ```string```s and ```path```s, here's what was wrong:

Unlike any sane toolchain, MSVC's implementation of the standard library stores the data of an ```std::filesystem::path``` in a ```std::wstring``` internally instead of a normal ```std::string```. You might not have noticed this, because implicit conversions between STL types are well implemented and have no ADL-related issues since they're all within the same namespace.

However, if a class outside the ```std``` namespace implements ```operator std::string``` but not ```operator std::wstring``` (such as the ```nlohmann::basic_json``` class), the conversion on MSVC will fail because it'd have to cast through the following chain: ```your_class``` => ```std::string``` => ```std::wstring``` => ```std::filesystem::path```. Solution: explicitly cast your type to something in the ```std``` namespace, and then construct an ```std::filesystem::path``` from that. Thank you Microsoft!

2022-10-02 15:35 UTC, philbucher commented
:window: :man_facepalming:

2022-10-03 07:56 UTC, pooyan-dadvand approved these changes
Thank you all!

2022-10-03 11:09 UTC, pooyan-dadvand commented
@loumalouomega would you please check if you can unblock the PR?

2022-10-03 11:10 UTC, loumalouomega approved these changes
Approving

2022-10-03 11:10 UTC, loumalouomega commented
> @loumalouomega would you please check if you can unblock the PR?

Done

2022-10-03 14:49 UTC, merged