[FastPR][Core] Minor improvement in automatic differentiation utilities
KratosMultiphysics/Kratos pull request #10022
Opened 2022-07-12 15:37 UTC by rubenzorrilla

**📝 Description**
I've experienced some weird things when using the `DoubleContraction` implemented in the `sympy_fe_utilities.py` with symbolic arrays. These are caused by the `rank` function, which is not returning the expected value. Besides, it is extremely slow. Instead, the length of the matrix shape can be used.

2022-07-12 20:50 UTC, matekelemen commented
um, I'm guessing ```A.rank()``` refers to the [rank of the matrix in a linear algebraic sense](https://en.m.wikipedia.org/wiki/Rank_(linear_algebra)), which can be an intensive task to compute on a large symbolic matrix.

2022-07-13 07:20 UTC, rubenzorrilla commented
> um, I'm guessing `A.rank()` refers to the [rank of the matrix in a linear algebraic sense](https://en.m.wikipedia.org/wiki/Rank_(linear_algebra)), which can be an intensive task to compute on a large symbolic matrix.

Yes. Clearly is due to this. Besides in this context it makes no sense to use the rank of the matrix as we only need the sizes to do the contractions from the products of the outer tensors.

2022-07-13 08:26 UTC, sunethwarna requested changes
This is fine for me except for the print(i)

2022-07-13 08:26 UTC, sunethwarna commented on kratos/python_scripts/sympy_fe_utilities.py
> +        print(i)
```suggestion
```

This can be removed ryt?

2022-07-13 08:41 UTC, rubenzorrilla commented on kratos/python_scripts/sympy_fe_utilities.py
> +        print(i)
Ouch. Thanks for spotting.

2022-07-13 09:21 UTC, RiccardoRossi approved these changes
this is ok to me, with the only comment (also for myself) that this will only work for square tensors

not sure if in the future it makes sense to extend to the case of nonsquare tensors

2022-07-13 12:07 UTC, rubenzorrilla commented
@sunethwarna we need you to unblock this.

2022-07-13 12:51 UTC, sunethwarna approved these changes
👍

2022-07-13 13:01 UTC, merged