Bug fix in Thermal DEM App
KratosMultiphysics/Kratos pull request #10088
Opened 2022-07-29 13:30 UTC by rlrangel

2022-07-30 10:27 UTC, AlejandroCornejo commented
Since it only affects your App, ok!

just pinging @AFranci , @maceligueta and @KratosMultiphysics/technical-committee to inform them that this issue can happen in other tetgen dependent apps

2022-07-30 10:30 UTC, AlejandroCornejo requested changes

2022-07-30 10:30 UTC, AlejandroCornejo commented on applications/ThermalDEMApplication/CMakeLists.txt
> +## kratos_add_dependency(${KRATOS_SOURCE_DIR}/applications/DelaunayMeshingApplication) ## UNCOMMENT TO GET TETGEN FROM DELAUNAY_MESHING APPLICATION
maybe is it better to solve directly the DelaunayApp? @KratosMultiphysics/technical-committee

2022-07-30 10:30 UTC, AlejandroCornejo commented on applications/ThermalDEMApplication/external_libraries/tetgen/example.poly
> +3  2  2  0  1
what is the purpose of this?

2022-08-22 15:58 UTC, rubenzorrilla commented
> We cannot add tetgen to the repository. Those files should be removed. Tetgen options must be activated so that it gets downloaded and compiled automatically. I thought that was already solved in the Delaunay App. See https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md#tpl-libraries

That's the main point. @roigcarlo would you mind keeping track of this on behalf of the @KratosMultiphysics/technical-committee ?

2022-08-22 18:22 UTC, roigcarlo requested changes
Blocking as well. Under no circumstance we can allow tetgen code in the repo.

If tetgen is needed it needs to be included via the usage of any of the flavours of `USE_TETGEN_NONFREE_TPL` as explained [here](https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md#tetgen)

Also please provide a description of the changes in the PR description as otherwise is hard to keep track of them (we have some automated systems that depen on this).

Finally, if you remove tetgen directly in this PR, when eventually merging, please use the `merge and squash` as this will prevent tetgen files appearing in the history as well.

2022-08-22 19:24 UTC, rlrangel commented
Sorry for not adding a proper title and description to the PR.
I have just uploaded them.

I was not aware that the TetGen files cannot be added to the repo (is it related to license?)

I will later check these links to see if there is a solution to my issue.
If not, I currently have no clue on how to solve.

2022-08-22 20:43 UTC, roigcarlo commented
@rlrangel Yep its because tetgen licence invalidates BSD... for us is not strictly a problem but as long as someone needs to integrate Kratos in their code it becomes an ordeal.

We created the macro for that, so that you can include tetgen without having it into the repo, I think there is a PR currently open with a similar scenario (#10127) You can take a look at how they are including tetgen. The CMakes for the meshing application should give yo an idea as well.

P.s. Thanks for updatin the description!

2022-08-23 03:10 UTC, rlrangel commented
Thanks for the clarifications @roigcarlo.

I think this PR can be closed.

2022-08-23 09:04 UTC, rubenzorrilla commented
Closing as suggested by @rlrangel.

2022-08-23 09:04 UTC, closed without merging