Fix various typos in doxygen and misc. source comments
KratosMultiphysics/Kratos pull request #10112
Opened 2022-08-07 20:58 UTC by luzpaz

---
name: 🗎 Documentation and Styling
about: Adding or modifying **documentation** or **code style**.

---

**Description**

Fixing typos in doxygen and cleaning up varioys typos in source comments

**Changelog**

-Fixed doxygen and source comment typos

2022-08-08 06:39 UTC, loumalouomega commented on kratos/python_scripts/application_generator/classes/classCreator.py
> -            members: list of 'KratosClasMemeber'
I prefer Memeber...

2022-08-08 06:41 UTC, loumalouomega submitted a review, later dismissed
Just comments, so a priori the code is not affected. Thanks

2022-08-08 06:43 UTC, loumalouomega commented
> Just comments, so a priori the code is not affected. Thanks

AS this is your first contribution, it also requires the approval of a maintainer. Therefore, @KratosMultiphysics/technical-committee. @roigcarlo can you take a look?

2022-08-15 11:03 UTC, luzpaz commented
soft bump

2022-08-15 16:10 UTC, rubenzorrilla approved these changes, later dismissed
Many thanks!

2022-08-15 20:18 UTC, loumalouomega commented
There is a conflict that must be solved

2022-08-15 20:56 UTC, luzpaz commented
Conflict solved. Rebased

2022-08-15 21:16 UTC, loumalouomega requested changes
Please move to kratos/python_scripts/testing/run_tests.py

2022-08-16 00:11 UTC, luzpaz commented
Rebased on master.

> Please move to kratos/python_scripts/testing/run_tests.py

@loumalouomega that file doesn't exist on this branch.

![Screenshot_20220815_201120](https://user-images.githubusercontent.com/4140247/184756987-30b866d6-21e7-42ec-985d-d97580cd83b6.png)

2022-08-16 06:14 UTC, loumalouomega commented
> Rebased on master.
> 
> > Please move to kratos/python_scripts/testing/run_tests.py
> 
> @loumalouomega that file doesn't exist on this branch.
> 
> ![Screenshot_20220815_201120](https://user-images.githubusercontent.com/4140247/184756987-30b866d6-21e7-42ec-985d-d97580cd83b6.png)

Because you solve the conflict in a wrong manner. Please, add manually the file, with the corresponding corrections and I will allow the merge

2022-08-16 11:26 UTC, luzpaz commented
> Because you solve the conflict in a wrong manner. Please, add manually the file, with the corresponding corrections and I will allow the merge

:facepalm: so sorry! Have no idea how that happened. That's actually never happened to me before until now. Reverted in 28e403d

2022-08-16 11:27 UTC, loumalouomega approved these changes, later dismissed

2022-08-31 19:39 UTC, luzpaz commented
shall i rebase?

2022-09-01 06:03 UTC, loumalouomega commented
> shall i rebase?

Wait until CI passes and just merge

2022-09-01 06:04 UTC, loumalouomega submitted a review, later dismissed

2022-11-28 17:53 UTC, luzpaz commented
Let me know if rebase is needed

2023-02-28 13:04 UTC, roigcarlo commented
Can someone re-aprove?

2023-02-28 13:52 UTC, loumalouomega approved these changes

2023-02-28 15:25 UTC, merged

2023-02-28 15:25 UTC, roigcarlo commented
I will try to merge these as they were already approved from long ago