[PfemFluid] [Proposal] Print GiD output into gid_output folder
KratosMultiphysics/Kratos pull request #10213
Opened 2022-09-01 16:32 UTC by miguelmaso

**📝 Description**
This helps to keep files tidy

The behavior is modified, but anything is broken.

**🆕 Changelog**
- Added `gid_output` folder

2022-09-02 09:26 UTC, jginternational requested changes
There is a field in the json parameters for that

2022-09-02 10:02 UTC, miguelmaso commented
> There is a field in the json parameters for that
> 
> ![image](https://user-images.githubusercontent.com/5918085/188109671-a990136d-baf9-4f92-8f39-7aaa37388f2c.png)

In this case, you're constructing the `GiDOutputProcess` using the standard mechanism. However, the PFEM problemtype implements its own mechanism:
```jsonc
{
    "problem_data"         : {
        "problem_name"   : "pfem",
        "start_time"     : 0.0,
        "end_time"       : 1.0,
        "echo_level"     : 0,
        "parallel_type"  : "OpenMP",
        "threads"        : 1,
        "gravity_vector" : [0.0,-9.81,0.0]
    },
    // more settings...
    "output_configuration" : {
        "result_file_configuration" : {
            "gidpost_flags"               : {
                "GiDPostMode"           : "GiD_PostBinary",
                "WriteDeformedMeshFlag" : "WriteDeformed",
                "WriteConditionsFlag"   : "WriteConditions",
                "MultiFileFlag"         : "MultipleFiles"
            },
            "file_label"                  : "time",
            "output_control_type"         : "time",
            "output_interval"             : 0.1,
            "body_output"                 : true,
            "node_output"                 : true,
            "skin_output"                 : false,
            "plane_output"                : [],
            "nodal_results"               : ["VELOCITY","PRESSURE"],
            "gauss_point_results"         : [],
            "nodal_nonhistorical_results" : []
        },
        "point_data_configuration"  : []
    }
}
```

The optimal solution would be to use the standard mechanism and set the filed you're pointing. But it requires a modification of the PFEM AnalysisStage (Kratos repo) and a modification of the PFEM problemtype (GiDInterface repo). Out of the scope of this PR...

2022-09-02 13:09 UTC, miguelmaso commented
see #8408

2022-09-06 09:00 UTC, AFranci approved these changes

2022-09-27 08:38 UTC, jginternational approved these changes

2022-09-27 12:17 UTC, merged