added changes to improve entities_utilities
KratosMultiphysics/Kratos pull request #10309
Opened 2022-09-23 15:18 UTC by mcgicjn2

**📝 Description**
Improving the initialization and finalization of entities to only include those that entities that are active during the solutionstep. Originally implemented by @Vahid-Galavi.

**🆕 Changelog**
- Added active check to entitie for initialize and finalize solution step.

2022-09-23 15:39 UTC, rubenzorrilla commented on kratos/utilities/entities_utilities.h
> +
```suggestion
```
This will be extremely verbose.

2022-09-23 15:55 UTC, loumalouomega commented on kratos/utilities/entities_utilities.h
> +
Indeed

2022-10-23 14:31 UTC, RiccardoRossi requested changes
the current behaviour is consistent with the one of the builder and solver, so i am afraid we cannot change it easily.

@KratosMultiphysics/technical-committee opinions?

2023-01-31 07:33 UTC, mcgicjn2 commented
As this is a stale branch and the functionality appears not to be required on our side. Perhaps we can close this and related branches I.e. #10265

2023-01-31 07:34 UTC, mcgicjn2 commented
Closing

2023-01-31 07:34 UTC, closed without merging