[Core] Consistent number retrieve in Parameters
KratosMultiphysics/Kratos pull request #10303
Opened 2022-09-23 07:51 UTC by loumalouomega

**📝 Description**

Fixes #10302. This makes consistent the `Is` and `Get` methods for double and integers

**🆕 Changelog**

- [Consistent number retrieve in Parameters](https://github.com/KratosMultiphysics/Kratos/commit/ed07f9dfcd8f884dba71c506e2b875eec18d05ba)

2022-09-23 08:00 UTC, matekelemen reviewed
Fine by me, but this is technically a behaviour change and will break a couple of tests (speaking from experience 😢).

2022-09-23 08:02 UTC, loumalouomega commented
> Fine by me, but this is technically a behaviour change and will break a couple of tests (speaking from experience 😢).

I know, but this is more consistent, otherwise we can do what you suggest, but it will be more inconsistent.

2022-09-23 11:31 UTC, RiccardoRossi requested changes
blocking since you are chaning the behaviour while the current one is by design

2022-09-23 11:34 UTC, loumalouomega commented
> blocking since you are chaning the behaviour while the current one is by design

Yes I know, see my comment

2022-09-23 12:22 UTC, loumalouomega commented
I applied @matekelemen suggestion

2022-09-23 14:32 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> +    KRATOS_ERROR_IF_NOT(mpValue->is_number_integer()) << "Argument must be an integer number" << std::endl;
```suggestion
    KRATOS_ERROR_IF_NOT(mpValue->is_number()) << "Argument must be a number" << std::endl;
```
Revert

2022-09-27 08:49 UTC, loumalouomega commented
@RiccardoRossi @matekelemen are we happy with the proposal changes?

2022-09-27 10:11 UTC, RiccardoRossi commented on kratos/sources/kratos_parameters.cpp
> -    return mpValue->is_number_float();
why are u changing this?

it was correct before...

in essence getDouble is like doing a static_cast<double>

2022-09-27 10:12 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> -    return mpValue->is_number_float();
See https://github.com/KratosMultiphysics/Kratos/issues/10302

2022-09-27 14:16 UTC, loumalouomega commented on kratos/sources/kratos_parameters.cpp
> -    return mpValue->is_number_float();
In addition to that, there is a comment in the change

2022-09-28 07:41 UTC, matekelemen reviewed
This is exactly what I want so I'm happy with it, but it's ultimately up to what the technical committee thinks.

The reason why I think this is the way to go is validation: if we want to catch bugs due to misconfiguration as early as possible, the first thing we can do is validate the input each object gets. If we ever want to implement a robust input validation scheme, we need consistent, logical system, and a clear separation of responsibilities.

```Parameters``` is our de-facto input interface, so imagine we want to instantiate an object with it. ```Parameters``` cannot validate the **value** of each of its items (that's the object's responsibility), but it *can* validate their **types** based on a default ```Parameters``` instance for the given object. Systematically, if an input passes type validation, the object doesn't have to check that again and can continue validating the **values** of the items within. For this to be reliable though, we need to be consistent about querying the *type* of an item (```Parameters::Is...()```) and parsing its *value* (```Parameters::Get...()```).

The current behaviour in master is that ```Parameters::IsInt()``` and ```Parameters::IsDouble()``` can fail while ```Parameters::GetInt()``` and ```Parameters::GetDouble()``` succeed for the same input. As a result, if we want add systematic validation to existing objects, they'll likely break tests/user scripts that otherwise work correctly. To avoid that, we need to implement workarounds for ```int``` and ```double```, which leads to code duplication, increased complexity, and makes maintenance more painful.

2022-09-28 07:55 UTC, loumalouomega commented
> This is exactly what I want so I'm happy with it, but it's ultimately up to what the technical committee thinks.
> 
> The reason why I think this is the way to go is validation: if we want to catch bugs due to misconfiguration as early as possible, the first thing we can do is validate the input each object gets. If we ever want to implement a robust input validation scheme, we need a consistent, logical system, and a clear separation of responsibilities.
> 
> `Parameters` is our de-facto input interface, so imagine we want to instantiate an object with it. `Parameters` cannot validate the **value** of each of its items (that's the object's responsibility), but it _can_ validate their **types** based on a default `Parameters` instance for the given object. Systematically, if an input passes **type** validation, the object doesn't have to check that again and can continue validating the **values** of the items within. For this to be reliable though, we need to be consistent about querying the **type** of an item (`Parameters::Is...()`) and parsing its **value** (`Parameters::Get...()`).
> 
> The current behaviour in master is that `Parameters::IsInt()` and `Parameters::IsDouble()` can fail while `Parameters::GetInt()` and `Parameters::GetDouble()` succeed for the same input. As a result, if we want to add systematic validation to existing objects, they'll likely break tests/user scripts that otherwise work correctly. To avoid that, we need to implement workarounds for `int` and `double`, which leads to code duplication, increased complexity, and makes maintenance more painful.

Thanks for the explanation FYI @RiccardoRossi

2022-10-03 12:13 UTC, loumalouomega commented
As #10302 is closed I close this

2022-10-03 12:16 UTC, RiccardoRossi commented
well here i added only my point of view. mentioning @KratosMultiphysics/technical-committee in case the view is different

2022-11-21 10:48 UTC, loumalouomega commented
Any agreement? @RiccardoRossi

2022-12-30 09:14 UTC, loumalouomega commented
> Any agreement? @RiccardoRossi

Hello 👋

2023-03-03 10:25 UTC, RiccardoRossi reviewed
@KratosMultiphysics/technical-committee  agrees that a double is a double and an int is not ... 

that is, sorry but we disagree with this behaviour change

2023-03-03 11:19 UTC, closed without merging