[PfemFluid] Multiple refining boxes in 2D and 3D
KratosMultiphysics/Kratos pull request #10386
Opened 2022-10-21 09:23 UTC by AFranci

This PR introduces the possibility of defining multiple refining boxes. The parameters to set are the limit coordinates of the box, the initial and final times, and the number of elements in the transition from the fine mesh to the coarse one. The mesh size of the different zones (especially the transition zones) is set inside mesher_utilities.cpp (before it was duplicated and not optimized). This value is used by the three main remeshing processes (alpah shape, generatation and removal of nodes).

2022-10-21 09:35 UTC, AlejandroCornejo requested changes

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.cpp
> +              const double radius = pow(distanceToBoxX, 2) + pow(distanceToBoxY, 2);
we usually use std::pow and std::sqrt

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.cpp
> +              distanceToBox = sqrt(radius);
std::

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.cpp
> +              const double radius = pow(distanceToBoxX, 2) + pow(distanceToBoxY, 2);
std

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.cpp
> +                const double radius = pow(distanceToBoxX, 2) + pow(distanceToBoxY, 2) + pow(distanceToBoxZ, 2);
idem

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.cpp
> +                distanceToBox = sqrt(radius);
idfem

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_utilities/mesher_utilities.hpp
> +                        RefiningBoxMinimumPoint.resize(size);
`resize(size, false)` is faster

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
> +				NewPositions.resize(0);
,false

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
> +				const double tolerance = 1.8;
interesting tolerance

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
>  			array_1d<unsigned int, 3> FirstEdgeNode(3, 0);
const?

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
> +				const double tolerance = 1.8;
if repeatred you could define this tolerance in the .h file as a const expr

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/generate_new_nodes_before_meshing_process.hpp
> +				penalization = 1.2; // to avoid to gain too much volume during remeshing step
alquimist :D

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/remove_mesh_nodes_for_fluids_process.hpp
>  				// if (mrRemesh.Refine->RemovingOptions.Is(MesherUtilities::REMOVE_NODES_ON_ERROR))
remove unused code?

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/remove_mesh_nodes_for_fluids_process.hpp
>  					if ((ie->GetGeometry()[i].Is(RIGID) && ie->GetGeometry()[i].IsNot(INLET)) || ie->GetGeometry()[i].Is(SOLID))
you can declar a `const auto& r_geometry = GetGeometry()` and the reuse the `r_geometry`

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/select_mesh_elements_for_fluids_process.hpp
> +                                                                  (sqrt(pow(nodesVelocities[0][0], 2) + pow(nodesVelocities[0][1], 2)) *
std

2022-10-21 09:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_processes/select_mesh_elements_for_fluids_process.hpp
> +                    Alpha *= 1.2;
![imagen](https://user-images.githubusercontent.com/26402605/197164485-de075a80-069c-4fe3-b500-67813968272e.png)

2022-10-21 16:37 UTC, rlrangel approved these changes
Ok.

2022-10-22 13:26 UTC, AlejandroCornejo approved these changes
ok!!!

2022-10-22 14:52 UTC, merged