Fixed an error in the definition of a python process.
KratosMultiphysics/Kratos pull request #1043
Opened 2017-11-17 15:08 UTC by ipouplana

I also added a comment in the readme.txt.

2017-11-17 15:12 UTC, lorenzogracia requested changes

2017-11-17 15:12 UTC, lorenzogracia commented on applications/DamApplication/README.txt
> +-DFLUID_DYNAMICS_APPLICATION=ON   					                                    \
I think this is not necessary for Dam Application

2017-11-17 15:46 UTC, lorenzogracia approved these changes

2017-11-17 22:34 UTC, ipouplana commented
Hi @roigcarlo, Travis checks have failed because: "The job exceeded the maximum time limit for jobs, and has been terminated" and this blocks the possibility of merging this PR, which has no changes in any C++ file (only python and txt).
So, I was wondering, is there any way to distinguish PRs that introduce changes in C++ files and need to be compiled before merging from those that do not need to be compiled (like this one)? That could reduce the cues in the Travis checks...

2017-11-17 22:36 UTC, roigcarlo commented
Sadly travis does not know if we have touched a cpp or a python. But there are ways to apply filters. I want to discuss this in the next meeting

2017-11-17 22:42 UTC, ipouplana commented
Perfect, thanks @roigcarlo !

2017-11-18 10:02 UTC, ipouplana commented
@roigcarlo sorry to disturb you with this PR, but the Trevis checks have failed again with the same message: "The job exceeded the maximum time limit for jobs, and has been terminated"...
Does the Travis check restart automatically? If not, how can I restart it?
Thanks

2017-11-18 10:04 UTC, roigcarlo commented
There is a button in the travis page but you must log in with the github
account, let me re-restart it

El sáb., 18 nov. 2017 11:02, Ignasi de Pouplana <notifications@github.com>
escribió:

> @roigcarlo <https://github.com/roigcarlo> sorry to disturb you with this
> PR, but the Trevis checks have failed again with the same message: "The job
> exceeded the maximum time limit for jobs, and has been terminated"...
> Does the Travis check restart automatically? If not, how can I restart it?
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/1043#issuecomment-345431883>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB2Jr--hyH6260bfCJAVTvlXG-SII_diks5s3qshgaJpZM4QiKt3>
> .
>

2017-11-18 10:30 UTC, roigcarlo commented
Now it passes :+1:

2017-11-18 17:23 UTC, merged