[All] Cleaning empty json elements using REGEX like a pro
KratosMultiphysics/Kratos pull request #10567
Opened 2022-12-16 21:54 UTC by loumalouomega

**📝 Description**

Until now (https://github.com/KratosMultiphysics/Kratos/pull/10562) when generating results in JSON of empty values were added filling of garbage the json result files. This clean up that. I was cleaning by hand until I remembered that REGEX exists...

**🆕 Changelog**

- [Cleaning (I)](https://github.com/KratosMultiphysics/Kratos/commit/4523b69e1a277e2e6bacc422d458b4f1bd0261cf)
- [Using REGEX like a pro](https://github.com/KratosMultiphysics/Kratos/commit/91c5ba94bdb7db06a20d6f6fd6f64135182deae0)

2022-12-16 23:05 UTC, matekelemen reviewed
https://stackoverflow.com/a/1732454/12350793 -- same for JSON; it's probably safer to just parse the JSONs, get rid of the junk, and write them anew.

Also, I doubt anyone will honestly review changes to ~200 single-line JSON files.

2022-12-16 23:05 UTC, matekelemen commented on applications/IgaApplication/tests/coupling_condition_tests/two_patch_refined_test/two_patch_refined_test_lagrange_membrane_result.json
>      "ELEMENT_25": {}
line breaks are still there, and the last entries seem to be ignored

2022-12-18 10:36 UTC, loumalouomega commented on applications/IgaApplication/tests/coupling_condition_tests/two_patch_refined_test/two_patch_refined_test_lagrange_membrane_result.json
>      "ELEMENT_25": {}
I cleaned that too

2022-12-18 19:03 UTC, rubenzorrilla requested changes
To be discussed in @KratosMultiphysics/technical-committee

2024-05-27 09:24 UTC, RiccardoRossi commented
@KratosMultiphysics/technical-committee is not positive about this large automatic refactorings unless there is an important reason. Our point of view is that the risk is not worth the advantage the change may bring onto the table as they may easily introduce bugs.

2024-05-27 09:26 UTC, closed without merging