correctly cloning the submodelparts
KratosMultiphysics/Kratos pull request #106
Opened 2017-03-01 13:22 UTC by RiccardoRossi

this branch ensures that submodelparts are correctly cloned

2017-03-01 20:37 UTC, RiccardoRossi commented
@pooyan-dadvand  i think you are the one to agree about this

2017-03-02 12:01 UTC, pooyan-dadvand requested changes
In general I would suggest to remove the watches and the optional change of the add methods to avoid the ids.

2017-03-02 12:01 UTC, pooyan-dadvand commented on kratos/utilities/connectivity_preserve_modeler.h
> +        KRATOS_WATCH(OriginModelPart)
Would you please remove the watches?

2017-03-02 12:01 UTC, pooyan-dadvand commented on kratos/utilities/connectivity_preserve_modeler.h
> +            KRATOS_WATCH(part->Name())
One more

2017-03-02 12:01 UTC, pooyan-dadvand commented on kratos/utilities/connectivity_preserve_modeler.h
> +            destination_part.AddNodes(ids);
Is there any reason to use this version by ids? It won't be better to add it by the method accepts the iterators:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/model_part.h#L711

2017-03-02 12:01 UTC, pooyan-dadvand commented on kratos/utilities/connectivity_preserve_modeler.h
> +            destination_part.AddElements(ids);
Same as the nodes

2017-03-02 12:01 UTC, pooyan-dadvand commented on kratos/utilities/connectivity_preserve_modeler.h
> +            destination_part.AddConditions(ids);
Same as the conditions

2017-03-02 12:32 UTC, RiccardoRossi commented on kratos/utilities/connectivity_preserve_modeler.h
> +            destination_part.AddConditions(ids);
yes you are right about iterators (and watches were leftovers)

now corrected to use iterators

2017-03-02 23:39 UTC, pooyan-dadvand approved these changes
👍

2017-03-03 09:50 UTC, merged