[Core] Make Double methods virtual
KratosMultiphysics/Kratos pull request #10622
Opened 2023-01-07 14:39 UTC by sunethwarna

**📝 Description**
As stated in the title, this PR makes the relevant double methods virtual. It is required to create a way to compute sensitivities w.r.t material properties which is required to perform system identification, optimization, etc.... for material properties.

Since, these won't be used with derrived classes in general cases (only in specific cases optimization cases), AFAIK this won't be adding a significant cost to the simulations.

**🆕 Changelog**
- Make double methods virtual

2023-01-07 15:58 UTC, loumalouomega commented
@sunethwarna even if not derived, just being virtual has a cost (depends on the compiler of course). But you are telling that that method must be accessed by table with a significant penalty. I will block for a proper discussion

FYI @pooyan-dadvand

2023-01-07 15:58 UTC, loumalouomega requested changes
Please discussion required

2023-01-07 15:59 UTC, loumalouomega commented
> @sunethwarna even if not derived, just being virtual has a cost (depends on the compiler of course). But you are telling that that method must be accessed by table with a significant penalty. I will block for a proper discussion
> 
> FYI @pooyan-dadvand

See https://web.archive.org/web/20210225014950/http://assemblyrequired.crashworks.org/how-slow-are-virtual-functions-really/

2023-01-07 16:00 UTC, loumalouomega commented
FYI @KratosMultiphysics/altair (we already have a lot of problems with the properties acess)

2023-01-07 16:50 UTC, sunethwarna commented
I also don't like the virtual methods, but, at the moment I don't have any other solution. My requirement is as follows.

1. I need to have some properties of the materials (such as `THICKNESS`, `DENSITY`) to be different for each element
2. I don't want to change how those variables are read in the `Element` classes.
3. I want to add least cost to the existing problems.

Any suggestions are highly appreciated. :D

2023-01-07 19:09 UTC, AlejandroCornejo commented
> I also don't like the virtual methods, but, at the moment I don't have any other solution. My requirement is as follows.
> 
>     1. I need to have some properties of the materials (such as `THICKNESS`, `DENSITY`) to be different for each element
> 
>     2. I don't want to change how those variables are read in the `Element` classes.
> 
>     3. I want to add least cost to the existing problems.
> 
>     4. I don't want to duplicate `Properties` and assign individual `Properties` for each `Element` which duplicates all the other tables, values constitutive laws, etc.
> 
> 
> Any suggestions are highly appreciated. :D

what if you use the same value for the property (i.e. YOUNG) and assign a sensitivity  element-wise via `element->GetValue(SENSITIVITY)`, after, within the element you can do:

~~~cpp
if (elem.HasValue(SENSITIVITY)) {
    young *= elem.GetValue(SENSITIVITY)
}
~~~

2023-01-07 19:47 UTC, loumalouomega commented
Alejandro did a good and simple solution!

El sáb., 7 ene. 2023 20:09, Alejandro Cornejo Velázquez <
***@***.***> escribió:

> I also don't like the virtual methods, but, at the moment I don't have any
> other solution. My requirement is as follows.
>
> 1. I need to have some properties of the materials (such as `THICKNESS`, `DENSITY`) to be different for each element
>
> 2. I don't want to change how those variables are read in the `Element` classes.
>
> 3. I want to add least cost to the existing problems.
>
> 4. I don't want to duplicate `Properties` and assign individual `Properties` for each `Element` which duplicates all the other tables, values constitutive laws, etc.
>
> Any suggestions are highly appreciated. :D
>
> what if you use the same value for the property (i.e. YOUNG) and assign a
> sensitivity element-wise via element->GetValue(SENSITIVITY), after,
> within the element you can do:
>
> if (elem.HasValue(SENSITIVITY)) {
>     young *= elem.GetValue(SENSITIVITY)
> }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/10622#issuecomment-1374578424>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYQZACNHJVOPNHLMZOF5YLWRG5PBANCNFSM6AAAAAATT7ODRE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-01-07 19:51 UTC, AlejandroCornejo commented
Noting that this `HasValue()` is better to do it in the Initialize of the element (in order to do this check once). Also you can set this element-wise value in the mdpa file or by a custom process.

2023-01-07 20:52 UTC, sunethwarna commented
Thanks @AlejandroCornejo, Yes that's true, but that's what I want to avoid. I don't want to change existing elements. I want to be able to use existing elements throughout so it will enable me to use sensitivities with any element without special modification to element. :/

2023-01-07 22:33 UTC, loumalouomega commented
The DataValueContainer is in every element, you don't need to modify your
element one by one.

El sáb., 7 ene. 2023 21:53, Suneth Warnakulasuriya ***@***.***>
escribió:

> Thanks @AlejandroCornejo <https://github.com/AlejandroCornejo>, Yes
> that's true, but that's what I want to avoid. I don't want to change
> existing elements. I want to be able to use existing elements throughout so
> it will enable me to use sensitivities with any element without special
> modification to element. :/
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/10622#issuecomment-1374608614>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEYQZACT7KWNUNZVRPYEIITWRHJS3ANCNFSM6AAAAAATT7ODRE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-01-07 23:01 UTC, sunethwarna commented
I am not sure I am getting your point @loumalouomega, @AlejandroCornejo. Let me summarize what I understood.

You are saying to store some `SENSITIVITY` variable in the data value contaienr of `Element`, and then use it within the `Element` when `YOUNGS_MODULUS` is calculated. But that means, I have to change the existing `Element` formulations which I don't want to do. This is highly error prone and hard to detect since if someone accidentally uses (highly likely because it will be hard to change all the elements and maintain them).

If we somehow find a way to mimick `GetValue` and `operater[]` to wrap original `Properties` such that, the `WrapperProperties` gives `Element`  `YOUNG_MODULUS` when required, otherwise it will get the original `Properties` values. At the moment, this is achieved by assigning different `Properties` object for each element. I want to avoid that. Having different `Properties` object for each element is redundant because `Properties` object has some material properties which are same for the all the elements in the model part, hence copying them is redundant (such as `CONSTITUTIVE_LAW`, etc...) Thats why I was thinking about making the `Properties` interface to support virtual method so, I can create `PropertiesWrapper` which gives `Element` value for `YOUNGS_MODULUS`, for ther variables it gives original `Properties` object value. Then I can have a process to assign these `PropertiesWrapper` by default for optimization problems.

The advantage of this is,
1. Less error prone, because all the exiting elements are compatible, no change at all required in `Element` formulations
2. No change in anywhere is required in the solving procedure (the whole process) except for adding one `json` process to replace existing `Properties` with `PropertiesWrapper`
3. No maintenance is required at all for elements, solution strategies, etc.

2023-01-07 23:52 UTC, sunethwarna commented
Or the second option is to use **Non-Virtual Interface** Idiom as in the following example.

```c++
class Properties
{
public:
    template<class TVar>
    void GetValue(TVar variable) { return GetDataContainer(variable).GetValue(variable);} 
private:
    virtual inline DataContainer& GetDataContainer(TVar Variable) { return mData; }
};

class PropertiesWrapper: public Properties
{
public:
   PropertiesWrapper(int id, Properties::Pointer pPointer, Element::Pointer pElement)
      :  Properties(id),
         mpElement(pElement),
         mpProperties(pProperties)
       {}

private:
   inline DataContainer& GetDataContainer(TVar variable) override {
      if (variable == YOUNG_MODULUES) { // this check can be done to any number of selected variables
         mpElement->mData;
      } else {
         mpProperties->mData;
      }
};
```

2023-01-08 01:11 UTC, matekelemen commented
> Or the second option is to use **Non-Virtual Interface** Idiom as in the following example.
> 
> ```c++
> class Properties
> {
> public:
>     template<class TVar>
>     void GetValue(TVar variable) { return GetDataContainer(variable).GetValue(variable);} 
> private:
>     virtual inline DataContainer& GetDataContainer(TVar Variable) { return mData; }
> };
> 
> class PropertiesWrapper: public Properties
> {
> public:
>    PropertiesWrapper(int id, Properties::Pointer pPointer, Element::Pointer pElement)
>       :  Properties(id),
>          mpElement(pElement),
>          mpProperties(pProperties)
>        {}
> 
> private:
>    inline DataContainer& GetDataContainer(TVar variable) override {
>       if (variable == YOUNG_MODULUES) { // this check can be done to any number of selected variables
>          return mpElement->mData;
>       } else {
>          return mpProperties->mData;
>       }
> };
> ```

?
This always calls `GetDataContainer`, which **is** a virtual function. By the way, I'm not a fan of making only the `double` overloads of `GetValue` virtual. I know that's what you need right now but it'll be super confusing for everyone else to see that some overloads are virtual while others are not.

As for performance, I'm gonna be a broken record and reiterate that a benchmark should be run with and without the change, and see just how much of an impact it has, all things considered. If only there was such a system at hand that could help us with that ...

2023-01-08 17:49 UTC, sunethwarna commented
Ok I did a small test to check the `virtual` cost. And the output is shown below. As far as I see, there is no need to be alarmed about the cost of using `virtual` since, there is no visual change in the execution time (they are almost same for all the problems). Hence use of it doesn't have a visible effect for higher number of elelemnts.

The reasons may be, the properties are used usually outside the gauss point loop, and gauss loop is relatively large. So the properties calls may be having cache missses a lot. I did the same test without calling the `CalculateLocalSystem`, and calling directly virtual `Properties::SetValue`, `Properties::GetValue` and `Properties::Has` for many number of times (1e+9). In that you can clearly see an advantage of not using virtual as @loumalouomega  pointed out. But in Kratos, we never call `Properties::GetValue`, etc million times consecutively in a row to get the cache miss advantage for non-virtual functions. Hence, I think having virtual does not have any impact for the performance.

@loumalouomega @AlejandroCornejo @pooyan-dadvand 

Following is the test program
```python
def Calculate(fname):
    n_list = [1e+2, 1e+3, 1e+4, 1e+5, 1e+6, 1e+7]

    results = []
    for n in n_list:
        n = int(n)
        start_time = timer.time()

        model = Kratos.Model()
        model_part = model.CreateModelPart("test")
        model_part.AddNodalSolutionStepVariable(Kratos.DISPLACEMENT)

        ## nodes_block - start
        nodes_start_time = timer.time()
        # create nodes
        pos = [
            [0.0, 0.0, 0.0],
            [1.0, 0.0, 0.0],
            [1.0, 1.0, 0.0]]
        for id in range(1, n+1):
            model_part.CreateNewNode(id, pos[id % 3][0], pos[id % 3][1], pos[id % 3][2])
        #nodes_block - end

        ## properties_block - start
        properties_start_time = timer.time()
        properties = model_part.CreateNewProperties(1)
        ## properties_block - end


        ## element_creation_block - start
        elements_start_time = timer.time()
        for id in range(1, n+1):
            model_part.CreateNewElement("SmallDisplacementElement2D3N", id, [((id) % n) + 1, ((id + 1 ) % n) + 1, ((id + 2) % n) + 1], properties)
        ## element_creation_block - end

        ## materials_block - start
        materials_start_time = timer.time()
        Kratos.ReadMaterialsUtility(Kratos.Parameters("""{"Parameters":{"materials_filename": "materials_json.json"}}"""), model)

        m = Kratos.Matrix()
        v = Kratos.Vector()

        ## materials_block - end

        ## initialize_block - start
        initialize_start_time = timer.time()
        for element in model_part.Elements:
            element.Initialize(model_part.ProcessInfo)
        ## initialize_block - end

        ## calculate_local_system_block - start
        calculate_local_system = timer.time()
        for element in model_part.Elements:
            element.CalculateLocalSystem(m, v, model_part.ProcessInfo)
        ## calculate_local_system_block - end

        end_time = timer.time()

        data = [
            n,
            end_time - start_time,
            end_time - calculate_local_system,
            calculate_local_system - initialize_start_time,
            initialize_start_time - materials_start_time,
            materials_start_time - elements_start_time,
            elements_start_time - properties_start_time,
            properties_start_time - nodes_start_time,
            nodes_start_time - start_time
        ]
        results.append(data)

    results = np.array(results)
    np.savetxt(fname, results, delimiter=",")
```

And the results are depicted for each start end block with the same names in following figures.
![initialize_block](https://user-images.githubusercontent.com/7856520/211210826-e338a767-793b-44db-ac9e-766d4c7b7fcc.png)
![materials_block](https://user-images.githubusercontent.com/7856520/211210828-a62eba85-f4e2-47da-bae2-45ea5051f82f.png)
![Total_time](https://user-images.githubusercontent.com/7856520/211210829-0fd8326c-5e28-4d9c-95f4-00937fc7cc7c.png)
![calculate_local_system_block](https://user-images.githubusercontent.com/7856520/211210830-24ab0fdb-926c-4684-8b14-67e60300a574.png)
![element_creation_block](https://user-images.githubusercontent.com/7856520/211210832-e8cd089c-7d60-4560-86c9-b1842ee17b9f.png)

2023-01-08 20:43 UTC, loumalouomega commented
> Ok I did a small test to check the `virtual` cost. And the output is shown below (each figure relates to a block in teh shown code). As far as I see, there is no need to be alarmed about the cost of using `virtual` since, there is no visual change in the execution time (they are almost same for all the problems). Hence use of it doesn't have a visible effect for any number of elelemnts.
> 
> The reasons may be, the properties are used usually outside the gauss point loop, and gauss loop is relatively large. So the properties calls may be having cache missses a lot. I did the same test without calling the `CalculateLocalSystem`, and calling directly virtual `Properties::SetValue`, `Properties::GetValue` and `Properties::Has` for many number of times (1e+9). In that you can clearly see an advantage of not using virtual as @loumalouomega pointed out. But in Kratos, we never call `Properties::GetValue`, etc million times consecutively in a row to get the cache miss advantage for non-virtual functions (because, we will have many `Node::FastGetSolutionStepValue` callsin between `Properties::GetValue` calls). Hence, I think having virtual does not have any impact for the performance.
> 
> @loumalouomega @AlejandroCornejo @pooyan-dadvand
> 
> Personally, I like the NVI method. I will push the NVI changes to the `properties.h`
> 
> Following is the test program
> 
> ```python
> def Calculate(fname):
>     n_list = [1e+2, 1e+3, 1e+4, 1e+5, 1e+6, 1e+7]
> 
>     results = []
>     for n in n_list:
>         n = int(n)
>         start_time = timer.time()
> 
>         model = Kratos.Model()
>         model_part = model.CreateModelPart("test")
>         model_part.AddNodalSolutionStepVariable(Kratos.DISPLACEMENT)
> 
>         ## nodes_block - start
>         nodes_start_time = timer.time()
>         # create nodes
>         pos = [
>             [0.0, 0.0, 0.0],
>             [1.0, 0.0, 0.0],
>             [1.0, 1.0, 0.0]]
>         for id in range(1, n+1):
>             model_part.CreateNewNode(id, pos[id % 3][0], pos[id % 3][1], pos[id % 3][2])
>         #nodes_block - end
> 
>         ## properties_block - start
>         properties_start_time = timer.time()
>         properties = model_part.CreateNewProperties(1)
>         ## properties_block - end
> 
> 
>         ## element_creation_block - start
>         elements_start_time = timer.time()
>         for id in range(1, n+1):
>             model_part.CreateNewElement("SmallDisplacementElement2D3N", id, [((id) % n) + 1, ((id + 1 ) % n) + 1, ((id + 2) % n) + 1], properties)
>         ## element_creation_block - end
> 
>         ## materials_block - start
>         materials_start_time = timer.time()
>         Kratos.ReadMaterialsUtility(Kratos.Parameters("""{"Parameters":{"materials_filename": "materials_json.json"}}"""), model)
> 
>         m = Kratos.Matrix()
>         v = Kratos.Vector()
> 
>         ## materials_block - end
> 
>         ## initialize_block - start
>         initialize_start_time = timer.time()
>         for element in model_part.Elements:
>             element.Initialize(model_part.ProcessInfo)
>         ## initialize_block - end
> 
>         ## calculate_local_system_block - start
>         calculate_local_system = timer.time()
>         for element in model_part.Elements:
>             element.CalculateLocalSystem(m, v, model_part.ProcessInfo)
>         ## calculate_local_system_block - end
> 
>         end_time = timer.time()
> 
>         data = [
>             n,
>             end_time - start_time,
>             end_time - calculate_local_system,
>             calculate_local_system - initialize_start_time,
>             initialize_start_time - materials_start_time,
>             materials_start_time - elements_start_time,
>             elements_start_time - properties_start_time,
>             properties_start_time - nodes_start_time,
>             nodes_start_time - start_time
>         ]
>         results.append(data)
> 
>     results = np.array(results)
>     np.savetxt(fname, results, delimiter=",")
> ```
> 
> And the results are depicted for each start end block with the same names in following figures (log-log) ![initialize_block](https://user-images.githubusercontent.com/7856520/211210826-e338a767-793b-44db-ac9e-766d4c7b7fcc.png) ![materials_block](https://user-images.githubusercontent.com/7856520/211210828-a62eba85-f4e2-47da-bae2-45ea5051f82f.png) ![Total_time](https://user-images.githubusercontent.com/7856520/211210829-0fd8326c-5e28-4d9c-95f4-00937fc7cc7c.png) ![calculate_local_system_block](https://user-images.githubusercontent.com/7856520/211210830-24ab0fdb-926c-4684-8b14-67e60300a574.png) ![element_creation_block](https://user-images.githubusercontent.com/7856520/211210832-e8cd089c-7d60-4560-86c9-b1842ee17b9f.png)
> 
> And the results are depicted for each start end block with the same names in following figures (semilogx) ![Total_time](https://user-images.githubusercontent.com/7856520/211211550-f60e4b56-5a18-4062-9043-0d8d4320fdcb.png) ![calculate_local_system_block](https://user-images.githubusercontent.com/7856520/211211551-5bc738e1-43fd-4896-9480-fd2a7fe65973.png) ![element_creation_block](https://user-images.githubusercontent.com/7856520/211211552-290b9978-85d8-49e8-9e81-3efaac57d853.png) ![initialize_block](https://user-images.githubusercontent.com/7856520/211211553-62d8fbf6-a44a-4989-97f4-25a5932831f2.png) ![materials_block](https://user-images.githubusercontent.com/7856520/211211554-643e2e5d-6a9f-4ba7-a255-24e58b8ca482.png)

The problem is that "usually", some implementations, specially CL implementations, call the method internally in each GP. We do this in @KratosMultiphysics/altair , also some implementations of @AlejandroCornejo are like that. 

For your particular case I cannot think in any  solution. I will think about it. Probably metaprogramming could be a solution.

2023-01-08 20:44 UTC, loumalouomega commented
Assigning @pooyan-dadvand, this is relevant

2023-01-13 10:44 UTC, RiccardoRossi requested changes
this is performance critical, so we cannot change it lighthartedly

2023-01-17 08:08 UTC, closed without merging