[Meshing] Adding local refine tets parallel to boundaries
KratosMultiphysics/Kratos pull request #10636
Opened 2023-01-10 12:39 UTC by ddiezrod

**📝 Description**
This was a development created by @pablobecker in Altair side, but I think it is better to have on the common side. @pablobecker Can you add any more details about the implementation?

2023-01-10 13:17 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +//  License:		 BSD License
tabs

2023-01-10 13:17 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        }
unify the if

2023-01-10 13:18 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +#if !defined(KRATOS_LOCAL_REFINE_TETRAHEDRA_MESH_PARALLEL_TO_BOUNDARIES)
pragma once

2023-01-10 13:18 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +/* Project includes */
```suggestion
// External includes

// Project includes
```

2023-01-10 13:19 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +	    id = 1;
TABS

2023-01-10 13:19 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        for (ModelPart::ElementsContainerType::iterator it = mModelPart.ElementsBegin(); it != mModelPart.ElementsEnd(); it++)
reorder in parallel, we should unify the reordering

2023-01-10 13:19 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        boost::numeric::ublas::vector<int> List_New_Nodes;                         // The news nodes
why not std::vector?

2023-01-10 13:20 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +            block_for_each(mModelPart.Nodes(), [&](Node<3>& rNode)
There is an utility to move mesh already

2023-01-10 13:21 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        for (ElementsArrayType::iterator it = it_begin; it != it_end; ++it)
More elegant with for (auto& r_elem:...)

2023-01-10 13:21 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        ConditionsArrayType& rConditions = this_model_part.Conditions();
Idem more elegant

2023-01-10 13:21 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +            compressed_matrix<int>& Coord
Huuuuuum

2023-01-10 13:22 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +                    for ( GlobalPointersVector< Node<3> >::iterator iParent = rFatherNodes.begin();
use auto instead

2023-01-10 13:22 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +            for (auto iNode = rModelPart.Nodes().ptr_begin();
it_node

2023-01-10 13:22 UTC, loumalouomega requested changes
Some comments

2023-01-10 13:43 UTC, pablobecker commented
thanks @ddiezrod for creating the PR

2023-01-10 15:28 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_geometry_mesh.hpp
>  					 );
Tabs

2023-01-10 15:28 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_geometry_mesh.hpp
>  							  );
Tabs

2023-01-10 15:30 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh.hpp
>  	  if (create_element == true)
Tabs, also you can avoid ==true

2023-01-10 15:30 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh.hpp
> +    void UpdateSubModelPartConditions(ModelPart& this_model_part, PointerVector< Condition >& NewConditions)
rModelPart

2023-01-10 15:30 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh.hpp
> +                    /*
Remove unused watch

2023-01-10 15:31 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh.hpp
> +                    */
```suggestion
```

2023-01-10 15:31 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        compressed_matrix<int> Coord;                                              // The matrix that stores all the index of the geometry
What type is this?

2023-01-10 15:32 UTC, loumalouomega commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +                const array_1d<double, 3 > & disp = rNode.FastGetSolutionStepValue(DISPLACEMENT);
Don't we have an utility for this?

2023-01-10 16:04 UTC, ddiezrod commented on applications/MeshingApplication/custom_utilities/local_refine_tetrahedra_mesh_parallel_to_boundaries.hpp
> +        compressed_matrix<int> Coord;                                              // The matrix that stores all the index of the geometry
I think it is the one from ublas, I can try to use a Matrix, but it will involve changes in other files.

2023-01-10 16:07 UTC, loumalouomega submitted a review, later dismissed
Ok

2023-01-11 08:27 UTC, ddiezrod commented
I submitted some minor changes, can you approve again @loumalouomega ?

2023-01-11 09:05 UTC, loumalouomega approved these changes

2023-01-11 10:35 UTC, merged