[TrinilinosApplication] Cleaning up Trilinos includes
KratosMultiphysics/Kratos pull request #10689
Opened 2023-01-27 11:29 UTC by loumalouomega

**📝 Description**

 `#include "trilinos_space.h"` already include most of the Trilinos dependencies, so in this PR I am cleaning the duplicates on includes due to this inclusion. 

**🆕 Changelog**

- [Cleaning up Trilinos includes](https://github.com/KratosMultiphysics/Kratos/commit/9e3e7ac5f867d01f93bb4c0d41fede32c9863f87)
- Some clean up

2023-01-27 12:00 UTC, rubenzorrilla commented on applications/TrilinosApplication/external_includes/amgcl_mpi_solver_impl.cpp
> +//  Main authors:
I'd take the chance to add the authors.

2023-01-27 12:18 UTC, loumalouomega commented on applications/TrilinosApplication/external_includes/amgcl_mpi_solver_impl.cpp
> +//  Main authors:
Who?

2023-01-27 12:19 UTC, loumalouomega commented on applications/TrilinosApplication/external_includes/amgcl_mpi_solver_impl.cpp
> +//  Main authors:
I assume these ones

2023-01-27 13:57 UTC, philbucher requested changes
I do not like these changes
What is your motivation?

I am pretty hesitant changing something that (see the failing CI) can easily break with older versions of trilinos, which is often the case on the cluster

Usually I am all up for cleaning, but in this particular case I would not change a working system

2023-01-27 14:01 UTC, loumalouomega commented
> I do not like these changes What is your motivation?

Cleaning up, looks like I removed more includes than supposed, some classes have similar name, and maybe I confused some names

> I am pretty hesitant changing something that (see the failing CI) can easily break with older versions of trilinos, which is often the case on the cluster
> 
> Usually I am all up for cleaning, but in this particular case I would not change a working system

2023-01-27 14:29 UTC, loumalouomega commented
> I do not like these changes What is your motivation?
> 
> I am pretty hesitant changing something that (see the failing CI) can easily break with older versions of trilinos, which is often the case on the cluster
> 
> Usually I am all up for cleaning, but in this particular case I would not change a working system

Funny thing is that in this PR I discovered we are using inconsistently `Epetra_FEVector` and `Epetra_Vector`, the first derives from the second but is not the same. This could be conflicting...

2023-01-27 15:57 UTC, philbucher commented
> Funny thing is that in this PR I discovered we are using inconsistently `Epetra_FEVector` and `Epetra_Vector`, the first derives from the second but is not the same. This could be conflicting...

The FE versions have the assembly functionalities (same for the FECrsMatrix)

2023-01-27 16:23 UTC, loumalouomega commented
> > Funny thing is that in this PR I discovered we are using inconsistently `Epetra_FEVector` and `Epetra_Vector`, the first derives from the second but is not the same. This could be conflicting...
> 
> The FE versions have the assembly functionalities (same for the FECrsMatrix)

Yes i know, but we are mixing them, I don't know if in purpose

2023-01-30 17:33 UTC, philbucher approved these changes
Now is good

2023-01-30 18:30 UTC, merged