trting to remove the python iterator for parameters
KratosMultiphysics/Kratos pull request #10823
Opened 2023-03-03 10:12 UTC by RiccardoRossi

i want to see how many errors we get, in order to try addressing #10649

**📝 Description**
A brief description of the PR.

Please mark the PR with appropriate tags: 
- Api Breaker, Mpi, etc...

**🆕 Changelog**
Please summarize the changes in one list to generate the changelog:
E.g.
- Added feature X to Y
- Added Foo Application
- Fixed X (#XXXX Reference to issue if apply) 
- etc...

2023-03-03 11:40 UTC, loumalouomega commented
CI is not passing

2023-03-03 12:20 UTC, sunethwarna commented
We may need to deprecate the existing and promote using `items`, `values` and `keys`...

2023-03-05 10:07 UTC, philbucher commented
While I approve of removing this method, I strongly agree with @sunethwarna , this must be deprecated.

Imagine all the code that is outside the repo (custom processes etc!) that would be broken if you remove it directly!

2023-03-05 21:53 UTC, RiccardoRossi commented
the problem is that you cannot deprecate this since it is in the python interface...

2023-03-06 07:51 UTC, philbucher commented
You can add a deprecation warning in the py interface

We have done this dozens of times

2023-03-06 19:48 UTC, philbucher requested changes
> the problem is that you cannot deprecate this since it is in the python interface...

[it is](https://github.com/KratosMultiphysics/Kratos/pull/10835) ;)

2023-03-06 20:55 UTC, RiccardoRossi commented
adding a comment for myself: the following function allows returning the correct type in python from parameters without having to call the GetXXX method.

~~~cpp
.def("find", [](Parameters& rParam, std::string name) -> py::object {
        auto my_obj = rParam[name];
        if(my_obj.IsDouble())
            return py::cast(my_obj.GetDouble());
        else if(my_obj.IsInt())
            return py::cast(my_obj.GetInt());
        else if(my_obj.IsBool())
            return py::cast(my_obj.GetBool());
        else if(my_obj.IsString())
            return py::cast(my_obj.GetString());
        else if(my_obj.IsVector())
            return py::cast(my_obj.GetVector());
        else if(my_obj.IsVector())
            return py::cast(my_obj.GetVector());
        else if(my_obj.IsMatrix())
            return py::cast(my_obj.GetMatrix());
        else if(my_obj.IsNull())
            return py::none();
        else
            return py::cast(my_obj);
                })
~~~

if we replaced the current implementation of __getitem__ and __setitem__ by this, the Parameters would work as a normal dictionary. too bad that we would break everything...

2023-03-06 21:09 UTC, matekelemen commented
> adding a comment for myself: the following function allows returning the correct type in python from parameters without having to call the GetXXX method.
> 
> ```c++
> .def("find", [](Parameters& rParam, std::string name) -> py::object {
>         auto my_obj = rParam[name];
>         if(my_obj.IsDouble())
>             return py::cast(my_obj.GetDouble());
>         else if(my_obj.IsInt())
>             return py::cast(my_obj.GetInt());
>         else if(my_obj.IsBool())
>             return py::cast(my_obj.GetBool());
>         else if(my_obj.IsString())
>             return py::cast(my_obj.GetString());
>         else if(my_obj.IsVector())
>             return py::cast(my_obj.GetVector());
>         else if(my_obj.IsVector())
>             return py::cast(my_obj.GetVector());
>         else if(my_obj.IsMatrix())
>             return py::cast(my_obj.GetMatrix());
>         else if(my_obj.IsNull())
>             return py::none();
>         else
>             return py::cast(my_obj);
>                 })
> ```
> 
> if we replaced the current implementation of **getitem** and **setitem** by this, the Parameters would work as a normal dictionary. too bad that we would break everything...

we have [ParametersWrapper](https://github.com/KratosMultiphysics/Kratos/blob/6dcf133f24441f8cf356a42a31a9f983f9781228/applications/HDF5Application/python_scripts/core/utils.py#L16) in the HDF5Application that does exactly this. It could be nice but in my experience, unless **all** `Parameters` are replaced by this in python, it's a colossal pain to support both versions.

2023-03-08 11:45 UTC, philbucher commented
Sure, but can you please remove the accidentally committed files in the DEMApp?

2023-03-08 11:46 UTC, philbucher commented on kratos/tests/test_kratos_parameters.py
> +        #nitems = 0
And please remove this

2023-03-11 22:33 UTC, RiccardoRossi reviewed
@philbucher done!

2023-03-12 08:33 UTC, philbucher approved these changes
Great!

2023-03-12 08:33 UTC, philbucher commented on applications/SwimmingDEMApplication/python_scripts/parameters_tools.py
> +        for i, _ in enumerate(parameters.values()):
That one could be redone better I believe 🤔
FYI @sunethwarna

2023-03-12 21:08 UTC, merged

2023-03-12 21:09 UTC, RiccardoRossi commented
@matekelemen this, together with #10835 should solve for good the problem with parameters iterators in python