Feature/add 2d beam
KratosMultiphysics/Kratos pull request #1087
Opened 2017-11-27 15:57 UTC by KlausBSautter

Hey I added the 2 d version of the cr beam. I did it in a new file to avoid too much code being nested and I could go for an easier rotation strategy. 
There are additional tests and I did several non-linear benchmarks which all work pretty nicely

2017-11-27 15:59 UTC, loumalouomega approved these changes
OK, looks fine

2017-11-27 16:20 UTC, philbucher requested changes
Just some very minor changes
Also I will upload a small fix, see #1083

2017-11-27 16:20 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +#define Pi 3.141592653589793238462643383279502884197169399375105820974944592308
Please use `Globals::Pi`

2017-11-27 16:20 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +		S(1, 2) = 2.00 / L;
what if `L` is very small? => add check (maybe even in `CalculateCurrentLength`-function)

2017-11-27 16:20 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +		Kd(0, 0) = E*A / L;
same

2017-11-27 16:20 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +		const double Q = (-2.00 / L) * this->DeformationForces[2];
same

2017-11-27 16:20 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +		const int B = A / (2.00 * Pi);
globals::Pi

2017-11-27 20:02 UTC, RiccardoRossi reviewed
minor comments

2017-11-27 20:02 UTC, RiccardoRossi commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +	CrBeamElement2D2N::CrBeamElement2D2N(IndexType NewId,
honestly i don't love this mechanism.

you are storing a bool in each element for this purpose, and you are using a non-standard constructor. Would it be much more complex to use derivation (for example deriving the linear beam from the nonlinear beam, or the contrary)?

2017-11-27 20:02 UTC, RiccardoRossi commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.hpp
> +		CrBeamElement2D2N() {};
define it as

CrBeamElement2D2N() = delete;

2017-11-27 20:02 UTC, RiccardoRossi commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.hpp
> +		Matrix K_master = ZeroMatrix(msElementSize,msElementSize);
do you really need to store this?

2017-11-28 07:55 UTC, philbucher approved these changes

2017-11-28 08:24 UTC, KlausBSautter commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.hpp
> +		CrBeamElement2D2N() {};
I need this for the serializer

2017-11-28 08:48 UTC, KlausBSautter commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.hpp
> +		Matrix K_master = ZeroMatrix(msElementSize,msElementSize);
Yes I need the internal forces which are converged from the last iteration of the last step in my RHS

2017-11-28 08:49 UTC, KlausBSautter commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_2D2N.cpp
> +	CrBeamElement2D2N::CrBeamElement2D2N(IndexType NewId,
I will merge this branch now and discuss with @AndreasWinterstein  and @philbucher  about this possibility, as I can then also change the other elements

2017-11-28 08:49 UTC, merged