Geo/10805 normal load
KratosMultiphysics/Kratos pull request #10951
Opened 2023-03-31 11:23 UTC by aronnoordam

2023-04-04 08:01 UTC, mcgicjn2 requested changes
Slight change required otherwise fine by me.

2023-04-04 08:01 UTC, mcgicjn2 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> +        vector_of_neighbours(0) = Element::WeakPointer(*pItElem.base());
```suggestion
	const std::pair<hashmap::iterator, hashmap::iterator> face_pair = rFacesMap.equal_range(rItFace->first);
        for (hashmap::iterator it = face_pair.first; it != face_pair.second; ++it) {
            std::vector<Condition::Pointer>& r_conditions = it->second;

            GlobalPointersVector< Element > vector_of_neighbours;
            vector_of_neighbours.resize(1);
            vector_of_neighbours(0) = Element::WeakPointer(*pItElem.base());
```
Corrected the alignment

2023-04-04 12:23 UTC, mnabideltares approved these changes, later dismissed

2023-04-05 14:13 UTC, avdg81 reviewed
I have looked at the C++ code only. You have made some nice improvements there, so thanks for that.

2023-04-05 14:13 UTC, avdg81 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> -                    }
Very nice that you have found and eliminated this duplicated piece of code 😄

2023-04-05 14:13 UTC, avdg81 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> +    return true;
I believe this is an algorithm from the STL:
```suggestion
    const auto& rConditions = mrModelPart.Conditions();
    return std::all_of(rConditions.begin(), rConditions.end(),
                       [](const auto& r_cond){return r_cond.Is(VISITED);});
```
Using such an algorithm makes your intent very clear and easy to read. But please check (and test) this suggested change carefully before incorporating it in your work.

2023-04-05 14:13 UTC, avdg81 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> +	    {
I have found a few accidentals tabs here.

2023-04-05 14:13 UTC, avdg81 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> +                }
I believe this is a transformation:
```suggestion
                const auto& rNodes = rBoundaryGeometries[iFace];
                std::transform(rNodes.begin(), rNodes.end(), FaceIds.begin(),
                               [](const auto& rNode){ return rNode.Id(); });
```
And once again: please check this suggestion carefully before incorporating it. Thanks.

2023-04-05 14:13 UTC, avdg81 commented on applications/GeoMechanicsApplication/custom_processes/find_neighbour_elements_of_conditions_process.cpp
> +	const std::pair<hashmap::iterator, hashmap::iterator> face_pair = rFacesMap.equal_range(rItFace->first);
I have found an accidental tab here. Also the following appear to have incorrect indentation levels, which makes it more difficult to read.

2023-04-06 08:06 UTC, mcgicjn2 approved these changes

2023-04-06 08:20 UTC, merged