[Core] add option to set nodes on interface to zero
KratosMultiphysics/Kratos pull request #10982
Opened 2023-04-10 11:25 UTC by ddiezrod

When computing ray distances we check if the distance to the intersection is lower than mEpsilon here
https://github.com/KratosMultiphysics/Kratos/blob/7a7e56d2259ddf2ad524884ee8f0d7b3c5ed8eeb/kratos/processes/apply_ray_casting_process.cpp#L172

However, this is not considered later when we set the nodal distance, we only change the sign there. Here I am adding the option to set the distance to zero on nodes that are close to the interface (closer than mEpsilon). This would be useful for me to recognize objects that are completely intersect with the skin. Current behaviour is kept though by default.

2023-04-10 12:45 UTC, loumalouomega approved these changes
Okay from my side

2023-04-10 19:58 UTC, rubenzorrilla requested changes
Though current behavior is  kept, we need to carefully consider changes in this class.

First, is this a bugfix or introducing a new feature/behavior. If the first, I think it makes no sense to keep current behavior.

On the contrary, if it is the second I'm of the opinion that, instead of adding an option to circunvent current behavior to use this process for a valid but different purpose, a derived class with clear intended usage must be created.

2023-04-11 07:32 UTC, ddiezrod commented
I think this is more a design decision rather than a bug. I also considered if this should go to a new class or as an option and I do not have a strong opinion, I did it this way first because it was easier for the discussion. I'll do it the other way around.

2023-04-11 08:54 UTC, rubenzorrilla commented
> 

If so, I think it would be better to create a `DetectSkinObjectProcess` (or something of this sort) with clear settings and intended usage. Besides, I also think that this would give us complete freedom to give special treatment to the corner cases that can eventually arise.

2023-04-11 09:08 UTC, ddiezrod commented
> > 
> 
> If so, I think it would be better to create a `DetectSkinObjectProcess` (or something of this sort) with clear settings and intended usage. Besides, I also think that this would give us complete freedom to give special treatment to the corner cases that can eventually arise.

The thing is I need to identify all cases, if a node falls out, in, or on the interface. It'd be good if I could do that with only one process.

2023-04-14 07:05 UTC, rubenzorrilla commented
@ddiezrod as far as I understand we can close this one now. Am I wrong?

2023-04-14 07:16 UTC, ddiezrod commented
> @ddiezrod as far as I understand we can close this one now. Am I wrong?

Yep! closing

2023-04-14 07:16 UTC, closed without merging