Geo/11003-ManageMultipleMovingPointLoads
KratosMultiphysics/Kratos pull request #11007
Opened 2023-04-14 15:09 UTC by mcgicjn2

**📝 Description**
Create process managing a collection of moving_loads

- initialization, operations must be consistent
- multiple moving loads based on a configuration translating to an offset

This will be a PR depends on the structuralmechanics application until PR #10997 is merged

Closes #11003 

**🆕 Changelog**
Added process to set and manage a collection multiple moving point loads
- clones mutliple moving_line_conditions into compute model part
- removes associated original moving line conditions from compute model part
- manages list of multiple set_moving_line_load processes + calls
+ some associated tests

2023-06-21 05:56 UTC, huhaas commented on applications/GeoMechanicsApplication/custom_processes/set_multiple_moving_loads.cpp
> +    		count++;
Indents are not consistent due to tab usage.

2023-06-21 06:07 UTC, huhaas commented on applications/GeoMechanicsApplication/custom_processes/set_multiple_moving_loads.h
> +	        std::vector<SetMovingLoadProcess> mMovingPointLoadsProcesses;
Maybe it is better to use the Kratos unique pointer construction here. Currently the push_back in cpp line 80 creates unwanted copies.

2023-06-21 06:07 UTC, huhaas commented on applications/GeoMechanicsApplication/custom_processes/set_multiple_moving_loads.cpp
> +    ModelPart& SetMultipleMovingLoadsProcess::CloneMovingConditionInComputeModelPart(std::string NewBodyPartName)
Argument can be const&

2023-06-21 07:20 UTC, huhaas commented on applications/GeoMechanicsApplication/tests/test_set_multiple_moving_load_process.py
> +class TestSetMultipleMovingLoadsProcess(KratosUnittest.TestCase):
I have some suggestions to improve this class. Let's discuss this in the office. Also SonarCloud does not agree with this change.

2023-06-21 07:20 UTC, huhaas requested changes
Please update

2023-06-23 12:29 UTC, huhaas commented on applications/GeoMechanicsApplication/tests/test_set_multiple_moving_load_process.py
> +            self.assertAlmostEqual(rhs_val, expected_val, tols)
```suggestion
        for rhs_val, expected_val, tol in zip(rhs, expected_res, tols):
            self.assertAlmostEqual(rhs_val, expected_val, tol)
```

2023-07-10 07:09 UTC, aronnoordam commented
LGTM

2023-07-10 07:09 UTC, aronnoordam approved these changes, later dismissed

2023-07-14 10:28 UTC, avdg81 approved these changes
I have made several minor coding improvements (see my last commit). It looks good to me now, Jon. Thanks for the hard work that you've put into this!

2023-07-14 15:42 UTC, huhaas approved these changes

2023-07-14 15:43 UTC, merged