[CLApp] WORK in progress - Adding Deactivate Element Process
KratosMultiphysics/Kratos pull request #11230
Opened 2023-06-05 10:45 UTC by AlejandroCornejo

**📝 Description**
In this PR I am adding a process to deactivate elements according to a certain `Variable `and `Threshold`

~~~json
        {
            "help"                        : "This process deactivates elements that satisfy a predefined threshold of a Variable",
            "mesh_id"                     : 0,
            "model_part_name"             : "please_specify_model_part_name",
            "variable_name"               : "DAMAGE",
            "variable_maximum_threshold"  : 0.9999,
            "average_calculation_over_ip" : true
        }
~~~

2023-06-05 10:46 UTC, AlejandroCornejo commented
@atfard you can try to use this and let me know if it works properly.

2023-06-05 10:50 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/python_scripts/element_deactivation_process
> +def Factory(settings, Model):
This could be a C++ process, it would be faster

2023-06-05 10:50 UTC, loumalouomega requested changes
Add test + move to C++

2023-06-05 10:51 UTC, AlejandroCornejo commented
> Add test + move to C++

Yes indeed, after @atfard tries it, I will move it to parallel c++

2023-06-06 07:52 UTC, atfard commented
I checked it in a DCB test with isotropic damage, and is working properly. The point is that in Traction Separation CL, damage variable is vector so we should think about generalizing it.
![image](https://github.com/KratosMultiphysics/Kratos/assets/94042205/c2c5ad07-da2e-483b-b330-c1b5c694f0d5)

2023-06-06 13:33 UTC, loumalouomega submitted a review, later dismissed
I applied the suggestions myself to avoid disturb you

2023-06-06 14:20 UTC, atfard approved these changes, later dismissed

2023-06-06 18:03 UTC, atfard approved these changes

2023-06-06 21:32 UTC, merged