[Core] add input tolerance in search is inside
KratosMultiphysics/Kratos pull request #11275
Opened 2023-06-15 15:16 UTC by vdivine

Tolerance is a constexpr as 1.0E-12. For some cases, i need to use a smaller tolerance, otherwise a given point is not found anywhere.
This PR allows user to input a tolerance value.

2023-06-15 15:17 UTC, vdivine commented
ping @ddiezrod @pooyan-dadvand @loumalouomega

2023-06-15 15:21 UTC, loumalouomega commented
I would set it on the constructor, opinion @pooyan-dadvand ?

2023-06-15 16:09 UTC, rubenzorrilla requested changes
This breaks current API. I'd follow @loumalouomega's suggestion instead.

2023-06-22 07:13 UTC, vdivine commented
ping @loumalouomega @ddiezrod

2023-06-22 07:31 UTC, ddiezrod commented on kratos/python/add_search_strategies_to_python.cpp
> +    .def(py::init<ElementsContainerType&, double>())
I'd add  the constructor without the tolerance too

2023-06-22 08:17 UTC, ddiezrod commented
OK for me, I leave the approval for @rubenzorrilla

2023-06-28 09:50 UTC, vdivine commented
ping @rubenzorrilla

2023-07-05 10:24 UTC, rubenzorrilla commented on kratos/spatial_containers/geometrical_objects_bins.h
> +    GeometricalObjectsBins(TContainer& rGeometricalObjectsVector, double Tolerance = 1e-12)
```suggestion
    GeometricalObjectsBins(
        TContainer& rGeometricalObjectsVector,
        const double Tolerance = 1e-12)
```

2023-07-05 10:24 UTC, rubenzorrilla commented on kratos/spatial_containers/geometrical_objects_bins.h
> +        double Tolerance = 1e-12
```suggestion
        const double Tolerance = 1e-12
```

2023-07-05 12:54 UTC, rubenzorrilla approved these changes
Should be OK now. Thanks.

2023-07-06 07:33 UTC, merged