[OptApp] Improving terminal log output
KratosMultiphysics/Kratos pull request #11289
Opened 2023-06-19 15:11 UTC by RezaNajian

This is a quick PR that enhances the logging of OptApp, particularly at the algorithm level.

2023-06-20 10:27 UTC, sunethwarna submitted a review, later dismissed
This is really cool. Could you may be put a sample output in the PR to see. :D

2023-06-20 10:27 UTC, sunethwarna commented on applications/OptimizationApplication/python_scripts/algorithms/algorithm_steepest_descent.py
>                      print(self.__objective.GetInfo())
```suggestion
                    Kratos.Logger.PrintInfo("AlgorithmSteepestDescent", "\n" + self.__objective.GetInfo())
```

2023-06-20 10:27 UTC, sunethwarna commented on applications/OptimizationApplication/python_scripts/algorithms/algorithm_steepest_descent.py
> +                    print(self.__line_search_method.GetInfo())
```suggestion
                    Kratos.Logger.PrintInfo("AlgorithmSteepestDescent", "\n" + self.__line_search_method.GetInfo())
```
                    Kratos.Logger.PrintInfo("AlgorithmSteepestDescent", "\n" + self.__objective.GetInfo())

2023-06-20 10:27 UTC, sunethwarna commented on applications/OptimizationApplication/python_scripts/algorithms/algorithm_steepest_descent.py
> +                    print(self.__convergence_criteria.GetInfo())
```suggestion
                    Kratos.Logger.PrintInfo("AlgorithmSteepestDescent", "\n" + self.__convergence_criteria.GetInfo())
```

2023-06-20 16:33 UTC, RezaNajian commented
@sunethwarna ready for your review

2023-06-26 11:38 UTC, Igarizza approved these changes, later dismissed
Nice work

2023-06-26 11:38 UTC, Igarizza commented on applications/OptimizationApplication/python_scripts/algorithms/standardized_constraint.py
> +            "abs_violation [%]": self.GetAbsoluteViolation(),
```suggestion
            "abs_violation [%]": self.GetAbsoluteViolation() * 100,
```

2023-06-26 14:02 UTC, Igarizza submitted a review, later dismissed
sure

2023-06-26 14:58 UTC, Igarizza approved these changes
good catch

2023-06-26 14:58 UTC, Igarizza commented on applications/OptimizationApplication/python_scripts/algorithms/algorithm_steepest_descent.py
> +                self.UpdateControl()
Yes, I see, in old version the control_field was from next iteration (after adding update). Good catch, thnx!

2023-06-26 15:12 UTC, Igarizza requested changes
@RezaNajian @sunethwarna Let's use decorator instead of with TimeLogger. Here is an example: 
https://www.geeksforgeeks.org/timing-functions-with-decorators-python/

It would allow to do the same thing as you did but without one Tab level. And you need to add only one decorator line to use it.

2023-06-27 08:01 UTC, RezaNajian commented
@Igarizza Thanks for the point. I have checked the link and also discussed it with Suneth. That improves and saves the implementation. I would suggest extending the current implementation in a separate PR.

2023-06-27 11:15 UTC, Igarizza approved these changes
I have crearted a following PR with decorator #11326 . You can merge.

2023-06-27 11:29 UTC, merged