[GeoMechanics] Matching Function Names in GeoMechanicsAnalysis
KratosMultiphysics/Kratos pull request #11321
Opened 2023-06-27 08:51 UTC by Rbravo555

depends on #11320

This is the **2nd of 3** PRs for using the RomApp with the GeoMechanicsApp 

**📝 Description**
The RomApp will use all of the features of the GeoMechanicsAnalysis, except for the BuilderAndSolver, which will be set as the RomB&S. For this, the required functions should be named _CreateBuilderAndSolver rather than _ConstructBuilderAndSolver, and there should be a function returning the linear solver.

**🆕 Changelog**
- changed _ConstructBuilderAndSolver(self, param1) ==> _CreateBuilderAndSolver(self)
- added method _GetLinearSolver(self)

2023-06-27 09:21 UTC, huhaas approved these changes
Looks good. (Given it will be rebased on previous commit)

2023-07-03 11:35 UTC, huhaas requested changes
Looks good. (Given it will be rebased on previous commit)

2023-07-07 07:33 UTC, huhaas approved these changes, later dismissed

2023-07-07 07:35 UTC, huhaas approved these changes, later dismissed

2023-07-07 07:38 UTC, avdg81 submitted a review, later dismissed

2023-07-25 10:33 UTC, closed without merging

2023-07-25 10:41 UTC, Rbravo555 commented
Moved this PR to #11425 for triggering internal tests