Core/fix side evaluation warning
KratosMultiphysics/Kratos pull request #1203
Opened 2017-12-19 15:46 UTC by roigcarlo

Fixes annoying warnings...
This is very old (picked from https://github.com/KratosMultiphysics/Kratos/tree/feature-correct-kratos-components-clang-warning) and was edited with atom, so plenty of whitespace removal... sorry for that

2017-12-20 12:11 UTC, roigcarlo commented
@pooyan-dadvand Ping!

2017-12-20 13:24 UTC, pooyan-dadvand requested changes
There are no equivalent std trait for `isTypeIndexEq`? 

Also you should apply the class name Kratos convention.

2017-12-20 13:24 UTC, pooyan-dadvand commented on kratos/sources/model_part_io.cpp
> +    /// Compare component type utility
This is not the equivalent to `std::is_same`?

2017-12-20 13:33 UTC, roigcarlo commented
I think `std::is_same` is equivalent to `std::remove_cv_t<std::remove_reference_t<TypeA>> == std::remove_cv_t<std::remove_reference_t<TypeB>>`

Basically `std::is_same` does not ignore the `const` and `volatile` attributes, while comparing typeid does. If this is not relevant here I can change it.

Also is a function!, but the `i` is wrong right, changing

2017-12-22 09:32 UTC, roigcarlo commented
Just for the record, we are investigating now if this code is even necessary, the PR is not halt.

2018-01-01 19:52 UTC, pooyan-dadvand commented
I would suggest to make a test for this part and then change it to see if it is still working.

2018-01-17 14:17 UTC, roigcarlo commented
I am closing this as the code has changed again. I will open an issue with the problem because I don't want to fix this for the third time unless we agree what to do.

2018-01-17 14:17 UTC, closed without merging