Bumping min CMake version
KratosMultiphysics/Kratos pull request #12094
Opened 2024-02-20 13:00 UTC by roigcarlo

**📝 Description**
Bumping minimal cmake version to 3.21 (If not possible, we can live with 3.15)

@KratosMultiphysics/altair Please check that this PR does not break your CI's
@KratosMultiphysics/geomechanics Same, please check that this does not break any CI on your side.

2024-02-20 14:05 UTC, sunethwarna commented
Should we remove the following in a different PR or in this same PR?
https://github.com/KratosMultiphysics/Kratos/blob/fe329f4a1feb08a82a3795c64ad65377068545b9/scripts/post_install/CMakeLists.txt#L4-L10

2024-02-20 14:06 UTC, sunethwarna commented
Oh, nvm :)

2024-02-21 12:07 UTC, philbucher approved these changes
:love_you_gesture:

2024-02-21 12:15 UTC, loumalouomega commented
~~~sh
:: initializing oneAPI environment ...
   d07ced12-1044-45b5-89cd-55cd85c255a6.sh: BASH_VERSION = 5.1.16(1)-release
   args: Using "$@" for setvars.sh arguments: 
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dpl -- latest
:: mkl -- latest
:: tbb -- latest
:: oneAPI environment initialized ::
 
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/kratos/python_scripts/testing/run_tests.py", line 1, in <module>
    import KratosMultiphysics as KM
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/__init__.py", line 16, in <module>
    from . import python_registry
  File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/python_registry.py", line 4, in <module>
    from KratosMultiphysics.kratos_utilities import GetListOfAvailableApplications
ModuleNotFoundError: No module named 'KratosMultiphysics.kratos_utilities'
~~~

Why?

2024-02-21 12:15 UTC, loumalouomega commented
> ```shell
> :: initializing oneAPI environment ...
>    d07ced12-1044-45b5-89cd-55cd85c255a6.sh: BASH_VERSION = 5.1.16(1)-release
>    args: Using "$@" for setvars.sh arguments: 
> :: compiler -- latest
> :: debugger -- latest
> :: dev-utilities -- latest
> :: dpl -- latest
> :: mkl -- latest
> :: tbb -- latest
> :: oneAPI environment initialized ::
>  
> Traceback (most recent call last):
>   File "/__w/Kratos/Kratos/kratos/python_scripts/testing/run_tests.py", line 1, in <module>
>     import KratosMultiphysics as KM
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/__init__.py", line 16, in <module>
>     from . import python_registry
>   File "/__w/Kratos/Kratos/bin/Custom/KratosMultiphysics/python_registry.py", line 4, in <module>
>     from KratosMultiphysics.kratos_utilities import GetListOfAvailableApplications
> ModuleNotFoundError: No module named 'KratosMultiphysics.kratos_utilities'
> ```
> 
> Why?

Looks like it is compiled but not installed?

2024-02-21 12:17 UTC, loumalouomega commented
> Oh, nvm :)

![](https://preview.redd.it/tfugj4n3l6ez.png?auto=webp&s=b8163176d8482d5e78ac631e16b7973a52e3b188)

2024-02-21 12:33 UTC, loumalouomega requested changes
Block until CI @KratosMultiphysics/altair  passed

2024-02-21 13:07 UTC, loumalouomega commented
> Block until CI @KratosMultiphysics/altair passed

I can confirm as in Kratos CI our CI fails, same reason, the compilation is not installed?

2024-02-21 13:28 UTC, roigcarlo commented
Yep i am aware, trying to understand why, most likely a policy

2024-03-05 11:04 UTC, roigcarlo commented
Will close this until #11790 is merged

2024-03-05 11:04 UTC, closed without merging