[ConvDiffApp] Adding Substepping thermomechanical solver
KratosMultiphysics/Kratos pull request #12126
Opened 2024-03-01 04:41 UTC by AlejandroCornejo

**📝 Description**
In this PR I am adding a substepping version of the thermomechanical coupled solver. 

A coupled one-way thermo-mechanical solver in which the time step of the two solvers is independent. It is assumed that the dt of the structural part is equal or lower than the thermal one.

2024-03-01 08:02 UTC, rubenzorrilla requested changes
Though this is a long-demanded feature, I think we should discuss it carefully. At first glance I see two important things in here:
1. Time advance has been so far handled at the `AnalysisStage` level. Changes in this PR go against this.
2. Substepping strategy must be the same across applications.

2024-03-01 08:39 UTC, AlejandroCornejo commented
Hi! Let me comment your questions

1. _Time advance has been so far handled at the AnalysisStage level. Changes in this PR go against this._ Actually I am not technically advancing time in non of the solvers. I use this pseudo structural time to know how many steps are needed/done but the `AdvanceInTime` is done as in other solvers.

2. That is something that we can discuss

2024-03-01 09:12 UTC, loumalouomega commented on applications/ConvectionDiffusionApplication/python_scripts/coupled_structural_thermal_solver.py
```suggestion
```

2024-03-01 09:13 UTC, loumalouomega commented on applications/ConvectionDiffusionApplication/python_scripts/coupled_structural_thermal_substepping_solver.py
> +
```suggestion
```

2024-03-01 12:42 UTC, philbucher commented on applications/ConvectionDiffusionApplication/python_scripts/coupled_structural_thermal_substepping_solver.py
> +        super(CoupledThermoMechanicalSubsteppingSolver, self).__init__(model, custom_settings)
```suggestion
        super().__init__(model, custom_settings)
```

2024-03-01 12:42 UTC, philbucher commented on applications/ConvectionDiffusionApplication/python_scripts/coupled_structural_thermal_substepping_solver.py
> +        self.var_utils = KratosMultiphysics.VariableUtils()
```suggestion
```

this should be instantiated in place

2024-03-01 12:42 UTC, philbucher commented on applications/ConvectionDiffusionApplication/python_scripts/python_solvers_wrapper_convection_diffusion.py
> +        elif (solver_type == "thermo_mechanically_coupled_substepping" or solver_type == "ThermoMechanicallyCoupledSubstepping"):
```suggestion
        elif solver_type == "thermo_mechanically_coupled_substepping":
```

new solvers should only use the json style

2024-05-27 09:37 UTC, RiccardoRossi commented on applications/ConvectionDiffusionApplication/python_scripts/coupled_structural_thermal_substepping_solver.py
> +            self.RemoveConvectiveVelocity()
the database does not go back to the original status for the past steps, is that correct?

2024-11-23 20:27 UTC, AlejandroCornejo commented
state of this?

2024-11-26 07:58 UTC, loumalouomega commented
> > state of this?
> 
> ❄️

Ironic, because is thermomechanic...

2024-11-26 12:10 UTC, rubenzorrilla commented
> Is this in the TO-DO list of the @KratosMultiphysics/technical-committee ?

It is since long ago.

2024-12-16 10:09 UTC, RiccardoRossi commented
@rubenzorrilla and @RiccardoRossi will do some brainstorming about this and come back with a concrete proposal

2025-02-11 11:20 UTC, RiccardoRossi commented
This one was discussed in the @KratosMultiphysics/technical-committee and @pooyan-dadvand has an idea for solving this nicely. He will make a proposal over the next months for a way of storing substep data at nodes.

2026-03-29 18:03 UTC, closed without merging