StructuralMechanics: Process for comparing the eigenvalues postprocessing files
KratosMultiphysics/Kratos pull request #1247
Opened 2018-01-07 00:25 UTC by philbucher

The test `Eigen_Q4_Thick_2x2_Plate_test` failes bcs I added the file postprocessing checking (introduced in #1079 ) with plain file comparison.
This does not work bcs of machine accuracies so I wrote a process that checks the values.
I checked this on two machines, now it should work fine 

Feast is needed to run this test in case you try (this test is skipped if feast is not available)

2018-01-07 13:55 UTC, philbucher commented
Hi @msandre I think you also noticed that the test failed, could you please try if it works for you? Thx

2018-01-07 16:43 UTC, loumalouomega submitted a review, later dismissed
Ok for me

2018-01-07 23:08 UTC, philbucher commented
Vicente did you run the test?

2018-01-08 11:08 UTC, loumalouomega commented
![imagen](https://user-images.githubusercontent.com/19991680/34668198-90569f5c-f46c-11e7-94eb-189407059a47.png)

2018-01-08 11:13 UTC, loumalouomega commented
Maybe we should add .res to the gitignore to avoid having new files detected by git

2018-01-08 12:51 UTC, philbucher commented
thx @loumalouomega 
Yep adding .res to gitignore makes sense in my eyes.

I also wanted to add a process that deletes files, e.g. after a test

@loumalouomega what is this new code review tool? should we follow it or what is the rule on this?

2018-01-08 13:14 UTC, loumalouomega commented
We should, @pooyan-dadvand says

2018-01-08 13:21 UTC, msandre requested changes

2018-01-08 13:21 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/check_postprocess_eigenvalues_file_process.py
> +                                       abs(float(tmp2[j])), 15)
It would be good if you could make the tolerance an input parameter instead of hard coding it.

2018-01-08 13:21 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/check_postprocess_eigenvalues_file_process.py
> +        lines1 = ref_file.readlines()
Could you name these variables something like ref_lines and output_lines or check_lines?

2018-01-08 13:21 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/check_postprocess_eigenvalues_file_process.py
> +            for j in range(len(tmp1)):
Code readability could be improved here by doing something like 

```
for ref_value, output_value in zip(list_of_ref_values, list_of_output_values):
    self.assertAlmostEqual(...)
```

2018-01-08 13:21 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/check_postprocess_eigenvalues_file_process.py
> +                results_available = True
I think `results_found` would be better here.

2018-01-08 13:21 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/check_postprocess_eigenvalues_file_process.py
> +    This process compares the *.post.res file written by the PostprocessEigenvaluesProcess
This class assumes a certain results format. Can you give a ref to the format or to the class that creates the results file expected by this class?

2018-01-08 14:56 UTC, pooyan-dadvand commented
The codacy is an static analysis tool and I am testing its output on Kratos. At this moment is not forced to comply it to be merge-able but of course I would encourage you to take a look at its reports. 

Nevertheless some tuning of its rules are necessary to be practical in Kratos. Of course all your comments are welcomed and I will make an issue for that.

2018-01-08 16:14 UTC, philbucher commented
Hi @pooyan-dadvand thx for the explanation
I completely agree with using this, one improvement I am not sure abt is [this line](https://github.com/KratosMultiphysics/Kratos/pull/1247/files#diff-ed4eee0fbd7d8e122d2a8a4f643beaf6R12). The type checking is used everywhere, I didn't come up with this. In this case I think type checking is actually better, unless there will be derived classes of `Parameters`

2018-03-02 09:17 UTC, philbucher commented
Hi guys,
I finally had time to finish this, sorry it took so long.

I changed how I test the process, now the test is self-contained

I implemented the comparison of `.post.res` files in a generic way in the `CompareTwoFilesCheckProcess` such that it can also be used by others

@loumalouomega I improved this process a bit and slightly changed the interface. I updated the tests in the MeshingApplication, but I cannot run them because I don't have MMG installed. Could you please run them and see if they are still working? (no need to recompile I only changed python files)

2018-03-02 09:33 UTC, loumalouomega approved these changes
For me OK, it is clearer, sorry if I chose a bad name :P

2018-03-02 11:00 UTC, msandre approved these changes

2018-03-02 11:24 UTC, merged