[Structural] Schemes for OSS and testing
KratosMultiphysics/Kratos pull request #12585
Opened 2024-07-29 10:48 UTC by rubenzorrilla

**📝 Description**
In this PR I'm adding two new static and Bossak schemes to the `StructuralMechanicsApplication`. The requirement of these comes from the need of doing the L2-projections for OSS-stabilised formulations. Nevertheless, I made them with generality in mind so we can eventually use them also for other purposes. Of course these derive from the corresponding `KratosCore` schemes, so they are almost empty.

Changes in the `KratosCore` basically resume to the addition of the reaction variables corresponding to the projections (for the non-linear OSS case) and minors in the base schemes in order to call some methods from the new derived classes.

Tests have been added and modified accordingly.

2024-07-29 11:58 UTC, loumalouomega submitted a review, later dismissed

2024-07-29 13:32 UTC, philbucher requested changes
minor comments, but please reduce the huge test file sizes

2024-07-29 13:32 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_implicit_dynamic_solver.py
> +        oss_available_schemes = ["newmark","bossak"]
```suggestion
        oss_available_schemes = ("newmark","bossak")
```

2024-07-29 13:32 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_implicit_dynamic_solver.py
> +        if (scheme_type == "newmark" or scheme_type == "bossak"):
```suggestion
        if scheme_type in ("newmark", "bossak"):
```

2024-07-29 14:32 UTC, rubenzorrilla commented
> minor comments, but please reduce the huge test file sizes

The test is the one that we use to have but now with different elements. Note that the large test is in the nightly suite (in the small one I only added a patch test).

2024-07-29 15:24 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/cook_membrane_test/cook_membrane_incompressible_oss_results.json
I guess you check the results on every node, can you only check a few selected instead?

2024-07-30 09:06 UTC, rubenzorrilla commented on applications/StructuralMechanicsApplication/tests/cook_membrane_test/cook_membrane_incompressible_oss_results.json
Sure. Lets do this.

2024-07-30 09:55 UTC, rubenzorrilla commented
@philbucher should be ready now. Thanks for noting it.

2024-07-30 10:13 UTC, philbucher approved these changes

2024-07-30 14:50 UTC, rubenzorrilla commented
CI is failing because of the MPM application Python tests... @KratosMultiphysics/mpm

2024-08-01 09:40 UTC, rubenzorrilla commented
@ncrescenzio MPM application Python tests are still failing. I guess the problem comes from this one
````
2024-07-31T16:32:27.4190338Z test_execution (restart_tests.MPMRestartTestDynamicCantilever2D) ... malloc(): unaligned tcache chunk detected
````

2024-08-01 10:14 UTC, ncrescenzio commented
> @ncrescenzio MPM application Python tests are still failing. I guess the problem comes from this one
> 
> ```
> 2024-07-31T16:32:27.4190338Z test_execution (restart_tests.MPMRestartTestDynamicCantilever2D) ... malloc(): unaligned tcache chunk detected
> ```

I have seen, but this is not the same test that was failing two days ago... I am trying to find the problem but at the moment I am not able to reproduce the issue on my laptop...

2024-08-01 13:56 UTC, merged

2024-08-02 06:37 UTC, rubenzorrilla commented
Automerge was enabled but I don't really know how this got merged as nothing apparently changed in the branch...

2024-08-02 08:05 UTC, ncrescenzio commented
It seems that the test is not always failing (the same happened with the one i fixed in #12593). So I have tried to run again the tests in the CI only for the configuration that is having issues (ubuntu, full debug, clang) and this time they all passed. Same happened in PR #12597.
If in some other PRs the the same test is failing (`MPMRestartTestDynamicCantilever2D`), I suggest to try to run again the tests. At the moment I have no idea how to fix the problem because on my laptop everything is working

2024-08-02 16:29 UTC, rubenzorrilla commented
> It seems that the test is not always failing (the same happened with the one i fixed in #12593). So I have tried to run again the tests in the CI only for the configuration that is having issues (ubuntu, full debug, clang) and this time they all passed. Same happened in PR #12597. If in some other PRs the the same test is failing (`MPMRestartTestDynamicCantilever2D`), I suggest to try to run again the tests. At the moment I have no idea how to fix the problem because on my laptop everything is working

According to your description, it could be a memory leak. Did you try to run the case with `FullDebug` build and Valgrind?