[CORE] Move initial residual assignment
KratosMultiphysics/Kratos pull request #12604
Opened 2024-08-02 12:44 UTC by juancamarotti

This PR addresses #12394 [Incorrect initial residuals for convergence criteria in CoSim]

## Changes
We moved the initial residual assignment from `InitializeSolutionStep` to `PostCriteria`with the condition that the `NL_ITERATION_NUMBER` must be 1. This ensures that the initial residual is updated between coupling iterations. 

## Drawback
The initial residual is computed after the first non-linear iteration, since we do not have access to the residual before the first one.

## Outlook
Properly solving this problem would mean adding new virtual functions for the initialization and finalization of the non linear solvers and related objects. This would be an extensive change what we are planning to implement in the future,. However, for now, this solution is less inaccurate than the current state. 

FYI @philbucher @matekelemen @sunethwarna @Igarizza

2024-08-02 16:27 UTC, rubenzorrilla requested changes
This means that you're always doing a non-linear iteration (with the corresponding call to the linear solver) even though the residual criteria are fulfilled. If so, this is in my opinion a delicate change that requires careful discussion.

2024-08-02 16:46 UTC, juancamarotti commented
With this new implementation, convergence could be achieved in the first iteration in an absolute sense. Is that what you mean? @rubenzorrilla

2024-08-03 07:50 UTC, rubenzorrilla commented
> With this new implementation, convergence could be achieved in the first iteration in an absolute sense. Is that what you mean? @rubenzorrilla

I mean in zero iteration (if provided guess already accomplishes with the convergence criteria)

2024-08-03 08:27 UTC, matekelemen commented
> I mean in zero iteration (if provided guess already accomplishes with the convergence criteria)

Ok, having a closer look at the implementation of [`ResidualBasedNewtonRaphsonStrategy`](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L941-L995) it looks like with this PR, we're actually computing the initial residual **before the first nonlinear iteration**, which is exactly what we want so there's no drawback.

The confusion comes from `NL_ITERATION_NUMBER` being [set to 1](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L940-L941) before the first iteration. At the very beginning of the first nonlinear iteration, `NL_ITERATION_NUMBER` [is incremented](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L992-L995), so the first iteration actually runs with iteration number 2 ...

2024-08-06 06:36 UTC, juancamarotti commented
> > I mean in zero iteration (if provided guess already accomplishes with the convergence criteria)
> 
> Ok, having a closer look at the implementation of [`ResidualBasedNewtonRaphsonStrategy`](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L941-L995) it looks like with this PR, we're actually computing the initial residual **before the first nonlinear iteration**, which is exactly what we want so there's no drawback.
> 
> The confusion comes from `NL_ITERATION_NUMBER` being [set to 1](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L940-L941) **before** the first iteration. At the very beginning of the first nonlinear iteration, `NL_ITERATION_NUMBER` [is incremented](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L992-L995), so the **first iteration actually runs with iteration number 2** ...

I agree with @matekelemen on this point. What do you think @rubenzorrilla?

2024-08-07 11:14 UTC, rubenzorrilla commented
> > > I mean in zero iteration (if provided guess already accomplishes with the convergence criteria)
> > 
> > 
> > Ok, having a closer look at the implementation of [`ResidualBasedNewtonRaphsonStrategy`](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L941-L995) it looks like with this PR, we're actually computing the initial residual **before the first nonlinear iteration**, which is exactly what we want so there's no drawback.
> > The confusion comes from `NL_ITERATION_NUMBER` being [set to 1](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L940-L941) **before** the first iteration. At the very beginning of the first nonlinear iteration, `NL_ITERATION_NUMBER` [is incremented](https://github.com/KratosMultiphysics/Kratos/blob/03e42164e26fa06bdeaed54389a86e1fee3c4d7f/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L992-L995), so the **first iteration actually runs with iteration number 2** ...
> 
> I agree with @matekelemen on this point. What do you think @rubenzorrilla?

- There are more stategies than the NR that might be using this
- Tests from several applications are failing so I'm still a bit hesitant about saying that the behavior is exactly the same...

2026-03-17 16:32 UTC, closed without merging