[GeoMechanicsApplication] Create documentation for the new line interface geometry
KratosMultiphysics/Kratos pull request #12647
Opened 2024-08-26 09:29 UTC by rfaasse

2024-08-26 11:08 UTC, WPK4FEM reviewed
Thank you for the good start of documentation for interfaces. Not much to complain about. The documentation may grow as point or plane interfaces and diff-order interfaces are added.

2024-08-26 11:08 UTC, WPK4FEM commented on applications/GeoMechanicsApplication/custom_geometries/2Plus2NodedLineGeometry.svg
Nice pictures! Maybe wise to indicate the \xi axis here (with origin in the middle of the mid-geometry.
Another question is how we clarify that this is 2 dimensional geometry.

2024-08-26 11:08 UTC, WPK4FEM commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +The geometry is defined by two lines, one on each side of the interface, where they can connect to the larger body of the domains separated by the interface. Most calculations are performed on the 'm
The first sentence is quite complex and with many comma's. I suggest make the last part a separate sentence. The lines connect to other model parts, that not necessarily are "larger bodies". ( you can also connect a line to a body using an interface. The line then still is "smaller" than the interface.

2024-08-26 11:11 UTC, mnabideltares requested changes
@rfaasse 
Thank for for the documentation., I have just few minor comments

2024-08-26 11:11 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +One thing to note, is that this line interface geometry does not implement functions from the Geometry base class which are related to the integration scheme. That is because most of the time, interf
It needs to be mentioned that this geometry is not independent, and it is based on line geometry of 2d_2n, and 2d_3n, which are available in the core

2024-08-26 11:11 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +Geometries are responsible for calculating several geometric properties, such as the normal vector, shape function values at a given position and the (inverse/determinant of the) Jacobian. This folde
As far as I remember, the inverse of jacobian is not defined for this geometry!

2024-08-26 11:11 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +![2Plus2NodedGeometry](2Plus2NodedLineGeometry.svg)
Needs to define the local coordinate in the picture

2024-08-26 12:08 UTC, rfaasse reviewed
Thanks for the quick review, I processed the comments, let me know if this is what you had in mind.

2024-08-26 12:08 UTC, rfaasse commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +Geometries are responsible for calculating several geometric properties, such as the normal vector, shape function values at a given position and the (inverse/determinant of the) Jacobian. This folde
Indeed, for our geometry, the inverse is not defined. This first part is a short intro on geometries in general (which could have them defined). Do you think we should mention explicitly here that the inverse of the jacobian is not implemented for the interface (because it isn't for the underlying lines?)

2024-08-26 12:08 UTC, rfaasse commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +One thing to note, is that this line interface geometry does not implement functions from the Geometry base class which are related to the integration scheme. That is because most of the time, interf
Good point, I added links to the line_2d_2.h and line_2d_3.h files.

2024-08-26 12:08 UTC, rfaasse commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +The geometry is defined by two lines, one on each side of the interface, where they can connect to the larger body of the domains separated by the interface. Most calculations are performed on the 'm
Done, let me know if this was what you meant!

2024-08-26 12:08 UTC, rfaasse commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +![2Plus2NodedGeometry](2Plus2NodedLineGeometry.svg)
Agreed, done

2024-08-26 12:08 UTC, rfaasse commented on applications/GeoMechanicsApplication/custom_geometries/2Plus2NodedLineGeometry.svg
I added the $\xi$ axis and an xy indication, I think that should do it.

2024-08-26 12:25 UTC, mnabideltares requested changes
@rfaasse 
Thank you for adressing the review points. I still have few minor suggestions

2024-08-26 12:25 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +Geometries are responsible for calculating several geometric properties, such as the normal vector, shape function values at a given position and the (inverse/determinant of the) Jacobian. This folde
I think it is not necessary to mention that the inverse Jacobian is not calculated/defined for this geometry. It is too much details. So, maybe it is good to leave the text as it is.

2024-08-26 12:25 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +![2Plus2NodedGeometry](2Plus2NodedLineGeometry.svg)
I think x-y is irrelevant here. It is in xi , one dimensional local coordinate(s).

2024-08-26 12:25 UTC, mnabideltares commented on applications/GeoMechanicsApplication/custom_geometries/README.md
> +![3Plus3NodedGeometry](3Plus3NodedLineGeometry.svg)
It is more clear if the length is mentioned here, namely -1 to +1. However, as it is a dependent geometry, maybe a full picture is needs in the original geometry. So, I leave it up to you!!!

2024-08-27 07:46 UTC, WPK4FEM approved these changes
Good to go for me.

2024-08-27 07:46 UTC, mnabideltares approved these changes
Ok to me

2024-08-27 07:57 UTC, merged