additional SBM features to nurbs_curve_on_surface_geometry
KratosMultiphysics/Kratos pull request #12717
Opened 2024-10-02 08:58 UTC by NickNick9

**📝 Description**
We have added to the nurbs_curve_on_surface_geometry the possibility of considering an SBM brep surface.
Instead of using the method ComputeAxisIntersection, in the SBM case we use a different one called ComputeAxisIntersectionSBM (that only looks for intersections on the knot vertices).

Moreover, we have also added the SBM case in the CreareQuadraturePoints method in the same file.

IgaApplication
Geometry

2024-10-02 13:43 UTC, AlejandroCornejo commented on kratos/geometries/nurbs_curve_on_surface_geometry.h
> +        double physical_length_segment = norm_2(physical_coord_1-physical_coord_2);
const?

2024-10-02 13:43 UTC, AlejandroCornejo commented on kratos/sources/variables.cpp
> +KRATOS_CREATE_VARIABLE(bool, IS_SBM)
maybe `IS_SHIFTED_BOUNDARY` ?

2024-10-02 15:39 UTC, rubenzorrilla requested changes
I need to do a further review, but at first glance, I'm not a big fan of adding a geometry that depends on the method... In other words, I don't really like the `IS_SBM` stuff. Can you please justify its need?

2024-10-03 07:59 UTC, NickNick9 commented
@rubenzorrilla  > I need to do a further review, but at first glance, I'm not a big fan of adding a geometry that depends on the method... In other words, I don't really like the `IS_SBM` stuff. Can you please justify its need?

@NickNick9 
The fact is that our SBM stuff is very similar to the IBRA one. So we basically use the same geometries, but at the very end, we only cut along the knot vertices. So in more than one place, we have to differentiate between the two (Create an additional function SpansLocalSpace_SBM would be complex because it is called in many other places and still we would need a flag I guess). We are planning to use the IS_SBM when we create the gauss points for example.

So my reason is: SBM and IBRA conceptually are very similar, we want a flag that says which approach you want to use when you have to deal with the un-fitted boundary in IGA.

2024-12-16 09:33 UTC, rubenzorrilla commented on kratos/geometries/nurbs_curve_on_surface_geometry.h
> +    void SpansLocalSpaceSBM(std::vector<double>& rSpans, IndexType DirectionIndex = 0) const
```suggestion
    void SpansLocalSpaceSBM(
        std::vector<double>& rSpans,
        IndexType DirectionIndex = 0) const
```
Please follow the [style guide](https://kratosmultiphysics.github.io/Kratos/pages/Kratos/For_Users/Conventions/Style_Guide.html).

2024-12-16 09:34 UTC, rubenzorrilla commented on kratos/geometries/nurbs_curve_on_surface_geometry.h
> +        double Start, double End) const
```suggestion
    void SpansLocalSpaceSBM(
        std::vector<double>& rSpans,
        double Start,
        double End) const
```
Same comment.

2024-12-16 12:01 UTC, rubenzorrilla reviewed
Overall makes sense. Nevertheless, I'd indicate the upcoming changes with code comments. Specially the unification of the SBM and the untrimmed cases, which is something that IMO must be done for sure (most probably in a future PR).

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/tests/cpp_tests/geometries/test_nurbs_curve_on_surface_geometry.cpp
> +        NurbsCurveOnSurfaceGeometry<3, PointerVector<Point>, PointerVector<Point>> curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
Can't you continue using the `auto` type?
```suggestion
        auto curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
```

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/tests/cpp_tests/geometries/test_nurbs_curve_on_surface_geometry.cpp
> +        NurbsCurveOnSurfaceGeometry<3, PointerVector<Point>, PointerVector<Point>> curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
Can't you continue using the `auto` type?
```suggestion
        auto curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
```

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/tests/cpp_tests/geometries/test_nurbs_curve_on_surface_geometry.cpp
> +        NurbsCurveOnSurfaceGeometry<3, PointerVector<Point>, PointerVector<Point>> curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
Can't you continue using the `auto` type?

```suggestion
        auto curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
```

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/tests/cpp_tests/geometries/test_nurbs_curve_on_surface_geometry.cpp
> +        NurbsCurveOnSurfaceGeometry<3, PointerVector<Point>, PointerVector<Point>> curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
Can't you continue using the `auto` type?

```suggestion
        auto curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
```

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/tests/cpp_tests/geometries/test_nurbs_curve_on_surface_geometry.cpp
> +        NurbsCurveOnSurfaceGeometry<3, PointerVector<Point>, PointerVector<Point>> curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
Can't you continue using the `auto` type?

```suggestion
        auto curve_on_surface = GenerateReferenceNurbs2dforKnotIntersections(brep_coordinates);
```

2024-12-16 12:01 UTC, rubenzorrilla commented on kratos/sources/variables.cpp
> +
Do `checkout master variables.cpp` and commit to revert the file to master status.

2024-12-17 15:25 UTC, rubenzorrilla commented on kratos/includes/variables.h
> +    KRATOS_DEFINE_VARIABLE(bool, IS_SBM)
These are no longer needed right?

2024-12-17 15:25 UTC, rubenzorrilla commented on kratos/sources/variables.cpp
> +KRATOS_CREATE_VARIABLE(bool, IS_SBM)
I think is no longer needed.

2024-12-17 15:26 UTC, rubenzorrilla commented on kratos/sources/variables.cpp
> +    KRATOS_REGISTER_VARIABLE(IS_SBM)
I think is no longer needed.

2024-12-17 16:01 UTC, andrewgorgi commented on kratos/sources/variables.cpp
> +    KRATOS_REGISTER_VARIABLE(IS_SBM)
Is it possible that you are referring to an old commit? The last commit should be without any modification on the variables.h/.cpp files

2024-12-17 17:39 UTC, rubenzorrilla commented on kratos/sources/variables.cpp
> +    KRATOS_REGISTER_VARIABLE(IS_SBM)
You're right. My notifications got crazy.

2024-12-17 17:41 UTC, rubenzorrilla commented
> Overall makes sense. Nevertheless, I'd indicate the upcoming changes with code comments. Specially the unification of the SBM and the untrimmed cases, which is something that IMO must be done for sure (most probably in a future PR).

Did you already add the comments I mentioned in here? (I did not find them).

2024-12-18 14:00 UTC, rubenzorrilla approved these changes
All my initial concerns have been addressed (aside of the unification of the traditional and SBM integration points creation, which will be done in an upcoming PR).

2024-12-18 14:01 UTC, merged