[OptApp] License File update
KratosMultiphysics/Kratos pull request #12829
Opened 2024-11-07 13:03 UTC by Igarizza

**🆕 Changelog**
This pull request includes a change to the `applications/OptimizationApplication/license.txt` file. The most important change is the update to the copyright information.

**📝 Description**
* Updated the copyright information to include new contributors and affiliations.

2024-11-07 15:34 UTC, RezaNajian requested changes
Please add new contributors to a new line after line 4, i mean add to the line 5.

2024-11-07 15:57 UTC, Igarizza commented
> Please add new contributors to a new line after line 4, i mean add to the line 5.

done

2024-11-08 15:02 UTC, philbucher commented on applications/OptimizationApplication/license.txt
> +	Roland Wüchner *
can you reference the commits of this contributor please? :stuck_out_tongue:

2024-11-12 12:50 UTC, Igarizza commented
@RezaNajian @sunethwarna If there are no more comments I will merge it=)

2024-12-09 19:24 UTC, RezaNajian approved these changes

2024-12-09 19:24 UTC, merged