[Documentation] Adding `Registry` class documentation
KratosMultiphysics/Kratos pull request #12928
Opened 2024-12-11 14:25 UTC by loumalouomega

**📝 Description**

Adding `Registry` class documentation. ALso enhance the in code documentation of the `Registry` and `RegistryItem` classes.

**🆕 Changelog**

- [Adding `Registry` class documentation](https://github.com/KratosMultiphysics/Kratos/commit/e6a6b3e9f2a9612a3995fac7fd6a7c7491767dbd)
- [Enhance `Registry` class documentation with detailed descriptions](https://github.com/KratosMultiphysics/Kratos/commit/21f4abef9a923d14610886e72b200a33c4a372f4)
- [Adding extra documentation to `RegistryItem` class](https://github.com/KratosMultiphysics/Kratos/commit/80b7b885c445a61f661a50caefde426b3833361c)

2024-12-11 15:59 UTC, rubenzorrilla requested changes
Documentation seems to be AI-generated and, in my opinion, is far from being useful for users. Indeed, there are some things wrong (e.g., the cpp layer is deliberately hidden from Python, so users do not need to distinguish the cpp and Python layers when retrieving).

2024-12-11 16:15 UTC, loumalouomega commented
> Documentation seems to be AI-generated and, in my opinion, is far from being useful for users. Indeed, there are some things wrong (e.g., the cpp layer is deliberately hidden from Python, so users do not need to distinguish the cpp and Python layers when retrieving).

It is AI assisted, but I reviewed. Currently there is no documentation at all, so if you need to use it you need to read the code and understand it. It took me 3 hours yesterday because without the Prototype word was not working and the error message wasnot giving any feedback. Tell me something you feel off and i will remove it.

2024-12-11 16:18 UTC, loumalouomega commented
> > Documentation seems to be AI-generated and, in my opinion, is far from being useful for users. Indeed, there are some things wrong (e.g., the cpp layer is deliberately hidden from Python, so users do not need to distinguish the cpp and Python layers when retrieving).
> 
> It is AI assisted, but I reviewed. Currently there is no documentation at all, so if you need to use it you need to read the code and understand it. It took me 3 hours yesterday because without the Prototype word was not working and the error message was not giving any feedback. Tell me something you feel off and i will remove it.

The documentation includes examples, I think people will appreciate it.

2024-12-11 16:27 UTC, rubenzorrilla commented
OK. If you don't mind I would like to edit it a bit by myself?

2024-12-11 16:36 UTC, loumalouomega commented
> OK. If you don't mind I would like to edit it a bit by myself. I agree that right now the `Registry` is useless because no one knows how to fill it / use it.
> 
> EDIT: I'll try to find the time to make it soon.

Feel free

2025-01-08 10:03 UTC, loumalouomega commented
> > OK. If you don't mind I would like to edit it a bit by myself. I agree that right now the `Registry` is useless because no one knows how to fill it / use it.
> > EDIT: I'll try to find the time to make it soon.
> 
> Feel free

👋

2025-01-11 14:29 UTC, rubenzorrilla commented
> > > OK. If you don't mind I would like to edit it a bit by myself. I agree that right now the `Registry` is useless because no one knows how to fill it / use it.
> > > EDIT: I'll try to find the time to make it soon.
> > 
> > 
> > Feel free
> 
> 👋

Perdona Tote, voy de culo. Lo hago ASAP.

2025-01-13 11:57 UTC, rubenzorrilla commented
@loumalouomega I made the changes. Let me know if you're OK.

2025-01-13 12:33 UTC, loumalouomega commented
> @loumalouomega I made the changes. Let me know if you're OK.

Now, it is perfect

2025-01-13 13:03 UTC, rubenzorrilla approved these changes

2025-01-13 16:18 UTC, merged