removing unneeded virtual public from convergence criterias
KratosMultiphysics/Kratos pull request #1292
Opened 2018-01-12 15:17 UTC by RiccardoRossi

this PR takes out "virtual public" and "public virtual" which were wrongly added to some convergence criterias. 

@loumalouomega @msandre @jcotela @roigcarlo can u grep "virtual public" and "public virtual" and see if it is needed? this is a forward looking change...so please take them out if you can

2018-01-13 18:24 UTC, loumalouomega submitted a review, later dismissed
OK

2018-01-13 18:30 UTC, roigcarlo requested changes
These ones are missing i think

* applications/SolidMechanicsApplication/custom_strategies/convergence_criteria/displacement_convergence_criterion.hpp
* applications/SolidMechanicsApplication/custom_strategies/convergence_criteria/component_wise_residual_convergence_criterion.hpp

2018-01-14 11:44 UTC, RiccardoRossi commented
@roigcarlo done

2018-01-14 18:19 UTC, msandre commented
removed all instances from hdf5 application.

2018-01-15 15:03 UTC, roigcarlo approved these changes
All good :+1:

2018-01-15 15:25 UTC, merged