Adding missing methods to VariableUtils
KratosMultiphysics/Kratos pull request #1339
Opened 2018-01-18 18:03 UTC by loumalouomega

TODO: Discuss about names of the methods (specially python)

2018-01-18 18:05 UTC, loumalouomega commented on kratos/python/add_utilities_to_python.cpp
> +    .def("SetVariable", &VariableUtils::SetVariable< bool >)
Should the non historical values have a methods just called SetVariable?, and then a different name for the historical variables (just the nodes have historical variables)

2018-01-23 11:59 UTC, loumalouomega commented
@RiccardoRossi PING

2018-01-27 16:01 UTC, loumalouomega commented
@RiccardoRossi PING

2018-02-05 10:12 UTC, loumalouomega commented
@RiccardoRossi PING

2018-02-05 11:30 UTC, rubenzorrilla commented on kratos/utilities/variable_utils.cpp
> +void VariableUtils::SetVectorVarNonHistorical(
I would call it SetNonHistoricalVectorVar.

2018-02-05 11:30 UTC, rubenzorrilla commented on kratos/utilities/variable_utils.h
> +    void SetScalarVarNonHistorical(
Same

2018-02-05 11:40 UTC, loumalouomega commented on kratos/utilities/variable_utils.cpp
> +void VariableUtils::SetVectorVarNonHistorical(
@rubenzorrilla Let's wait what @RiccardoRossi

2018-02-05 11:45 UTC, RiccardoRossi reviewed
I am fine with the commit. I agree with @rubenzorrilla 's comment on the name. So i let him approve this

2018-02-05 11:46 UTC, loumalouomega commented
OK, I will change it

2018-02-05 13:48 UTC, loumalouomega commented
Done

2018-02-05 13:50 UTC, loumalouomega commented
Besides I just discover you cannot access in python to the components of a variable fro conditions and elements, I will add it in a different PR

2018-02-05 14:14 UTC, loumalouomega commented
I cannot add a GetValue for components in python for conditions and elements, so avoid my previous comment

2018-02-06 16:50 UTC, loumalouomega commented
Ping

2018-02-08 19:13 UTC, loumalouomega commented
![imagen](https://user-images.githubusercontent.com/19991680/35867376-e2292dfa-0b59-11e8-8ec9-db7ad94a9d5c.png)

2018-02-13 15:59 UTC, loumalouomega commented
PING

2018-02-13 16:02 UTC, rubenzorrilla requested changes
Please check Codacy suggestion. I'm approving as soon as you fix that.

2018-02-13 16:33 UTC, rubenzorrilla approved these changes

2018-02-13 17:41 UTC, merged