MMG and other MeshingApplication Doxygen improve/Clean up
KratosMultiphysics/Kratos pull request #1453
Opened 2018-02-05 20:41 UTC by loumalouomega

2018-02-11 13:21 UTC, loumalouomega commented
Ping

2018-02-12 09:08 UTC, pooyan-dadvand commented
I think that you should divide this PR in two. Changes in code, not only in doxygen files

2018-02-12 09:31 UTC, loumalouomega commented
I thought that, but the changes are minor tweaks, I can separate it in several PR for several files

2018-02-12 13:15 UTC, pooyan-dadvand requested changes
You are adding global enums to Kratos namespace which is not a good practice...

2018-02-12 13:35 UTC, loumalouomega commented
Even with enum class?

2018-02-13 08:36 UTC, RiccardoRossi submitted a review, later dismissed
please take a look at my comments. at least one looks like a typo (you are summing twice the same var).

I approvie in case it is the expected behaviour

2018-02-13 08:36 UTC, RiccardoRossi commented on applications/MeshingApplication/custom_processes/internal_variables_interpolation_process.h
> +     * @details There are mainly two ways to interpolate the internal variables (there are three, but just two are behave correctly)
shouldn't we remove the broken one?

2018-02-13 08:36 UTC, RiccardoRossi commented on applications/MeshingApplication/custom_processes/mmg_process.cpp
> +                std::cout << "WARNING: YOUR GEOMETRY CONTAINS CERTAIN TYPE THAT CAN NOT BE REMESHED" << std::endl;
not very descriptive...

2018-02-13 08:36 UTC, RiccardoRossi commented on applications/MeshingApplication/custom_processes/mmg_process.cpp
> +        if (((num_tetra + num_tetra) < elements_array.size()) && mEchoLevel > 0)
this looks strange. you sure?

2018-03-04 18:42 UTC, loumalouomega commented
I will take into account these considerations, I will do as soon as I finish what I am doing right now

2018-03-09 15:33 UTC, loumalouomega commented
@pooyan-dadvand I need to do some changes in the internal_variables_interpolation_process, do you mind if I merge to avoid conflicts and I incorporate your suggestions in this new PR?

2018-03-11 14:28 UTC, loumalouomega commented on applications/MeshingApplication/custom_processes/internal_variables_interpolation_process.h
> +     * @details There are mainly two ways to interpolate the internal variables (there are three, but just two are behave correctly)
OK

2018-03-11 16:04 UTC, loumalouomega commented on applications/MeshingApplication/custom_processes/mmg_process.cpp
> +                std::cout << "WARNING: YOUR GEOMETRY CONTAINS CERTAIN TYPE THAT CAN NOT BE REMESHED" << std::endl;
Ok

2018-03-11 17:06 UTC, loumalouomega commented
Done, sorry for the delay

2018-03-15 18:36 UTC, loumalouomega commented
@pooyan-dadvand What is missing?

2018-03-16 08:02 UTC, pooyan-dadvand commented
Have you applied the comments of @RiccardoRossi ?

What are LST, CPT, etc? IMO a more descriptive name especially for enums is useful.

2018-03-16 11:32 UTC, loumalouomega commented
Yes, I applied the changes suggested by @RiccardoRossi. The methods are
described in the doxygen of the Execute method.

El 16 mar. 2018 9:02 a. m., "Pooyan Dadvand" <notifications@github.com>
escribió:

> Have you applied the comments of @RiccardoRossi
> <https://github.com/riccardorossi> ?
>
> What are LST, CPT, etc? IMO a more descriptive name especially for enums
> is useful.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/1453#issuecomment-373634260>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATEMgBDM5tfMf9S-7iH7FidhhB3GODlpks5te3GbgaJpZM4R6ETw>
> .
>

2018-03-16 12:00 UTC, pooyan-dadvand commented
LST, CPT, etc are not methods and reading the doxygen for understanding a variable is from 80s.

2018-03-16 12:11 UTC, loumalouomega commented
OK, I will append a description on place

El 16 mar. 2018 1:00 p. m., "Pooyan Dadvand" <notifications@github.com>
escribió:

> LST, CPT, etc are not methods and reading the doxygen for understanding a
> variable is from 80s.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/1453#issuecomment-373692763>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATEMgH4MaSVEka-VSEAoB4-uGL4FMmD8ks5te6lhgaJpZM4R6ETw>
> .
>

2018-03-16 12:25 UTC, loumalouomega commented
Done, i found I typo too

2018-03-16 12:26 UTC, loumalouomega commented
Besides I use Doxygen because I thought it is the proper way to document

2018-03-16 12:36 UTC, jcotela commented
@loumalouomega: you should not need to read the comments to understand what the name of your variable means. The days of 8-character-maixmum variable names are gone.

2018-03-16 13:12 UTC, loumalouomega commented
I don't have any problem with large name for variables, in the code you can see as I use `constitutive_law_vector` and similar names to describe variables.

 I am just using an acronym for a method, which is the classic name people uses in the literature. I think this is not necessarily wrong approach. We usually write PK2 not Piola-Kirchoff 2

2018-03-24 19:56 UTC, pooyan-dadvand commented
Thanks for changing the methods but the enums are still there....

2018-03-24 19:58 UTC, loumalouomega commented
True, I cahnged to enum class, but I forgot to move it inside the class, one sec

2018-03-24 20:04 UTC, loumalouomega commented
Done, sorry I did the hard part and not the easy one :P

2018-03-26 16:33 UTC, loumalouomega commented
@pooyan-dadvand Do I need to do anything else?

2018-03-26 16:52 UTC, pooyan-dadvand commented
I would change the enum lst cpt etc to more descriptive names

2018-03-26 17:36 UTC, loumalouomega commented
Done

2018-03-27 04:09 UTC, pooyan-dadvand approved these changes
Do we need TRANSFER in the enum names?

2018-03-27 07:09 UTC, loumalouomega commented
It is just a descriptive name

2018-03-27 07:09 UTC, merged