Dem feature parallelize rigid elements
KratosMultiphysics/Kratos pull request #1469
Opened 2018-02-08 08:15 UTC by joaquinirazabal

The parallelism in the function GetRigidBodyElementsForce was applied over the elements loop. As the rigid elements used to be  a few with a lot of nodes, now the parallel loop is applied over the nodes, as it was discussed with @maceligueta.

2018-02-08 09:00 UTC, GuillermoCasas requested changes
should center_to_node_vector not be made private to the thread (idem with additional_torque)?

2018-02-08 09:52 UTC, joaquinirazabal commented
Of course, @GuillermoCasas, thank you for the feedback. I've just pushed the changes you suggested.

2018-02-08 10:44 UTC, maceligueta commented
Hi, don't you think this style is too long?
```
vector<unsigned int> node_partition;
array_1d<double, 3> additional_torque;		 
int NumberOfThreads = OpenMPUtils::GetNumThreads();        
OpenMPUtils::CreatePartition(NumberOfThreads, mListOfNodes.size(), node_partition);  		  
NodesArrayType::iterator i_begin = mListOfNodes.begin();		
#pragma omp parallel for
NodesArrayType::iterator i_end = mListOfNodes.end();		
for (int k = 0; k < NumberOfThreads; k++) {
       NodesArrayType::iterator i_begin = mListOfNodes.begin() + node_partition[k];
        for (ModelPart::NodeIterator i = i_begin; i != i_end; ++i) {		 
            NodesArrayType::iterator i_end = mListOfNodes.begin() + node_partition[k + 1];
```
I am trying to move to something like:

```
#pragma omp parallel for
for (int k = 0; k < mListOfNodes.size(); k++) {
   ModelPart::NodeIterator i = mListOfNodes.begin() + k;
    ...
```
open for discussion, but the second one allows different types of scheduling, while the first one is always static (apart from a really big chunk of code).

2018-02-08 14:50 UTC, joaquinirazabal commented
I agree with you @maceligueta, the way you suggested is more elegant. I changed it in RigidBodyElement and also in the strategy were the ugly chunk of code appeared twice.

2018-02-08 15:21 UTC, maceligueta commented
@joaquinirazabal , many thanks! 
Concerning the 'schedule dynamic(100)', I use it when I expect the loop to be unbalanced. However, for loops where the work is exactly the same for all the iterations, I don't put it. For instance: spheres can have different number of neighbours, so the amount of work is different for each sphere, then I use dynamic scheduling. For the integration of trajectories or for setting values to 0.0 I would not use it, because it has an overhead that would bring no benefit...

2018-02-08 17:40 UTC, maceligueta commented
@joaquinirazabal , I made some slight changes that -I hope- did not break anything. Can you try your specific test?

2018-02-09 08:02 UTC, joaquinirazabal commented
It works!!

2018-02-10 17:04 UTC, maceligueta requested changes
I just saw that the RigidBodyElement has one little problem: when it's a wall, the parallel loop should be over its nodes (few walls, many nodes), however, when it's a cluster the parallel loop should be over the clusters (many clusters, few nodes per cluster). It's just for performance...
The solution we can manufacture is to create the object ParallelizedRigidBody3D, where all loops are parallel. Then, walls would derive from the parallel version, while the clusters would derive from the serial version. 
@pooyan-dadvand (or anyone) could bring ideas to this maybe...

2018-02-12 07:58 UTC, pooyan-dadvand commented on applications/DEM_application/custom_elements/rigid_body_element.cpp
> +        for (int k = 0; k < (int)mListOfNodes.size(); k++) {
I would suggest the use of static_cast for casting:

```c++
for (int k = 0; k < static_cast<int>(mListOfNodes.size()); k++) {
```
The reasoning is the fact that now the casting is more visible and is obvious that a compile time casting is done.

2018-02-12 08:06 UTC, pooyan-dadvand commented
I understand that you have a parallel loop over these loops you are mentioning. Then I would just make them with dynamic scheduling and leave the cluster loops all in serial avoiding nested parallelization. Maybe @RiccardoRossi has a better solution.

2018-02-12 10:25 UTC, maceligueta commented
What about this?
```
#pragma omp parallel for if(number_of_solids > 100)
for (int i = 0; i < number_of_solids; k++) {
    #pragma omp parallel for if(number_of_nodes_per_solid > 300 && number_of_solids <= 100)
    for (int k = 0; k < number_of_nodes_per_solid; k++) {
```

2018-02-12 11:31 UTC, maceligueta commented
Apparently, my last idea is not working at all. It seems like for a small number_of_solids OpenMP decides to work in one thread, then the next #pragma (over nodes of the solid) tries to make the parallelism inside that single thread, so it gets really slow. I tried it with a dummy code.
This makes me think that the apporach proposed by @pooyan-dadvand with the 'dynamic' clause would lead to the same bad result.

2018-02-12 13:30 UTC, pooyan-dadvand commented
In my approach the inner loop is only in serial to avoid the nested parallel loop problem you got in your example. The dynamic would give benefit if you have a large number of clusters with heterogeneous loop sizes.

2018-02-13 10:18 UTC, maceligueta commented
I just found out that the loop over the walls and the loop over the clusters are totally separated, so the outer loop is already specialized. The inner loop, right now, is also independent, so we have to find some way to unify them (or not, seeing the problems that this might bring). This will be in a future PR.

2018-02-15 11:32 UTC, maceligueta approved these changes

2018-02-15 11:33 UTC, maceligueta commented
@GuillermoCasas:  approval?

2018-02-15 15:27 UTC, GuillermoCasas approved these changes

2018-02-15 16:25 UTC, merged