Doxygen linear and NR strategy
KratosMultiphysics/Kratos pull request #1483
Opened 2018-02-12 10:39 UTC by loumalouomega

2018-02-14 17:55 UTC, msandre commented
This is really good for the core :+1:

2018-02-14 18:11 UTC, loumalouomega commented
(then approve me wink, wink)

2018-02-15 08:29 UTC, msandre requested changes
Some minor changes.

2018-02-15 08:29 UTC, msandre commented on kratos/solving_strategies/strategies/residualbased_linear_strategy.h
> +     * @return mpBuilderAndSolver: The pointer to the builder and solver considered
Is there a reason for the : here?

2018-02-15 08:29 UTC, msandre commented on kratos/solving_strategies/strategies/residualbased_linear_strategy.h
> +     * @brief This method prints information after reach the max number of interations
iterations has a typo.

2018-02-15 08:29 UTC, msandre commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> +     * @param CalculateReactionFlag The flag for the reaction calculation
MaxIterations is missing.

2018-02-15 08:29 UTC, msandre commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> +     * @param CalculateReactions The flag for the reaction calculation
MaxIterations is missing.

2018-02-15 08:29 UTC, msandre commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> + * @details This strategy iterates until the convergence is achieved (or the maximum number of iterations is suppased) using a Newton Raphson algorithm
surpassed has a typo.

2018-02-15 11:37 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_linear_strategy.h
> +     * @return mpBuilderAndSolver: The pointer to the builder and solver considered
Sorry

2018-02-15 11:37 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_linear_strategy.h
> +     * @brief This method prints information after reach the max number of interations
I am uhman

2018-02-15 11:37 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> +     * @param CalculateReactionFlag The flag for the reaction calculation
True

2018-02-15 11:37 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> +     * @param CalculateReactions The flag for the reaction calculation
True

2018-02-15 11:37 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h
> + * @details This strategy iterates until the convergence is achieved (or the maximum number of iterations is suppased) using a Newton Raphson algorithm
Okidoki

2018-02-15 11:43 UTC, loumalouomega commented on kratos/solving_strategies/strategies/residualbased_linear_strategy.h
> +     * @return mpBuilderAndSolver: The pointer to the builder and solver considered
No, it is Ok for @return

2018-02-15 11:46 UTC, loumalouomega commented
Done

2018-02-15 14:21 UTC, msandre commented
Thx, but the spelling, can you fix it?

2018-02-15 16:45 UTC, msandre approved these changes

2018-02-15 16:46 UTC, msandre commented
Nevermind I'm confused.

2018-02-15 21:52 UTC, merged