Overwriting properties in the read_materials_process
KratosMultiphysics/Kratos pull request #1567
Opened 2018-02-23 13:33 UTC by armingeiser

Add HasTables, HasVariables to properties in and print a Info message if read_materials_process is modifiying them.

closes Issue #1556

2018-02-23 13:48 UTC, philbucher commented
Could you also implement the `IsEmpty` Method for the `Properties`?
~~~c
bool const IsEmpty()
{
        return !( HasVariables() || HasTable() );
}
~~~

2018-02-24 13:42 UTC, philbucher commented
Thx!
Looks good to me, lets have @pooyan-dadvand have a look

2018-02-27 10:32 UTC, pooyan-dadvand requested changes
They look ok to me. Only a minor comment.

2018-02-27 10:32 UTC, pooyan-dadvand commented on kratos/includes/properties.h
> +        return (mTables.size() > 0);
You may use `mTables.empty()` as a slightly better implementation. (in some container it is faster)

2018-02-27 17:44 UTC, philbucher commented
@pooyan-dadvand done

2018-02-27 17:51 UTC, armingeiser commented
@philbucher thanks, did not find the time today

2018-03-02 08:17 UTC, pooyan-dadvand commented
The change looks good to me, but seems that appveyor complaining...

2018-03-02 08:19 UTC, philbucher commented
It was out of time (`Build execution time has reached the maximum allowed time for your plan (60 minutes).`)
and I dont know how to restart it

2018-03-02 08:24 UTC, philbucher commented
@roigcarlo can we restart the appveyor manually?
I cannot find the option, even after logging in

2018-03-02 08:58 UTC, roigcarlo commented
It should be possible if you login with the github account, but it works a bit oddly. For some reason the only account that can trigger restarts is mine so we made all members of the KratosGroup memebers of a Team in that account. It should appear a new login prompt if you try to loggin which lets you select "Kratos" which show allow you to restart the build.

Anyway I restarted it myself this time, I will keep investigating if there is any other easier solution.

2018-03-02 09:30 UTC, philbucher commented
ok thx for the explanation

2018-03-03 09:16 UTC, philbucher commented
@pooyan-dadvand now it compiled, all three checks are passing

2018-03-06 11:52 UTC, philbucher commented
ping @pooyan-dadvand

2018-03-08 08:01 UTC, pooyan-dadvand approved these changes
:+1:

2018-03-08 09:35 UTC, merged