DEM Bugfix Virtual Sea Surface
KratosMultiphysics/Kratos pull request #1834
Opened 2018-04-10 17:25 UTC by salvalatorre

The Virtual Sea Surface info was missing in the default DEM parameters

2018-04-11 15:53 UTC, salvalatorre commented
Added a subsection in the json for the virtual sea surface settings. Made the necessary adjustments in the problem type

2018-04-11 16:38 UTC, maceligueta requested changes
Great! You are the first at indentating the json in DEM! Looks nice. Just a question, is there an option to activate/deactivate this virtual surface? If so, it can be put inside this block.

2018-04-11 17:11 UTC, salvalatorre commented
Bug corrected, thanks!

2018-04-11 17:20 UTC, maceligueta commented
The abreviation sea_settings = self.DEM_parameters["virtual_sea_surface_settings"] is still pending. I'll approve after that. Please make sure the examples run, I don't have any at hand right now (and any case without the sea as well!).

2018-04-11 17:44 UTC, salvalatorre commented
Wait, benchmarks don't work, only GiD benchmarks...

2018-04-12 12:29 UTC, maceligueta approved these changes

2018-04-12 12:29 UTC, maceligueta commented on applications/DEM_application/python_scripts/DEM_procedures.py
> +            self.PrintVirtualSeaSurface = True
_self.DEM_parameters["virtual_sea_surface_settings"]_ is repeated many times, you can save it in a local variable like:
`sea_settings = self.DEM_parameters["virtual_sea_surface_settings"]`
then you can do:
`self.SeaSurfaceY1 = sea_settings ["PostVirtualSeaSurfaceY1"].GetDouble()`
But I also wonder if it is really necessary to save self.SeaSurfaceY1 if we can access sea_settings ["PostVirtualSeaSurfaceY1"].GetDouble() any time we want. Your call on the last comment.

2018-04-16 08:37 UTC, merged