Fix harmonic test
KratosMultiphysics/Kratos pull request #1862
Opened 2018-04-12 16:18 UTC by qaumann

Fixes #1793, thanks to @msandre

2018-04-12 19:29 UTC, philbucher reviewed
Two minor comments

Thx for fixing it!

runs for me both in Release and FullDebug

2018-04-12 19:29 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/eigen_solution_input_process.py
> +import KratosMultiphysics
would you please use the same header format as in the other files?

2018-04-12 19:29 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/eigen_solution_input_process.py
> +    if not isinstance(settings, KratosMultiphysics.Parameters):
I would check with ´type´ explicitly since that is whats done everywhere else in Kratos

2018-04-12 19:29 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/eigen_solution_output_process.py
> +import KratosMultiphysics
same

2018-04-12 19:29 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/eigen_solution_output_process.py
> +    if not isinstance(settings, KratosMultiphysics.Parameters):
same

2018-04-13 07:35 UTC, msandre requested changes

2018-04-13 07:35 UTC, msandre commented on applications/StructuralMechanicsApplication/python_scripts/eigen_solution_input_process.py
> +    """A process for writing eigenvalue and eigenvector results."""
Docstring is wrong.

2018-04-13 14:51 UTC, qaumann commented
Thank you for your comments, I changed everything you mentioned.

2018-04-13 14:53 UTC, philbucher approved these changes
thx

2018-04-13 15:11 UTC, msandre approved these changes

2018-04-13 15:11 UTC, msandre commented
thanks @qaumann

2018-04-16 08:24 UTC, merged