Feature hdf5application element data
KratosMultiphysics/Kratos pull request #1963
Opened 2018-04-26 13:06 UTC by sunethwarna

This PR adds the ability to have element variable values in the HDF file output and to visualize element variables in paraview.

2018-04-26 13:38 UTC, philbucher commented
I am very interested in this feature and will try it as soon as it it merged

A test is missing

2018-04-26 14:34 UTC, sunethwarna commented
@philbucher test case added.

2018-04-26 14:51 UTC, msandre requested changes

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +//#include "custom_utilities/local_ghost_splitting_utility.h"
delete comment.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    for (auto it = rElements.begin(); it != rElements.end(); ++it)
Add check size is same and resize output if necessary. Also make it an omp loop.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    GetElementReferences(rElements, local_elements);
It is cleaner to do this in one line (see http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-conventional).

```
std::vector<ElementType*> local_elements = GetElementReferences(rElements);
```

The operation is cheap because std::vector uses move constructor.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    GetElementReferences(rElements, local_elements);
same here.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +void ElementSolutionStepDataIO::ReadElementResults(ElementsContainerType& rElements, Communicator& rComm, unsigned Step)
Remove the Communicator from the function parameters. It is not needed here because we don't need to synchronize element data. Also remove Step.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +                   unsigned Step)
Remove unused Step from parameters.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +                              unsigned Step)
Remove unused Step from parameters.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    void WriteElementResults(ElementsContainerType const& rElements, unsigned Step=0);
Remove Step and rComm.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +class Communicator;
remove Communicator

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    std::string const& GetPrefix() const noexcept
I think you can remove this function to simplify.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    std::vector<std::string> const& VariableNames() const noexcept
Also remove this one.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    File& GetFile()
And this one.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_element_solution_step_data_io.cpp
> +#include "includes/communicator.h"
You don't need to include the communicator here.

2018-04-26 14:51 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_element_solution_step_data_io.cpp
> +        HDF5::ElementType& r_write_element = r_element;
You don't need `HDF5::ElementType& r_write_element = r_element;`.

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +//#include "custom_utilities/local_ghost_splitting_utility.h"
done.

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    for (auto it = rElements.begin(); it != rElements.end(); ++it)
done

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    GetElementReferences(rElements, local_elements);
done

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +    GetElementReferences(rElements, local_elements);
done

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.cpp
> +void ElementSolutionStepDataIO::ReadElementResults(ElementsContainerType& rElements, Communicator& rComm, unsigned Step)
done

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    std::string const& GetPrefix() const noexcept
done

2018-04-27 07:16 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    std::vector<std::string> const& VariableNames() const noexcept
done

2018-04-27 07:17 UTC, sunethwarna commented on applications/HDF5Application/custom_io/hdf5_element_solution_step_data_io.h
> +    File& GetFile()
done

2018-04-27 07:17 UTC, sunethwarna commented on applications/HDF5Application/tests/test_hdf5_element_solution_step_data_io.cpp
> +#include "includes/communicator.h"
done

2018-04-27 07:17 UTC, sunethwarna commented on applications/HDF5Application/tests/test_hdf5_element_solution_step_data_io.cpp
> +        HDF5::ElementType& r_write_element = r_element;
done

2018-04-27 07:29 UTC, msandre approved these changes
Thanks Suneth. Approving.

2018-04-27 09:53 UTC, merged