Change name of ALEApplication to MeshMovingApplication
KratosMultiphysics/Kratos pull request #1998
Opened 2018-05-02 10:06 UTC by AndreasWinterstein

As proposed in the issue some weeks ago, I renamed the ALEApplication in MeshMoving Application, since it is used not only for FSI but also for other application cases.

2018-05-02 10:10 UTC, jcotela commented on .vscode/settings.json
> +{
This file should not be in github, please add it to your git exclude list.

2018-05-02 10:11 UTC, jcotela commented on applications/ExternalSolversApplication/externalsolvers_application.h
> +#define KRATOS_MESH_MOVING_APPLICATION_H_INCLUDED
I think you just found a big name error in the ExternalSolversApplication...

2018-05-02 10:14 UTC, jcotela commented on applications/MultiScaleApplication/CMakeLists.txt
> +if(${MULTISCMESH_MOVING_APPLICATION_USE_EIGEN} MATCHES ON)
Careful here! search and replace is not your friend.

2018-05-02 12:20 UTC, msandre requested changes
I will approve as soon as the problem mentioned by @jcotela is fixed. Also, for the future please try to avoid committing files that are autoformatted for spaces only. There are many such files in this pr and it makes it difficult to track meaningful changes.

2018-05-02 12:20 UTC, msandre commented on applications/FSIapplication/python_scripts/partitioned_fsi_base_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
Shouldn't KratosALE also be renamed?

2018-05-02 12:20 UTC, msandre commented on applications/FSIapplication/python_scripts/trilinos_partitioned_fsi_base_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
Shouldn't KratosALE also be renamed?

2018-05-02 12:20 UTC, msandre commented on applications/FSIapplication/python_scripts/trilinos_partitioned_fsi_dirichlet_neumann_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
Shouldn't KratosALE also be renamed?

2018-05-02 12:30 UTC, armingeiser commented
@msandre In the ```Files changed``` tab, on the top right, you can go to ```Diff settings``` and ```Hide whitespace changes```.

2018-05-02 12:31 UTC, rubenzorrilla commented on applications/FSIapplication/python_scripts/partitioned_fsi_base_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
IMO should be. Maybe KratosMeshMoving?

2018-05-02 12:33 UTC, rubenzorrilla commented on applications/FSIapplication/python_scripts/trilinos_partitioned_fsi_base_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
Same

2018-05-02 12:33 UTC, rubenzorrilla commented on applications/FSIapplication/python_scripts/trilinos_partitioned_fsi_dirichlet_neumann_solver.py
> +import KratosMultiphysics.MeshMovingApplication as KratosALE
Same

2018-05-02 12:38 UTC, rubenzorrilla commented
As a comment aside, I'm implementing a new explicit mesh moving technique (based on the FM-ALE method) for the embedded nodes initialization. Do you think it's better to merge it right now (it's implementation is finished but it has not been tested yet) or to merge it after this PR? I'm afraid of the conflicts that this PR may rise up.

2018-05-02 12:48 UTC, msandre commented
@armingeiser that helped thanks. Still I would ask to avoid such commits in the future since it can still be a problem when one needs to go back through the git commit history to locate a bug. Probably git has a special command to hide white space changes, but I don't know if this is easy to do.

2018-05-02 12:49 UTC, AndreasWinterstein commented
@msandre This happens in this case since I was using the replace function from vs code. I do not know why this happens also in files I did not touch.

2018-05-02 12:51 UTC, AndreasWinterstein commented
@rubenzorrilla I do not know if this will cause too many conflicts. I also did not change anything concerning the names of the mesh solvers themselves and it worked.

2018-05-02 13:25 UTC, armingeiser commented
@AndreasWinterstein VSCode automatically removes trailing whitespaces from lines when you save a file.
So even if you don`t actively change code, but hit Ctrl+S on a file, you will get some whitespace changes.

2018-05-02 13:55 UTC, msandre requested changes
Two small changes are still needed for external solvers app.

2018-05-02 13:55 UTC, msandre commented on applications/ExternalSolversApplication/externalsolvers_application.h
> +        KRATOS_WATCH("in KratosMeshMovingApplication application");
This is wrong.

2018-05-02 13:55 UTC, msandre commented on applications/ExternalSolversApplication/externalsolvers_application.h
> +#endif  // KRATOS_MESH_MOVING_APPLICATION_H_INCLUDED  defined
Wrong comment.

2018-05-03 09:03 UTC, AndreasWinterstein commented
@msandre: if it is ok for you now, you can approve th PR. @dbaumgaertner has added the changes for the ShapeOptimizationApplication.

2018-05-03 14:31 UTC, msandre approved these changes
Thanks.

2018-05-04 05:53 UTC, merged