Dem/missing changes for extra stiff cl
KratosMultiphysics/Kratos pull request #2110
Opened 2018-05-17 15:25 UTC by farrufat-cimne

2018-05-17 15:56 UTC, maceligueta requested changes

2018-05-17 15:56 UTC, maceligueta commented on applications/DEM_application/custom_constitutive/DEM_D_Linear_HighStiffness_CL.cpp
> +        const double mKn_augmenter = 100.0;
If mKn_augmenter is not a member variable, you should not use this name. You can write 'augmenter' or 'kn_augmenter' or anything following our style, to avoid misunderstandings.

2018-05-17 15:57 UTC, farrufat-cimne commented on applications/DEM_application/custom_constitutive/DEM_D_Linear_HighStiffness_CL.cpp
> +        const double mKn_augmenter = 100.0;
ok

2018-05-17 16:05 UTC, maceligueta commented
Did you run a case to test that it is not crashing? I mean with the GUI.

2018-05-18 09:15 UTC, farrufat-cimne commented
GUI test passed.

2018-05-18 09:47 UTC, maceligueta approved these changes

2018-05-18 13:21 UTC, merged