[Core] Adding HasNodalSolutionStepVariable to ModelPart
KratosMultiphysics/Kratos pull request #2298
Opened 2018-06-10 11:27 UTC by philbucher

Adding a missing method

2018-06-10 19:38 UTC, loumalouomega submitted a review, later dismissed
OK, thanks

2018-06-12 12:24 UTC, jcotela requested changes
I have mixed feelings about this one... The model part is already a quite heavy class. I think a better solution would be to ask the nodal data variables list directly, the equivalent of doing in C `ModelPart.GetNodalSolutionStepVariablesList().Has()`. I understand that the variables container is not exposed to python though, and that the node already does the same.

In summary, I don't love it but I will approve if it is needed. However, I would at least make the method `const`.

2018-06-12 12:24 UTC, jcotela commented on kratos/includes/model_part.h
> +    bool HasNodalSolutionStepVariable(Variable<TDataType> const& ThisVariable)
I would make the method `const` if possible.

2018-06-12 13:22 UTC, jcotela approved these changes

2018-06-12 16:34 UTC, merged