[Core] Missing copy data clone on element and condition base
KratosMultiphysics/Kratos pull request #2344
Opened 2018-06-19 10:11 UTC by loumalouomega

Besides, we should add the data copy to the derived ones too

2018-06-19 12:53 UTC, pooyan-dadvand requested changes
Your proposal make sense as clone should really clone everything. Nevertheless this clone method was an special one for prototyping where we haven't used the other data of the elements. 

Why you have not change this ones in the Clone of GeometricalObject?

2018-06-19 12:53 UTC, pooyan-dadvand commented on kratos/includes/condition.h
> +	p_new_cond->Set(Flags(*this));
I would suggest `static_cast` here...

2018-06-19 12:53 UTC, pooyan-dadvand commented on kratos/includes/element.h
> +        p_new_elem->Set(Flags(*this));
And here...

2018-06-19 12:58 UTC, loumalouomega commented
There is not clone in GeometricalObject

2018-06-19 12:59 UTC, loumalouomega commented on kratos/includes/condition.h
> +	p_new_cond->Set(Flags(*this));
What do you mean with static_cast

2018-06-19 13:11 UTC, pooyan-dadvand commented
So I was saying to add one and put the repeated core there.

2018-06-19 13:13 UTC, loumalouomega commented
But the GeometricalObject just contains the geometry. Does not contain Data or Flags

2018-06-19 13:17 UTC, loumalouomega commented
OK, I got it, to add the clone to geometrical object, so in the clone does not generate a base geometry, that explains the error I was getting and why was unable to plot the mesh

2018-06-19 13:37 UTC, loumalouomega commented
I cannot add the Clone to the GeometricalObject, it conflicts with the Clone of the Condition and the Element

2018-06-20 07:57 UTC, pooyan-dadvand commented
why it makes conflict?

2018-06-20 08:57 UTC, loumalouomega commented
Because the geometrical object lacks of flags and data container. So in
case you define the clone it tries to override, but it lacks that, so can
not compile. Maybe adding a clone method to the geometrical object, but not
virtual will work,but I don't know if this was the idea.

El mié., 20 jun. 2018 9:57, Pooyan Dadvand <notifications@github.com>
escribió:

> why it makes conflict?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/2344#issuecomment-398659436>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATEMgF5GUHDpmM7LDXibpTx96n6k7GP3ks5t-gB6gaJpZM4UtOId>
> .
>

2018-06-22 11:40 UTC, pooyan-dadvand commented
Would you please add a test to it? A cpp test would be more appropated

2018-06-22 15:07 UTC, loumalouomega commented
Ok

2018-06-22 19:06 UTC, loumalouomega commented
Done @pooyan-dadvand

2018-06-25 09:31 UTC, pooyan-dadvand approved these changes
👍

2018-06-25 09:42 UTC, merged