Feature adjoint transient optimization
KratosMultiphysics/Kratos pull request #2373
Opened 2018-06-25 09:03 UTC by sunethwarna

This PR adds followings:

1. A response function which runs a method "Run", response value and its gradients need to be calculated inside this "Run" method and needs to be passed in a dictionary for the optimizer.
2. Restart capabilities for this response function is implemented.
3. External analyzer class to handle this response function is implemented in the test case (05 test case with an example)
4. The example combines AdjointFluidApplication and FluidDynamicsApplication to calculate shape sensitivities for a fluid problem. (This is for a transient example)

2018-06-25 10:10 UTC, philbucher reviewed
@sunethwarna you don't need the is_MPI flags from what I saw
you can get the barriers also through the ModelPart-Communicator
if you do sth in rank 0 this works both with and without MPI

2018-06-25 13:48 UTC, philbucher commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/impose_parabolic_inlet_process.py
> +import KratosMultiphysics
I think the InletProcess in Fluid is able to do what you do with this process
@jcotela @rubenzorrilla ?

2018-06-25 13:48 UTC, philbucher commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/impose_parabolic_inlet_process.py
> +        for node in self.model_part.Nodes:
if you decide to keep this then please use the function form `kratos/utilities/variable_utils` for this

2018-06-25 16:10 UTC, msandre requested changes
I would wait for a review from @armingeiser or @dbaumgaertner on this, but here are my small comments.

2018-06-25 16:10 UTC, msandre commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/response_analysis.py
> +def Run(optimization_model_part, response_data, custom_settings):
Is it correct that `optimization_model_part` is not used?

2018-06-25 16:10 UTC, msandre commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/response_analysis.py
> +        adjoint_simulation._GetSolver().main_model_part.GetCommunicator().AssembleCurrentData(KratosMultiphysics.SHAPE_SENSITIVITY)
I think it is safe to call `AssembleCurrentData` without mpi (it does nothing). So you don't need the if statement.

2018-06-25 16:10 UTC, msandre commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/response_analysis.py
> +        response_data["response_gradients"] = __get_response_gradients(adjoint_simulation)
This does not work for MPI right? It would only return the response gradients from the first process.

2018-06-25 16:10 UTC, msandre commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/analyzer_external_transient.py
> +# ==============================================================================
File name should be like class name: `external_transient_analyzer.py`

2018-06-25 16:47 UTC, philbucher commented on applications/ShapeOptimizationApplication/test_examples/05_External_Fluid_Adjoint_Transient_Analyzer/base_case/response_analysis.py
> +    if is_MPI:
this if is not needed for example

2018-11-22 11:25 UTC, msandre commented
Suneth, this must be quite outdated with current master. I think it's better to first discuss with structural optimization team before spending time to update/fix the branch. If we don't want it anymore then we should close it.

2019-01-30 10:05 UTC, closed without merging