[Core][Geometry] Adding hasintersection function to hexa and quad 3D
KratosMultiphysics/Kratos pull request #2386
Opened 2018-06-26 08:39 UTC by bodhinandach

@loumalouomega @roigcarlo 

I added the `HasIntersection()` function for hexa3D8 and quad3D4 by reusing the triangular3D3's function.
This implementation is similar to the one implemented in quad2D4.

This function is apparently needed by the binbased_fast_point_locator.h, particularly on function `UpdateSearchDatabase()`

I have been validated it for the new hexahedral element implemented in ParticleMechanicsApplication.

2018-06-26 08:41 UTC, loumalouomega requested changes
Perfect, I will approve as soon as you add the corresponding tests

2018-06-27 08:22 UTC, bodhinandach commented
@loumalouomega as mentioned, I haven't checked whether it is working or not, since I am not sure which cmakelist or file that I have to modify to include the test. Therefore, currently, the code has not yet been compiled or run, which therefore might have some errors. Please reconfirm. Thanks!

2018-06-27 08:52 UTC, loumalouomega commented
As you can see Travis failed because tests failed

2018-06-27 08:56 UTC, bodhinandach commented
@loumalouomega I see! Corrected it! I wonder how to check the test in my PC?

2018-06-27 09:19 UTC, roigcarlo commented
```Python
from KratosMultiphysics import *
Tester.SetVerbosity(Tester.Verbosity.TESTS_OUTPUTS)
Tester.RunAllTestCases()
```

2018-06-27 09:48 UTC, loumalouomega approved these changes
Thanks

2018-06-27 10:20 UTC, merged