[ParticleMechanicsApplication] Feature hexahedral element 3D8N
KratosMultiphysics/Kratos pull request #2387
Opened 2018-06-26 08:43 UTC by bodhinandach

I extended the UL Quad element to Hexahedral. For the implementation to run, the PR #2386 is needed, else it will throw an error while accessing binbased_fast_point_locator.h's UpdateSearchDatabase() function.

I have validated it with a simple beam example as attached.
![snapshot](https://user-images.githubusercontent.com/37140224/41899787-44cc9506-7968-11e8-98a7-6127ba6fb92a.png)

2018-06-26 08:54 UTC, loumalouomega requested changes
Wait until #2386 is merged. Besides add that beam as test, please

2018-06-27 10:05 UTC, bodhinandach commented
@loumalouomega this one also waiting for approval :bowing_man:

2018-06-27 10:25 UTC, loumalouomega requested changes
Minor comments

2018-06-27 10:25 UTC, loumalouomega commented on applications/ParticleMechanicsApplication/custom_python/particle_mechanics_python_application.cpp
> +    UpdatedLagrangianQuadrilateral::Pointer NewElement(
Use make_shared instead, is more efficient

2018-06-27 10:25 UTC, loumalouomega commented on applications/ParticleMechanicsApplication/custom_strategies/strategies/MPM_strategy.h
> +            if (m_GeometryElement == "Triangle"){
There are some enums to check the geometry type, please use those ones

2018-06-27 13:24 UTC, bodhinandach commented
ping @loumalouomega

2018-06-27 13:51 UTC, loumalouomega approved these changes
Ok

2018-06-28 01:18 UTC, merged