Outlet inflow prevention implementation
KratosMultiphysics/Kratos pull request #246
Opened 2017-04-04 17:00 UTC by rubenzorrilla

An extra term has been added to the RHS of the navier_stokes_wall_condition to prevent inflow in outlet BCs.

2017-04-04 18:05 UTC, jcotela requested changes
The condition code should only be executed when the condition is marked as OUTLET (please also make sure that you are marking the condition, not only the nodes)

2017-04-04 18:05 UTC, jcotela commented on applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp
> +    const double S_0 = 0.5*(1-tanh(vGaussProj/U_0/delta));
vGaussProj/(U_0*delta) should be cheaper

2017-04-04 18:05 UTC, jcotela commented on applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp
> +        if (rGeom[i].Is(OUTLET))
I think it would be better to calculate this term based on the condition, not the node, since it represents a boundary integral: You want it to act over all triangles on the outlet.
Therefore my recommendation would be to perform the operations in this function only when the CONDITITON is flagged as OUTLET. Such condition will then always (?) act on all its nodes.

2017-04-05 06:08 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp
> +    const double S_0 = 0.5*(1-tanh(vGaussProj/U_0/delta));
Done!

2017-04-05 06:12 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp
> +        if (rGeom[i].Is(OUTLET))
Totally agree. Yes, I think that the condition should act on all its nodes (even in the corner and edge nodes).

2017-04-05 09:09 UTC, jcotela approved these changes

2017-04-05 09:09 UTC, merged