Adding check for the triangle_3d_3 area calculation
KratosMultiphysics/Kratos pull request #250
Opened 2017-04-05 09:25 UTC by loumalouomega

I am having some troubles with interface triangles which are in a bad shape, and I saw that there is not any check in the Heron formula to check that. I switch to the math_utils Heron formula that includes a check

2017-04-05 09:28 UTC, loumalouomega commented
Thing to discuss if the consider that this check is expensive or we can assume it (it is just a check if the area before sqrt is negative)

2017-04-05 11:01 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        return Area();
Maybe I'm missing something but why is the DomainSize() method returning the Area?

2017-04-05 11:07 UTC, loumalouomega commented on kratos/geometries/triangle_3d_3.h
> +        return Area();
I don't know, it was that way when I arrived

2017-04-07 09:42 UTC, pooyan-dadvand commented on kratos/geometries/triangle_3d_3.h
> +        return Area();
This is THE example of how a bad name for a method can mislead everyone. DomainSize returns area for 2d shapes and volume for 3d shapes

2017-04-07 09:44 UTC, loumalouomega commented on kratos/geometries/triangle_3d_3.h
> +        return Area();
This is a 2D triangle in 3D space, what do we consider?

2017-04-07 10:44 UTC, pooyan-dadvand commented on kratos/geometries/triangle_3d_3.h
> +        return Area();
is a 2D shape so has area

2017-04-07 10:45 UTC, pooyan-dadvand requested changes
Actually I don't agree with this change because in my mesh optimisation I may get a negative area within a step and is not a problem. So I would suggest you to add a debug check in your application

2017-04-07 11:22 UTC, loumalouomega commented
I did the check in my application, I will change the flag

2017-04-07 11:25 UTC, loumalouomega commented
@pooyan-dadvand Done

2017-04-10 13:12 UTC, RiccardoRossi commented
i have no further comments on my side, let's wait for @pooyan-dadvand feedback

2017-05-01 20:14 UTC, rubenzorrilla commented
@loumalouomega shall we close this?

2017-05-01 22:02 UTC, loumalouomega commented
Yes, I will close this

2017-05-01 22:02 UTC, closed without merging

2017-05-02 12:55 UTC, pooyan-dadvand commented
Sorry for my absent.... Meanwhile the only important change in that branch was the check flag?

2017-05-02 14:58 UTC, maceligueta commented on kratos/geometries/triangle_3d_3.h
> +        return normFactor * (Area() * 2 / base ) / base;
One division can be avoided here. @loumalouomega

2017-05-02 14:59 UTC, maceligueta commented on kratos/geometries/triangle_3d_3.h
> +        return normFactor * Area() / std::pow(a+b+c, 2);
std::pow(x, 2) might be replaced by x*x. Who knows if the optimizer is doing it already... @loumalouomega

2017-05-02 15:40 UTC, loumalouomega commented
I thought that @pooyan-dadvand said that he doesn't need the check for some of his applications, and we agreed to put directly in my code a check to avoid the problem. That's why I decided to close the discussion.

2017-05-02 15:45 UTC, pooyan-dadvand commented
You are right @loumalouomega. It gives problem to my remeshing.

2017-05-02 15:54 UTC, loumalouomega commented
@pooyan-dadvand So, do we keep it closed?

2017-05-02 16:11 UTC, pooyan-dadvand commented
Yes we keep this closed. @roigcarlo would you please take in account the comments of @maceligueta ?

2017-05-02 16:36 UTC, roigcarlo commented
@pooyan-dadvand, @maceligueta With -O3 (Release) `sqrt::pow(x,2)` generates the same code as `x*x`. This pressumably also happens with -O2 (RelWithDebInfo). 

I havn't seen the implementation of `sqrt::pow` myself but I suspect they have some sort of specialization which would _probably_ make `sqrt::pow(x,2)` faster than a plain `x*x`. but anyway is going to be marginal.

So the only reaso to rewrote that as `(a+b+c) * (a+b+c)` would be if we really need that the debug version of the code runs faster ( and I don't think that this operation is particulary expensive) or to improve readability.

Still, if it helps in any of those we can ofcourse change it.

2017-05-03 08:45 UTC, pooyan-dadvand commented
If you are sure about the `pow `I am ok with that. Nevertheless you can use an auxiliary variable to improve readability:
```c++
const double sum = a + b + c;
return  normFactor * Area() / (sum * sum);
```
For me the more critical one is the double divisions:
```c++
return normFactor * (Area() * 2 / base ) / base;
```