Improvement hdf5 temporal output to add non historical variables
KratosMultiphysics/Kratos pull request #2726
Opened 2018-08-24 11:04 UTC by sunethwarna

This PR adds non-historical variables from solution steps to the HDF5 output historical files.

Advantages:
Can get rid of the if condition in the single_mesh_primal_output_process, which changes acceleration to relaxed acceleration in the HDF5 process (which is required by adjoint solvers)

The changes to the adjoint strategy and test cases will follow through test-hdf5-new-implementation branch later.

2018-08-24 11:08 UTC, loumalouomega commented
One thing, using https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/integration_values_extrapolation_to_nodes_process.cpp you can get values from GaussPoints too

2018-08-24 11:43 UTC, sunethwarna commented
hi @loumalouomega , I'm sorry, I'm little bit confused, Will this process be a problem? :/ (Its upto the user to decide which processes to be used when outputing to HDF5, ryt?)
On the other hand, If I'm to use this process to output GPs to HDF5, then this process should be moved to the core right?

2018-08-24 11:56 UTC, loumalouomega commented
I am suggesting that now that you support non historical variables, but GP not yet, you can use that process to extrapolate GP to nonhistorical values until you implement the GP. properly, just a suggestion

2018-08-24 17:14 UTC, msandre commented
I see now that I should have named the NodalResultsOutput more carefully. I suggest the following renaming, split across several PRs which get merged back into this one, for consistency:

PR 1:
- Replace `"/NodalResults/"` with `"/NodalSolutionStepData/"` in hdf5_nodal_solution_step_data_io.cpp
- Rename `NodalResultsOutput` to `NodalSolutionStepDataOutput` in hdf5_io.py
- Rename `"nodal_results_settings"` to `"nodal_solution_step_data_settings"`.

PR 2:
- Rename c++ classes `ElementSolutionStepDataIO` to `ElementDataValueIO` and `NonHistoricalNodalValueIO` to `NodalDataValueIO` and update the HDF5 paths in the .cpp files to `rPrefix + "/ElementDataValues"` and `rPrefix + "/NodalDataValues"`
- Rename `"element_results_settings"` to `"element_data_value_settings"`.
- Rename `ElementResultsInput` to `ElementDataValueInput` and `ElementResultsOutput` to `ElementDataValueOutput`
- Update `eigen_solution_input_process.py` and output process in structural mechanics application.

This PR:
- Merge master with the above changes back into this branch.
- Rename `NodalResultsInput` to `NodalSolutionStepDataInput` in hdf5_io.py
- Use `"nodal_data_value_settings"`, `NodalDataValueOutput` and `NodalDataValueInput` for the non-historical nodal values.

Let's discuss it on Monday.

2018-08-28 16:35 UTC, armingeiser commented
@MFusseder FYI

2018-08-30 13:17 UTC, msandre requested changes
Some minor changes:

- Remove single_mesh_primal_input_process.py and replace all remaining references to it by the single_mesh_temporal_input_process.

- Same for partitioned_single_mesh_primal_input_process.py

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/partitioned_single_mesh_temporal_input_process.py
> +    """Return a process for writing a transient primal solution from HDF5 to data containers."""
Docstring is wrong.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/single_mesh_temporal_input_process.py
> +    """Return a process for writing a transient primal solution form HDF5 to data containers."""
Docstring is wrong.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/partitioned_single_mesh_temporal_input_process.py
> +    input_time_settings = KratosMultiphysics.Parameters("""{}""")
Use the new default ctor for Parameters.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/single_mesh_temporal_input_process.py
> +    input_time_settings = KratosMultiphysics.Parameters("""{}""")
Use the new default ctor for Parameters.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_model_part_io.py
> +            element.SetValue(PRESSURE, random.random())
PRESSURE, VISCOSITY and DENSITY are all scalar doubles. You only need to test one of them. The element data value io can also handle `Variable<array_1d<double, 3>>` and `VariableComponent<...>`. You should also test these here (one variable per type is enough).

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_model_part_io.py
> +            node.SetValue(DISPLACEMENT_X, random.random())
DISPLACEMENT, VELOCITY and ACCELERATION are all of the same type. You only need to test DISPLACEMENT here. Same for PRESSURE, VISCOSITY and DENSITY. Also this function is getting long and code blocks such as this one are only needed for one test later on. Can you move this to `_assign_random_nodal_data_values` defined outside of the class (i.e., a private function to this module) and do the same for `_assign_random_element_data_values`? Then call these in the `test_HDF5NodalDataValueIO` and `test_HDF5ElementDataValueIO` after `_initialize_model_part`

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_model_part_io.py
> +    def _get_element_data_value_io(self, hdf5_file):
These could also be moved outside of the class.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +    """Provides the interface for reading a transient primal solution from a file."""
Update docstring. Remove "primal".

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +    """Provides the interface for reading a transient primal solution from a file."""
Update docstring.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +    """Provides the interface for writing non solution step nodal results to a file."""
for writing nodal data values

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/temporal_output_process_factory.py
> +    def ElementDataValueOutput(self, element_data_value_settings):
Here I think the plan is to eventually remove the PrimalBossakOutput which will allow us to simplify this module by removing `ResultsFactory`. Since the nodal and element data value io are identical we can already replace these with direct calls to `hdf5_io.NodalDataValueOutput(...)` in the `FactoryHelper`.

2018-08-30 13:17 UTC, msandre commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
>      results = []
You mentioned there is a problem if the same variable is used in data values and nodal solution step values. To detect this, can we replace the `results = []` with `results = {}` and replace this function body with

```
results = {}
if "/ResultsData/NodalSolutionStepData" in h5py_file:
    AddNodalSolutionStepData(h5py_file.get("..."), results)
if "/ResultsData/NodalDataValues" in h5py_file:
    AddNodalDataValues(h5py_file.get("..."), results)
return list(results.values)
```

and in the `Add...` functions do 

```
if variable_name in results:
    raise ValueError('Nodal result "' + variable_name + '" is already defined.')
```

2018-08-30 17:20 UTC, msandre approved these changes
Thanks Suneth!

2018-08-31 07:19 UTC, merged