[HDF5] fix for non-consecutive nodes
KratosMultiphysics/Kratos pull request #2830
Opened 2018-09-07 12:15 UTC by philbucher

This is a fix for when the node-ids are non-consecutive

It is not the best solution, @msandre we should talk abt this when you are back

2018-10-22 13:01 UTC, sunethwarna commented
ping @msandre

2018-10-22 13:36 UTC, philbucher commented
I discussed this with @jcotela last week, a better fix would be to use a map similar to the ReorderIO

2018-10-22 19:25 UTC, philbucher commented
I used a map now, this way it should be independent of the node-ordering

I haven't tested this, will do so tmr

@sunethwarna if you have a case where this is needed you could also give it a try

2018-10-23 11:54 UTC, msandre submitted a review, later dismissed
Hi, it looks fine to me, but please test it before merging.

2018-10-24 06:56 UTC, philbucher commented
It seems to be working fine, @sunethwarna could you please try this with one of you cases?
I treid several examples but in order to be sure
Thanks!

2018-10-24 08:55 UTC, sunethwarna commented
@philbucher This is working with my test cases. Thank you :+1:  :)

2018-10-24 10:02 UTC, philbucher commented
ok then this is ready to merge :+1:

2018-10-25 12:39 UTC, philbucher commented
I need a reapproval :)

2018-10-25 12:59 UTC, loumalouomega submitted a review, later dismissed

2018-10-25 12:59 UTC, msandre commented
Give me a minute to check befor merging

2018-10-25 13:26 UTC, msandre requested changes

2018-10-25 13:26 UTC, msandre commented on applications/HDF5Application/custom_processes/hdf5_xdmf_connectivities_writer_process.cpp
> +            << " is duplicated and only inserted once!" << std::endl;
We require a one-to-one mapping of ids onto indices in order to generate the xdmf connectivities. If this is not satisfied, we should throw an error instead of a warning:

```
const auto p = mKratosToXdmfIdMap.insert(IdMapType::value_type(node_ids[i], i));
KRATOS_ERROR_IF_NOT(p->second) << "Node #" << node_ids[i] << " at position " << i << " already exists at position " p->first->second << std::endl;
```

2018-10-25 15:19 UTC, philbucher commented on applications/HDF5Application/custom_processes/hdf5_xdmf_connectivities_writer_process.cpp
> +            << " is duplicated and only inserted once!" << std::endl;
done, thx

2018-10-25 15:27 UTC, msandre approved these changes
thx

2018-10-26 06:55 UTC, philbucher commented
I tested it again, I am fairly convinced that it works

Please let me know if this is not the case

2018-10-26 06:55 UTC, merged