WIP Hdf/output process
KratosMultiphysics/Kratos pull request #2876
Opened 2018-09-14 12:54 UTC by philbucher

this PR adds a process for easy creation of h5-output files tgth with the corresponding xdmf-files

I will add tests after we converged in the discussion (if there is any :) )

The interface is designed to be easy to use and in some way similar to the GiDOutputProcess

2018-09-17 12:14 UTC, msandre commented
I'm open to adding as many output processes as needed to fit the demands of different users. However the output requirements in kratos are very diverse, and therefore it doesn't make sense to me to try to pack them into one process. For example, most users don't know/care about backwards in time since it is very problem specific. They should not have to depend on a process which has settings/logic for backwards in time. And, if I decide to change something about the backwards in time, I should not have to change a process which could break something for the users who don't use backwards in time. My preference would be to have many small, client-specific processes with simple logic/settings than one massive process with many settings and if-statements. The motivation is for stable processes that still work with json parameters months/years later and are easier to maintain by adhering to open-closed and interface-segregation principles.

Based on past experience, I expect that this process would be changed often or evolve into some complex inheritance hierarchy in an attempt to fit new applications and requirements as they arise, causing old json parameters to stop working. I also would not want to review changes to such a large and complex module since I would probably spend a lot of time trying to read and understand what it is doing (and still get it wrong in the end).

Can you give a summary of the new features that should be added in this PR?

2018-09-17 14:36 UTC, philbucher commented
Hi Mike,
Thanks for your comments.
The main idea of this process is to add similar postprocessing capabilities that the GiDOutputProcess offers. This means it allows for easy creation of „standard“ post-files e.g for nodal solutionstep values.
I see it more as a thin wrapper for the temporal-ouput-process with a bit of logic for writing the xdmf-file rather than a self-contained process.
To sum up:
- works automatically with OpenMP and MPI
- can write the h5 files to a folder to prevent messing up the working directory
- automatic creation of the xdmf files, if desired in every step
- automatic deletion of old files to not mess up the creation of the xdmf files (also works with restart!) (here the setting backwards in time is used)
- Internal settings are automatically selected such as the mpio-setting when doing MPI
- the user does not have to deal with the implementational details of the HDF5 Application, which is for me a bit confusing

Our industry-partners constantly ask for postprocessing capabilities except GiD, this process will make it very easy for them to use.

If you are concerned abt the maintainance, I am happy to do it, since I want/have to use it in my project to give my project partner the possibility to view the output of Kratos.

I know this does not answer all your questions, but maybe it’s better to discuss the rest in person when I‘m back next week.

Philipp

On 17. Sep 2018, at 14:14, Michael Andre <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm open to adding as many output processes as needed to fit the demands of different users. However the output requirements in kratos are very diverse, and therefore it doesn't make sense to me to try to pack them into one process. For example, most users don't know/care about backwards in time since it is very problem specific. They should not have to depend on a process which has settings/logic for backwards in time. And, if I decide to change something about the backwards in time, I should not have to change a process which could break something for the users who don't use backwards in time. My preference would be to have many small, client-specific processes with simple logic/settings than one massive process with many settings and if-statements. The motivation is for stable processes that still work with json parameters months/years later and are easier to maintain by adhering to open-closed and interface-segregation principles.

Based on past experience, I expect that this process would be changed often or evolve into some complex inheritance hierarchy in an attempt to fit new applications and requirements as they arise, causing old json parameters to stop working. I also would not want to review changes to such a large and complex module since I would probably spend a lot of time trying to read and understand what it is doing (and still get it wrong in the end).

Can you give a summary of the new features that should be added in this PR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/KratosMultiphysics/Kratos/pull/2876#issuecomment-421990204>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AYTdnpvQmlkHllEcfjegTyw3d02RcZ9mks5ub5ImgaJpZM4WpOCe>.

2018-09-17 14:51 UTC, msandre commented
Thanks for clarifying. If the goal is to have close to the same json format as the GiD process, I'm fine with that as long as we give it a custom name like hdf5_wrapper_for_gid_output_process.py and test_hdf5_wrapper_for_gid_output_process.py and keep this from spreading into other application files. We can discuss when you are back.

2018-09-17 15:51 UTC, loumalouomega commented
I remember you that you can extrapolate Gauss points values to the nodes (and that way you will be able to represent the GP results) using MeshingApplication.IntegrationValuesExtrapolationToNodesProcess. maybe we can move the process to the core if necessary

2018-12-17 18:56 UTC, philbucher reviewed
@msandre I think the process fits now way better in your framework
Ofc we can still discuss it

2018-12-17 18:56 UTC, philbucher commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
> +        except OSError:
this is the change we discussed

2018-12-17 18:56 UTC, philbucher commented on applications/HDF5Application/python_scripts/file_utilities.py
> +import KratosMultiphysics as KM
this file is a collection of functions that I imagine can be useful also for other things in this app

2018-12-17 18:56 UTC, philbucher commented on applications/HDF5Application/python_scripts/temporal_output_process_factory.py
> +        file_utilities.CheckIfWriteInFolder(settings, model_part)
this is used in case one wants to write the h5 files to a folder
=> check the `file_utilities` to see how it works

2018-12-17 18:56 UTC, philbucher commented on applications/HDF5Application/tests/test_HDF5Application.py
> +from  test_hdf5_output_process import TestHDF5OutputProcess
I will add tests once we agreed on the rest

2018-12-17 18:56 UTC, philbucher commented on applications/HDF5Application/python_scripts/xdmf_visualization_postprocess_process.py
> +import KratosMultiphysics as KM
the name of this process is up for discussion

2018-12-17 19:45 UTC, philbucher commented
this is an example project-params btw:
~~~json
"auxiliar_process_list"            : [{
    "python_module" : "xdmf_visualization_postprocess_process",
    "kratos_module" : "KratosMultiphysics.HDF5Application",
    "process_name"  : "",
    "Parameters"    : {
        "model_part_name": "FluidModelPart",
        "file_settings": {
            "file_access_mode" : "truncate",
            "write_files_in_folder" : true
        },
        "nodal_solution_step_data_settings": {
            "list_of_variables": ["VELOCITY"]
        },
        "element_data_value_settings": {},
        "nodal_data_value_settings": {},
        "output_time_settings": {
            "output_step_frequency": 10
        }
    }
}]
~~~

2018-12-18 09:24 UTC, philbucher reviewed
@msandre with the current changes I can fully support the xdmf-writing

I think the changes I introduced are general enough, but we can discuss it

2018-12-18 09:24 UTC, philbucher commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +            del hdf5_file # force closing of file
Closing the file is currently implemented in the destructor of the hdf-file
Alternatively we could expose this

2018-12-18 09:24 UTC, philbucher commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +    def ExecutePostOutput(self, model_part, hdf5_file_name): pass
I added this bcs this way I can fully support the xdmf 
Plus I think this can also be useful for other outputs

2018-12-21 16:28 UTC, msandre requested changes
@philbucher I spent more time thinking about it and I think we should go ahead with this now. The new features are a good addition and I think the python scripts are overdue for a cleanup/refactoring with the new use cases in mind before we add more features on top. But that is something for next year. This is why I have suggested adding some "todos" below, which will help to remind where things need attention. Besides that, I just some small questions left.

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/xdmf_visualization_postprocess_process.py
> +import temporal_output_process_factory
```suggestion
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/xdmf_visualization_postprocess_process.py
> +    if Model[model_part_name].GetCommunicator().TotalProcesses() > 1:
Nice :+1:

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/tests/test_hdf5_output_process.py
> +    def test_serial_hdf5_output(self):
For consistency
```suggestion
     def test_HDF5SerialOutput(self):
```
probably we will need to come up with a less general name for the test.

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/tests/test_HDF5Application.py
> +from  test_hdf5_output_process import TestHDF5OutputProcess
```suggestion
# todo(philbucher): from  test_hdf5_output_process import TestHDF5OutputProcess
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/file_utilities.py
> +from create_xdmf_file import WriteXdmfFile
```suggestion
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/xdmf_visualization_postprocess_process.py
> +import KratosMultiphysics as KM
Name suggestion: `single_mesh_xdmf_output_process.py`
Reason: current naming convention distinguishes between "single" and "multiple" mesh in the first position. We also distinguish between "input" and "output" in the name. "visualization_postprocess" is not a requirement to use this process and makes the name a lot longer.

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
> +        except OSError:
I tried generating an exception with just python and h5py but couldn't. Can you post a minimal example of the error?

Also, can we send a warning to the logger?

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +        if self._output_step == 0: # this is an output step
```suggestion
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/xdmf_visualization_postprocess_process.py
> +
```suggestion
 #todo(msandre): collapse older partitioned scripts to their serial counterparts like this
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
>      temporal_grid = xdmf.TemporalGrid()
```suggestion
    #todo(msandre): generalize to WriteXdmfFile(xdmf_file_name, list_of_h5_file_paths):
     temporal_grid = xdmf.TemporalGrid()
```

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
> +    full_path_file_name = os.path.join(rel_path_h5_files, file_name)
Would it work to do `os.path.abspath(file_name)` and drop `rel_path_h5_files` as a parameter?

2018-12-21 16:28 UTC, msandre commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +    def ExecutePostOutput(self, model_part, hdf5_file_name): pass
Can we rename to `ExecuteAfterClose`?

2018-12-23 11:28 UTC, philbucher commented
please do not review yet, there are more changes coming

the refactoring of the tests is in a separate PR which should be merged first: #3718

2018-12-29 22:08 UTC, philbucher commented
@msandre :
>  tried generating an exception with just python and h5py but couldn't. Can you post a minimal example of the error?

it happens when you try to open an already open file:
~~~
  File "/home/philipp/software/Kratos_MasterBranch/applications/HDF5Application/python_scripts/create_xdmf_file.py", line 95, in WriteXdmfFile
    with h5py.File(current_file_name, "r") as h5py_file:
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/lib/python3/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2847)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/build/h5py-qzs83i/h5py-2.7.1/h5py/_objects.c:2805)
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open (/build/h5py-qzs83i/h5py-2.7.1/h5py/h5f.c:2129)
OSError: Unable to open file (unable to flock file, errno = 11, error message = 'Resource temporarily unavailable')
~~~

> Also, can we send a warning to the logger?

Sure, done

2018-12-29 22:10 UTC, philbucher commented on applications/HDF5Application/python_scripts/hdf5_io.py
> +        if self._output_step == 0: # this is an output step
I think it would be wrong then
Then it executes `ExecuteAfterClose` all the time, even if the current step is not an output-step

2018-12-29 23:31 UTC, philbucher commented on applications/HDF5Application/python_scripts/create_xdmf_file.py
> +    full_path_file_name = os.path.join(rel_path_h5_files, file_name)
I managed to do it even simpler :D

2018-12-29 23:32 UTC, philbucher commented
@msandre I think I addressed all your comments 
Also tests are added to test the new process

Please have a look

2018-12-29 23:34 UTC, philbucher commented
note that this PR now also contains the cleanup of the tests (#3718) which should be merged first

2019-01-14 11:06 UTC, philbucher commented
ping

2019-01-16 13:31 UTC, msandre approved these changes

2019-01-16 22:26 UTC, merged