[Core] Clean up constraints classes
KratosMultiphysics/Kratos pull request #2889
Opened 2018-09-17 13:51 UTC by loumalouomega

the original poupose of this PR was to move the member variables of the linear_master_slave_constraint to protected, in order to derive new constraints classes. I decided additionally to clean up and extend documentation

2018-09-18 15:55 UTC, adityaghantasala requested changes

2018-09-18 15:55 UTC, adityaghantasala commented on kratos/includes/linear_master_slave_constraint.h
> +        mSlaveDofsVector = mSlaveDofsVector;
this should be 
` mSlaveDofsVector = rOther.mSlaveDofsVector;` or ?

also in the following lines

2018-09-18 16:10 UTC, loumalouomega commented
True, solved @adityaghantasala

2018-09-19 07:24 UTC, adityaghantasala commented
Approving ! Thanks for putting in the doxygen comments !
One question though : SetData and GetData why do this base class need them ?

2018-09-19 07:26 UTC, adityaghantasala approved these changes

2018-09-19 08:15 UTC, loumalouomega commented
To access to the data container, the clone method uses this

2018-09-19 08:15 UTC, merged