[HDF5Application] Add missing output data types to elemental I/O
KratosMultiphysics/Kratos pull request #2903
Opened 2018-09-19 10:25 UTC by sunethwarna

This PR adds some of the missing data types in hdf5 elemental io process.

2018-09-20 15:19 UTC, msandre requested changes

2018-09-20 15:19 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_data_value_io.cpp
> +void SetElementDataValues(Variable<TDataType> const&,
I would omit all parameter names here rather than only one.

2018-09-20 15:19 UTC, msandre commented on applications/HDF5Application/custom_io/hdf5_element_data_value_io.cpp
> +void SetDataBuffer(Variable<Vector<double>> const& rVariable,
To be consistent you could also omit variable names for these prototypes. It's minor but makes maintenance slightly simpler.

2018-09-20 20:27 UTC, sunethwarna commented
@msandre , I made the changes :)

2018-09-21 07:11 UTC, msandre approved these changes
Thanks :+1:

2018-09-21 07:17 UTC, merged