Adding analytic tools
KratosMultiphysics/Kratos pull request #291
Opened 2017-04-15 13:53 UTC by GuillermoCasas

Two tools have been added: 
1. one that measures collisions between particles, which has been tested to work in a  test with two spheres.
2. One that counts fluxes of particles through analytic faces, which for the moment are defaulted to the 'phantom' version, since the collisional one is sort of already implemented in the RIgidFace for measuring wear and should probably be passed to an analytic version which has not been designed yet.

2017-04-19 13:16 UTC, maceligueta commented on applications/DEM_application/custom_conditions/RigidFace.h
> +    class ParticleDataBuffer
shouldn't this be called 'WallDataBuffer'?

2017-04-19 13:19 UTC, maceligueta commented on applications/DEM_application/custom_conditions/analytic_RigidFace.cpp
> +void AnalyticRigidFace3D::ComputeConditionRelativeData(int rigid_neighbour_index,
is this call necessary?

2017-04-19 13:22 UTC, maceligueta commented on applications/DEM_application/custom_elements/analytic_rigid_body_element.h
> +        using Element::Initialize;
not necessary, I think.

2017-04-19 13:58 UTC, maceligueta commented on applications/DEM_application/custom_utilities/analytic_tools/analytic_face_watcher.cpp
> +                                           boost::python::list tangential_relative_vel)
Do you think adding & would make a difference? I guess these lists are working already, so they are being modified in the function, but intuitively I would have received these arguments as a reference...

2017-04-19 14:17 UTC, maceligueta requested changes
There's an unnecessary file: TimesPartialRelease (Guillermo: I remove it in the next pull request, which is the one we will do)
There's also an empt _init_.py file which might be unnecessary. (It is necessary to make files visible from everywhere)

2017-04-20 08:59 UTC, GuillermoCasas commented on applications/DEM_application/custom_utilities/analytic_tools/analytic_face_watcher.cpp
> +                                           boost::python::list tangential_relative_vel)
I had the reference before, but realized they work without it, since they are references already, coming from python...

2017-04-20 09:00 UTC, GuillermoCasas commented on applications/DEM_application/custom_elements/analytic_rigid_body_element.h
> +        using Element::Initialize;
It can be filled up in the future, let as leave it there

2017-04-20 09:01 UTC, GuillermoCasas commented on applications/DEM_application/custom_conditions/RigidFace.h
> +    class ParticleDataBuffer
Yes, I will change it in the next request, which is the one that will be effective. This one will be erased

2017-04-20 09:10 UTC, GuillermoCasas commented on applications/DEM_application/custom_conditions/analytic_RigidFace.cpp
> +void AnalyticRigidFace3D::ComputeConditionRelativeData(int rigid_neighbour_index,
No, this is a left over from a previous design that required overriding. I will remove it in the next pull request, since this one will be cancelled

2017-04-20 11:07 UTC, merged