[Core][ConstitutiveLaw][TO DISCUSS] Adding InitializeMaterialOnIntegrationPoints
KratosMultiphysics/Kratos pull request #2924
Opened 2018-09-23 18:47 UTC by loumalouomega

I am developing together with @frastellini a rule of mixtures law, and in order to consider elements with more than one integration point the CL requires to know the integration method considered and the corresponding integration point index. 

I suggest to add a new method (InitializeMaterialOnIntegrationPoints) that calls by default InitializeMaterial, so in case of not implemented in the derived CL but in the element it preserves the same behavior. I modified the base solid element in order to show this

2018-09-24 15:24 UTC, RiccardoRossi requested changes
the constitutive law should not be aware of integration points... i think you are mising two concepts here

2018-09-24 16:20 UTC, loumalouomega commented
This is done only in the initialization of the CL in order to be able to compute redistribution of the layers when more than one GP is considered. Can we speak about an alternative design?

2018-09-25 07:56 UTC, frastellini commented
I agree with @RiccardoRossi, CL do not need to know integration points.
For each integration point, the composite CL should mix the behaviour of simple CLs (subproperties).
We can talk about the design for doing this...

2018-09-25 08:50 UTC, loumalouomega commented
OK, I will close this then

2018-09-25 08:50 UTC, closed without merging