[StructuralMechanicsApplication][TO DISCUSS+NOT MERGE] Adding RuleOfMixturesLaw (composite parallel law)
KratosMultiphysics/Kratos pull request #2933
Opened 2018-09-25 09:06 UTC by loumalouomega

This uses everything added on #2919. These two PR are related and they work together, one change on #2919 must be applied in this too

This PR adds a composite parallel law (classic rule of mixtures). This work is in close collaboration with @frastellini, he is more familiarized with the technical details

@frastellini, here we can discuss how to consider geometries with more than one GP

2018-10-09 09:52 UTC, frastellini submitted a review, later dismissed
Perfect! Thank you

2018-10-09 09:57 UTC, loumalouomega commented
Let's wait for the @KratosMultiphysics/technical-committee  to approve the #2919

2018-10-16 13:07 UTC, pooyan-dadvand submitted a review, later dismissed
As it is approved but title says for discussion, I block it to avoid merge by mistake.

2018-11-07 18:27 UTC, loumalouomega commented
Can we push this a bit?, I am solving too many conflicts

2019-02-08 15:38 UTC, loumalouomega commented
Conflicts solved

2019-02-08 15:39 UTC, loumalouomega commented
@frastellini can you please contact with @AlejandroCornejo, he is interested in continue the SP developments.

2019-02-08 17:16 UTC, frastellini commented
Yes. We have already commented the current state of developments and I offered Alejandro all my help for the joint development of Serial-Parallel mixing theory in Kratos (after 13 years of the doctoral thesis).
The complete SP composite model is very expensive in terms of computational cost. We can implement the complete model, but also cheaper models like the Vanishing-Fibre-Diameter (where the fibre only contributes in fibre direction, and neglected in transversal ones)

2019-11-09 22:53 UTC, philbucher reviewed
can you please move this law to the advanced-laws folder?

Will you create a test for it?

2019-11-09 22:53 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +    KRATOS_DEBUG_ERROR_IF(mConstitutiveLaws.size() == 0) << "RuleOfMixturesLaw: No constitutive laws defined" << std::endl;
maybe makes more sense to do once in `Check`?

2019-11-09 23:53 UTC, loumalouomega commented
Done

2019-11-13 12:25 UTC, philbucher requested changes
please move the test to the advanced claws tests folder

2019-11-13 12:26 UTC, philbucher commented
> please move the test to the advanced claws tests folder

same for the law itself, still in the wrong folder

Otherwise ok for me

2019-11-13 12:37 UTC, philbucher submitted a review, later dismissed
ok for me
I guess the CLaw guys had enough time to review it ;)
ping @pooyan-dadvand

2019-11-13 12:38 UTC, loumalouomega commented
> 
> 
> ok for me
> I guess the CLaw guys had enough time to review it ;)
> ping @pooyan-dadvand

Done, I moved the files

2019-11-15 08:11 UTC, loumalouomega commented
@pooyan-dadvand can you release the block?, @AlejandroCornejo can you review this?

2019-11-18 13:19 UTC, loumalouomega commented
Pleople from @KratosMultiphysics/structural-mechanics @AlejandroCornejo can anyone review this?

2019-11-18 14:35 UTC, AlejandroCornejo approved these changes
looks okkey to me, there's any test that I can check in order to update the PR of the serial-parallel RoM?

2019-11-18 14:39 UTC, merged

2019-11-18 14:40 UTC, loumalouomega commented
![](https://media2.giphy.com/media/11GWLm7bE2fibC/giphy.gif)