Force-driven inlet
KratosMultiphysics/Kratos pull request #305
Opened 2017-04-19 09:26 UTC by GuillermoCasas

A force-driven inlet has been implemented. itr works fine with DEM. All the DEM tests work.

2017-04-19 09:40 UTC, joaquinirazabal commented
Nice implementation, this would be useful.
This makes me think about creating a specific benchmarks to check if the inlet is working correctly (I don't remember any).
Now I am working in my PhD thesis, but I can do it in the future

2017-04-19 13:50 UTC, GuillermoCasas commented
@joaquinirazabal Sure, we need some benchmarks. I think the issue of inlets is quite interesting, full of technicalities. 

I would like to revisit the concept after my Thesis too and see what work can be done/written about. I am sure Miguel Angel too. Let us talk, when we are both done. Regards

2017-04-19 14:31 UTC, maceligueta commented on applications/DEM_application/custom_conditions/RigidFace.h
>  // Author: Miquel Santasusana msantasusana@cimne.upc.edu
@GuillermoCasas  should be author here, too.

2017-04-19 14:37 UTC, maceligueta requested changes
I see a lot of code duplicated with PR #291 (the same changes are in both branches).
I propose to finish PR #291, then merge master to this branch, then review the code.

From Guillermo: I have reviewed all your comments in the previous pull request, which I will remove and apply all changes to this pull request.

2017-04-20 09:11 UTC, GuillermoCasas commented on applications/DEM_application/custom_conditions/RigidFace.h
>  // Author: Miquel Santasusana msantasusana@cimne.upc.edu
Ok!

2017-04-20 10:21 UTC, maceligueta requested changes
TimesPartialRelease still to be removed

Ok, I will erase it

2017-04-20 10:44 UTC, maceligueta approved these changes

2017-04-20 11:07 UTC, merged