[Core][FluidDynamicsApplication] Changing from AreaNormal to Normal
KratosMultiphysics/Kratos pull request #3123
Opened 2018-10-20 13:41 UTC by loumalouomega

Fixes #940

2018-10-21 22:58 UTC, rubenzorrilla requested changes

2018-10-21 22:58 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/custom_conditions/embedded_ausas_navier_stokes_wall_condition.h
> -            p_ausas_modified_sh_func->ComputePositiveExteriorFaceAreaNormals(
I would only change what concerns to the geometries. Besides, I consider the old method names to be much more self-explicative.

2018-10-21 22:59 UTC, rubenzorrilla requested changes
I would only change what concerns to the geometries. Besides, I consider the old method names to be much more self-explicative.

2018-10-22 06:40 UTC, rubenzorrilla submitted a review, later dismissed
Blocking until we reach consensus.

2018-10-22 08:28 UTC, loumalouomega commented
OK

2018-10-22 09:08 UTC, loumalouomega commented
Now it just changes the geometries files and the calls to the Normal methods

2018-10-23 08:56 UTC, loumalouomega commented on applications/FluidDynamicsApplication/custom_conditions/embedded_ausas_navier_stokes_wall_condition.h
>              for (unsigned int i_gauss = 0; i_gauss < n_gauss; ++i_gauss) {
```suggestion
            // We compute the area normal in each Gauss point
            for (unsigned int i_gauss = 0; i_gauss < n_gauss; ++i_gauss) {
```

2018-10-24 07:51 UTC, loumalouomega commented
@rzorrilla ping

2018-10-24 08:16 UTC, rubenzorrilla commented
OK to what concerns the modified shape functions. However this decision was took 1 year ago, so l'd rather wait for the @KratosMultiphysics/technical-committee approval.

2018-10-24 09:59 UTC, loumalouomega commented
Ok

2018-10-31 08:58 UTC, loumalouomega commented
Ping @KratosMultiphysics/technical-committee

2018-11-01 16:47 UTC, RiccardoRossi reviewed
Area Normal has been changed to Normal in geometry?

@rubenzorrilla is this change ok for you? please review this

2018-11-01 16:48 UTC, RiccardoRossi commented
removing the FastPR label btw

2018-11-01 17:04 UTC, loumalouomega commented
@RiccardoRossi in #940 @pooyan-dadvand  said:

> The pull request correcting geometry normal #936 is the first step to change the behavior of Normal method in geometry. In this step the `Normal` changes to `UnitNormal` and defines `AreaNormal` which is not unit length. In a second step the `AreaNormal` will be changed to `Normal`. This issue is a reminder for the second step.

2018-11-01 19:16 UTC, RiccardoRossi reviewed
Are u sure this change will not break existing code?

2018-11-01 22:44 UTC, loumalouomega commented
I run all the tests and all checks are green

2018-11-05 10:34 UTC, rubenzorrilla commented
@RiccardoRossi did you mean about keeping `AreaNormal()` instead of `Normal()` to return the weighted normal? If this is the case, yes. I'd rather keep `AreaNormal()` which is a much more self-descriptive name than `Normal()`.

Actually, I don't see the problem in having `AreaNormal()` and `UnitNormal()`.

2018-11-05 13:37 UTC, jcotela commented
@RiccardoRossi @rubenzorrilla I believe that what @loumalouomega has implemented here matches the goals we set in the corresponding meeting of the committee. The argument for `Normal` instead of `AreaNormal` was to say that the method would implement the "fastest/most convenient possible" way of obtaining a normal vector.

In triangles it is easy to give it a modulus equal to the normal (`0.5 edge1 x edge2`) but the argument was that this is not true in general or for other geometries, where the area would be something like `Sum (modulus_of_normal_on_gauss_point_i * weight_of_gauss_point_i)` (or something of the sort, I don't remember the details). In the end it was decided to just go with `Normal` and not give any assurance that its modulus would be related to the area of the geometry.

Having said that, I do not have a preference for a specific solution, but I think it is fair to say that this is what was originally requested.

2018-11-05 14:13 UTC, rubenzorrilla commented
Makes sense. If this was @KratosMultiphysics/technical-committee decision,  I'm ok with `Normal()`.

2018-11-05 14:48 UTC, RiccardoRossi commented
@jcotela it is quite important that at least for triangles Normal() (or AreaNormal) delivers the normal multiplies by the Area....

If we give back something equivalent to

     array_1d<double,3> n = ZeroVector(3)
     for(unsigned int igauss = 0; igauss<ngauss; igauss++)
     {
            compute ngauss_unity
            n += integration_weight * ngauss_unity;
     }

so that the the n given back has a norm proportinal to the area of geometry in the direction of the n
than i am ok... if it is not so i need to block since otherwise this would break a lot of things

2018-11-05 14:58 UTC, jcotela commented
@RiccardoRossi I fully agree with you, but if I remember correctly, the argument at the time was that the name `AreaNormal` did not reflect this property either. In any case, let me reiterate that I would not be against an eventual change of name, I am just trying to recall what were the arguments for the decisions agreed on the committee meeting.

Also note that I believe that your definition is not consistent with a naive implementation of `AreaNormal` in triangles (since your gauss_weights sum to 0.5, if I remember correctly).

2018-11-06 07:55 UTC, loumalouomega commented
Then, what should I do?

2018-11-10 11:43 UTC, loumalouomega commented
How to proceed? @KratosMultiphysics/technical-committee

2018-11-30 15:21 UTC, roigcarlo commented
forwarding to @KratosMultiphysics/implementation-committee

2018-11-30 15:40 UTC, loumalouomega commented
This was the design proposed by @pooyan-dadvand in #940

2018-12-10 14:54 UTC, AlejandroCornejo submitted a review, later dismissed
approved by the implementation committee but need some documentation

2018-12-10 14:58 UTC, adityaghantasala commented on kratos/geometries/line_2d_2.h
>       * @return The area normal in the given point
not area normal ... but normal scaled with the area

2018-12-10 16:01 UTC, GuillermoCasas requested changes
It is not the 'normal scaled with the area', but rather the normal (external?) whose modulus is equal to the area of the underlying geometry. Please, could your documentation reflect this, more accurate, description?

2018-12-10 16:08 UTC, GuillermoCasas commented
Going back to the comments by @jcotela I realize that even the description I suggest in my previous comment is not accurate. Perhaps a more flexible description of what the method returns would be 'it returns a vector that is normal to its corresponding geometry', since there is no guarantee that it will be easy or feasible (see @jcotela comment) to implement a normal whose modulus is equal to the area in all cases. For a triangle, nonetheless, the previously mentioned description would be ok.

2018-12-10 16:11 UTC, loumalouomega commented
> it returns a vector that is normal to its corresponding geometry'

OK, I update the description

2018-12-10 17:26 UTC, GuillermoCasas approved these changes

2018-12-10 19:48 UTC, merged