[StructuralMechanicsApplication] Reduce verbosity on the StructuralMechanicsApplication tests
KratosMultiphysics/Kratos pull request #3165
Opened 2018-10-24 17:57 UTC by loumalouomega

2018-10-24 19:01 UTC, philbucher requested changes
Thanks, I will take a proper look tmr

Last time I had to spend a lot of time fixing tests bcs I didn’t look in detail xD

2018-10-24 19:30 UTC, loumalouomega commented
I run the tests :P

2018-10-25 08:42 UTC, philbucher approved these changes
if the tests are running then I approve :)

2018-10-25 08:42 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/adjoint_sensitivity_analysis_tests/adjoint_shell_structure_3d3n/linear_shell_test_nodal_disp_adjoint_parameters.json
> +            "time_step" : 1.0
@armingeiser @MFusseder FYI I would use a timestep > 1.0 in order to avoid problems with numerics => suggested: 1.1

2018-10-25 12:06 UTC, merged

2018-10-25 12:10 UTC, armingeiser commented
@loumalouomega thanks!

2018-10-25 12:12 UTC, loumalouomega commented
![imagen](https://user-images.githubusercontent.com/19991680/44592716-ab580800-a7c1-11e8-8f79-2b00ea1a830a.png)