More robust deactivation
KratosMultiphysics/Kratos pull request #318
Opened 2017-04-21 22:27 UTC by rubenzorrilla

Now those elements which fixed and inactive nodes sumamation is equal (or even larger) than the total number of nodes are deactivated as well.

2017-04-23 09:50 UTC, RiccardoRossi requested changes
you need to check for the components. The use of IsFixed you make is not correct

2017-04-23 09:50 UTC, RiccardoRossi commented on applications/FluidDynamicsApplication/custom_processes/distance_modification_process.h
> +                if (rGeometry[itNode].IsFixed(VELOCITY))
this makes no sense (and i guess it does not compile)

you need to check for the components

       if (rGeometry[itNode].IsFixed(VELOCITY_X))

2017-04-23 11:06 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/custom_processes/distance_modification_process.h
> +                if (rGeometry[itNode].IsFixed(VELOCITY))
You're right. Probably I committed a wrong file version. My bad. Thanks @RiccardoRossi .

2017-04-24 15:12 UTC, RiccardoRossi approved these changes
+1

2017-04-24 15:53 UTC, merged