[MeshMoving] increasing buffer-size only if needed
KratosMultiphysics/Kratos pull request #3324
Opened 2018-11-09 15:25 UTC by philbucher

In this PR I decrease the min-buffer size for the mesh-motion-solver

If it is used only for solving the mesh and not for computing the mesh-velocity (for which I am currently writing another utility) then a buffer-size of 1 should be sufficient
Only the [laplacian-solver needs 2](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshMovingApplication/custom_elements/laplacian_meshmoving_element.cpp#L65-L66)
@AndreasWinterstein can you confirm this please? We should speak abt this next week

@rubenzorrilla @dbaumgaertner I don't know how you handle the buffer-sizes
This solver used quite a large one so far (3), it could be if you don't do this yourselves so far that you now have to do it (which I think is the correct way anyway)
Please check your scripts

Tests are still working

2018-11-09 22:58 UTC, AndreasWinterstein submitted a review, later dismissed
This should be correct.

2018-11-10 09:57 UTC, AndreasWinterstein commented
If there are no complains from @rubenzorrilla or @dbaumgaertner I will merge this PR this evening.

2018-11-10 10:22 UTC, rubenzorrilla requested changes
(Blocking to avoid accidental merges)

I'm OK with the changes but my concern is about changing the buffer size of the mesh model part. Such mesh model part coincides with the fluid model part (at least in my FSI solvers and I think that this might be the same for other moving boundary solvers).

Does this imply that depending on the mesh solver we might be accidentally setting a buffer size which is not large enough for the fluid? Maybe we need to add a check of the current buffer size before modifying it.

2018-11-10 10:36 UTC, philbucher commented
@AndreasWinterstein I agree with @rubenzorrilla , this change might cause problems so we shouldn't hurry here

@rubenzorrilla I see your point, I will add the corresponding check
In the meantime I checked your FSI-solvers, it seems like you are fine
in `PrepareModelPart` you don't call `PrepareModelPart` for the meshsolver (which is how we also do it, since the fluidsolver should take care of this) and in `_GetAndSetMinimumBufferSize` you check for the required buffer-sizes of all solvers

2018-11-10 10:40 UTC, RiccardoRossi commented
can u wait until monday?

On Sat, Nov 10, 2018, 10:57 AM AndreasWinterstein <notifications@github.com
wrote:

> If there are no complains from @rubenzorrilla
> <https://github.com/rubenzorrilla> or @dbaumgaertner
> <https://github.com/dbaumgaertner> I will merge this PR this evening.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/3324#issuecomment-437572381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHr7ETghTAenSihhC0j0J-7vYoNbf2bkks5utqMmgaJpZM4YWxYq>
> .
>

2018-11-10 10:40 UTC, RiccardoRossi commented
ui forget it.,.ruben answered

On Sat, Nov 10, 2018, 11:39 AM Riccardo Rossi <rrossi@cimne.upc.edu wrote:

> can u wait until monday?
>
> On Sat, Nov 10, 2018, 10:57 AM AndreasWinterstein <
> notifications@github.com wrote:
>
>> If there are no complains from @rubenzorrilla
>> <https://github.com/rubenzorrilla> or @dbaumgaertner
>> <https://github.com/dbaumgaertner> I will merge this PR this evening.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/KratosMultiphysics/Kratos/pull/3324#issuecomment-437572381>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AHr7ETghTAenSihhC0j0J-7vYoNbf2bkks5utqMmgaJpZM4YWxYq>
>> .
>>
>

2018-11-10 10:41 UTC, philbucher commented
btw my new favorite: `Blocking to avoid accidental merges` :D

2018-11-10 10:49 UTC, philbucher commented
@rubenzorrilla I added a check, now it also takes into consideration if there was already a buffer-size specified in the ModelPart

2018-11-10 11:01 UTC, rubenzorrilla commented
@philbucher thanks! Go ahead with the accidental merge :smile:

2018-11-10 11:01 UTC, rubenzorrilla approved these changes

2018-11-12 13:14 UTC, dbaumgaertner commented
@philbucher fine from my side

2018-11-12 18:21 UTC, merged