Core/adding global pointer serialization
KratosMultiphysics/Kratos pull request #3461
Opened 2018-11-22 16:46 UTC by RiccardoRossi

this branch adding a container for global pointers with a working serialization mechanism.

the save and load functions use specialized save and load operators of global pointer.

**a somewhat specific behaviour however is that the object to which the GlobalPointer points to is not serialized (only the address of it is)**

2018-11-24 13:59 UTC, roigcarlo commented on kratos/containers/global_pointers_vector.h
> +				    GlobalPointersVector<TDataType>& rThis){}
```suggestion
				    GlobalPointersVector<TDataType>& rThis){ return rIStream;}
```

2018-11-24 13:59 UTC, roigcarlo commented on kratos/containers/global_pointers_vector.h
> +				    GlobalPointersVector<TDataType>& rThis){}
That should fix the travis error

2018-11-26 10:02 UTC, pooyan-dadvand commented
I see a technialc

2018-11-26 10:02 UTC, pooyan-dadvand commented
Sorry I closed it accidentally

2018-11-26 10:13 UTC, pooyan-dadvand requested changes
This implementation will break the use of global pointer as a local pointer after load....
Consider:
```c++
GlobalPointer p_node(0, &some_node); // points to position of some_node which is 0x1A1A in memory
save(p_node) //saving the 0x1A1A
save(some_node) 
....
load (p_node)   // now points to 0x1A1A 
                // which may be out of application memory: using it -> segmentation fault
load(some_node) // it is allocated in 0x1234 and p_node is not pointing to it!
```

2018-11-26 11:08 UTC, roigcarlo commented
Agree with @pooyan-dadvand, but I think @RiccardoRossi code is legit even in the scenario you suggest.

GlobalPointer was not ment to be serializable in the first place (hence the lack of save/load functions) and as I told @RiccardoRossi I can't remember the exact reasons for that decision but it may perfectly be related to this.

Once you serialize your global pointer you need to decide how they will behave: 

### 1 - You follow the pointer chain
and serialize everything, you cannot use such serializer to transfer them over processes as they will lose their relevance:

```C++
// Process 1
auto Node::Pointer some_node; // some_node = 0x1000
GlobalPointer some_node_gp:   // some_node_gp(@) -> 0x1000, some_node_gp(proc) -> 1
    // We serialize following the pointer chain

// Process 2 
    // We deserialize
auto Node::Pointer some_node; // some_node = 0x2000
GlobalPointer some_node_gp:   // some_node_gp(@) -> 0x2000, some_node_gp(proc) -> 1
```

Which doesn't make any sense as the GlobalPointer should keep the pointer of the original proc. But if you just save to a file and restore in the same proc the result will be ok.

### 2 - You keep the pointer
```C++
// Process 1
auto Node::Pointer some_node; // some_node = 0x1000
GlobalPointer some_node_gp:   // some_node_gp(@) -> 0x1000, some_node_gp(proc) -> 1
    // We serialize following the pointer chain

// Process 2 
    // We deserialize
auto Node::Pointer some_node; // some_node = 0x2000
GlobalPointer some_node_gp:   // some_node_gp(@) -> 0x1000, some_node_gp(proc) -> 1
```

Which is ok from the point of view of the GlobalPointer functionality, but as @pooyan-dadvand  points out will not work if you are trying to restore a process: the pointer will be GlobalPointer.

The only solution I see for this is to decide which behavior we want or make a specialized version of the serializer which handles the pointer differently. In which case we should move the save/load function of the global pointer inside the serializer itself.

2018-11-26 15:38 UTC, RiccardoRossi commented
From my point of view, the meaning of a GlobalPointer is closely related to that of a Weak Pointer.

I believe that the content of a GlobalPointer should NOT be serialized, that is, that the only relevant information to be serialized is the pointer address.
This however is one of the cases in which the meaning of serialization as "stop and restart" is very different from the use as mpi transfer.

From my point of view, the Stop-and-restart behaviour that we should have is a sort of "delayed loading".

With this i mean that in the load function we should construct  a list of the global pointers we load, pointing to the address that was originally stored.
At the end of the loading, when all the objecs are deserialized, we could go through this list and reassign the addresses according to the [saved_address, loaded_address] table constructed in the serializer.

this would mean that the global pointer containers would need to have two functions, one serializing to an array of addresses (without ant change) and a "real" save/load with the delayed mechanism. The second one could use internally the first, while the first would also have its use for efficient mpi transfer

2018-11-26 16:27 UTC, pooyan-dadvand commented
I see....
Nevertheless, I'm pretty sure that if we put the save and load someone would store it...
Maybe we should add some flags to serializer to distinguish between MPI, restart, dump, memory count, etc...:
```c++
if(serializer.Is(Serializer::MPI))
    save(pointer_address);
else
    KRATOS_ERROR << "you may not use global pointer for save and load";
```
or 
```c++
if(serializer.Is(Serializer::MPI))
    save(pointer_address);
else if(serializer.Is(Serializer::RESTART))
    save(pointer);
// do nothing for memory count ....
```
About the weak_ptr I disagree, I think they are valid cases in which they have to be saved and loaded... (i.e. parent element in hierarchical elements)

2018-11-29 15:06 UTC, RiccardoRossi commented
unfortunately it is not trivial to add flags to the serializer. The problem is that the serializer itself is used everywhere (and in particular in the flags) so including the flags in the serializer generates a cyclic include.

i could have a sort of behavioural flag included in the serializer...

2018-12-06 18:53 UTC, RiccardoRossi reviewed
@pooyan-dadvand serializer is now derived from flags as agreed. This required some gymnastics with a forward declaration of serializer in flags, but it doesn't look too bad

2018-12-07 14:14 UTC, RiccardoRossi reviewed
@pooyan-dadvand i think this is now ready for being in master

2018-12-28 09:49 UTC, RiccardoRossi commented
approving anyway, since the epsilon i pointed to has a different meaning

2019-01-09 11:02 UTC, pooyan-dadvand approved these changes
I would have used `static_cast` instead of `interpreter_cast` as they don't change the pointer address for alignment. However in your case the alignment is the same and the behaviour should be the same.

2019-01-14 10:27 UTC, merged

2019-01-14 10:28 UTC, RiccardoRossi commented
leaving this branch opened to try changing reinterprete_cast -> static_cast

2019-06-09 09:06 UTC, loumalouomega commented
@RiccardoRossi do you still need this branch?

2019-06-09 09:23 UTC, RiccardoRossi commented
no, please.feel free to remove, thx

On Sun, Jun 9, 2019, 11:06 AM Vicente Mataix Ferrándiz <
notifications@github.com> wrote:

> @RiccardoRossi <https://github.com/RiccardoRossi> do you still need this
> branch?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/3461?email_source=notifications&email_token=AB5PWEKTOSBVAQGROQ4HHV3PZTBZXA5CNFSM4GF6V7RKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXIGPZY#issuecomment-500197351>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB5PWENXJGVKTJHLMFPG27LPZTBZXANCNFSM4GF6V7RA>
> .
>