[ShapeOpt] fix initialization of ALPHA_MAPPED
KratosMultiphysics/Kratos pull request #3618
Opened 2018-12-08 16:11 UTC by armingeiser

ALPHA needs to be mapped before the first shape update if the bead side is chosen to be "negative" or "positive" instead of "both. 
Otherwise the optimization starts with a sharp kink in the mesh

To be merged after #3617

2018-12-08 16:12 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/algorithm_bead_optimization.py
> +        # initialize according to initial ALPHA values
```suggestion
        # Initialize ALPHA_MAPPED according to initial ALPHA values
```

2018-12-10 07:44 UTC, dbaumgaertner requested changes
Good that you found this. Thanks. Just a minor thing I commented.

2018-12-10 07:44 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/algorithm_bead_optimization.py
> +        self.mapper.Map(ALPHA, ALPHA_MAPPED)
It's better to put this to the function InitializeOptimizationLoop, I guess. As your comment already suggests, this is part of the initialization.

2018-12-10 10:24 UTC, dbaumgaertner approved these changes

2018-12-10 14:39 UTC, merged