[Core] Separating the register in the core from variables.cpp
KratosMultiphysics/Kratos pull request #3666
Opened 2018-12-15 11:30 UTC by loumalouomega

Fixes #3209

2018-12-15 11:31 UTC, loumalouomega commented
@AlejandroCornejo I meant this

2018-12-15 11:34 UTC, loumalouomega commented on kratos/sources/variables.cpp
> -    KRATOS_REGISTER_VARIABLE(IS_JACK_LINK)
I remove these variables because are registered already in the deprecated_variables.cpp. Without this is not possible to compile

2018-12-15 14:31 UTC, AlejandroCornejo commented
this doesn't generates incompatibilities isn't it?

2018-12-15 14:38 UTC, loumalouomega commented
Nope, and it compiles slightly faster as can be seen in the checks

2018-12-15 14:39 UTC, AlejandroCornejo commented
ok!

2018-12-15 14:39 UTC, AlejandroCornejo submitted a review, later dismissed

2018-12-15 14:40 UTC, loumalouomega commented
I will wait for @pooyan-dadvand or @KratosMultiphysics/technical-committee  approval, this is important

2018-12-15 14:41 UTC, AlejandroCornejo commented
Yes, i agree

2018-12-19 08:56 UTC, pooyan-dadvand commented
I don't see the conclusion of @KratosMultiphysics/implementation-committee in #3209 yet. 

In such a cases I would suggest the implementation team to block the PR (to avoid accidental merge) until the other discussion concluded and passes to @KratosMultiphysics/technical-committee

2018-12-19 09:03 UTC, pooyan-dadvand requested changes
In case of changing I would suggest to put the registery in application.cpp or variable_registering.cpp

Also I would directly look for a way to unify the creation and registration.

2018-12-19 10:01 UTC, loumalouomega commented
> I don't see the conclusion of @KratosMultiphysics/implementation-committee in #3209 yet.
> 
> In such a cases I would suggest the implementation team to block the PR (to avoid accidental merge) until the other discussion concluded and passes to @KratosMultiphysics/technical-committee

We haven plan any meeting for this week. I did the PR because I tried in my computer to do this changes and to have a magnitude order of the complexity of the task. it compiled in the first try, so I did the PR, that way is easier to discuss with some existing code.

The only thing I would improve is the name of the file. Like core_register.cpp or something like that

2018-12-19 11:45 UTC, GuillermoCasas commented
@loumalouomega Yes, Let us discuss the issue this week briefly. About changing the name to variables_register.cpp, it makes sense to me in principle, but only if what is done there is only registering the variables and not anything else. Also, would the name 'variables.cpp' reflect the contents of the file then?. Furthermore, It is not clear to me why a bunch of classes should be registered (and created) in one file and only the variables in another Why not do more types of classes in separate files?. Also, the flags, which are rather variable-like, would be defined in the general core_register.cpp, somewhat unexpectedly.

2018-12-19 11:50 UTC, loumalouomega commented
> @loumalouomega Yes, Let us discuss the issue this week briefly. About changing the name to variables_register.cpp, it makes sense to me in principle, but only if what is done there is only registering the variables and not anything else. Also, would the name 'variables.cpp' reflect the contents of the file then?. Furthermore, It is not clear to me why a bunch of classes should be registered (and created) in one file and only the variables in another Why not do more types of classes in separate files?. Also, the flags, which are rather variable-like, would be defined in the general core_register.cpp, somewhat unexpectedly.

The only thing I know for sure is that register everything in a file with a name as "variables" is confusing. We can discuss potential names and the way to proceed.

2018-12-23 13:48 UTC, RiccardoRossi commented
+1 for pooyan's comment.
 
note that the path we expect is:
1 - Implementation committee should reach a conclusion by consensus (NOT by voting). 
2 - the reccomendation is explained in the issue. If no consensus is reached it should be indicated
3 - the issue is passed to the @KratosMultiphysics/technical-committee for the final approval.

2018-12-23 15:41 UTC, loumalouomega commented
> +1 for pooyan's comment.
> 
> note that the path we expect is:
> 1 - Implementation committee should reach a conclusion by consensus (NOT by voting).
> 2 - the reccomendation is explained in the issue. If no consensus is reached it should be indicated
> 3 - the issue is passed to the @KratosMultiphysics/technical-committee for the final approval.

We understood, we will try to find a date for a future meeting for the @KratosMultiphysics/implementation-committee

2018-12-23 16:50 UTC, GuillermoCasas commented
@RiccardoRossi Concerning the three different points you mention about what is expected from the @KratosMultiphysics/implementation-committee:
1. We have agreed upon a consensus-based methodology, that we are currently trying. It is based on a minimum of three (out of five members) consensual affirmations with no discordant opinions in a fixed period of time after the consensus is reached.
2. We have not yet held the meeting to discuss this issue, although I suggest to schedule one in the interval December 27 to 31 to reach a conclusion; otherwise it will be left for after-Christmas.
3. Yes, maybe we can do it by applying the label 'Consensus' that I have just created.

2018-12-26 09:41 UTC, RiccardoRossi commented
dear Guillermo,

we specifically want you to reach a consensus. if this is not possible say
that no reccomendation could be reached and expose the different arguments.
there should be no time limit (within reason). the goal is NOT to have a
quick answer but rather a well thought one.


On Sun, Dec 23, 2018, 5:50 PM Guillermo Casas <notifications@github.com
wrote:

> @RiccardoRossi <https://github.com/RiccardoRossi> Concerning the three
> different points you mention about what is expected from the
> @KratosMultiphysics/implementation-committee
> <https://github.com/orgs/KratosMultiphysics/teams/implementation-committee>
> :
>
>    1. We have agreed upon a consensus-based methodology, that we are
>    currently trying. It is based on a minimum of three (out of five members)
>    consensual affirmations with no discordant opinions in a fixed period of
>    time after the consensus is reached.
>    2. We have not yet held the meeting to discuss this issue, although I
>    suggest to schedule one in the interval December 27 to 31 to reach a
>    conclusion; otherwise it will be left for after-Christmas.
>    3. Yes, maybe we can do it by applying the label 'Consensus' that I
>    have just created.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/3666#issuecomment-449649452>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AHr7Efio80AIGp3eMn9kuMpYUCxZAPY-ks5u77RRgaJpZM4ZUsdA>
> .
>

2018-12-26 18:52 UTC, GuillermoCasas commented
Dear @RiccardoRossi, I understand. The fixed time limit is there as a guide, precisely to keep it ‘within reason’ and it does not need to be a short time.

2018-12-26 19:07 UTC, GuillermoCasas commented
Given that the members of the @KratosMultiphysics/implementation-committee will be away for most of the following 2 weeks, we pospone our resolution for this and the rest of pending issues until after the Christmass period (after around January 7)

2019-01-21 15:10 UTC, GuillermoCasas commented
The @KratosMultiphysics/implementation-committee has reached the consensus that this PR is a step forward and it improves the organization. We still have doubts about the name of the new file 'kratos_core.cpp' and the convenience of the location of the flags separately from the regular variables. We leave these issues to the @KratosMultiphysics/technical-committee.

2019-02-20 12:25 UTC, pooyan-dadvand commented
I will review the changes. Meanwhile in @KratosMultiphysics/technical-committee we do not agree with the name of the kratos_core.cpp believing that the kratos_application.cpp is a better option.

2019-02-20 13:34 UTC, loumalouomega commented
> I will review the changes. Meanwhile in @KratosMultiphysics/technical-committee we do not agree with the name of the kratos_core.cpp believing that the kratos_application.cpp is a better option.

OK, I think that the name is just a convection

2019-02-20 20:28 UTC, loumalouomega commented
@pooyan-dadvand Updated to kratos_application

2019-02-25 13:50 UTC, pooyan-dadvand reviewed
I consider this refactory a clear imporovement of what we have due to many legacy changes. Nevertheless I see this very related to #3789 and #2902 and a factory base solution would remove completely the `RegisterVariables`

2019-02-25 16:23 UTC, loumalouomega commented
> I consider this refactory a clear imporovement of what we have due to many legacy changes. Nevertheless I see this very related to #3789 and #2902 and a factory base solution would remove completely the `RegisterVariables`

This can be fixed, the part related with the variables remains the same

2019-04-16 08:05 UTC, pooyan-dadvand commented
I mean merging this would cause lot of conflicts with the other ones. But I'm open to approve it.

2019-04-16 08:17 UTC, loumalouomega commented
> I mean merging this would cause lot of conflicts with the other ones. But I'm open to approve it.

I understand, but one of the reasons there are a lot of potential conflicts with this change is because the current implementation centralizes everything. In the future this kind of issues will be reduced

2019-04-16 08:56 UTC, philbucher commented
+1 from my side for approval, it will already solve some problems, others can be dealt with then later, I don't think it will be difficult

2019-04-24 09:11 UTC, pooyan-dadvand approved these changes
Thanks for cleanup! :+1:

2019-04-24 09:22 UTC, merged

2019-04-24 09:22 UTC, loumalouomega commented
thanks