[ConvectionDiffussionApplication] Adding option to deactivate the mesh check with check_mesh_orientation
KratosMultiphysics/Kratos pull request #3711
Opened 2018-12-21 11:08 UTC by loumalouomega

@RiccardoTosi is having some problems with the process after remeshing, but the bug is in the process itself (it is related with two conditions sharing the same nodes), I couldn't find the time to solve it properly. This options keeps the current code working as now, but the check can be manually deactivated is desired

2018-12-21 12:23 UTC, philbucher commented on applications/convection_diffusion_application/python_scripts/convection_diffusion_base_solver.py
>              KratosMultiphysics.ReplaceElementsAndConditionsProcess(self.main_model_part,self._get_element_condition_replace_settings()).Execute()
this is potentially dangerous, please add a warning in case the user disables it
sth like "WARNING, manually disabling the mesh-orientation-check, which is only recommended for developers / ppl that know what they are doing" or similar, I think you get what I mean :)

Also remember to remove this again once you figured out what is the problem with the `TetrahedralMeshOrientationCheck`

2018-12-21 13:19 UTC, loumalouomega commented on applications/convection_diffusion_application/python_scripts/convection_diffusion_base_solver.py
>              KratosMultiphysics.ReplaceElementsAndConditionsProcess(self.main_model_part,self._get_element_condition_replace_settings()).Execute()
yep

2018-12-21 13:22 UTC, loumalouomega commented on applications/convection_diffusion_application/python_scripts/convection_diffusion_base_solver.py
>              KratosMultiphysics.ReplaceElementsAndConditionsProcess(self.main_model_part,self._get_element_condition_replace_settings()).Execute()
Done

2018-12-21 13:37 UTC, philbucher approved these changes
can you please make an issue describing the problem you have to not forget abt this

2018-12-21 14:06 UTC, loumalouomega commented
Not need, I have a branch locally to solve that, that is my reminder

2018-12-21 15:15 UTC, rubenzorrilla requested changes
Personally I disagree about solving the issue in this way, since the bug will probably remain in there for quite a  long time... 

I know that you are extremely busy but maybe @RiccardoTosi has time to recover your branch and go through it to propose a final fix.

2018-12-21 15:23 UTC, loumalouomega commented
@rubenzorrilla, @RiccardoTosi needs this. For me this is not important, please let him say something

2018-12-21 15:34 UTC, RiccardoTosi commented
I can look into the function. Up to now the check is blocking after the mmg refinement process (not earlier). I would have accepted the PR and then looked into the check function because it is stopping my PR, but if @rubenzorrilla thinks so we can do his way.

2018-12-21 17:34 UTC, philbucher commented
@RiccardoTosi you can always comment this check in your local version ...

2018-12-23 11:51 UTC, philbucher commented
I think this can be closed, @RiccardoTosi has a local fix for this => #3717

2018-12-23 11:55 UTC, closed without merging

2018-12-23 11:55 UTC, loumalouomega commented
Done