Structural/Adding the d+d- and isotropic damage CL in 2D
KratosMultiphysics/Kratos pull request #3783
Opened 2019-01-08 18:20 UTC by AlejandroCornejo

In this PR I'm adding the d+d- and isotropic damage laws for the 2D case. Besides I've improved some fatures of the d+d- cl that some people asked for.

2019-01-09 09:56 UTC, AlejandroCornejo commented
ping

2019-01-09 17:22 UTC, AlejandroCornejo commented
@loumalouomega  pls take a look whenever you can :)

2019-01-09 19:15 UTC, loumalouomega requested changes
Look at my comment

2019-01-09 19:15 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/custom_constitutive/generic_small_strain_d_plus_d_minus_damage.cpp
> +       //return BaseType::GetValue(rThisVariable, rValue);
Why commenting?

2019-01-10 08:41 UTC, AlejandroCornejo commented on applications/StructuralMechanicsApplication/custom_constitutive/generic_small_strain_d_plus_d_minus_damage.cpp
> +       //return BaseType::GetValue(rThisVariable, rValue);
I forgot to uncomment jejeje thank you

2019-01-10 09:59 UTC, loumalouomega approved these changes
I activate it myself, I approve

2019-01-10 12:40 UTC, merged