Hotfix add missing functions to
KratosMultiphysics/Kratos pull request #381
Opened 2017-05-08 15:02 UTC by roigcarlo

This fixes #379.

Also, @GuillermoCasas I commented `GetMinPoint()` and `GetMaxPoint()` functions bodies from the `discrete_particle_configure.h` since the function states `void ...` but they are returning values. In modern compiler this is no longer a warning but an error. 

Not sure what is the mistake here so I leaving it like this, feel free to change it directly in this branch.

2017-05-08 15:23 UTC, GuillermoCasas requested changes
The GetMaxPoint() returning void is a mistake. It should return array_1d.That requires changing the type of mDomainMax, which I think is a good thing, anyway. Maybe it is cleanest if you do it, so let me require the changes. Otherwise I can take care of it...

2017-05-08 15:34 UTC, roigcarlo commented
@GuillermoCasas I've temporally changed that to return `double *` 

I would made the changes you suggest myself but after looking at the code It is not clear to me where this is being used right now ( I am compiling DEM, SWIMMING, PARTICLES and FLUID but can't find any usage) so I would prefer if you can take care of it since I am not sure what implications this will have or where since I can't identify where its being used.

2017-05-09 08:57 UTC, roigcarlo commented
@GuillermoCasas Could we merge this and tackle the problem in a separate PR? We are stalling some PR and the nightly builds :pray:

2017-05-09 11:41 UTC, GuillermoCasas commented
Yes, sure.

2017-05-09 11:42 UTC, GuillermoCasas approved these changes

2017-05-09 11:42 UTC, merged

2017-05-09 11:42 UTC, GuillermoCasas commented
I did merged.