[Dem]review benchmarks
KratosMultiphysics/Kratos pull request #3830
Opened 2019-01-15 11:57 UTC by farrufat-cimne

2019-01-15 11:57 UTC, farrufat-cimne commented
added fix for cluster destructor

2019-01-15 13:55 UTC, maceligueta commented
@farrufat-cimne , I see 209 files changed for a small code modification. I think it's due to a folder renaming.
Let's try this
`git mv test_examples benchmarks`
instead of changing the name outside git. In this way maybe the PR will be cleaner and, if it works, we'll learn something new.

2019-01-15 14:23 UTC, maceligueta commented
Forget my last comment, I tried myself and apparently it changes the name of each file, exactly the same as what we had.

2019-01-15 14:29 UTC, farrufat-cimne commented
fixed codacy errors

2019-01-16 09:59 UTC, GuillermoCasas commented
@farrufat-cimne Please resolve the conflicts.

2019-01-16 10:02 UTC, maceligueta commented
There's a file called '.directory' that should not be there, I think it comes from the Operating System.

2019-01-16 16:24 UTC, GuillermoCasas requested changes

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/benchmarks/multiprocess_benchmarking_full.py
> +            # if benchmark == 30:
Please, either remove these lines or not, do not just comment them.

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/benchmarks/multiprocess_benchmarking_full.py
> +        #### Discontinuum Tests. From 1 to 17
unnecessary

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/python_scripts/DEM_benchmarks_class.py
> +                    angular_node_z = node.GetSolutionStepValue(ANGULAR_VELOCITY)[2]
Could you make this type of assignments more concise? There are many of them in this file

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/python_scripts/DEM_benchmarks_class.py
> +                    force_node = sqrt(force_node_x*force_node_x + force_node_y*force_node_y + force_node_z*force_node_z)
Could you not just implement a modulus function?

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/python_scripts/DEM_benchmarks_class.py
> +                    data.write(str("%.8g"%time).rjust(12)+" "+str("%.6g"%force_node).rjust(13)+" "+str("%.6g"%angular_node).rjust(13)+" "+str("%.6g"%displacement_node).rjust(13)+"\n")
Could you encapsulate tyhis kind of writes? They seem to repeat often

2019-01-16 16:24 UTC, GuillermoCasas commented on applications/DEMApplication/test_examples/basic_benchmarks/paper_data/.directory
> -[Dolphin]
Please remove this directory as discussed

2019-01-17 11:01 UTC, closed without merging