[core] split validate and assign defaults and testing
KratosMultiphysics/Kratos pull request #3889
Opened 2019-01-18 15:50 UTC by armingeiser

Splits the implementation of the `ValidateAndAssignDefaults` into `AssignDefaults` and `ValidateDefaults`. the same for the recursive versions.

This allows more flexible handling of special cases of default parameters.

E.g. if some defaults should be assigned to a parameter object, without checking all parameters which are already there.

2019-01-18 15:53 UTC, armingeiser commented
By the way: are the versions with non const function argument `(Parameters& rDefaultParameters)` really needed? I think the `rDefaultParameters` should never be modified in those functions...

2019-01-21 08:01 UTC, philbucher reviewed
+1 for only having the function that accepts a `const` argument in case it should not be modified

Will take a closer look later

2019-01-21 08:36 UTC, RiccardoRossi commented
guys 2 things:

1 - you should not pass by reference a parameters object because of how it is implemented
2 - the non const version is defined as the modifications of the AssignDefault need to be stored in the parameters...

2019-01-21 08:43 UTC, loumalouomega commented
Even with the new implementation?

El lun., 21 ene. 2019 9:36, Riccardo Rossi <notifications@github.com>
escribió:

> guys 2 things:
>
> 1 - you should not pass by reference a parameters object because of how it
> is implemented
> 2 - the non const version is defined as the modifications of the
> AssignDefault need to be stored in the parameters...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/KratosMultiphysics/Kratos/pull/3889#issuecomment-455989059>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATEMgK8Law1wSL-9B97qMgYizeifM4pSks5vFXwIgaJpZM4aIKPI>
> .
>

2019-01-21 08:43 UTC, armingeiser commented
@RiccardoRossi 

1. The currently implemented functions in the kratos_parameter.h e.g. https://github.com/KratosMultiphysics/Kratos/blob/ea96ef46647d11c868eb35c17cab775366166e5c/kratos/includes/kratos_parameters.h#L734
already do that. So this should be changed too, right? 

2. The modifications should only be applied to the object where the method is called, not to the argument which are the defaults. So the method is non const, but the argument could be const.

2019-01-21 10:41 UTC, RiccardoRossi commented
@loumalouomega in this the behaviour should not be changed. ProjectParameters is a handle to a library below that.

regarding the const, and thinking about, we are not modifying the default parameters, so it can indeed be const

2019-01-21 10:42 UTC, RiccardoRossi commented
(point 2, implies that my previous comment was wrong...we can leave only the const version, and in this context most probably the & is ok)

2019-01-21 10:49 UTC, armingeiser commented
I removed the overloads with a non const argument. Tests are running.

2019-01-21 10:58 UTC, philbucher reviewed
some minor comments, haven't looked at it in detail yet

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the parameters under testing match the form prescribed by the rDefaultParameters. (const version)
```suggestion
     * @brief This function is designed to verify that the parameters under testing match the form prescribed by the rDefaultParameters.
```

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the parameters under testing contain at least all parameters prescribed by the rDefaultParameters. (const version)
```suggestion
     * @brief This function is designed to verify that the parameters under testing contain at least all parameters prescribed by the rDefaultParameters.
```

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the all parameteters in the parameters under testing have a matching parameter prescribed by the rDefaultParameters. (const version)
```suggestion
     * @brief This function is designed to verify that the all parameteters in the parameters under testing have a matching parameter prescribed by the rDefaultParameters.
```

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the all parameteters in the parameters under testing have a matching parameter prescribed by the rDefaultParameters. (const version)
```suggestion
     * @brief This function is designed to verify that the all parameteters in the parameters under testing have a matching parameter prescribed by the rDefaultParameters.
```

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the parameters under testing match the form prescribed by the defaults. (const version)
```suggestion
     * @brief This function is designed to verify that the parameters under testing match the form prescribed by the defaults.
```

2019-01-21 10:58 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +     * @brief This function is designed to verify that the parameters under testing contain at least all parameters prescribed by the rDefaultParameters. (const version)
```suggestion
     * @brief This function is designed to verify that the parameters under testing contain at least all parameters prescribed by the rDefaultParameters.
```

2019-02-01 14:14 UTC, philbucher requested changes
why no tests for `RecursivelyValidateDefaults`?

2019-02-01 14:14 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +    void ValidateDefaults(const Parameters& rDefaultParameters);
this should be a const function

2019-02-01 14:14 UTC, philbucher commented on kratos/includes/kratos_parameters.h
> +    void RecursivelyValidateDefaults(const Parameters& rDefaultParameters);
same

2019-02-01 14:17 UTC, philbucher commented
other than that it looks good to me, thanks for refactoring, I think this will be really useful

2019-02-04 09:38 UTC, armingeiser commented
fixed it

2019-02-20 12:18 UTC, pooyan-dadvand commented
Is this backward compatible?

2019-02-20 17:05 UTC, armingeiser commented
Yes, the old function that does both, validating and assigning defaults at the same time, is still there. Only internally the function has been split up and now the two parts can also be called individually.

2019-02-21 08:24 UTC, dbaumgaertner commented
Just to add that this is a very welcome change, as we were struggling with this missing flexibility quite some times. Thanks @armingeiser for the effort!

2019-03-01 09:44 UTC, roigcarlo commented
For the record, this is tightly related related with #2241. Linking for future references.

2019-03-01 20:53 UTC, RiccardoRossi commented
the assigndefaults is actually equivalent to merging the defaultparams into the settings no?

if so i agree this is a very welcome contribution

2019-03-01 22:44 UTC, philbucher submitted a review, later dismissed
removing my blocker
please wait until @KratosMultiphysics/technical-committee approves

2019-03-02 15:58 UTC, armingeiser commented
@RiccardoRossi Yes, AssignDefaults merges the missing settings into the parameters object.

2019-03-07 10:45 UTC, pooyan-dadvand commented
@KratosMultiphysics/technical-committee agrees with the intention of this PR and see it necessary. However would like to clarify more the name of `AssignDefaults` with something like `AddMissingParameters`. Any suggestion?

2019-03-08 23:14 UTC, armingeiser commented
I think ’AddMissingParameters’ is already quite descriptive. It is better than ’MergeParameters’, because the function does not overwrite already existing settings (if i think about merging in context of e.g. Git, thats what i would expect from a merge function).

2019-03-14 08:13 UTC, armingeiser commented
I renamed the function `AssignDefaults` to `AddMissingParameters`. It is ready for a final review from my point of view.

2019-03-28 10:26 UTC, philbucher commented
ping, I believe this is being accepted and blocks many developments / would make many developments easier :)

2019-04-01 11:13 UTC, ddiezrod commented
Is this ready to be merged? It would help us a lot

2019-04-01 16:17 UTC, armingeiser commented
@ddiezrod the implementation is ready, just someone from @KratosMultiphysics/technical-committee has to approve it.

2019-04-01 18:12 UTC, RiccardoRossi approved these changes
i think it is ok now!

thx!

2019-04-02 07:16 UTC, merged