Style-Guide conforming names for Linear-Solvers
KratosMultiphysics/Kratos pull request #3966
Opened 2019-01-25 19:33 UTC by philbucher

With this PR I am updating the names of the linear-solvers in json 
e.g. `"solver_type" : "SuperLUSolver"` => `"solver_type" : "super_lu"`

Previously it was not consistent with the style-guide, now I unified everything

Also now it is consistent btw mpi and non-mpi

The tests are updated and running

Backwards-compatibility is ensured, by replacing the old names with the new names (and giving a deprecation-warning)

I am quite happy that I could finally unify this! This is a part of Kratos that I have been struggling with since the beginning: I never new what names the linear-solvers had.
Now this is quite intuitive and consistent with the rest of the code :D

2019-01-25 19:38 UTC, loumalouomega requested changes
I am not happy with breaking retrocompatibility, wait for @KratosMultiphysics/technical-committee

2019-01-25 19:38 UTC, loumalouomega commented on applications/EigenSolversApplication/custom_python/add_custom_solvers_to_python.cpp
> +    KRATOS_REGISTER_LINEAR_SOLVER("sparse_lu", SparseLUFactory);
Are you sure you want to remove retrocompatibility?

2019-01-25 20:00 UTC, philbucher commented
I am not breaking retrocompatibility, read my message :)
> Backwards-compatibility is ensured, by replacing the old names with the new names (and giving a deprecation-warning)

2019-01-25 20:06 UTC, loumalouomega approved these changes
Oki

2019-01-25 20:08 UTC, philbucher commented
Still this should be reviewed and approved by the committee

2019-01-26 00:14 UTC, loumalouomega approved these changes

2019-01-26 00:15 UTC, loumalouomega commented
> Still this should be reviewed and approved by the committee

As you wish

2019-01-28 14:44 UTC, pooyan-dadvand commented
As it changes the input (even with backward compatibility) I would suggest to be reviewed by the @KratosMultiphysics/interface-committee

2019-01-28 17:20 UTC, dbaumgaertner commented
This indeed is a long necessary unification. Given that backward compatibility is ensured I would give it a go from @KratosMultiphysics/interface-committee side.

2019-01-30 08:18 UTC, philbucher commented
If none objects then I would go ahead with merging, since then @rubenzorrilla and I can finish the cleanup/updates of the linear-solvers in the interface

2019-01-30 11:47 UTC, pooyan-dadvand commented
@dbaumgaertner is this your opinion as a member of @KratosMultiphysics/interface-committee or is a consensus of all members?

2019-01-30 13:41 UTC, dbaumgaertner commented
@pooyan-dadvand I am currently waiting for the response of the others and will let you know.

2019-02-04 07:37 UTC, dbaumgaertner commented
Approving with consensus from @KratosMultiphysics/interface-committee

2019-02-04 10:56 UTC, jcotela approved these changes
The @KratosMultiphysics/technical-committee approves too. :+1:

2019-02-04 11:00 UTC, philbucher commented
@jginternational @rubenzorrilla I will make a PR in the Interface to update the names

2019-02-04 11:00 UTC, merged