Add discrete damping to the NodalConcentratedElement
KratosMultiphysics/Kratos pull request #424
Opened 2017-05-23 10:55 UTC by qaumann

Adding the possibility to define a nodal damping coefficient, which is used in the NodalConcentratedDampedElement2D1N and NodalConcentratedDampedElement3D1N. A test is provided.

2017-05-23 11:03 UTC, loumalouomega requested changes
I would consider the argument of using the Raleigh damping as false by default (adding "= false"  to the constructor)

2017-05-23 11:28 UTC, qaumann commented
Thanks for your comment, I changed that.

2017-05-23 13:22 UTC, loumalouomega approved these changes
Thanks, I will approve, everything looks in order

2017-05-23 13:22 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/custom_elements/nodal_concentrated_element.cpp
> +NodalConcentratedElement::NodalConcentratedElement( IndexType NewId, GeometryType::Pointer pGeometry, bool UseRayleighDamping )
Add = false as default argument (opinion)

2017-05-23 13:30 UTC, RiccardoRossi commented on applications/StructuralMechanicsApplication/tests/SmallTests.py
> +class DynamicNodalDampingTests(StructuralMechanichsTestFactory):
hi Quirin,

this is a suggestion, not a request, however iif you have a very small test, it would be much easier to debug if you do it really minimal, like what is done here (in a different context):

https://github.com/KratosMultiphysics/Kratos/blob/feature-porting-elements/applications/StructuralMechanicsApplication/tests/test_patch_test_large_strain.py

the reasoning behind my suggestion is that if it is in a single file and with only the features you need, it would be much easier to debug it in case something goes wrong

2017-05-23 13:34 UTC, qaumann commented on applications/StructuralMechanicsApplication/custom_elements/nodal_concentrated_element.cpp
> +NodalConcentratedElement::NodalConcentratedElement( IndexType NewId, GeometryType::Pointer pGeometry, bool UseRayleighDamping )
Oh, I got you wrong. I just changed it in the header file (like for the ShellThinElement / ShellThinCorotationalElement). Thanks for pointing that out, I will change it.

2017-05-23 13:36 UTC, qaumann commented on applications/StructuralMechanicsApplication/tests/SmallTests.py
> +class DynamicNodalDampingTests(StructuralMechanichsTestFactory):
Hi Riccardo,
thanks for the link, I will rewrite my test according to the patch test.

2017-05-26 11:25 UTC, qaumann commented
Hi @RiccardoRossi,
I changed the test according to the structure you provided. Is this what you intended? If so, I will merge the changes into the master.

2017-05-26 11:32 UTC, RiccardoRossi commented
yes, it is what i suggested. I think it will pay off!!

2017-05-26 15:01 UTC, merged