Hydrostatic pressure implementations
KratosMultiphysics/Kratos pull request #4295
Opened 2019-02-28 17:19 UTC by salvalatorre

2019-03-01 15:10 UTC, maceligueta commented on applications/DEMApplication/custom_constitutive/DEM_KDEM_Mohr_Coulomb_CL.cpp
> +                *element1->mBrokenSphere = *element2->mBrokenSphere = 1.0;
Breaks parallelism. You shouldn't write into two elements.

2019-03-01 15:12 UTC, maceligueta requested changes
This PR could be based on utilities. Instead, deep parts of the DEM application were modified. Let's discuss this in a meeting to see if we can improve it.

2019-10-22 09:10 UTC, philbucher commented
is this still active?

2019-10-22 13:23 UTC, salvalatorre commented
I don't think so... There are one or two interesting features that we will try to recover even after deleting this branch should we need them...
Thanks!

2019-10-22 13:24 UTC, closed without merging