[SDEM-PFEM] Updating DEM-PFEM coupling to new Swimming DEM standard
KratosMultiphysics/Kratos pull request #4381
Opened 2019-03-07 18:17 UTC by ipouplana

2019-03-07 18:37 UTC, GuillermoCasas requested changes
See comments

2019-03-07 18:37 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/swimming_DEM_analysis.py
> +        Add("material_acceleration_calculation_type").SetInt(8)
Modify your own analysis

2019-03-07 18:37 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/tests/NightTests.py
> +          Test
Use similar nomenclature

2019-03-07 18:37 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/DEM_coupled_pfem_fluid_dynamics_analysis.py
> +    def __init__(self, model, parameters=None, pp=None):
Here you should be passing the whole project_parameters and only pass to the parent the project_parameters["fluid_parameters"] bit. See [https://github.com/KratosMultiphysics/Kratos/blob/SDEM/debugging-and-cleaning-analysis/applications/SwimmingDEMApplication/python_scripts/DEM_coupled_fluid_dynamics_analysis.py](url).

2019-03-07 19:32 UTC, jgonzalezusua submitted a review, later dismissed

2019-03-07 21:46 UTC, philbucher commented on applications/PfemFluidDynamicsApplication/python_scripts/pfem_fluid_dynamics_analysis.py
> +from analysis_stage import AnalysisStage
it is more future-proof to do the following:
```suggestion
from KratosMultiphysics.analysis_stage import AnalysisStage
```

2019-03-07 21:54 UTC, GuillermoCasas submitted a review, later dismissed
I am approving, but please wait for my next pull request to apply more changes to the application

2019-03-08 16:16 UTC, jgonzalezusua submitted a review, later dismissed

2019-03-08 16:42 UTC, jgonzalezusua submitted a review, later dismissed

2019-03-08 18:50 UTC, GuillermoCasas approved these changes

2019-03-08 18:50 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/swimming_DEM_PFEM_analysis.py
> +        #self.vars_man.Dt = self.project_parameters['fluid_parameters']["problem_data"]["time_step"]
Please remove comments

2019-03-08 18:50 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/swimming_DEM_procedures.py
> +        SetModelPartSolutionStepValue(balls_model_part, BASSET_FORCE, Vector([0.]*3))
This should not be needed... Why is it not initially 0? Could you investigate this?

2019-03-08 18:50 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/variables_management.py
> +        if True or parameters["basset_force_type"].GetInt() > 0 and parameters["add_each_hydro_force_option"].GetBool():
For the moment just remove the 'if' and add it always please

2019-03-08 18:50 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/variables_management.py
> +
remove space

2019-03-08 20:59 UTC, merged