Temporaly disabling TotalLagrangian2D3_TransientSensitivity
KratosMultiphysics/Kratos pull request #4450
Opened 2019-03-15 10:17 UTC by roigcarlo

I have to disable this at least until we are in the release process, since otherwise people can no merge hotfixes. I will re-activate later.

There is another slow test in python that I may also have to temporally disable.

The idea is to merge it here and then in the release branch to keep the branches in synch. There seems to be no problem in the master.

2019-03-15 10:22 UTC, philbucher requested changes
why cannot you only merge this into the release-branch? The two branches are anyway already drifted apart and we will not need to merge those branches any more

I don't really agree abt disbaling working tests ...
I put a lot of effort in keeping the tests running (on master) to avoid breaking things

@loumalouomega @RiccardoRossi you did major modifications to the ResidualCriterion and the B&S in the meantime, did you check the differences btw the release and the master-branch which most probably causes these tests to fail?

ping @msandre , he wrote the tests

2019-03-15 10:30 UTC, roigcarlo commented
@philbucher I am not sure they diverged or if there are changes in the master and not in the release that may be causing the issue, hance I prefer to keep things coherent with the master if possible. I would go trough the changes myself but I am afraid I cannot easily identify which changes are relevant to this issue :S. If you can identify the problem would me much better but please be quick, as the release process takes some time and there are still fixes that need to be merged and tested into the branch,

2019-03-15 10:34 UTC, philbucher commented
I also don't know, that's why I keep pinging (**PING** @loumalouomega @RiccardoRossi )

I can approve if this is the better solution, but when would this test be reenabled?

2019-03-15 11:26 UTC, roigcarlo commented
I will re-enable once the final release is compiled (or there are no more incoming fixes).

2019-03-15 11:32 UTC, philbucher commented
ok, sorry for the noise then

2019-03-15 11:32 UTC, philbucher approved these changes

2019-03-15 12:00 UTC, roigcarlo commented
:+1: Thx. Still I need to disable another test. but not sure which one it is yet. Once I identify it I will commit here.

2019-03-27 08:12 UTC, philbucher commented
do we still need this PR?

2019-03-27 12:56 UTC, roigcarlo commented
Nono, outdated.

2019-03-27 12:56 UTC, closed without merging