Correcting a bug with large numbers and improving some macros
KratosMultiphysics/Kratos pull request #457
Opened 2017-06-01 09:58 UTC by GuillermoCasas

There was a bug by which very large number of particles were not processed correctly due to the limited range on ints. I also made the macros safer and  optimized some of them a bit.

2017-06-01 11:14 UTC, maceligueta commented on applications/DEM_application/custom_utilities/inlet.cpp
> +            assert(mp[INLET_NUMBER_OF_PARTICLES] >= 0);
Are you sure you want to use assert? It is not used anywhere in Kratos

2017-06-02 15:01 UTC, GuillermoCasas commented on applications/DEM_application/custom_utilities/inlet.cpp
> +            assert(mp[INLET_NUMBER_OF_PARTICLES] >= 0);
Ok, I replaced it for something better.

2017-06-02 15:08 UTC, maceligueta commented on applications/DEM_application/custom_utilities/inlet.cpp
> +            KRATOS_THROW_ERROR(std::runtime_error, "The value of the Model Part variable INLET_NUMBER_OF_PARTICLES is not a positive int: ", num_part_surface_time);
I have seen in other PRs that the recommended sintax here is KRATOS_ERROR<<"String" ...
KRATOS_THROW_ERROR is the old style, we have to change some of them.

2017-06-03 14:48 UTC, maceligueta requested changes
Some undesired files were uploaded in the last commit!
TimesPartialRelease, console_output, ...

2017-06-05 15:56 UTC, maceligueta approved these changes

2017-06-05 17:32 UTC, merged

2017-06-05 19:35 UTC, maceligueta commented
Should we delete this branch?

2017-06-06 08:02 UTC, GuillermoCasas commented
No, since I am still working on it.