Cps/implement moment coefficient
KratosMultiphysics/Kratos pull request #4613
Opened 2019-04-08 16:51 UTC by LHoeffner

New Python process computes moment acting on airfoil for potential flow solutions. Unit test has been added and (simple) example validated against Xfoil result.

2019-04-08 17:00 UTC, rubenzorrilla requested changes

2019-04-08 17:00 UTC, rubenzorrilla commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +import numpy as np
Use Kratos array types. `numpy` doesn't come as a default package of Python so it is possible that some users lack it.

2019-04-08 17:00 UTC, rubenzorrilla commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +        self.reference_point = np.array([0.0,0.0,0.0])
```suggestion
        self.reference_point = KratosMultiphysics.Vector(3)
```

2019-04-08 17:00 UTC, rubenzorrilla commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +        print('COMPUTE MOMENT')
Use the Kratos Logger for information output.

2019-04-08 17:00 UTC, rubenzorrilla commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +            n =  np.array(cond.GetValue(KratosMultiphysics.NORMAL)) #Inigo: normal direction? (ass. outward of domain)
Same `numpy` comment. And please remove comments that are not informative.

2019-04-08 17:00 UTC, rubenzorrilla commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +        print('moment = ', m[2])
Output using Kratos logger.

2019-04-08 17:20 UTC, philbucher commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +    if( not isinstance(settings,KratosMultiphysics.Parameters) ):
```suggestion
    if not isinstance(settings,KratosMultiphysics.Parameters):
```

2019-04-08 17:20 UTC, philbucher commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +        self.velocity_infinity[2] = settings["velocity_infinity"][2].GetDouble()
```suggestion
        self.velocity_infinity = settings["velocity_infinity"].GetVector()
```

2019-04-08 17:20 UTC, philbucher commented on applications/CompressiblePotentialFlowApplication/python_scripts/compute_moment_process.py
> +        self.reference_point[2] = settings["reference_point"][2].GetDouble()
same

2019-04-09 15:45 UTC, rubenzorrilla approved these changes
Congratulations on your first PR!

2019-04-10 06:51 UTC, merged