Pfem fluid make script object
KratosMultiphysics/Kratos pull request #469
Opened 2017-06-07 10:37 UTC by maceligueta

The file KratosPfemFluid.py file is recovered. Contains the same operations as the main script that is being used now, but it is now an object called Solution (a class). This object can be called from outside, by a coupling algorithm, and it can be derived to modify its behaviour according to the needs of the coupling algorithm.

2017-06-07 18:33 UTC, josep-m-carbonell commented
@maceligueta, I could not test it today, tomorrow I will try it. It seems ok. I pre approve it because it do not have conflicts with anything and it looks ok. Thank you MA.

2017-06-07 18:33 UTC, josep-m-carbonell approved these changes

2017-06-08 16:58 UTC, josep-m-carbonell requested changes

2017-06-08 16:58 UTC, josep-m-carbonell commented on applications/PfemFluidDynamicsApplication/python_scripts/KratosPfemFluid.py
> +        self.SetGraphicalOutput()
It raises an errror, self.computing_model_part is needed and it is created in the Initilialize...the position of this call must be after it.

2017-06-08 18:30 UTC, maceligueta commented on applications/PfemFluidDynamicsApplication/python_scripts/KratosPfemFluid.py
> +        self.SetGraphicalOutput()
Yes, I had it corrected in another branch. I just committed the fix. Thanks.

2017-06-08 21:35 UTC, josep-m-carbonell approved these changes

2017-06-08 21:35 UTC, josep-m-carbonell commented
Thsnk you MA 👍

2017-06-19 18:03 UTC, merged