Fixed tests in geometries
KratosMultiphysics/Kratos pull request #480
Opened 2017-06-08 16:04 UTC by roigcarlo

This fixes:

* TestTetrahedra3D4VolumeToEdgeLengthQuality
Which was failing when trying to calculate the quality function of tetrahedras with negative volume due to a negative number being elevated to a fraction power, resulting into a imaginary number that different compilers were handling... imaginatively:

Gcc -> 1
Clang -> -nan
Msvc -> -0

That was the reason that it was "working" both in win and clang but not in GCC. Even when GCC was the only not not giving nan....

* TestTetrahedra3D4VolumeToRMSEdgeLength:
This tests was calculating the wring quality metric (which happened to be the one failing). 
It has been fixed and now it calculates the correct metric.

2017-06-08 16:05 UTC, loumalouomega approved these changes
It looks fine to me

2017-06-08 16:06 UTC, roigcarlo commented
:+1: Let's wait for @pooyan-dadvand  to see it as well

2017-06-09 08:12 UTC, roigcarlo commented on kratos/geometries/tetrahedra_3d_4.h
> +      return normFactor * isInv * std::pow(3*absVol, 2.0 / 3.0) / (sa + sb + sc + sd + se + sf);
Actually I have a concern here. Is there any way to do this in a more clean way?

2017-06-09 08:53 UTC, pooyan-dadvand commented on kratos/geometries/tetrahedra_3d_4.h
> +      return normFactor * isInv * std::pow(3*absVol, 2.0 / 3.0) / (sa + sb + sc + sd + se + sf);
You are calculating twice the volume which is very costly operation

2017-06-09 08:55 UTC, pooyan-dadvand requested changes
the volume calculation is twice and this is too costy.

2017-06-09 08:55 UTC, pooyan-dadvand commented on kratos/geometries/tetrahedra_3d_4.h
> +      return normFactor * isInv * std::pow(3*absVol, 2.0 / 3.0) / (sa + sb + sc + sd + se + sf);
I would put (as we are talking with @jcotela ) `std::pow(9*vol*vol, 1.0 / 3.0) `

2017-06-09 11:03 UTC, roigcarlo commented
@pooyan-dadvand @jcotela Changes work but I am still dependent on the sign of the quality.
`std::pow(9*vol*vol, 1.0/3.0)` ends being the same as `std::pow(3*std::abs(vol), 2.0/3.0)`

2017-06-09 12:24 UTC, pooyan-dadvand commented
The sign of this should be always positive even if the volume is negative. So you should add the sign of the volume manually in order to keep the Quality result coherent with what is expected: (Quality() < 0 for inverted elements)

2017-06-09 15:01 UTC, pooyan-dadvand approved these changes

2017-06-09 15:14 UTC, merged

2017-06-09 15:14 UTC, roigcarlo commented
:+1: thx!