Moving corrected version to master branch
KratosMultiphysics/Kratos pull request #499
Opened 2017-06-14 14:24 UTC by loumalouomega

I can not find the original commit to cherrypick, I upload directly the final version

2017-06-14 14:25 UTC, loumalouomega commented
Concerning #495

2017-06-15 07:10 UTC, josep-m-carbonell commented
@loumalouomega  no files changed ...

This method has to be corrected too: @pooyan-dadvand  (see the NOTE)

    /** adds a Dof to the node and return new added dof or existed one. */
    inline typename DofType::Pointer pAddDof(DofType const& SourceDof)
    {
        KRATOS_TRY_LEVEL_3

        typename DofsContainerType::iterator i_dof = mDofs.find(SourceDof.GetVariable());

	//NOTE: here returns the same Dof if exists, but if the SourceDof has a reaction and the
	//found dof does not has it, then the reaction is not set!!!
        if(i_dof != mDofs.end())
            return *(i_dof.base());

        typename DofType::Pointer p_new_dof =  boost::make_shared<DofType>(SourceDof);
        mDofs.insert(mDofs.begin(), p_new_dof);

        p_new_dof->SetId(Id());

        p_new_dof->SetSolutionStepsData(&mSolutionStepsNodalData);

        mDofs.Sort();

        return p_new_dof;

        KRATOS_CATCH_LEVEL_3(*this);

    }

2017-06-15 09:21 UTC, loumalouomega commented
@josep-m-carbonell This is probably an error, I uploaded from the phone and the information was partial, I will check it now.

2017-06-15 09:25 UTC, loumalouomega commented
@josep-m-carbonell Indeed, the file changed was the node.h, not the model_part.h. Uploading. Sorry for the inconvenience

2017-06-15 14:27 UTC, RiccardoRossi requested changes
what is the reason of those changes? 
i would avoid cosmetic changes in the base class in the even they introduce errors. (in this specific case i think there is one with a KRATOS_ERROR which can not compile.

2017-06-15 14:27 UTC, RiccardoRossi commented on kratos/includes/node.h
> +    	    KRATOS_ERROR <<  "Solution step index out of range.", *this);
this can not compile...

2017-06-15 14:38 UTC, loumalouomega commented
@RiccardoRossi The KRATOS_ERROR you referred it was in a commented piece of code, so it didn't affected the compilation.

2017-06-15 16:14 UTC, RiccardoRossi commented
@josep-m-carbonell 

what you say is correct, the code should look something like

        if(i_dof != mDofs.end())
        {
             if(i_dof->GetReaction() != SourceDof.GetReaction())
                  i_dof->SetReaction(SourceDof.GetReaction());
            return *(i_dof.base());
       }

however such code does not compile (better said, it does not link).

@pooyan-dadvand what would be the correct way of doing this?

2017-06-16 14:27 UTC, loumalouomega reviewed
I corrected the i_dof with itDoF

2017-06-16 14:27 UTC, loumalouomega commented on kratos/includes/node.h
> +        if(i_dof != mDofs.end())
@RiccardoRossi It is called itDoF not i_dof

2017-06-16 14:36 UTC, RiccardoRossi commented
@loumalouomega, thank you

2017-06-17 07:11 UTC, RiccardoRossi approved these changes

2017-06-17 07:11 UTC, merged

2017-06-19 09:50 UTC, pooyan-dadvand commented on kratos/includes/node.h
> +        Node<3>::Pointer pNewNode = boost::make_shared<Node<3> >( this->Id(), (*this)[0], (*this)[1], (*this)[2]);
local variables are lower case with underline: `p_new_node`

2017-06-19 09:57 UTC, loumalouomega commented on kratos/includes/node.h
> +        Node<3>::Pointer pNewNode = boost::make_shared<Node<3> >( this->Id(), (*this)[0], (*this)[1], (*this)[2]);
OK

2017-06-19 13:00 UTC, loumalouomega commented on kratos/includes/node.h
> +        Node<3>::Pointer pNewNode = boost::make_shared<Node<3> >( this->Id(), (*this)[0], (*this)[1], (*this)[2]);
Do I reopen this?

2017-06-20 07:56 UTC, RiccardoRossi commented on kratos/includes/node.h
> +        Node<3>::Pointer pNewNode = boost::make_shared<Node<3> >( this->Id(), (*this)[0], (*this)[1], (*this)[2]);
i would not touch this again...

2017-06-20 09:04 UTC, loumalouomega commented on kratos/includes/node.h
> +        Node<3>::Pointer pNewNode = boost::make_shared<Node<3> >( this->Id(), (*this)[0], (*this)[1], (*this)[2]);
I am trying to do things right...