[Core] Read Materials - checking if variables and tables exist
KratosMultiphysics/Kratos pull request #5049
Opened 2019-06-06 15:09 UTC by ddiezrod

This is a small proposal: allow to have a json input file where variables and tables are not defined for a specific material. I throw a warning if that is the case.

I know we could just have an empty array in the json file but we would lose retro-compatibility in @KratosMultiphysics/altair side and I think the change is reasonable..

2019-06-06 15:18 UTC, philbucher commented
Ok from my side 👍

2019-06-06 15:41 UTC, loumalouomega commented
I would like if we can merge #2919 first, these conflicts are sending me to the nut house

2019-06-06 16:18 UTC, loumalouomega requested changes
Somme comments, missing test

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                array_1d<double, 3> temp(3, 0.0);
```suggestion
                array_1d<double, 3> temp = ZeroVector(3);
```

This constructor is not available on Amatrix

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<double>& variable = KratosComponents<Variable<double>>().Get(variable_name);
```suggestion
                const Variable<double>& r_variable = KratosComponents<Variable<double>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, value.GetDouble());
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, value.GetDouble());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, value.GetDouble());
```suggestion
                p_prop->SetValue(r_variable, value.GetDouble());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<bool>& variable = KratosComponents<Variable<bool>>().Get(variable_name);
```suggestion
                const Variable<bool>& r_variable = KratosComponents<Variable<bool>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, value.GetBool());
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, value.GetBool());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, value.GetBool());
```suggestion
                p_prop->SetValue(r_variable, value.GetBool());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<array_1d<double, 3>>& variable = KratosComponents<Variable<array_1d<double, 3>>>().Get(variable_name);
```suggestion
                const Variable<array_1d<double, 3>>& r_variable = KratosComponents<Variable<array_1d<double, 3>>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Vector& value_variable = value.GetVector();
```suggestion
                const Vector& r_value_variable = value.GetVector();
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                KRATOS_ERROR_IF(value_variable.size() != 3) << "The vector of variable " << variable_name << " has size " << value_variable.size() << " and it is supposed to be 3" << std::endl;
```suggestion
                KRATOS_ERROR_IF(r_value_variable.size() != 3) << "The vector of variable " << variable_name << " has size " << r_value_variable.size() << " and it is supposed to be 3" << std::endl;
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                    temp[index] = value_variable[index];
```suggestion
                    temp[index] = r_value_variable[index];
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, temp);
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, temp);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, temp);
```suggestion
                p_prop->SetValue(r_variable, temp);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<array_1d<double, 6>>& variable = KratosComponents<Variable<array_1d<double, 6>>>().Get(variable_name);
```suggestion
                const Variable<array_1d<double, 6>>& r_variable = KratosComponents<Variable<array_1d<double, 6>>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Vector& value_variable = value.GetVector();
```suggestion
                const Vector& r_value_variable = value.GetVector();
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                KRATOS_ERROR_IF(value_variable.size() != 6) << "The vector of variable " << variable_name << " has size " << value_variable.size() << " and it is supposed to be 6" << std::endl;
```suggestion
                KRATOS_ERROR_IF(r_value_variable.size() != 6) << "The vector of variable " << variable_name << " has size " << r_value_variable.size() << " and it is supposed to be 6" << std::endl;
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                    temp[index] = value_variable[index];
```suggestion
                    temp[index] = r_value_variable[index];
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, temp);
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, temp);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, temp);
```suggestion
                p_prop->SetValue(r_variable, temp);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<Vector>& variable = KratosComponents<Variable<Vector>>().Get(variable_name);
```suggestion
                const Variable<Vector>& r_variable = KratosComponents<Variable<Vector>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, value.GetVector());
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, value.GetVector());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, value.GetVector());
```suggestion
                p_prop->SetValue(r_variable, value.GetVector());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<Matrix>& variable = KratosComponents<Variable<Matrix>>().Get(variable_name);
```suggestion
                const Variable<Matrix>& r_variable = KratosComponents<Variable<Matrix>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, value.GetMatrix());
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, value.GetMatrix());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, value.GetMatrix());
```suggestion
                p_prop->SetValue(r_variable, value.GetMatrix());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                const Variable<std::string>& variable = KratosComponents<Variable<std::string>>().Get(variable_name);
```suggestion
                const Variable<std::string>& r_variable = KratosComponents<Variable<std::string>>().Get(variable_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                CheckIfOverwritingValue(*p_prop, variable, value.GetString());
```suggestion
                CheckIfOverwritingValue(*p_prop, r_variable, value.GetString());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +                p_prop->SetValue(variable, value.GetString());
```suggestion
                p_prop->SetValue(r_variable, value.GetString());
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +            const auto input_var = KratosComponents<Variable<double>>().Get(input_var_name);
```suggestion
            const auto& r_input_var = KratosComponents<Variable<double>>().Get(input_var_name);
```
Missing & !!!!!

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +            const auto output_var = KratosComponents<Variable<double>>().Get(output_var_name);
```suggestion
            const auto& r_output_var = KratosComponents<Variable<double>>().Get(output_var_name);
```

2019-06-06 16:18 UTC, loumalouomega commented on kratos/utilities/read_materials_utility.cpp
> +            p_prop->SetTable(input_var, output_var, table);
```suggestion
            p_prop->SetTable(r_input_var, r_output_var, table);
```

2019-06-06 17:00 UTC, loumalouomega submitted a review, later dismissed
:)

2019-06-06 17:01 UTC, loumalouomega commented
I will fix #2919 and depending PR later, go on

2019-06-06 17:10 UTC, ddiezrod commented
Thanks @loumalouomega ! I missed a couple of &'s so I will need you to reapprove

2019-06-06 17:10 UTC, loumalouomega approved these changes
:)))))))))))))))))))))))))))

2019-06-06 17:15 UTC, loumalouomega commented
> Thanks @loumalouomega ! I missed a couple of &'s so I will need you to reapprove

![imagen](https://user-images.githubusercontent.com/19991680/59052398-52101f80-888f-11e9-90d4-f22144727f54.png)
 I love this meme :3

2019-06-06 18:29 UTC, philbucher commented
> > Thanks @loumalouomega ! I missed a couple of &'s so I will need you to reapprove
> 
> ![imagen](https://user-images.githubusercontent.com/19991680/59052398-52101f80-888f-11e9-90d4-f22144727f54.png)
> I love this meme :3

Omg it’s amazing in this context 👍🏻

2019-06-07 06:15 UTC, ddiezrod commented
@loumalouomega Ok, I have to admit it, this is a good one hahaha

2019-06-07 06:15 UTC, merged