[FEMDEM] Some minor improvements
KratosMultiphysics/Kratos pull request #5102
Opened 2019-06-18 15:25 UTC by AlejandroCornejo

that's it

2019-06-18 15:32 UTC, loumalouomega requested changes
Minor comments

2019-06-18 15:32 UTC, loumalouomega commented on applications/FemToDemApplication/custom_elements/generic_small_strain_femdem_element.cpp
> +	if (this->GetValue(RECOMPUTE_NEIGHBOURS) > 0) {
Is this an integer or boolean?

2019-06-18 15:32 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application_variables.cpp
> +	KRATOS_CREATE_VARIABLE(bool, RECOMPUTE_NEIGHBOURS)
AHA!!

2019-06-18 15:32 UTC, loumalouomega commented on applications/FemToDemApplication/custom_elements/generic_small_strain_femdem_element.cpp
> +	if (this->GetValue(RECOMPUTE_NEIGHBOURS) > 0) {
Check is true and set False

2019-06-18 15:32 UTC, loumalouomega commented on applications/FemToDemApplication/custom_elements/generic_small_strain_femdem_element.cpp
> +	if (this->GetValue(RECOMPUTE_NEIGHBOURS) > 0) {
```suggestion
	if (this->GetValue(RECOMPUTE_NEIGHBOURS)) {
```

2019-06-18 15:32 UTC, loumalouomega commented on applications/FemToDemApplication/custom_elements/generic_small_strain_femdem_element.cpp
> +		this->SetValue(RECOMPUTE_NEIGHBOURS, 0);
```suggestion
		this->SetValue(RECOMPUTE_NEIGHBOURS, false);		
```

2019-06-20 16:56 UTC, AlejandroCornejo commented
changes done @loumalouomega

2019-06-21 07:23 UTC, loumalouomega approved these changes
👌

2019-06-21 07:33 UTC, merged