Utility for computing normal and tangential forces at given plane
KratosMultiphysics/Kratos pull request #531
Opened 2017-06-22 17:46 UTC by lorenzogracia

New utility for computing normal and tangential forces in the joint element at a given plane.  Also the headers have been updated.

2017-06-22 18:01 UTC, ipouplana requested changes
Hi @lorenzogracia this is a useful utility, but I think it would be better if we could pass the necessary parameters from Python without them being 'hardcoded'...

2017-06-23 09:59 UTC, ipouplana approved these changes

2017-06-23 10:24 UTC, rubenzorrilla commented on applications/DamApplication/custom_utilities/global_joint_stress_utility.hpp
> +        double mpmid0_0;
"mpmid0_0" stands for "member pointer mid0_0" but it is a double (in any case, mid0_0 is not very descriptive...). Besides, might it be possible to store it as a const array type or at least as an const double?.

2017-06-23 10:24 UTC, rubenzorrilla commented on applications/DamApplication/custom_utilities/global_joint_stress_utility.hpp
> +            Element::GeometryType& Geom = it->GetGeometry();
This is a reference. Call it "rGeom"

2017-06-23 10:24 UTC, rubenzorrilla commented on applications/DamApplication/custom_utilities/global_joint_stress_utility.hpp
> +        double TangentialForce = sqrt(VectorForceinPlane[0]*VectorForceinPlane[0] + VectorForceinPlane[1]*VectorForceinPlane[1]);
This cant be "const"

2017-06-23 14:33 UTC, lorenzogracia commented
@rubenzorrilla  thanks for your comments.

2017-06-23 16:02 UTC, merged