[FEMDEM] Updating App after summer
KratosMultiphysics/Kratos pull request #5417
Opened 2019-08-21 09:58 UTC by AlejandroCornejo

Several minor changes to adapt the changes done in summer.
PD: One change in Solid must be merged before merging this PR

2019-08-21 10:07 UTC, AlejandroCornejo commented
Waiting for https://github.com/KratosMultiphysics/Kratos/pull/5418 to be merged

2019-08-21 10:54 UTC, loumalouomega requested changes
Processes should be created with the process factory of the core

2019-08-21 10:54 UTC, loumalouomega commented on applications/FemToDemApplication/python_scripts/MainFemDem.py
> +		return (KratosMultiphysics.SolidMechanicsApplication.process_handler.ProcessHandler(self.Model, process_parameters))
Why you don't use the process factory from the core?

2019-08-21 10:54 UTC, loumalouomega commented on applications/SolidMechanicsApplication/python_scripts/process_handler.py
> +        python_module = import_module(process["kratos_module"].GetString() + "." + process["python_module"].GetString())
This should use the process factory from the core... I cannot approve this anyway, I am not involved in the Solid app

2019-08-22 09:11 UTC, loumalouomega commented
Merge this with the master and I approve

2019-08-22 09:11 UTC, AlejandroCornejo commented
the other PR has been merged @loumalouomega

2019-08-22 09:12 UTC, loumalouomega approved these changes

2019-08-22 10:10 UTC, merged