[Dem/structures] Python updated to current standard
KratosMultiphysics/Kratos pull request #5560
Opened 2019-09-10 17:35 UTC by ipouplana

Summary:

- Python import warning addressed
- Python files updated to work with new DEM analysis stage
- Cleanup of python main algorithm
- 2 small SP examples uploaded

2019-09-10 17:54 UTC, philbucher requested changes
can you please reduce the size of the files you are adding?
If this is not possible then please move those cases to the examples repo

2019-09-10 17:54 UTC, philbucher commented on applications/DemStructuresCouplingApplication/python_scripts/sp_dem_fem_coupling_algorithm.py
> +sys.path.insert(0, '')
```suggestion
```

2019-09-10 18:13 UTC, ipouplana commented
Done @philbucher , I just moved the test examples to the Examples repo (PR #52)

2019-09-10 18:16 UTC, philbucher commented
thanks!

I will approve once you have approval from someone that has knowledge about this app

2019-09-12 08:18 UTC, maceligueta approved these changes

2019-09-12 08:19 UTC, maceligueta commented
Great @ipouplana . Thanks for adapting/cleaning these files

2019-09-12 08:21 UTC, philbucher approved these changes

2019-09-12 08:22 UTC, merged