Femdem/minor changes pfemdem
KratosMultiphysics/Kratos pull request #5916
Opened 2019-11-11 17:35 UTC by AlejandroCornejo

In this PR I'm correcting some thing regarding the pfem-femdem coupling. I'm also adding the NeoHookean cl from structural (will be removed when the porting to the SMA will be done). A minor change in the DEM App `dem_fem_coupling_algorithm.py` (@maceligueta )

2019-11-11 18:25 UTC, loumalouomega requested changes
Many things to be removed, mainly the unnecessary duplicated backup when you have to your disposal the buffer

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_acceleration = it_node->FastGetSolutionStepValue(ACCELERATION, 0);
```suggestion
                const auto& current_acceleration = it_node->FastGetSolutionStepValue(ACCELERATION, 0);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto prev_acceleration    = it_node->FastGetSolutionStepValue(ACCELERATION, 1);
```suggestion
                const auto& prev_acceleration    = it_node->FastGetSolutionStepValue(ACCELERATION, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_displ = it_node->FastGetSolutionStepValue(DISPLACEMENT, 0);
```suggestion
                const auto& current_displ = it_node->FastGetSolutionStepValue(DISPLACEMENT, 0);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto prev_displ    = it_node->FastGetSolutionStepValue(DISPLACEMENT, 1);
```suggestion
                const auto& prev_displ    = it_node->FastGetSolutionStepValue(DISPLACEMENT, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_current_accel_backup = current_acceleration;
```suggestion
                noalias(r_current_accel_backup) = current_acceleration;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_prev_accel_backup    = prev_acceleration;
```suggestion
                noalias(r_prev_accel_backup)  = prev_acceleration;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_current_displ_backup = current_displ;
```suggestion
                noalias(r_current_displ_backup) = current_displ;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_prev_displ_backup    = prev_displ;
```suggestion
                noalias(r_prev_displ_backup) = prev_displ;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP);
```suggestion
                const auto& current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP);
```suggestion
                const auto& current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_current_acceleration = current_accel_backup;
```suggestion
                noalias(r_current_acceleration) = current_accel_backup;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_current_acceleration = current_accel_backup;
```suggestion
                noalias(r_current_acceleration) = current_accel_backup;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_prev_acceleration = prev_accel_backup;
```suggestion
                noalias(r_prev_acceleration) = prev_accel_backup;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_displ_backup = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP);
This backups take a lot of memory, and why do you need to have to variables for backup?, all historical variables have buffer, you can acces from previous positions

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_python/fem_to_dem_python_application.cpp
> +    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(m,DISPLACEMENT_PREVIOUS_BACKUP);
Remove this please and use the buffer from DISPLACEMENT_BACKUP, idem for ACCELERATION_BACKUP

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto &r_prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_PREVIOUS_BACKUP);
```suggestion
                auto &r_prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto &r_prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_PREVIOUS_BACKUP);
```suggestion
                auto &r_prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_PREVIOUS_BACKUP);
```suggestion
                auto prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_PREVIOUS_BACKUP);
```suggestion
                conts auto& prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_current_displ = current_displ_backup;
```suggestion
                noalias(r_current_displ) = current_displ_backup;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                r_prev_displ = prev_displ_backup;
```suggestion
                noalias(r_prev_displ) = prev_displ_backup;
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto current_displ_backup = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP);
```suggestion
                const auto& current_displ_backup = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                auto &r_prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_PREVIOUS_BACKUP);
```suggestion
                auto &r_prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 1);
```

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application.cpp
> +    KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application.cpp
> +    KRATOS_REGISTER_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application_variables.cpp
> +    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application_variables.cpp
> +    KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application_variables.h
> +    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/fem_to_dem_application_variables.h
> +    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/python_scripts/MainFEM_for_PFEM_coupling.py
> +        self.main_model_part.AddNodalSolutionStepVariable(KratosFemDem.ACCELERATION_PREVIOUS_BACKUP)
Remove

2019-11-11 18:25 UTC, loumalouomega commented on applications/FemToDemApplication/python_scripts/MainFEM_for_PFEM_coupling.py
> +        self.main_model_part.AddNodalSolutionStepVariable(KratosFemDem.DISPLACEMENT_PREVIOUS_BACKUP)
Remove

2019-11-13 11:12 UTC, AlejandroCornejo commented
Dear @loumalouomega , the backups are done because of the PFEM-FEMDEM coupling. Summarizing, the pfem sets to 0 the accelerations of the boundaries (FEMDEM skin) and this is a problem for the FEMDEM solve. With the backups I can save the acc and reset them after the PFEM solves.

In my opinion has nothing to do with the bufer :)

Thank you kindly,

2019-11-13 12:58 UTC, loumalouomega commented
> 
> 
> Dear @loumalouomega , the backups are done because of the PFEM-FEMDEM coupling. Summarizing, the pfem sets to 0 the accelerations of the boundaries (FEMDEM skin) and this is a problem for the FEMDEM solve. With the backups I can save the acc and reset them after the PFEM solves.
> 
> In my opinion has nothing to do with the buffer :)
> 
> Thank you kindly,

If your buffer is size 2, and you want  to save 2 values, you are actually saving 4 values!!! If you use the second position of the buffer as I suggested you will not waste half of memory

2019-11-18 08:20 UTC, AlejandroCornejo commented
> 
> 
> > Dear @loumalouomega , the backups are done because of the PFEM-FEMDEM coupling. Summarizing, the pfem sets to 0 the accelerations of the boundaries (FEMDEM skin) and this is a problem for the FEMDEM solve. With the backups I can save the acc and reset them after the PFEM solves.
> > In my opinion has nothing to do with the buffer :)
> > Thank you kindly,
> 
> If your buffer is size 2, and you want to save 2 values, you are actually saving 4 values!!! If you use the second position of the buffer as I suggested you will not waste half of memory

so you're saying that I only have to create one new variables and use the buffer, okkey :) changing it

2019-11-18 08:23 UTC, AlejandroCornejo commented
At least I have to create a new backup because the PFEM app resets the currect acc and the previous...

2019-11-18 09:28 UTC, loumalouomega commented
> 
> 
> At least I have to create a new backup because the PFEM app resets the current acc and the previous...

Yeah, but my question is why do it in two different variables and not only one variable

2019-11-18 09:39 UTC, AlejandroCornejo commented
> 
> 
> > At least I have to create a new backup because the PFEM app resets the current acc and the previous...
> 
> Yeah, but my question is why do it in two different variables and not only one variable

because I need the current and the previous acceleration and the same with the displ... :)

2019-11-18 09:44 UTC, loumalouomega commented
> 
> 
> > > Dear @loumalouomega , the backups are done because of the PFEM-FEMDEM coupling. Summarizing, the pfem sets to 0 the accelerations of the boundaries (FEMDEM skin) and this is a problem for the FEMDEM solve. With the backups I can save the acc and reset them after the PFEM solves.
> > > In my opinion has nothing to do with the buffer :)
> > > Thank you kindly,
> > 
> > 
> > If your buffer is size 2, and you want to save 2 values, you are actually saving 4 values!!! If you use the second position of the buffer as I suggested you will not waste half of memory
> 
> so you're saying that I only have to create one new variables and use the buffer, okkey :) changing it

Yes I meant that, is already changed?

2019-11-18 09:46 UTC, AlejandroCornejo commented
yes @loumalouomega I've changed that

2019-11-18 10:07 UTC, loumalouomega reviewed
Some missing &

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 0);
```suggestion
                const auto& current_accel_backup = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 0);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 1);
```suggestion
                const auto& prev_accel_backup    = it_node->FastGetSolutionStepValue(ACCELERATION_BACKUP, 1);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto current_displ_backup = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 0);
```suggestion
                const auto& current_displ_backup = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 0);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 1);
```suggestion
                const auto& prev_displ_backup    = it_node->FastGetSolutionStepValue(DISPLACEMENT_BACKUP, 1);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto current_acceleration = it_node->FastGetSolutionStepValue(ACCELERATION, 0);
```suggestion
                const auto& current_acceleration = it_node->FastGetSolutionStepValue(ACCELERATION, 0);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto prev_acceleration    = it_node->FastGetSolutionStepValue(ACCELERATION, 1);
```suggestion
                const auto& prev_acceleration    = it_node->FastGetSolutionStepValue(ACCELERATION, 1);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto current_displ = it_node->FastGetSolutionStepValue(DISPLACEMENT, 0);
```suggestion
                const auto& current_displ = it_node->FastGetSolutionStepValue(DISPLACEMENT, 0);
```

2019-11-18 10:07 UTC, loumalouomega commented on applications/FemToDemApplication/custom_processes/fix_free_velocity_on_nodes_process.cpp
> +                const auto prev_displ    = it_node->FastGetSolutionStepValue(DISPLACEMENT, 1);
```suggestion
                const auto& prev_displ    = it_node->FastGetSolutionStepValue(DISPLACEMENT, 1);
```

2019-11-18 10:35 UTC, AlejandroCornejo commented
> 
> 
> Some missing &

I tried to use the referendcesw but there was memory corruption so... I prefer to leave it as it is now :)

2019-11-18 11:06 UTC, loumalouomega commented
> 
> 
> > Some missing &
> 
> I tried to use the referendcesw but there was memory corruption so... I prefer to leave it as it is now :)

Even whit the noalias now?, I think that with the noalias should copy the result not reference it. Can you try?

2019-11-18 13:18 UTC, loumalouomega approved these changes

2019-11-18 14:51 UTC, merged