Structural/adjoint spring damper element
KratosMultiphysics/Kratos pull request #5954
Opened 2019-11-20 14:28 UTC by MFusseder

Within this PR I add the adjoint spring damper element. The implementation is straight forward compared to the other adjoint finite difference elements. The only major differences are due to the specialty of the spring damper element to save its stiffness properties (e.g. `NODAL_DISPLACEMENT_STIFFNESS`) within the non-historical data base instead of the properties. This circumstance leads to the need to explicitly transfer the stiffness values from the adjoint to the primal element in order the have them available for the computation of the element matrices. As the stiffness values are not part of the properties the functions of `element_finite_difference_utility` can't be used the compute the pseudo-load contribution. But as there is a linear dependency between the element residual and the stiffness values the additional code to get also the pseudo-load for stiffness values of the spring is low. 
The PR also add a test case for the new adjoint spring damper element.

2019-11-20 21:07 UTC, armingeiser requested changes
Looks good overall, just some minor comments.

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp
> +        const SizeType  write_points_number = this->GetGeometry()
write_points_number is a strange name for the number of gauss points =)

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_spring_damper_element_3D2N.cpp
> +    this->pGetPrimalElement()->SetValue(NODAL_DISPLACEMENT_STIFFNESS, this->GetValue(NODAL_DISPLACEMENT_STIFFNESS));
please add a short comment here as this is something special

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_spring_damper_element_3D2N.cpp
> +            array_1d<double, 3> perturbed_nodal_stiffness = ZeroVector(3);
noalias

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_spring_damper_element_3D2N.cpp
> +        rOutput = ZeroMatrix(0, local_size);
noalias

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_spring_damper_element_3D2N.cpp
> +    KRATOS_CATCH( "Problem in the Check in the SpringDamperElement3D2N" )
AdjointFiniteDifference...

2019-11-20 21:07 UTC, armingeiser commented on applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py
> +    nightSuite.addTests(KratosUnittest.TestLoader().loadTestsFromTestCases([TTestAdjointSensitivityAnalysisSpringDamperStructure]))
this test should be very fast, maybe you can even add it to the smallSuite?

2019-11-21 08:27 UTC, armingeiser commented on applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_spring_damper_element_3D2N.cpp
> +            noalias(perturbed_nodal_stiffness) = ZeroVector(3);
sorry here i was wrong, the old version was better.

2019-11-21 09:21 UTC, armingeiser submitted a review, later dismissed

2019-11-21 09:34 UTC, philbucher requested changes
minor request

2019-11-21 09:34 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/test_adjoint_sensitivity_analysis_spring_damper_3d2n_structure.py
> +class controlledExecutionScope:
please use the one from KratosUnittest

2019-11-21 09:34 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/test_adjoint_sensitivity_analysis_spring_damper_3d2n_structure.py
> +        Logger.GetDefaultOutput().SetSeverity(Logger.Severity.WARNING)
please set it to INFO otherwise

2019-11-21 10:59 UTC, philbucher submitted a review, later dismissed

2019-11-21 11:35 UTC, armingeiser approved these changes

2019-11-21 12:35 UTC, merged

2020-01-14 14:33 UTC, philbucher commented
@MFusseder can you please run the test in `FullDebug`? It fails there, but I think it is easy to fix