[ShapeOpt] in-plane vertex morphing
KratosMultiphysics/Kratos pull request #6104
Opened 2019-12-16 20:36 UTC by armingeiser

This is a new mapper for in plane vertex morphing on curved surfaces.

It allows updates only in the in-plane direction of a background mesh.
The background mesh is also needed to describe the "surface" outside of the starting geometry (example follows)

![kratos_in_plane](https://user-images.githubusercontent.com/25903585/70941080-fd264080-204b-11ea-8595-69556319b6bd.gif)

2019-12-16 20:39 UTC, armingeiser commented
@dbaumgaertner the implementation is already quite mature - most critical point: The in plane mapper needs some additional working variables, but at the point our mappers are created, the mesh is already imported and the variables can not be added anymore. At the moment i hardcoded this in steepest descent...

Except from that i think only the place of a few utility functions is still questionable.

Let me know what you think.

2019-12-17 14:07 UTC, dbaumgaertner requested changes
I have a few comments and also questions. Apart from naming and alike, there are three main points:

1) The variables should be moved to a better place.
2) The handling of some aliases is not very clean imo. 
3) The construction of the new mapper could also be improved imo

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/tests/in_plane_opt_test/optimization_parameters.json
> +            "type"                               : "vertex_morphing",
Bad indentation. Also other places in this file.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/tests/in_plane_opt_test/optimization_parameters.json
> +                "in_plane" : true,
```suggestion
                "in_plane_morphing" : true,
```

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/tests/in_plane_opt_test/optimization_parameters.json
> +                "in_plane_settings" : {
```suggestion
                "in_plane_morping_settings" : {
```

Obviously, this requires some adjustment in other places of the code as well.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_python/add_custom_utilities_to_python.cpp
> +        .def("ProjectNodalVariableToDirection", &GeometryUtilities::ProjectNodalVariableToDirection)
```suggestion
        .def("ProjectNodalVariableOnDirection", &GeometryUtilities::ProjectNodalVariableOnDirection)
```

I think "on" is the proper word here. Also, the other functions need to be adjusted accordingly.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_python/add_custom_utilities_to_python.cpp
> +        .def("ProjectNodalVariableToTangentOfDirection", &GeometryUtilities::ProjectNodalVariableToTangentOfDirection)
idem

```suggestion
        .def("ProjectNodalVariableOnTangentOfDirection", &GeometryUtilities::ProjectNodalVariableOnTangentOfDirection)
```

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_utilities/geometry_utilities.h
>      {
This function is technically not necessary anymore then.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_utilities/mesh_controller_utilities.h
> +        // TODO this is a copy from optimization_utilities
Then we should unify this somehow.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_utilities/mesh_controller_utilities.h
> +    void CalculateDistanceToVariable( const Variable<array_1d<double,3>> &rInputVariable,
The name here is really not descriptive. We should find a better one. I am still thinking about it.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/algorithm_steepest_descent.py
> +        #TODO find the right place to add variables to the mesh for in plane mapping
This is a very bad place for the variables, I think. What about placing them in the optimizer_factory?

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapper_factory.py
> +    mapper_settings.ValidateAndAssignDefaults(default_settings)
Why this change?

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapper_factory.py
> +        return in_plane_vertex_morphing_mapper.InPlaneVertexMorphingMapper(origin_model_part, destination_model_part, mapper_settings, vm_mapper)
I understand what you are doing here. But passing a mapper to another mapper as an argument seems a bit weird. This seems to be against the concept of classes and inheritance... What about creating the needed vm mapper internally?

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        # TODO destination does already exist can not add here anymore - non historical??
What about these comments?

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        elif in_plane_settings["model_import_settings"]["input_type"].GetString() in ["vrml", "wrl"]:
Nice to be able to directly use the vrml feature here.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +# TODO temporary aliases for some variables specific for in plane mapping
Why todo? Is there a better solution that could be immediately implemented?

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        # project on tangent plane
Instead of placing a comment. Wrap the following two lines also into a descriptive private function. Much like "_CorrectOutOfPlane..."

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        # project on tangent plane
Again remove comment using the same function as suggested above.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        KSO.MeshControllerUtilities(self.background_mesh).WriteCoordinatesToVariable(_BACKGROUND_COORDINATE)
I would add an empty line before.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        # calculate out of plane delta
I do not quite understand what happens here. You need to explain this to me.

2019-12-17 14:07 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        #TODO damping should only be used if activated for x, y, z - where to check??!!
why this?

2019-12-17 14:21 UTC, armingeiser commented on applications/ShapeOptimizationApplication/custom_utilities/mesh_controller_utilities.h
> +        // TODO this is a copy from optimization_utilities
intermediate solution - use optimization_utilities

2019-12-17 14:23 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/mapper_factory.py
> +    mapper_settings.ValidateAndAssignDefaults(default_settings)
There where no levels in the old settings and now as i added the in_plane_settings i wan't to validate them in the in plane mapper directly

2019-12-17 14:25 UTC, armingeiser commented on applications/ShapeOptimizationApplication/custom_utilities/mesh_controller_utilities.h
> +    void CalculateDistanceToVariable( const Variable<array_1d<double,3>> &rInputVariable,
SubtractCoordinatesFromVariable

2019-12-17 14:32 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/algorithm_steepest_descent.py
> +        #TODO find the right place to add variables to the mesh for in plane mapping
Try to make them non historical

2019-12-17 14:56 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/mapper_factory.py
> +        return in_plane_vertex_morphing_mapper.InPlaneVertexMorphingMapper(origin_model_part, destination_model_part, mapper_settings, vm_mapper)
try the cyclic import again

2019-12-17 14:56 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        # TODO destination does already exist can not add here anymore - non historical??
They where meant for you =) to easier understand the problem with the variables

2019-12-17 14:58 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +# TODO temporary aliases for some variables specific for in plane mapping
new variables in shape opt app

2019-12-17 15:46 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/algorithm_steepest_descent.py
> +        #TODO find the right place to add variables to the mesh for in plane mapping
In new MR

2019-12-17 16:36 UTC, armingeiser commented on applications/ShapeOptimizationApplication/custom_utilities/mesh_controller_utilities.h
> +        // TODO this is a copy from optimization_utilities
-> new issue about unifying utilities

2019-12-18 16:07 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/optimizer_factory.py
> +def _ValidateCombinationOfSettings(optimization_settings):
After discussion: remove this validation and add docstring to the mapper

2019-12-18 16:13 UTC, dbaumgaertner requested changes
Minor comments as discussed. Also, I adjusted some empty lines to be consistent with all new files from the last few days. 

Note also, that I adjusted the name of the packaging test here, as it was not properly adjusted previously.

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_utilities/geometry_utilities.h
> +    void ProjectNodalVariableOnDirection( const Variable<array_3d> &rNodalVariable, const Variable<array_3d> &rNormalVariable)
If this is a generic function, then also the input variables should be generic, i.e.:

```suggestion
    void ProjectNodalVariableOnDirection( const Variable<array_3d> &rNodalVariable, const Variable<array_3d> &rDirectionVariable)
```

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/custom_utilities/geometry_utilities.h
> +    void ProjectNodalVariableOnTangentPlane( const Variable<array_3d> &rNodalVariable, const Variable<array_3d> &rNormalVariable)
See comment above, should be a generic input variable.

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/custom_ios/wrl_io.py
> +        node_usage_count = {}
what about the following name: 
```suggestion
        node_multiplicity = {}
```

Requires also some adjustments further below.

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/custom_ios/wrl_io.py
> +        counter = 0
```suggestion
        # Remove flying nodes
        counter = 0
```

I think here a comment makes sense.

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/mapping/in_plane_vertex_morphing_mapper.py
> +        geometry_utilities.ProjectNodalVariableOnDirection(KSO.OUT_OF_PLANE_DELTA, KSO.BACKGROUND_NORMAL) #TODO???
Is this ToDo still a leftover or is there still an open point here?

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/tests/in_plane_opt_test/optimization_parameters.json
> +                    }
```suggestion
                    }
                "background_sub_model_part_name" : ""
```

To give a hint that there is this option of using a sub-mdpa. What do you think?

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/tests/in_plane_opt_test/optimization_parameters.json
> +                "in_plane_morphing" : true,
Nice and clean settings with only little impact on the overall settings.

2019-12-18 16:13 UTC, dbaumgaertner commented on applications/ShapeOptimizationApplication/python_scripts/optimizer_factory.py
> +        not _HasDampingNotInAllCartesianDirections(optimization_settings["model_settings"]["damping"]):
Avoid a double negation: "not _HasDampingNot...." It would be more readable if "not_HasDampingInAll...".

2019-12-18 16:16 UTC, dbaumgaertner commented
@armingeiser just to remind you that here also a gif of the big shell model would be nice.

2019-12-18 17:00 UTC, philbucher approved these changes
![image](https://user-images.githubusercontent.com/25484702/71106811-3d0e3480-21c0-11ea-9520-be5aa6ccdf2a.png)

2019-12-18 17:01 UTC, dbaumgaertner approved these changes

2019-12-18 21:04 UTC, merged