Feature change beam inertia to vector
KratosMultiphysics/Kratos pull request #623
Opened 2017-07-15 13:08 UTC by KlausBSautter

Hi everyone,
1.) 
as already discussed I changed the way the local beam inertias are defined from 3 doubles to the usage of an already existing Matrix variables.  I used that instead of a new vector as it already exists. One will have to write in the *.mdpa :
    LOCAL_INERTIA_TENSOR [1,3] ((0.00001,0.00001,0.00001))
2.)
I noticed that a boolean was not registered so I fixed that.

Cheers, Klaus

2017-07-16 08:49 UTC, loumalouomega requested changes
Discuss about using a vector or a matrix for Voigt notation

2017-07-16 08:49 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_3D2N.cpp
> +		Matrix inertia = GetProperties()[LOCAL_INERTIA_TENSOR];
Maybe it's better to use a vector instead of a matrix if you are going to store the values using Voigt notation

2017-07-16 08:53 UTC, KlausBSautter commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_3D2N.cpp
> +		Matrix inertia = GetProperties()[LOCAL_INERTIA_TENSOR];
yes I can change it to a vector, I just thought I'd use an already existing variable.

2017-07-16 08:57 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_3D2N.cpp
> +		Matrix inertia = GetProperties()[LOCAL_INERTIA_TENSOR];
OK, but that variable maybe was designed for rigid elements, I did a grep and it is used in the rigid element from the ContactMechanicsApplication and in the legacy structual. In this one the values are stored in a traditional way:

~~~cpp
    Matrix* inertia;
    if( GetProperties().Has(LOCAL_INERTIA_TENSOR) )
    {
        inertia = &(GetProperties()[LOCAL_INERTIA_TENSOR]);
    }
    else if( GetProperties().Has(INERTIA) )
    {
        inertia = &(GetProperties()[INERTIA]);
    }
    else if( Has(LOCAL_INERTIA_TENSOR) )
    {
        inertia = &(GetValue(LOCAL_INERTIA_TENSOR));
    }
    else if( Has(INERTIA) )
    {
        inertia = &(GetValue(INERTIA));
    }
    else
        KRATOS_THROW_ERROR(std::logic_error, "The Inertia is not fully defined for the element", "")
    mInertia_x = (*inertia)(0,0);
    mInertia_y = (*inertia)(1,1);
    mInertia_Polar = (*inertia)(0,1);
~~~

2017-07-16 09:08 UTC, KlausBSautter commented on applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_3D2N.cpp
> +		Matrix inertia = GetProperties()[LOCAL_INERTIA_TENSOR];
alright I'll change it to vector, it will also be more convinient to use, thanks.

2017-07-16 09:54 UTC, KlausBSautter commented
alright, I changed it to a vector @loumalouomega

2017-07-16 10:03 UTC, loumalouomega approved these changes
Allright, let's wait to the opinion of the others

2017-07-26 10:17 UTC, merged

2017-08-09 20:10 UTC, pooyan-dadvand commented
Would you please delete this branch?