[EigenSolvers] Add Eigen library to application
KratosMultiphysics/Kratos pull request #6240
Opened 2020-01-16 12:30 UTC by oberbichler

As discussed yesterday the Eigen library is now included inside the `EigenSolversApplication`.

Tested on windows.

Can you do a quick test if this is also working on your machines?

2020-01-16 13:43 UTC, qaumann commented
Cool, works for me on Linux

2020-01-17 14:21 UTC, armingeiser requested changes

2020-01-17 14:21 UTC, armingeiser commented on applications/EigenSolversApplication/CMakeLists.txt
> -if( NOT DEFINED EIGEN_ROOT )
As the EIGEN_ROOT variable is not needed anymore, the README of the application has to be adapted.

2020-01-17 15:25 UTC, armingeiser commented on applications/EigenSolversApplication/CMakeLists.txt
> -if( NOT DEFINED EIGEN_ROOT )
done

2020-01-17 15:32 UTC, armingeiser approved these changes

2020-01-17 16:08 UTC, philbucher requested changes
blocking to prevent accidental merge

2020-01-22 12:34 UTC, philbucher commented
@KratosMultiphysics/technical-committee approves this, thanks for the effort

we will leave the treatment of `DEIGEN_MPL2_ONLY` as is for the moment, unless someone needs it, in which case please let us know

2020-01-23 09:45 UTC, philbucher approved these changes

2020-01-23 09:47 UTC, merged

2020-01-23 13:18 UTC, philbucher commented
for the record, this added 5,1MB in files