[DEM]unittest for restitution coefficient
KratosMultiphysics/Kratos pull request #6299
Opened 2020-01-27 16:14 UTC by farrufat-cimne

2D and 3D versions.
Restitution value is not exact since the test uses 10x recommended timestep.
Although, the tolerance values are strict.

2020-01-27 16:15 UTC, farrufat-cimne commented
Importing    KratosDEMApplication 
DEM: 
DEM:      KRATOS |  _ \| ____|  \/  |  _ \ __ _  ___| | __      
DEM:             | | | |  _| | |\/| | |_) / _` |/ __| |/ /      
DEM:             | |_| | |___| |  | |  __/ (_| | (__|   <       
DEM:             |____/|_____|_|  |_|_|   \__,_|\___|_|\_\      
DEM: 
DEM: Importing DEMApplication... ( compiled in mode "Release" ) done.
...............
----------------------------------------------------------------------
Ran 15 tests in 4.183s

OK

2020-01-27 16:15 UTC, farrufat-cimne commented
```
Importing    KratosDEMApplication 
DEM: 
DEM:      KRATOS |  _ \| ____|  \/  |  _ \ __ _  ___| | __      
DEM:             | | | |  _| | |\/| | |_) / _` |/ __| |/ /      
DEM:             | |_| | |___| |  | |  __/ (_| | (__|   <       
DEM:             |____/|_____|_|  |_|_|   \__,_|\___|_|\_\      
DEM: 
DEM: Importing DEMApplication... ( compiled in mode "Release" ) done.
...............
----------------------------------------------------------------------
Ran 15 tests in 4.183s

OK

```

2020-01-27 16:33 UTC, maceligueta requested changes

2020-01-27 16:33 UTC, maceligueta commented on applications/DEMApplication/tests/test_DEM_2D_restitution.py
> +            restitution_coefficient = -final_vel / self.initial_normal_vel
All these prints should use the KratosLogger. Otherwise we will see too many things on screen

2020-01-28 09:42 UTC, maceligueta approved these changes

2020-01-28 09:45 UTC, merged