[PfemFluid] Add 3D Inlet test
KratosMultiphysics/Kratos pull request #6432
Opened 2020-02-18 14:20 UTC by MZecchetto

just that

2020-02-18 16:24 UTC, philbucher requested changes
@MZecchetto can you please reduce the size of the mdpa file you are adding?
we usually try to have less than 1000 lines in order to not blow up the size of the Kratos repo too much.
Thanks a lot

2020-02-18 17:08 UTC, MZecchetto commented
Dear @philbucher ,
I didn't know that there are limits on the number of line, thanks for letting me know.
I tried to reduced as much as I can the size of the mdpa, but it is hard to reach 1000 lines. Is this modified test acceptable?

2020-02-18 18:15 UTC, philbucher submitted a review, later dismissed
Ok for me, thx for improving 
1000 lines is a rough guideline, if it is not possible more is also ok

For big examples we have the Examples Repo

2020-05-04 13:58 UTC, AFranci approved these changes

2020-05-04 14:11 UTC, merged