[Core] Add GetValueOnIntegrationPoints to Python
KratosMultiphysics/Kratos pull request #6498
Opened 2020-03-03 05:48 UTC by tteschemacher

Hi all,

I am entering the world of beauty. I know that this was already a long and bad discussion, but I need it. It might confuse with the GetValue**S**OnIntegrationPoints which is wrongly calling the CalculateOnIntegrationPoints. 

This calls the correct function and comes without the controversial additional s.

Feel free to blame me. But I need this to make the MPM run again.

Cheers!

2020-03-03 06:50 UTC, loumalouomega approved these changes
This approval should be granted

2020-03-03 07:29 UTC, RiccardoRossi requested changes
i am blocking since i don't understand what is going on here.

if we add GetValuesOnIntegrationPoints we need to remove the version without the s...

2020-03-03 08:03 UTC, RiccardoRossi commented
well, the function with the s (which should be called CalculateValueOnIntegrationPoints) is only used in 3 files, so we could just rename it here

~~~
grep -r GetValuesOnIntegrationPoints --include=*.py
applications/PfemSolidMechanicsApplication/python_scripts/gauss_point_utility.py:            cauchy_vector = elem.GetValuesOnIntegrationPoints( KratosMultiphysics.CAUCHY_STRESS_TENSOR, SomeProcessInfo)
applications/PfemSolidMechanicsApplication/python_scripts/gauss_point_utility.py:            epsi_vector = elem.GetValuesOnIntegrationPoints( KratosMultiphysics.GREEN_LAGRANGE_STRAIN_TENSOR, SomeProcessInfo)
applications/FemToDemApplication/python_scripts/MainCouplingFemDem.py:                    stress_tensor = Elem.GetValuesOnIntegrationPoints(KratosFemDem.STRESS_VECTOR_INTEGRATED, self.FEM_Solution.main_model_part.ProcessInfo)
~~~

2020-03-03 08:06 UTC, RiccardoRossi commented on kratos/python/add_mesh_to_python.cpp
> +    // GetValue  s  OnIntegrationPoints
my proposal would be to rename the GetValueS... to CalculateValueS... and to also change it in the 3files that make use of it. 

Other than that i think we simply need to keep track of the change in 
https://github.com/KratosMultiphysics/Kratos/projects/26

and to mark the current PR as APIBreaker

2020-03-03 10:04 UTC, philbucher requested changes
if we go ahead with this one then I would say it should be as proposed in #2194 
=> `CalculateOnIntegrationPoints`

All elements in Structural implement both, `CalculateOnIntegrationPoints` and `GetValuesIntegrationPoints`, where the later is only a wrapper to call `CalculateOnIntegrationPoints`

2020-03-03 10:04 UTC, philbucher commented on kratos/python/add_mesh_to_python.cpp
> +    dummy.GetValueOnIntegrationPoints(rVariable, values, rCurrentProcessInfo);
this should be mapped to `CalculateOnIntegrationPoints` I would say, its what we wanted to do in #2194

2020-03-03 11:39 UTC, tteschemacher commented
Guys. That are NO productive comments.

This is related to a hot fix to make the ParticleMechanics run again.

2020-03-03 11:55 UTC, philbucher commented
> Guys. That are NO productive comments.
> 
> This is related to a hot fix to make the ParticleMechanics run again.

I don't agree, I gave constructive criticism
This is big changes in the core after all!

In any case, @RiccardoRossi will post sth in the next minutes

2020-03-03 11:58 UTC, RiccardoRossi commented
@tteschemacher the point is that what you propose is NOT a hotfix.
you are adding an interface that will remain there forever, without fixing the underlying issue...

now, we definitely do not want u to make an enormous change through the Kratos to fix the mpm.

my proposal is the following:
1 - in the MPM use CalculateOnIntergrationPoint (i don't know if there is the "s" or not, i am referring to the function defined in the element API). My point is to use the function called Calculate instead of the one called Get
2 - Let's expose to python ONLY the function CalculateOnIntegrationPoints, and remove the other functions. This way you will also not need to add your new interface, but just to change the name to a few functions
3 - no function "Get*OnIntegrationPoint" is exposed at all...but you don't need since you will use CalculateOnIntegrationPoints instead.

as far as i can see 2 only requires changing 3 python files:

~~~
grep -r GetValuesOnIntegrationPoints --include=*.py
applications/PfemSolidMechanicsApplication/python_scripts/gauss_point_utility.py:            cauchy_vector = elem.GetValuesOnIntegrationPoints( KratosMultiphysics.CAUCHY_STRESS_TENSOR, SomeProcessInfo)
applications/PfemSolidMechanicsApplication/python_scripts/gauss_point_utility.py:            epsi_vector = elem.GetValuesOnIntegrationPoints( KratosMultiphysics.GREEN_LAGRANGE_STRAIN_TENSOR, SomeProcessInfo)
applications/FemToDemApplication/python_scripts/MainCouplingFemDem.py:   
~~~

@tteschemacher  does this make sense to you?

2020-03-16 06:39 UTC, tteschemacher commented
I am closing this PR as it was exchanged by #6528 .

2020-03-16 06:39 UTC, closed without merging