[MLMC][WIP] Add XMC into application
KratosMultiphysics/Kratos pull request #6729
Opened 2020-04-07 13:59 UTC by riccardotosi

Do not merge. I open the PR for testing the work done.

2020-04-07 22:32 UTC, philbucher reviewed
just browsing through
Please reduce the size of the mdpa you are adding (should be less than 1000 lines)

2020-04-07 22:32 UTC, philbucher commented on .github/workflows/ci.yml
> +        export PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/bin/${{ matrix.build-type }}:${GITHUB_WORKSPACE}/bin/${{ matrix.build-type }}/KratosMultiphysics/MultilevelMonteCarloApplication
this should not be changed
I think you could put this in an __init__

2020-04-30 11:22 UTC, philbucher commented
just to say that if this goes in it should be `squashed` otherwise we have another large file in the git-history

2020-04-30 11:23 UTC, philbucher commented
as I wrote before probably the right place to add things to the path is in the `__init__.py` of the application

2020-04-30 11:49 UTC, roigcarlo commented
Yep, at this point is just testing why the hell the module is not found on the CI. (Seems to work everywhere else...)

2020-05-08 08:49 UTC, philbucher requested changes
Blocking because I want to give this a final review before it is being merged

2020-05-11 16:01 UTC, philbucher commented
guys there are still some huge mdpas in this PR
also some *bin files

Please clean this

2020-05-11 16:03 UTC, riccardotosi commented
You are right @philbucher , my bad. Thanks (but it was not ready for reviewing)

2020-05-11 16:10 UTC, roigcarlo commented
@philbucher Maybe we can try the Merge-Squash here so we don't have to care about blobs in this PR. what do you say?

2020-05-11 16:14 UTC, philbucher commented
> @philbucher Maybe we can try the Merge-Squash here so we don't have to care about blobs in this PR. what do you say?

[quoting myself](https://github.com/KratosMultiphysics/Kratos/pull/6729#issuecomment-621772468), yes this is necessary here IMO, otherwise we again have some more mdpas in the history :)

2020-05-12 20:41 UTC, philbucher commented
To me looks good
Some questions:
- Should this app be in the CI?
    - What are the long-term plans?
    - Who are the official maintainers?
- Since there were many big files involved this should be merged with a squash-commit

2020-05-13 07:25 UTC, riccardotosi commented
> Should this app be in the CI? 

I don't think I am the one who should answer this question. Are there some criteria? If so, I can try to answer them.

> Who are the official maintainers?

Official maintainers are @RiccardoRossi and myself. Regarding the XMC library, official maintainers are Riccardo Rossi, myself, a team at EPFL and one at BSC.

> What are the long-term plans?

`MultilevelMonteCarloApplication` follows the start of the ExaQUte application, as well as the XMC library. I cannot speak for what will happen after the project, probably @RiccardoRossi has a wider view on this question.

> Since there were many big files involved this should be merged with a squash-commit.

Ok.

2020-05-18 14:33 UTC, RiccardoRossi commented
> To me looks good
> Some questions:
> 
>     * Should this app be in the CI?
>       
>       * What are the long-term plans?
>       * Who are the official maintainers?
> 
>     * Since there were many big files involved this should be merged with a squash-commit

Hi,

i would like this to be in the CL if possible. This app is interesting longer term, apart for the ExaQUte project.

i am completely ok with the squash.

also @riccardotosi @marcnunezc this is your creature, so you deserve being the official mantainers

2020-05-18 14:51 UTC, philbucher commented
green light :traffic_light: from me then

@roigcarlo @rubenzorrilla @pooyan-dadvand ?

2020-05-18 15:00 UTC, roigcarlo commented
Ok to me also :+1:

2020-05-22 15:13 UTC, roigcarlo submitted a review, later dismissed
Re-Approving changes for the new XMC branch

2020-05-22 15:19 UTC, riccardotosi commented
From my side, I am ready to merge (with squash commit).

2020-05-22 16:52 UTC, philbucher approved these changes

2020-05-25 07:39 UTC, merged

2020-05-25 07:41 UTC, riccardotosi commented
Seems merged correctly with the squash. Thanks @roigcarlo @philbucher for the help!