[Core] separate Communicator exposure
KratosMultiphysics/Kratos pull request #6733
Opened 2020-04-07 16:36 UTC by philbucher

Up until now the `Communicator` is exposed in `add_model_part_to_python`
Now it is moved to its own file, `add_communicator_to_python`

I also took the chance and removed the long deprecated functions that were moved to the `DataCommunicator` a long time ago

2020-04-07 16:43 UTC, loumalouomega commented on kratos/python/add_communicator_to_python.cpp
> +Communicator::MeshType& CommunicatorGetLocalMesh(Communicator& rCommunicator)
Why no lambdas?

2020-04-07 16:44 UTC, loumalouomega requested changes
Why no lambdas for a full refactor?

2020-04-07 16:50 UTC, philbucher commented
As I [commented earlier](https://github.com/KratosMultiphysics/Kratos/pull/6603#discussion_r398456433) one should not just change code for the sake of changing it !!!!!

Maybe if we can use `pybind::overload_case` then it is worth, but not for an intermediate solution (aka lambdas)

It is ok for NEW code but changing old code has no benefit except the introduction of bugs

2020-04-07 17:13 UTC, loumalouomega approved these changes
Okay

2020-04-08 08:59 UTC, rubenzorrilla approved these changes

2020-04-08 11:06 UTC, merged