Core add GetSystem functions base strategy
KratosMultiphysics/Kratos pull request #6763
Opened 2020-04-10 11:04 UTC by adityaghantasala

Following the discussion in #6748 

This PR adds the `GetSystemMatrix` , `GetSystemVector` , `GetSolutionVector` methods to the base solution strategy. This is required to do 
`norm_dx = TSparseSpace::TwoNorm(mpMomentumStrategy->GetSolutionVector());`

2020-04-10 11:24 UTC, loumalouomega requested changes
Missing virtual , and override the functions in the derived classes (expose them to python BTW)

2020-04-10 11:24 UTC, loumalouomega commented on kratos/solving_strategies/strategies/solving_strategy.h
> +    TSystemMatrixType& GetSystemMatrix()
```suggestion
    virtual TSystemMatrixType& GetSystemMatrix()
```

2020-04-10 11:24 UTC, loumalouomega commented on kratos/solving_strategies/strategies/solving_strategy.h
> +    TSystemVectorType& GetSystemVector()
```suggestion
    virtual TSystemVectorType& GetSystemVector()
```

2020-04-10 11:24 UTC, loumalouomega commented on kratos/solving_strategies/strategies/solving_strategy.h
> +    TSystemVectorType& GetSolutionVector()
```suggestion
    virtual TSystemVectorType& GetSolutionVector()
```

2020-04-10 11:54 UTC, adityaghantasala commented
Sorry forgot ! Added !

2020-04-10 12:02 UTC, adityaghantasala commented
By the way there are some implementations of these methods in applications. What is preferred ? to make the changes here or in a different PR ?

2020-04-10 12:02 UTC, loumalouomega submitted a review, later dismissed

2020-04-10 12:09 UTC, loumalouomega commented
> By the way there are some implementations of these methods in applications. What is preferred ? to make the changes here or in a different PR ?

If there not many in this PR, otherwise in a independent one (if CI works)

2020-09-04 07:57 UTC, philbucher commented
why wasn't this merged yet?

2020-09-04 08:04 UTC, loumalouomega commented
> why wasn't this merged yet?

Was not approved, and now there is conflict

2020-09-04 08:07 UTC, philbucher approved these changes, later dismissed

2020-09-04 09:55 UTC, philbucher commented
sth went wrong with the merge

2020-09-04 10:06 UTC, philbucher approved these changes

2020-09-04 13:49 UTC, adityaghantasala commented
@loumalouomega  thanks for merging the master !! 
@philbucher thanks for approving !

2020-09-04 13:50 UTC, merged