[CoSim] adding Process for creating point-based entities
KratosMultiphysics/Kratos pull request #6885
Opened 2020-05-06 21:02 UTC by philbucher

Often for coupled problems we need `PointLoadConditions` on the structure such that the loads (`POINT_LOAD`) are considered in the RHS.

This can ofc be done in the preprocessor, but in the past this has proven to be inefficient. Hence here I add a process (to be used like any other `Process`) with which those conditions (or other point-based conditions) can be created
I also took care that on overlapping interfaces the conditions are only created once (relevant for practical problems)

I thought long where to put it put eventually I think that the CoSimApp is the correct place since this is usually where it is used

@inigolcanalejo this is what I told you abt yesterday
@shahrokh-shayegan this is what I spoke with you abt some time ago
@KlausBSautter this replaces the `CreatePointLoadModelPart` with sth more generic. Can you please refactor the test in CoSim that uses that after this PR is done?

2020-05-07 11:34 UTC, inigolcanalejo requested changes
Thanks for adding this process @philbucher! I will take a closer look later on. For now you can check my minor comments

2020-05-07 11:34 UTC, inigolcanalejo commented on applications/CoSimulationApplication/python_scripts/processes/create_point_based_entites_process.py
> +        [node.Id for mp in model_parts for node in mp.GetCommunicator().LocalMesh().Nodes]
I think this line should be removed

2020-05-07 11:34 UTC, inigolcanalejo commented on applications/CoSimulationApplication/tests/test_processes.py
> +        num_procs = data_comm.Size()
As codacy says your are not using this variables so you can remove them

```suggestion
```

2020-05-07 11:53 UTC, philbucher commented
done, thx @inigolcanalejo

2020-05-07 12:41 UTC, inigolcanalejo submitted a review, later dismissed

2020-05-11 09:49 UTC, philbucher commented
@KratosMultiphysics/cosimulation this should be ready now
After the feedback of @KlausBSautter I think now it should be general enough

2020-05-11 12:10 UTC, inigolcanalejo approved these changes

2020-05-11 13:17 UTC, merged