[ShapeOpt] Adding interface to SU2
KratosMultiphysics/Kratos pull request #6914
Opened 2020-05-15 15:56 UTC by dbaumgaertner

This PR adds an interface that allows running an optimization with the open-source CFD code [SU2](https://su2code.github.io/).

An example can be found in the examples repository [here](https://github.com/KratosMultiphysics/Examples/tree/master/shape_optimization):

2020-05-15 19:14 UTC, philbucher commented
Seems to be suitable also for CoSimulation ;)

2020-05-16 10:42 UTC, rubenzorrilla requested changes
I think that the addition of this to the master branch should be considered in the @KratosMultiphysics/technical-committee (and possibly in the Kratos Steering Committee).

2020-05-16 17:51 UTC, dbaumgaertner commented
@rubenzorrilla Just out of curiosity, why do you think it must be specifically considered by the technical and steering committee? Is there a general interest in such an interface? I mean this little script is really tailored to optimization.

2020-05-17 08:11 UTC, rubenzorrilla commented
> @rubenzorrilla Just out of curiosity, why do you think it must be specifically considered by the technical and steering committee? I mean this little script is really tailored to optimization. But indeed, I should have given this PR a more descriptive title.
> 
> In any case, I am open for any feedback or advice in this context.

More than programming its kind of political issue. Do we want to open the possibility that our master branch links to other Open Source codes that have similar capabilities to our in-house ones? I think this should be at least discussed.

2020-05-18 08:02 UTC, armingeiser requested changes
In general it looks ok to me. I suggest putting it in a subfolder, to better separate it from "internal" code.

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +            "su2_related":
`_related` reads strange, how about `su2_parameters` or `_settings`?

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +            print("> Start writing mdpa file...")
please use the logger, as in the other scripts of ShapeOpt

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +        self.new_file = open(os.path.join(target_directory,self.interface_parameters["su2_related"]["mesh_motion_file"].GetString()), 'w')
`new_file` is only used in this function, can be local variable. Also you could use the `with open() as new_file` pattern

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +        self.new_file = open(self.interface_parameters["kratos_related"]["mdpa_file"].GetString(), 'w')
please use the `with open(...) as ...` pattern

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +    def ReadNodalValuesFromCSVFile(self, filename, collum_with_node_id, collums_to_read, number_of_header_rows):
typo: column

Also this method could be a function

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +        ''' imports mesh and builds python dictionary structure
docstring belongs directly under function name, not in the middle of the method

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +            if line[0] == "%":
Is it possible that there is a space before the `%`?

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                    [ t(s) for t,s in zip(pattern,line.split()) ]
I don't know this syntax, out of curiosity: Does it do any kind of validation? 
* transforming values to ints
* checking for the correct number of entries?

Also `tuple( [int] + [int]*9 )`is the same as `tuple( [int]*10 )`

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                # convert string to int int
```suggestion
                # convert string to int
```

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                markelem = [
this same code for reading the elements is duplicated

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                kratos_id = elem[-1]
```suggestion
                kratos_id = su2_id
```

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                condition_id = condition_id+1
```suggestion
                condition_id += 1
```

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                condition_id = condition_id+1
```suggestion
                condition_id += 1
```

2020-05-18 08:02 UTC, armingeiser commented on applications/ShapeOptimizationApplication/python_scripts/interface_su2.py
> +                condition_id = condition_id+1
same for the following

2020-05-19 08:21 UTC, adityaghantasala commented
> More than programming its kind of political issue. Do we want to open the possibility that our master branch links to other Open Source codes that have similar capabilities to our in-house ones? I think this should be at least discussed.

Well Co-Sim app is already in Master and it is designed to do exactly that.  The point for me would be to have all the possibilities of communicating  with externally solvers/tools centrally at one place inside of Kratos. So that it is clean and well defined. 

In any case, one can already put this SU2 wrapper inside of CoSimApp and use it in ShapeOptimizationApp via CoSimmApp. 

I will also encourage @dbaumgaertner and others from @KratosMultiphysics/optimization   to consider this possibility of doing optimization via CoSimApp.

2020-05-19 09:58 UTC, rubenzorrilla commented
> > More than programming its kind of political issue. Do we want to open the possibility that our master branch links to other Open Source codes that have similar capabilities to our in-house ones? I think this should be at least discussed.
> 
> Well Co-Sim app is already in Master and it is designed to do exactly that. The point for me would be to have all the possibilities of communicating with externally solvers/tools centrally at one place inside of Kratos. So that it is clean and well defined.
> 
> In any case, one can already put this SU2 wrapper inside of CoSimApp and use it in ShapeOptimizationApp via CoSimmApp.
> 
> I will also encourage @dbaumgaertner and others from @KratosMultiphysics/optimization to consider this possibility of doing optimization via CoSimApp.

Agree. Some days ago @philbucher and I reached the similar conclusion.

2020-05-20 08:59 UTC, dbaumgaertner commented
Thanks all for the comments! Looking into the CoSimApp I totally agree that it fits much better in there.  I wasn't aware that the App is already such mature. In fact, features are great from what I see. So I will change this PR and instead, propose an SU2 wrapper in the CoSimApp (which still just interfaces optimization relevant things in SU2, though). I will come back to @philbucher or @adityaghantasala in this context.

As far as the realization of the optimization workflow with the Co-Sim App is concerned, I see the possibilities of setting up a process flow (co-simulation) with the app. Still, I am a bit more hesitating in this context, as I do not yet see an advantage in realizing the optimization algorithm within some json-settings, which requires a basic understanding of the Co-Sim workflow, rather than directly putting it in one single python script. Also, the output and the actual simulations are more tricky as there are many cross-dependencies. I am sure, this all could be realized with the Co-Sim App somehow. I just wonder what is the advantage of bringing in an additional level of complexity in the already confusing enough world of Vertex Morphing. Obviously, this is just a guts feeling and should be tested carefully. Maybe the implementation is far simpler than I can think of now and we could indeed use synergies. 

In any case, having and using the wrappers in the Co-Sim App is great for the optimization capabilities!

2020-05-20 09:12 UTC, philbucher commented
I agree with @dbaumgaertner that this needs some figuring out of things!

In the long run the goal would be to reduce complexity and not add more. I think we can manage this by clearly separating the responsibilities: CoSimApp communicates with external solvers, ShapeOptApp uses this information then

Also I wanted to mention that the [CoSimIO](https://github.com/KratosMultiphysics/CoSimIO) which had its first release yesterday would be a good fit for this usecase

2020-05-20 12:50 UTC, adityaghantasala commented
@philbucher I think  CoSimIO  would be an overkill in this case. Since SU2 has a good python interface a simple IO for SU2 should suffice. 

By the way congratulations on the first release of CoSimIO. !!

2020-05-21 12:53 UTC, philbucher commented
> @philbucher I think CoSimIO would be an overkill in this case. Since SU2 has a good python interface a simple IO for SU2 should suffice.

I am not sure
Most of this interface deals with translating and reading/writing meshes and gradients from one to another format. This is essentially what the CoSimIO does too. 
I guess it would be possible to access SU2 directly and get the mesh (similarly to how the gradient is accessed). This mesh could be given to the CoSimIO which would do the transfer to/from Kratos
Same for the Gradient

2020-07-27 10:32 UTC, rubenzorrilla submitted a review, later dismissed
@KratosMultiphysics/technical-committee also favors the coupling with other codes through the co-simulation application. Removing the blockages so you can proceed with the migration.

2020-09-28 16:05 UTC, philbucher reviewed
![image](https://user-images.githubusercontent.com/25484702/94457512-f0c33c80-01b4-11eb-9b4c-c8e1f175ee95.png)

please add the big example to the Examples repo
also this PR must be squashed otherwise we have those huge files in the history! => [how to squash a PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request)

more detailed review coming in the next days

2020-09-29 09:39 UTC, dbaumgaertner commented
Sorry, it seems that somehow I have required another review. This is not necessary. I am going to withdraw this PR and add the interface using the Co-Sim App if necessary. Regarding the examples. Since this PR is to be used by somebody less familiar with the Kratos structure I wanted to keep things simple and in one place. But obviously, this is not the best way. I am going to put the examples in the examples repo. Thanks, @philbucher for your hints!

2020-09-29 09:41 UTC, closed without merging

2020-09-29 09:44 UTC, philbucher commented
do you still need the branch?

2020-09-29 10:44 UTC, dbaumgaertner commented
yes, for this year. As I said, somebody else still works with it. But I removed /squashed all memory-blasting commits. So apart from another entry in the list of branches, the footprint of this branch should be very low.