[PfemFluid] new frictional viscoplastic law and cleaning
KratosMultiphysics/Kratos pull request #7056
Opened 2020-06-10 11:55 UTC by AFranci

2020-06-10 12:16 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_2D_law.cpp
> +        if (mean_pressure > 0.0) // in case of tractions
I would suggest to use a "tolerance" instead of 0.0, it is safer (epsilon)

2020-06-10 12:16 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_2D_law.cpp
> +            const double friction_angle_rad= friction_angle*3.14159265359/180;
Pi is defined in Globals::Pi with more accuracy :)

2020-06-10 12:16 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_3D_law.cpp
> +        if (mean_pressure > 0.0) // in case of tractions
same with tolerance

2020-06-10 12:16 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_3D_law.cpp
> +            const double friction_angle_rad= friction_angle*3.14159265359/180;
IDEM pi

2020-06-10 12:35 UTC, AlejandroCornejo requested changes

2020-06-10 12:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/bingham_2D_law.cpp
> +    if (equivalent_strain_rate <= 1e-8) {
This can be set in the .h as a `constexpr double `

2020-06-10 12:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_2D_law.cpp
> +        return effective_cohesion;
wouldn't be cleaner if we put `return rParameters.GetMaterialProperties()[COHESION]` :D

2020-06-10 12:35 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_constitutive/fluid_laws/frictional_viscoplastic_3D_law.cpp
> +        if (equivalent_strain_rate == 0)
it is safer to check if `equivalent_strain_rate <= tolerance`

2020-06-10 13:29 UTC, AFranci commented
Thank you @AlejandroCornejo I addressed most of your comments!

2020-06-10 18:00 UTC, AFranci commented
Is it Ok now?

2020-06-11 09:39 UTC, AlejandroCornejo approved these changes

2020-06-11 09:44 UTC, merged