Cps/transonic compute density derivatives
KratosMultiphysics/Kratos pull request #7084
Opened 2020-06-15 13:58 UTC by eloisabaez

The following functions and tests calculate the various upwinded density derivatives outlined and graphed below, following Fully Simulataneous Coupling of the Full Potential Equation and the Integral Boundary Layer Equations in Three Dimensions by Brian Nishida (1996), Section A.2.6. Essentially three cases exist: the subsonic case, the supersonic and accelerating case, and the supersonic and deaccelerating case. Then the density derivative is also calculated with respect to the current elements squared velocity or the upwind elements squared velocity.

![Screen Shot 2020-06-15 at 3 53 00 PM](https://user-images.githubusercontent.com/60355972/84665915-b218b780-af20-11ea-9a91-2534153e92be.png)
![Screen Shot 2020-06-15 at 2 06 55 PM](https://user-images.githubusercontent.com/60355972/84665931-b7760200-af20-11ea-9c99-a210324bff0a.png)
![Screen Shot 2020-06-15 at 2 45 26 PM](https://user-images.githubusercontent.com/60355972/84665935-b93fc580-af20-11ea-9527-8119d945e3cf.png)
![Screen Shot 2020-06-15 at 2 47 06 PM](https://user-images.githubusercontent.com/60355972/84665939-ba70f280-af20-11ea-8eb4-2f4953ac1705.png)
![Screen Shot 2020-06-15 at 3 03 28 PM](https://user-images.githubusercontent.com/60355972/84665942-bc3ab600-af20-11ea-82c7-c69ec08e2ba4.png)
![Screen Shot 2020-06-15 at 3 16 40 PM](https://user-images.githubusercontent.com/60355972/84665946-be9d1000-af20-11ea-8c92-d0bbef601935.png)

2020-06-16 15:23 UTC, inigolcanalejo requested changes
Thanks for adding the tests, formulas and graphs in this PR. As we discussed earlier, I think the density derivative should also be clamped. The easiest and most consistent way, from my point of view, is to pass the mach number squared as you do for the density. The rest of the suggestions are just minor, some try to simplify code and reduce the computational cost.

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    return free_stream_values_const * std::pow(speed_of_sound_ratio, speed_of_sound_power);
For very high local velocities the speed of sound ratio falls below zero. This will cause this line to crash. We need to either throw and error when this happens, or clamp this function as we are doing for the rest (I would go for the second). Since for the density you are passing the local mach number squared, it might make sense to do the same here for consistency? This also will clamp this function automatically. Let's discuss it.

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +double ComputeUpwindedDensityDerivativeWRTVelocitySquaredSupersonicAccelerating(
Just as an observation: some terms of this function are clamped and others not. In particular Drho_Dq2 is clamped and the rest isn't. Just for us to know. I'm not sure this is what we want.

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double Drho_Dq2 = ComputeDensityDerivativeWRTVelocitySquared<Dim, NumNodes>(inner_prod(rCurrentVelocity, rCurrentVelocity), rCurrentProcessInfo);
Minor suggestions: I would do this in two lines just for visibility, since otherwise the line is too long. But it is a matter of taste.

```suggestion
    const double velocity_squared = inner_prod(rCurrentVelocity, rCurrentVelocity);
    const double Drho_Dq2 = ComputeDensityDerivativeWRTVelocitySquared<Dim, NumNodes>(velocity_squared, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double upwind_factor = SelectMaxUpwindFactor<Dim, NumNodes>(rCurrentVelocity, rUpwindVelocity, rCurrentProcessInfo);
Since you are in the supersonic accelerating case, you already know that the upwind factor is the one computed with the current velocity, so I would directly compute it using ComputeUpwindFactor:

```suggestion
    const double upwind_factor = ComputeUpwindFactor<Dim, NumNodes>(current_mach_sq, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    return Drho_Dq2 - bracket_term;
I would simplify these two lines (also in the formula that you provide in the table taking Drho Dq2 out of the square braquets):

```suggestion
    return Drho_Dq2 (1 - upwind_factor) - upwind_factor_derivative * (current_density - upwind_density);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double upwind_factor_derivative = ComputeUpwindFactorDerivativeWRTVelocitySquared<Dim, NumNodes>(rCurrentVelocity, rCurrentProcessInfo);
Minor suggestion: Now that I see where you call this function, I think it would make sense to also pass current_mach_sq:

```suggestion
    const double upwind_factor_derivative = ComputeUpwindFactorDerivativeWRTVelocitySquared<Dim, NumNodes>(rCurrentVelocity, current_mach_sq, rCurrentProcessInfo);
```
this will allow  you to reduce computational cost by avoiding recomputing the local mach number squared in the line:

```cpp
const double mach_squared = ComputeLocalMachNumberSquared<Dim,NumNodes>(rVelocity, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    return Drho_Dq2 - upwind_factor * Drho_Dq2;
```suggestion
    return Drho_Dq2 * (1.0 - upwind_factor);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double upwind_factor = SelectMaxUpwindFactor<Dim, NumNodes>(rCurrentVelocity, rUpwindVelocity, rCurrentProcessInfo);
```suggestion
    const double upwind_mach_sq = ComputeLocalMachNumberSquared<Dim, NumNodes>(rUpwindVelocity, rCurrentProcessInfo);
    const double upwind_factor = ComputeUpwindFactor<Dim, NumNodes>(upwind_mach_sq, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double upwind_factor = SelectMaxUpwindFactor<Dim, NumNodes>(rCurrentVelocity, rUpwindVelocity, rCurrentProcessInfo);
```suggestion
    const double current_mach_sq = ComputeLocalMachNumberSquared<Dim, NumNodes>(rCurrentVelocity, rCurrentProcessInfo);
    const double upwind_factor = ComputeUpwindFactor<Dim, NumNodes>(current_mach_sq, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double upwind_factor = SelectMaxUpwindFactor<Dim, NumNodes>(rCurrentVelocity, rUpwindVelocity, rCurrentProcessInfo);
```suggestion
    const double upwind_factor = ComputeUpwindFactor<Dim, NumNodes>(current_mach_sq, rCurrentProcessInfo);
```

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    const double Drho_Dq2 = ComputeDensityDerivativeWRTVelocitySquared<Dim, NumNodes>(inner_prod(rUpwindVelocity, rUpwindVelocity), rCurrentProcessInfo);
As mentioned above, maybe in two lines is better?

2020-06-16 15:23 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    return -upwind_factor_derivative * (current_density - upwind_density) + (upwind_factor * Drho_Dq2);
Tiny picky rearrangement:

```suggestion
    return upwind_factor * Drho_Dq2 - upwind_factor_derivative * (current_density - upwind_density);
```

2020-06-17 14:40 UTC, inigolcanalejo approved these changes
Great, thanks for the changes. There are two commented lines that you are not using any more and would be better to remove. Feel free to do it in this PR or in the next one.

2020-06-17 14:40 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    // const double current_mach_sq = ComputeLocalMachNumberSquared<Dim, NumNodes>(rCurrentVelocity, rCurrentProcessInfo);
We usually try not to commit unused commented lines of code into master, do you need this one for later?
```suggestion
```

2020-06-17 14:40 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_utilities/potential_flow_utilities.cpp
> +    // const double upwind_mach_sq = ComputeLocalMachNumberSquared<Dim, NumNodes>(rUpwindVelocity, rCurrentProcessInfo);
```suggestion
```

2020-06-17 18:26 UTC, eloisabaez commented
I just noticed I think the accelerating and deaccelerating cases are flipped...

2020-06-17 21:13 UTC, inigolcanalejo commented
Where do you think they are flipped?

I just checked and the functions: 

- ComputeUpwindedDensityDerivativeWRTVelocitySquaredSupersonicAccelerating
- ComputeUpwindedDensityDerivativeWRTVelocitySquaredSupersonicDeaccelerating
- ComputeUpwindedDensityDerivativeWRTUpwindVelocitySquaredSupersonicAccelerating
- ComputeUpwindedDensityDerivativeWRTUpwindVelocitySquaredSupersonicDeaccelerating

look fine according to the formulas. I might be missing sth. What do you mean?

2020-06-18 07:01 UTC, eloisabaez commented
Oh no, you're right. I confused myself.

2020-06-18 07:01 UTC, merged