Adding fluid dynamics to ROM App
KratosMultiphysics/Kratos pull request #7086
Opened 2020-06-15 18:25 UTC by Rbravo555

This PR generalizes the ROM structure to cope with fluid dynamics using the monolithic solver

2020-06-15 19:33 UTC, philbucher requested changes
there are a few huge files, please reduce the size

2020-06-16 07:09 UTC, RiccardoRossi reviewed
I agree with the comment of @philbucher we need the tests to be smaller than this, otherwise they will take too long to run and they will make our repo enormous...

2020-06-16 07:09 UTC, RiccardoRossi commented on applications/RomApplication/python_scripts/navier_stokes_solver_vmsmonolithic_rom.py
> +class ROMSolver(NavierStokesSolverMonolithic):
this name looks a little too generic ...

2020-06-16 07:24 UTC, philbucher commented
In order to not have the huge files in the repo you can do two things:
- Instead of doing a merge commit (this is what we normally do) do a squash commit. Then all changes are squashed into one commit
- reset the last commit locally and force push, this way it will be gone. After that add the test with smaller files

BTW I see that you are using non-standard python modules (e.g. numpy). For those you need to add `skiptest` otherwise those tests will fail when running them on a machine where those modules are not available
[This](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/tests/co_simulation_test_factory.py#L11-L15) is how we do this in the CoSimApp

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/python_scripts/fluid_dynamics_analysis_rom.py
> +        with open('RomParameters.json') as rom_parameters:
why a separate json and not in ProjectParameters.json?

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/python_scripts/fluid_dynamics_analysis_rom.py
> +        super(FluidDynamicsAnalysisROM,self).__init__(model,project_parameters)
```suggestion
        super().__init__(model,project_parameters)
```

this is possible with python3 (we dropped python2 support :tada:)

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/python_scripts/navier_stokes_solver_vmsmonolithic_rom.py
> +        super(ROMSolver, self).__init__(model, custom_settings)
```suggestion
        super().__init__(model, custom_settings)
```

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/python_scripts/navier_stokes_solver_vmsmonolithic_rom.py
> +        default_settings.AddMissingParameters(super(ROMSolver,cls).GetDefaultSettings())
```suggestion
        default_settings.AddMissingParameters(super().GetDefaultSettings())
```

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/tests/fluid_dynamics_test_files/MainKratosROM.py
> +        super(TestFluidDynamicsROM,self).FinalizeSolutionStep()
```suggestion
        super().FinalizeSolutionStep()
```

2020-06-17 10:01 UTC, philbucher commented on applications/RomApplication/tests/fluid_dynamics_test_files/MainKratosROM.py
> +        super(TestFluidDynamicsROM,self).__init__(model,project_parameters)
```suggestion
        super().__init__(model,project_parameters)
```

2021-03-19 15:22 UTC, closed without merging