Cps/transonic calculate rhs
KratosMultiphysics/Kratos pull request #7137
Opened 2020-06-25 13:23 UTC by eloisabaez

Functions and test to calculate the left hand side for a supersonic element which follows the below equation:

![Screen Shot 2020-06-25 at 3 23 05 PM](https://user-images.githubusercontent.com/60355972/85727999-ccf4e400-b6f7-11ea-8387-1a4d9e2609aa.png)

Based the residual definition of A.2.7 in Fully Simultaneous Coupling of the Full Potential Equation and the Integral Boundary Layer Equations in Three Dimensions by Brian Allen Nishida (MIT, 1996)

2020-06-25 16:01 UTC, inigolcanalejo requested changes
Only the minor comments we talked about. I see that you have added tests for the lhs and rhs for the supersonic accelerating case :+1: could you also add ones for the supersonic decelerating case?

2020-06-25 16:01 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_elements/transonic_perturbation_potential_flow_element.cpp
> +    BoundedMatrix<double, TNumNodes, TNumNodes> common_part_lhs = data.vol * density * prod(data.DN_DX, trans(data.DN_DX));
```suggestion
    BoundedMatrix<double, TNumNodes, TNumNodes> linear_term = data.vol * density * prod(data.DN_DX, trans(data.DN_DX));
```

2020-06-25 16:01 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_elements/transonic_perturbation_potential_flow_element.cpp
> +    if (upwind_factor_case == 0) { // subsonic, not inlet
```suggestion
    if (upwind_factor < 0.0) { // subsonic, not inlet
```

2020-06-25 16:01 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_elements/transonic_perturbation_potential_flow_element.cpp
> +    else if (upwind_factor_case == 1) { // supersonic, accelerating
```suggestion
    else if (upwind_factor >= upstream_upwind_factor) { // supersonic, accelerating
```

2020-06-25 16:01 UTC, inigolcanalejo commented on applications/CompressiblePotentialFlowApplication/custom_elements/transonic_perturbation_potential_flow_element.cpp
> +    else if (upwind_factor_case == 2) { // supersonic, deaccelerating
```suggestion
    else { // supersonic, deaccelerating
```

2020-06-26 14:59 UTC, eloisabaez commented
Hi Iñigo, I think I have addressed all the comments now. The only thing which I did a bit differently is I just checked the Mach numbers instead of the upwind factors in the CalculateLeftHandSideNormalElement function.

2020-06-26 15:26 UTC, inigolcanalejo approved these changes
Looks good :+1: Thanks for addressing the suggestions. I would say the code is ready to start with the validation. 

I think it is also a good idea to first update the python test you have in order to trigger your transonic implementation in some of the elements? You could just increase the free stream mach number. You can do this in another PR.

2020-06-26 15:27 UTC, inigolcanalejo commented
> Looks good +1 Thanks for addressing the suggestions. I would say the code is ready to start with the validation.
> 
> I think it is also a good idea to first update the python test you have in order to trigger your transonic implementation in some of the elements? You could just increase the free stream mach number. You can do this in another PR.

The reason for making the test is that most probably you will have to change your code during the validation and it is always good to have a test with an example that you can quickly run and check whether it breaks or not

2020-06-26 16:35 UTC, merged