[Core] Add geometry python interfaces
KratosMultiphysics/Kratos pull request #7292
Opened 2020-07-27 09:22 UTC by tteschemacher

**Description**
This PR adds a couple of python interfaces to the geometry. It also removes interfaces which would run into errors (GetFastNormal and GetFastUnitNormal -  here the local location is always created on 0,0 which doesn't make sense)

**Changelog**
Python interfaces are added for:
- IntegrationPointsNumber
- Normal with IntegrationPointIndex
- UnitNorma with IntegrationPointIndex
- Jacobian
- DeterminantOfJacobian
- ShapeFunctionsValues
-ShapeFunctionDerivatives

2020-07-27 09:29 UTC, loumalouomega requested changes
Please, replace all these methods with lambdas

2020-07-27 09:50 UTC, tteschemacher commented
> 
> 
> Please, replace all these methods with lambdas

Good that I've got nothing better to do than converting things into lambdas ;) it's done.

2020-07-27 09:53 UTC, loumalouomega submitted a review, later dismissed

2020-07-27 09:56 UTC, tteschemacher commented
thanks @loumalouomega for your review and comment! :)

2020-07-27 10:14 UTC, philbucher submitted a review, later dismissed
:+1:

2020-07-27 10:17 UTC, tteschemacher commented
@loumalouomega the tests are failing in the test_exact_integration because I removed the corrupted interface. Could you check what is wrong there?

2020-07-27 10:22 UTC, loumalouomega commented
> @loumalouomega the tests are failing in the test_exact_integration because I removed the corrupted interface. Could you check what is wrong there?

Later, right now I cannot

2020-07-27 10:28 UTC, loumalouomega commented
> > @loumalouomega the tests are failing in the test_exact_integration because I removed the corrupted interface. Could you check what is wrong there?
> 
> Later, right now I cannot

Please do not remove methods, it may be used by someone else, like me

2020-07-27 10:28 UTC, loumalouomega submitted a review, later dismissed

2020-07-27 10:36 UTC, tteschemacher commented
If they're used by someone it would be better for them to know it. Because they really don't produce anything good :P

2020-07-27 11:30 UTC, philbucher commented
how about adding deprecation warnings to those functions?

2020-07-27 15:09 UTC, philbucher submitted a review, later dismissed
please consider adding a deprecation warning to the critical function

2020-07-27 15:25 UTC, loumalouomega commented
> please consider adding a deprecation warning to the critical function

What I don't understand is why do we need to deprecate those methods

2020-07-27 15:51 UTC, philbucher commented
> > please consider adding a deprecation warning to the critical function
> 
> What I don't understand is why do we need to deprecate those methods

I think because it gives the normal at an undefined location but @tteschemacher knows better

2020-07-27 15:57 UTC, loumalouomega commented
> > > please consider adding a deprecation warning to the critical function
> > 
> > 
> > What I don't understand is why do we need to deprecate those methods
> 
> I think because it gives the normal at an undefined location but @tteschemacher knows better

Lines and triangles (which are 95% of conditions real cases) only have one integration point, and for the quadrilateral (the other 4.8%, the 0.2 lets says corresponds with the quadratic entities) the zero local coordinates correspond with the center. This is very practical because you don't need to use dummy local coordinates, that many times are not trivial

2020-07-27 15:58 UTC, loumalouomega commented
> > > > please consider adding a deprecation warning to the critical function
> > > 
> > > 
> > > What I don't understand is why do we need to deprecate those methods
> > 
> > 
> > I think because it gives the normal at an undefined location but @tteschemacher knows better
> 
> Lines and triangles (which are 95% of conditions real cases) only have one integration point, and for the quadrilateral (the other 4.8%, the 0.2 lets says corresponds with the quadratic entities) the zero local coordinates correspond with the center. This is very practical because you don't need to use dummy local coordinates, that many times are not trivial

[Here an explanation of the numbers I used](https://www.youtube.com/watch?v=7tzfl1wTemM)

2020-07-27 16:00 UTC, philbucher commented
hm sounds reasonable, but this also means that using it for quads is wrong no?

2020-07-27 16:01 UTC, loumalouomega commented
> hm sounds reasonable, but this also means that using it for quads is wrong no?

If you want to get the normal in the center (usually you do), it is not

2020-07-27 16:02 UTC, loumalouomega commented
> > hm sounds reasonable, but this also means that using it for quads is wrong no?
> 
> If you want to get the normal in the center (usually you do), it is not

A debug message can be throw in other cases...

2020-07-27 16:03 UTC, philbucher commented
maybe calling this one `NormalInCenter` then? Or sth similar

2020-07-27 16:05 UTC, loumalouomega commented
> maybe calling this one `NormalInCenter` then? Or sth similar

It is only the center for geometries where zero local coordinates are the center (triangles is the corner)

2020-07-27 16:20 UTC, philbucher commented
ok for me then

if the method stays then please add some comment explaining this!

2020-07-27 17:16 UTC, loumalouomega submitted a review, later dismissed

2020-07-27 18:38 UTC, loumalouomega submitted a review, later dismissed

2020-07-28 07:36 UTC, philbucher commented on kratos/python/add_geometries_to_python.cpp
> +        { const auto& r_type = self.GetGeometryType(); KRATOS_WARNING_IF("Geometry", !(r_type == GeometryData::KratosGeometryType::Kratos_Line2D2 || r_type == GeometryData::KratosGeometryType::Kratos
this is where lambdas are not really that useful any more, one can barely read what is happening ;)

```suggestion
        { const auto& r_type = self.GetGeometryType(); KRATOS_WARNING_IF("Geometry", !(r_type == GeometryData::KratosGeometryType::Kratos_Line2D2 || r_type == GeometryData::KratosGeometryType::Kratos_Triangle3D3)) << "Your geometry is not linear, please provide local coordinates or a GP index. Normal will be computed in zero local coordinates" << std::endl; CoordinatesArrayType LocalCoords; LocalCoords.clear(); return(self.UnitNormal(LocalCoords)); })
```

2020-07-30 08:43 UTC, philbucher approved these changes

2020-07-31 04:01 UTC, tteschemacher commented
Thanks a lot to everyone for the help and the review!! 👍 :)

2020-07-31 04:01 UTC, merged