New process for imposing temperature according monitoring device
KratosMultiphysics/Kratos pull request #769
Opened 2017-09-14 12:30 UTC by lorenzogracia

2017-09-14 12:55 UTC, ipouplana reviewed
I checked the new process and it seems right to me. I just have a comment: perhaps you could substitute the message
`std::cout << "ERROR!!, PLEASE REPEAT THE SEARCH " << std::endl;`
by a KRATOS_ERROR message.

2017-09-14 15:04 UTC, ipouplana approved these changes
Thanks!

2017-09-14 16:04 UTC, rubenzorrilla requested changes

2017-09-14 16:04 UTC, rubenzorrilla commented on applications/DamApplication/custom_processes/dam_temperature_by_device_process.hpp
> +                                Parameters rParameters
This is copying the Parameters arguments instead of getting a reference.

2017-09-14 16:04 UTC, rubenzorrilla commented on applications/DamApplication/custom_processes/dam_temperature_by_device_process.hpp
> +    ModelPart& mr_model_part;
The usual styling for member variables is mMyVariable ("m" + camelcase)

2017-09-14 16:04 UTC, rubenzorrilla commented on applications/DamApplication/custom_processes/dam_temperature_by_device_process.hpp
> +            for(int k = 0; k<nelements; k++)
At first glance, these element loops should work with OpenMP parallelism.

2017-09-14 16:08 UTC, rubenzorrilla commented on applications/DamApplication/python_scripts/impose_uniform_temperature_process.py
> +        self.process.ExecuteInitialize()
Is this correct? It makes not so much sense to me to call the ExecuteInitialize() in the ExecuteInitializeSolutionStep() (just wondering...)

2017-09-14 17:24 UTC, lorenzogracia commented
Hi Ruben,

Thanks for your suggestions, I have changed the variable names and I passed the Parameters as reference. The usage of OMP with break instruction generates compilation problems, this is the reason for not using OMP. There was a mistake in the python process, thanks.

2017-09-14 17:34 UTC, rubenzorrilla commented
Maybe you can try a while loop as is done in here [https://stackoverflow.com/questions/9793791/parallel-openmp-loop-with-break-statement](url)

2017-09-14 17:34 UTC, rubenzorrilla approved these changes

2017-09-15 08:27 UTC, lorenzogracia commented
Thank you for your recommendation but not sure about the improvement having the necessity of using a critical.

2017-09-15 08:29 UTC, merged