use generic algorithm
KratosMultiphysics/Kratos pull request #7785
Opened 2020-11-11 07:06 UTC by mohittyagi-k

Use the generic algorithm for normal computation. This is to enable the use of the slip process on quads.

@rubenzorrilla @ddiezrod @KratosMultiphysics/altair

2020-11-11 07:54 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/python_scripts/apply_slip_process.py
> +        KratosMultiphysics.NormalCalculationUtils().CalculateNormals(self.model_part, True)
```suggestion
        consider_unit_normal = True
        KratosMultiphysics.NormalCalculationUtils().CalculateNormals(self.model_part, consider_unit_normal)
```

2020-11-11 07:55 UTC, rubenzorrilla commented on applications/FluidDynamicsApplication/python_scripts/apply_slip_process.py
> +            KratosMultiphysics.NormalCalculationUtils().CalculateNormals(self.model_part, True)
```suggestion
            consider_unit_normal = True
            KratosMultiphysics.NormalCalculationUtils().CalculateNormals(self.model_part, consider_unit_normal)
```

2020-11-11 07:56 UTC, rubenzorrilla submitted a review, later dismissed
After having checked the geometries implementation, I don't think we will notice the performance affectation (slightly slower for the `Triangle3D3N`). Thanks!

2020-11-11 08:31 UTC, mohittyagi-k commented
Thank you @rubenzorrilla . Could you please re-approve it?

2020-11-11 09:10 UTC, philbucher commented
this doesn't change anything in the results right?
Asking bcs we recently had a nasty bug in a similar part that was hard to catch

FYI @mpentek @sunethwarna

2020-11-11 10:27 UTC, sunethwarna requested changes
This makes the default behaviour to use GenericGeometryAlgorithm ryt (even for Tets, and triangles). And I would suggest you to change the name of the variable since what you are doing is to use generic algorithm, not enforce normals to be unit normals.

PS: You are calling the following which sets `EnforceGenericGeometryAlgorithm` to `True`
https://github.com/KratosMultiphysics/Kratos/blob/d86dfe3e827e058a6c52a3851babf331073fa8eb/kratos/python/add_geometrical_utilities_to_python.cpp#L114

2020-11-11 11:55 UTC, mohittyagi-k commented
> This makes the default behaviour (always behaviour) to use GenericGeometryAlgorithm ryt? (even for Tets, and triangles). And I would suggest you to change the name of the variable since what you are doing is to use generic algorithm, not directly enforce normals to be unit normals

you are absolutely right... just changed it.

2020-11-11 12:01 UTC, mohittyagi-k commented
> I won't be able to use the `apply_slip_process` since it always resorts to use GenericAlgorithm.

The generic algorithm should be able to do what `CalculateOnSimplex` is doing on simplex geometries.. isn't it? I think I am missing the point.

2020-11-11 13:42 UTC, sunethwarna reviewed
> The generic algorithm should be able to do what CalculateOnSimplex is doing on simplex geometries.. isn't it? I think I am missing the point.

Sorry for the noise. I checked `line_2d_2` and `triangle_3d_3`. They are consistent with what we have in `CalculateOnSimplex` methods. So It does not affect the shape derivatives.

But I still think it will be better to have a flag rather than making it always true. I will leave upto @rubenzorrilla to decide whether it is ok to change the default behaviour to always use `GenericAlgorithms`.

2020-11-11 13:43 UTC, sunethwarna approved these changes

2020-11-11 14:05 UTC, mohittyagi-k commented
> this doesn't change anything in the results right?
> Asking bcs we recently had a nasty bug in a similar part that was hard to catch

I hope not, my hope is based on the reason that all tests are passing. 😄

2020-11-11 14:10 UTC, rubenzorrilla commented
As @mohittyagi-k says, this doesn't affect the simplex geometries. The unique change is that the normal calculation in the `Triangle3D3N` is that now a cross product is explicitly performed. With the simplex algorithm the analytical result of such cross product is hardcoded (this is what my performance comment meant to describe).

For the sake of robustness, it's better to always do the generic calculation. Considering that this will have a minor affectation to the total `Triangle3D3N`-case computation time, I'm not so much in favour of introducing more complexities (optional flag) to the process.

Concerning your comment
https://github.com/KratosMultiphysics/Kratos/blob/d86dfe3e827e058a6c52a3851babf331073fa8eb/kratos/python/add_geometrical_utilities_to_python.cpp#L114
Yes, you're right. I missed that bool. In any case, this API export is way misleading and we should probably avoid it...

2020-11-11 14:17 UTC, philbucher commented
> > this doesn't change anything in the results right?
> > Asking bcs we recently had a nasty bug in a similar part that was hard to catch
> 
> I hope not, my hope is based on the reason that all tests are passing. smile

I guess this was a joke, but those comments make me very uncomfortable / scare me in case in 2 weeks from now we compile & run a large case on the cluster it suddenly fails :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: :sweat_smile: 
The FluidDynamicsApplication is used by a LOT of ppl, changes here should be done very carefully!

Since our testing doesn't cover everything, please
- run ALL tests locally (also dependent applications like RANS, PotentialFlow, SDEM). Esp for fluid cases due to the long runtime the CI barely covers usages
- Since you are using it please make sure to give it a real try, ideally on a cluster

not blocking bcs @rubenzorrilla says it is ok

TL,DR: please TEST properly before making sensitive changes

2020-11-12 08:18 UTC, mohittyagi-k commented
@philbucher I ran the local tests for FluidDynamicsApplications (all pass). I have been running some problems (medium and large in MPI) with this change and the slip process seems to be working fine.

2020-11-12 09:54 UTC, philbucher approved these changes
> @philbucher I ran the local tests for FluidDynamicsApplications (all pass). I have been running some problems (medium and large in MPI) with this change and the slip process seems to be working fine.

thx!

2020-11-12 09:59 UTC, mohittyagi-k commented
Thank you everyone, going ahead with the merge.

2020-11-12 09:59 UTC, merged