Adding T_SolAir Fluxes
KratosMultiphysics/Kratos pull request #805
Opened 2017-09-29 19:22 UTC by lorenzogracia

- Adding new process for computing heat fluxes accoding t sol air theory
- Including FACE_HEAT_FLUX in thermal solver
- Updating check and prepare model accoding new thermal loads
- Updating test_examples involved in thermal problem

2017-09-30 07:32 UTC, rubenzorrilla requested changes

2017-09-30 07:32 UTC, rubenzorrilla commented on applications/DamApplication/custom_processes/dam_t_sol_air_heat_flux_process.hpp
> +        KRATOS_WATCH(mTableId)
Missing KRATOS_WATCH

2017-09-30 07:32 UTC, rubenzorrilla commented on applications/DamApplication/custom_processes/dam_t_sol_air_heat_flux_process.hpp
> +                double heat_flux = mH0*(t_sol_air - temp_current);
These two variables can be const.

2017-09-30 08:40 UTC, lorenzogracia commented
Hi Ruben, thank you for your comments. I have done a commit with the requested changes.

2017-09-30 11:09 UTC, ipouplana approved these changes

2017-10-01 09:52 UTC, rubenzorrilla approved these changes

2017-10-01 10:22 UTC, merged

2017-10-02 13:54 UTC, pooyan-dadvand commented on applications/DamApplication/custom_processes/dam_t_sol_air_heat_flux_process.hpp
> +                "absortion_index"                 : 0.0,
@lorenzogracia I think the absorption is misspelled here...

2017-10-02 13:54 UTC, pooyan-dadvand commented on applications/DamApplication/custom_processes/dam_t_sol_air_heat_flux_process.hpp
> +    double mAbsortion_index;
Here Also

2017-10-03 08:09 UTC, lorenzogracia commented on applications/DamApplication/custom_processes/dam_t_sol_air_heat_flux_process.hpp
> +    double mAbsortion_index;
Thanks @pooyan-dadvand, I will change them.