[MPM] Change default dynamic scheme from Bossak to UNSPECIFIED
KratosMultiphysics/Kratos pull request #8054
Opened 2021-01-11 05:39 UTC by peterjwilson

**Description**
Change the default MPM implicit dynamic solver scheme to 'UNSPECIFIED'. This at least forces the use the choose the time-stepping algorithm, instead of having one chosen for them and them possibly assuming they are using another!

**A story of my misery**
Once upon a time, a Newmark lover much desired to use average acceleration implicit MPM to model great things, however, his results did not make sense. After much investigation, he found the evil Bossak had infiltrated and corrupted his model, unbeknownst to him.

2021-01-11 05:44 UTC, tteschemacher approved these changes
You get an approve only for that beautiful text. I do not really care about the rest 💯

2021-01-11 05:50 UTC, VeronikaSinger commented
I agree to change the default value :)

2021-01-11 08:31 UTC, rubenzorrilla requested changes
This is what the defaults are intender for. If you want to make sure that the user knows about the time scheme that is to be used throw a warning if this is not provided.

Note that this change goes in the opposite direction as the rest of Kratos solvers. The idea is that non-experienced users can run a simulation by just providing a very few mandatory fields.

2021-01-12 00:15 UTC, peterjwilson commented
> 
> 
> This is what the defaults are intender for. If you want to make sure that the user knows about the time scheme that is to be used throw a warning if this is not provided.
> 
> Note that this change goes in the opposite direction as the rest of Kratos solvers. The idea is that non-experienced users can run a simulation by just providing a very few mandatory fields.

No worries @rubenzorrilla, I get what you mean - I'll just leave it as it is and close this PR shortly (this is not my hill to die on 😄 ). Here's some points you (and maybe the tech committee) may want to consider moving forward:
1. I agree printing warnings is good, but 99% of the time they are buried in a massive log. I'm pretty sure most people don't meticulously scour the console log once their job is complete. One idea would be to collect all warnings during the sim and re-print them at the end so they are in the user's face (maybe this is already in the pipeline).
2. For beginners, I understand that just getting a simulation running is important too without wading through heaps of "UNSPECIFIED" errors - that's a good point. However, I don't think Bossak damping should be the default without the user knowing (point 1), especially if they haven't explicitly specified damping. Maybe this is just a difference of opinion here. By the way, the structural mechanics uses Bossak as the default too.
3. Solvers are different to time integrators and they don't necessarily have to follow the same philosophy: the choice of solver should not change the solution (just how fast it is reached) while using different time integrators will invariably alter the solution. A beginner using a mystery solver chosen for them is different to them using mystery damping without them knowing.

2021-01-12 17:53 UTC, rubenzorrilla commented
> > This is what the defaults are intender for. If you want to make sure that the user knows about the time scheme that is to be used throw a warning if this is not provided.
> > Note that this change goes in the opposite direction as the rest of Kratos solvers. The idea is that non-experienced users can run a simulation by just providing a very few mandatory fields.
> 
> No worries @rubenzorrilla, I get what you mean - I'll just leave it as it is and close this PR shortly (this is not my hill to die on smile ). Here's some points you (and maybe the tech committee) may want to consider moving forward:
> 
>     1. I agree printing warnings is good, but 99% of the time they are buried in a massive log. I'm pretty sure most people don't meticulously scour the console log once their job is complete. One idea would be to collect all warnings during the sim and re-print them at the end so they are in the user's face (maybe this is already in the pipeline).
> 

Totally agree. Actually I really like your idea. I also think it should be technically possible if such warning messages are managed by the logger. However I'm afraid of the performance affectation, specially if the warnings rise from the elements/conditions. 

>     2. For beginners, I understand that just getting a simulation running is important too without wading through heaps of "UNSPECIFIED" errors - that's a good point. However, I don't think Bossak damping should be the default without the user knowing (point 1), especially if they haven't explicitly specified damping. Maybe this is just a difference of opinion here. By the way, the structural mechanics uses Bossak as the default too.
> 

Also the fluid uses the Bossak by default. For me it's good that by default the eventual high frequencies are damped (I think it's safer than not doing so). In any case, I'm far from being an expert on dynamics so please don't take this as a super strong assertion.

If you guys think that the Bossak doesn't suit your MPM needs, you could set the Newmark as default, but for such field I think it is important to provide something.

>     3. Solvers are different to time integrators and they don't necessarily have to follow the same philosophy: the choice of solver should not change the solution (just how fast it is reached) while using different time integrators will invariably alter the solution. A beginner using a mystery solver chosen for them is different to them using mystery damping without them knowing.

This depends on what you understand by solver... (the solver border has been always a blurry thing in Kratos :smile:). In any case your point is fair to me as well: "should we provide defaults for those fields affecting the final solution? (even though without these a simulation can't be run)" IMO, yes but I think it still worth it to discuss it.

Would you mind opening two issues, one with the warning log and one with the defaults stuff to have some feedback from the community? (please also assign them to the @KratosMultiphysics/technical-committee so we can discuss it in a future meeting).

Thanks!

2021-01-13 08:12 UTC, pooyan-dadvand commented
I agree with @rubenzorrilla about having a default that suits well your problem. The solver should run in its optimum way by its defaults. 

About showing the warnings at the end is a good idea and also technically possible.

2021-01-13 23:22 UTC, peterjwilson commented
Looks like we all agree on the main points @rubenzorrilla @pooyan-dadvand and the others are just differences of opinion (which, of, course, I'll defer to the Kratos masters 😄 ) - thanks for the discussion!

2021-01-13 23:22 UTC, closed without merging

2022-08-05 11:34 UTC, loumalouomega commented
@peterjwilson do we still need this branch?, can we delete it?