[Core] Adding new test looking for error in #8096
KratosMultiphysics/Kratos pull request #8112
Opened 2021-01-20 12:45 UTC by loumalouomega

**Description**
Trying to find the error from #8096. I added a new test that works in OMP. I do not know how to trigger the problem. In theory, it appeared when the DOF was only in the MPC but not in the element. This small test does that but does not trigger the problem, any idea why? @emiroglu 

**Changelog**
- New MPC test

2021-01-20 13:44 UTC, emiroglu commented
It could be because there is only one `LinearMasterSlaveConstraint` defined on the "orphan" slave node. The [loop](https://github.com/KratosMultiphysics/Kratos/blob/7f61ff8d43086adee6112bb140d32850649a2782/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1165-L1172) in `ApplyConstraints` is executed only once which does not allow another thread to try to access the matrix at the same time. In #8096 the slave node is a slave to multiple master nodes.

2021-01-20 13:48 UTC, emiroglu requested changes
This should trigger

2021-01-20 13:48 UTC, emiroglu commented on kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp
> +                rModelPart.CreateNewNode(4, 3.0, 0.0, 0.0);
rModelPart.CreateNewNode(5, 4.0, 0.0, 0.0);

2021-01-20 13:48 UTC, emiroglu commented on kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp
> +                }
auto pnode5 = rModelPart.pGetNode(5);
                    rModelPart.CreateNewMasterSlaveConstraint("LinearMasterSlaveConstraint", 2, *pnode3, DISPLACEMENT_X, *pnode5, DISPLACEMENT_X, 1.0, 0.0);

2021-01-20 13:55 UTC, loumalouomega commented on kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp
> +                rModelPart.CreateNewNode(4, 3.0, 0.0, 0.0);
Oki doki

2021-01-20 13:57 UTC, loumalouomega commented on kratos/tests/cpp_tests/strategies/builder_and_solvers/test_builder_and_solver.cpp
> +                }
Oki doki

2021-01-20 15:32 UTC, emiroglu approved these changes
OK from my side

2021-01-20 17:01 UTC, loumalouomega commented
For some reason the RANS test are failing due to timeout... @sunethwarna

2021-01-20 17:03 UTC, philbucher commented
I think the CI is just overall slow today (I haven't checked if github has any issues)
I also had to several times restart some runs

2021-01-20 17:15 UTC, sunethwarna commented
Then I'll wait maybe untill tomorrow @loumalouomega . If this still persists, I'll check it. :) Would that be ok?

2021-01-21 09:19 UTC, merged

2021-01-21 09:19 UTC, loumalouomega commented
> Then I'll wait maybe untill tomorrow @loumalouomega . If this still persists, I'll check it. :) Would that be ok?

False alarm