[Core][Structural] improve performance of Damping
KratosMultiphysics/Kratos pull request #8252
Opened 2021-02-09 09:29 UTC by philbucher

**Description**
This PR proposes to add a new method to `Element` and `Condition`: The Calculation of the Damping Matrix with precomputed LHS and MassMatrix

Motivation:
In structural problem often (for us: always) Rayleigh damping is used to calculate the damping matrix: `D = a*M + b*K`
This requires the Stiffness- and the MassMatrix. Unfortunately the current interfaces don't allow the passing of these matrices even if they are available (see the scheme I updated). Hence they have to be computed again, which is quite expensive.

Hence I am proposing the addition of a new method with which the Striffness- and MassMatrix can be used directly without having to be recomputed.
I made the necessary minimal changes and ported one element such that one can fully understand my intentions

FYI @KlausBSautter

2021-02-09 09:49 UTC, AlejandroCornejo commented
This reminds me that currently in Kratos the damping is computed with the tangent stiffness matrix (**K**) instead of with the **K_o** (initial stiffness) and this add a non-linearity to the system in dynamic calculations (in the literature **K0** is used). Maybe this can solve the problem

2021-02-09 09:53 UTC, philbucher commented
> This reminds me that currently in Kratos the damping is computed with the tangent stiffness matrix (**K**) instead of with the **K_o** (initial stiffness) and this add a non-linearity to the system in dynamic calculations (in the literature **K0** is used). Maybe this can solve the problem

This is a similar issue, I though of it while doing this

Unfortunately I could still not come up with  a good way of storing the damping matrix.

2021-02-09 10:01 UTC, philbucher commented
BTW @AlejandroCornejo do you have a reference for computing the damping matrix only once?
I would like to read up on this too so that I could get some more ideas how to implement it properly

2021-02-09 10:03 UTC, KlausBSautter commented
> This reminds me that currently in Kratos the damping is computed with the tangent stiffness matrix (**K**) instead of with the **K_o** (initial stiffness) and this add a non-linearity to the system in dynamic calculations (in the literature **K0** is used). Maybe this can solve the problem

This would also be a nice performance increase

2021-02-09 13:08 UTC, loumalouomega approved these changes
Okay

2021-11-15 09:46 UTC, pooyan-dadvand requested changes
@KratosMultiphysics/technical-committee feels that scheme is a better place to do Rayleigh damping implemented. 

Is there a special reason to have this one in element instead of in Scheme?

2021-11-15 09:49 UTC, loumalouomega commented
> Is there a special reason to have this one in element instead of in Scheme?

It has been always like that (besides, scheme does not know anything about the physics of the problem itself, and for that reason the element could be more suited)

2021-11-15 10:12 UTC, philbucher commented
> > Is there a special reason to have this one in element instead of in Scheme?
> 
> It has been always like that (besides, scheme does not know anything about the physics of the problem itself, and for that reason the element could be more suited)

I have the same POV. 

What @KratosMultiphysics/technical-committee suggest can be done, but it is a very large change, that, speaking from experience, will not be done

2021-12-28 16:08 UTC, AlejandroCornejo commented
> BTW @AlejandroCornejo do you have a reference for computing the damping matrix only once? I would like to read up on this too so that I could get some more ideas how to implement it properly

BTW, what if we recompute the Damping matrix according to the initial configuration always? It reminded me the `use_old_stiffness_in_first_iteration ` that @RiccardoRossi implemented in the BuilderAndSolver. You could use the same idea but not in the previous conf whereas in the initial one...

2022-02-24 14:01 UTC, closed without merging