[Core] Remove warning in the ReadMaterialsUtility
KratosMultiphysics/Kratos pull request #8336
Opened 2021-02-18 17:05 UTC by riccardotosi

**Description**
In #8304, @rubenzorrilla proposed the following

> What I agree it that defining empty properties in the mdpa and then giving values in the materials.json is quite annoying. As this is always required in order to assign properties to elements in the preprocess, I'd only throw a warning if the properties in the mdpa are not empty.

This PR addresses this comment, removing the warning. I would like to remark that we are still warning users if we are overriding some values in [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/read_materials_utility.cpp#L44).

Let me know if I misunderstood something.

This PR closes #8304.

Please mark the PR with appropriate tags: 
- Kratos Core

**Changelog**
Please summarize the changes in one list to generate the changelog:
- Removed a warning, as proposed in #8304.

2021-02-18 17:12 UTC, philbucher requested changes
I do not agree with this change, as I said earlier this was added after trying to figure out where the issue was
To me this warning is valid, if you have properties in your materials file that already exist in the ModelPart it should issue a warning

also mentioning @armingeiser who was the one with the issues, maybe he can also comment

@riccardotosi can you explain again the issue you have? I thought it was solved?

2021-02-18 17:19 UTC, riccardotosi commented
Right now, I define properties in my mdpa as
~~~
Begin Properties 0

End Properties
~~~
and my materials file as
~~~json
{
    "properties" : [{
        "model_part_name" : "MainModelPart",
        "properties_id"   : 0,
        "Material"        : {
            "Variables"        : {
                "DENSITY"       : 1.0,
                "CONDUCTIVITY"  : 1.0,
                "SPECIFIC_HEAT" : 1.0
            },
            "Tables"           : {}
        }
    }]
}
~~~

When running, I get this warning
~~~bash
[WARNING] ReadMaterialsUtility: WARNING:: The properties ID: 0 in mesh ID: 0 is already defined. This will overwrite the existing values
~~~

I get this warning many times, since I am running a MC algorithm.
What we discussed on removed this type of warnings:
~~~bash
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has CONDUCTIVITY.
Overwriting 1 with 1
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has DENSITY.
Overwriting 1 with 1
[WARNING] ReadMaterialsUtility: The properties ID: 1 already has SPECIFIC_HEAT.
Overwriting 1 with 1
~~~

2021-02-18 17:26 UTC, armingeiser commented
The issue was, that there is no way to check if the property 0 from the mdpa file already has the parameters you are going to set, or not. Thats why the only way to know if you are going to overwrite somethign that may have existed already in the mdpa file, ist to throw a warning when the ReadMaterialsUtility checks if the property is already there. 

Simple solution to avoid the warning, is to use another property id in the material settings json, since the property will be created and assigned by model part, not by the property id that was used to create the elements/condition in the mdpa.

2021-02-18 17:42 UTC, rubenzorrilla commented
I want to clarify that this is not what I meant. I totally agree @philbucher and @armingeiser in here.

What I meant in my previous comment is that the warning should be issued only in case the properties in the mpda are not empty. To clearly state that the json material properties will overwrite those values in the mdpa. These changes do not yield such behavior.

2021-02-18 17:42 UTC, riccardotosi commented
Isn't it better to throw an Info, rather than a warning? Warning makes me think something is bad and should be improved.

2021-02-18 17:52 UTC, armingeiser commented
In my opinion the definition of the same property in multiple places should not be allowed. This can easily lead to confusion when setting up a case and running it with wrong material parameters without knowing. Thats why i prefer the warning but thats just my opinion. 

(Maybe a bad example: But defining a node with the same id twice in the input leads to an error, instead of just updating the coordinates)

Ideally we could figure out if the property that is going to be assigned by the ReadMaterialsUtility is empty in case it already exists. If so, the warning here could be ommited. But as far as i remember, that is not possible.

2021-02-19 07:56 UTC, riccardotosi commented
It seems a bit counterintuitive to me to use empty properties and then a materials file with **different** propertiy Id to avoid warnings. However, if this is the standard behavior to avoid the warning, I have nothing against it nor I want to create particular issues.

If you agree with what I comment, I can post this solution in the issue I opened and close it.

2021-02-22 08:49 UTC, closed without merging

2021-02-22 13:49 UTC, philbucher commented
> It seems a bit counterintuitive to me to use empty properties and then a materials file with **different** propertiy Id to avoid warnings. However, if this is the standard behavior to avoid the warning, I have nothing against it nor I want to create particular issues.
> 
> If you agree with what I comment, I can post this solution in the issue I opened and close it.

Having to declare empty properties is kinda legacy since the mdpa format requires to have properties associated with Elements& Conditions
The materials file was created/introduced much later

I agree that it is not the best solution, but I think we cannot change this easily

In structural usually the mdpa has Properties ID 0 and then the Materials file contains Properties with ID > 0