[StructuralMechanicsApplicatin] Adding factories to strategies
KratosMultiphysics/Kratos pull request #8660
Opened 2021-04-21 16:32 UTC by loumalouomega

**Description**
Adding factories to strategies (not used yet)

**Changelog**
- Adding Factories to strategies
- Adding Parameters constructors
- Adding Parameters methods (Default/Assign)
- Some clean up

2021-04-22 07:31 UTC, philbucher commented
lets hold this until #8654 is solved, I am not sure if there are still some fundamental issues

2021-04-22 07:34 UTC, philbucher requested changes
please separate the new constructors from the adding of factories

there are already some problems and I don't want to introduce more

sorry :/

2021-04-22 07:34 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/eigensolver_strategy.hpp
> +                "stiffness_matrix_diagonal_value" : 0.0
those are wrong, check the eigensolver (python)

2021-04-22 07:34 UTC, philbucher commented on applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/eigensolver_strategy.hpp
> +                auto p_linear_solver = LinearSolverFactoryType().Create(ThisParameters["linear_solver_settings"]);
this is wrong, an eigensolver is needed here, and this factory doesn't exist yet in cpp

2023-06-16 08:27 UTC, pooyan-dadvand commented
@KratosMultiphysics/technical-committee thinks that we should close this PR and use the new registry mechanism to register the entities and then create the factories based on the registered entities

2023-06-19 08:24 UTC, loumalouomega commented
> @KratosMultiphysics/technical-committee thinks that we should close this PR and use the new registry mechanism to register the entities and then create the factories based on the registered entities

Any example how to do that?

2024-10-17 11:58 UTC, loumalouomega commented
Should I close this or adapt it to new registry? @rubenzorrilla

2024-10-22 06:25 UTC, rubenzorrilla commented
> Should I close this or adapt it to new registry? @rubenzorrilla

We should definitively use the new registry for such purposes. In this particular case, maybe it's easier to close this one and create a new "registry-based" branch. This is up to you.

2024-10-22 06:34 UTC, loumalouomega commented
> > Should I close this or adapt it to new registry? @rubenzorrilla
> 
> We should definitively use the new registry for such purposes. In this particular case, maybe it's easier to close this one and create a new "registry-based" branch. This is up to you.
> 
> EDIT: In any case, and considering that we are to change the strategies, I'd leave this in standby for a while...

In any case I think https://github.com/KratosMultiphysics/Kratos/pull/8672 is still valid

2024-10-22 06:34 UTC, closed without merging