[PfemFluid] New FS  strategies and elements
KratosMultiphysics/Kratos pull request #8970
Opened 2021-07-15 07:26 UTC by AFranci

A new 3-step v-p strategy has been added. This and the old 2-step v-p strategy derives from a general v-p strategy. The required elements have also added. The PR has also an extended cleaning to avoid warnings in compilation.

2021-07-15 07:59 UTC, AlejandroCornejo requested changes
A lot of comments just to let you know a few easy optimizations that really pay off

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_meshers/triangular_mesh_2D_mesher.cpp
> +    //   std::cout<<" [ MESH GENERATION (TIME = "<<end_time-begin_time<<") ] "<<std::endl;
If not used it is advisabel to erased commented code

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/DelaunayMeshingApplication/custom_processes/build_model_part_boundary_process.hpp
> +        //   if( mEchoLevel >= 1 ){
IDEM

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/CMakeLists.txt
> +	${CMAKE_CURRENT_SOURCE_DIR}/custom_elements/two_step_updated_lagrangian_V_P_implicit_fluid_FIC_element.cpp
In order to avoid adding a lot of files one by one you can write:
`${CMAKE_CURRENT_SOURCE_DIR}/custom_constitutive/*.cpp`

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +//   Date:                $Date:               June 2021 $
This is the old header, I'd use the new one as in the ConstitutiveLawsApp.

~~~cpp
   ___  __                  ___ _       _     _    ___                             _          
  / _ \/ _| ___ _ __ ___   / __| |_   _(_) __| |  /   \_   _ _ __   __ _ _ __ ___ (_) ___ ___ 
 / /_)| |_ / _ | '_ ` _ \ / _\ | | | | | |/ _` | / /\ | | | | '_ \ / _` | '_ ` _ \| |/ __/ __|
/ ___/|  _|  __| | | | | / /   | | |_| | | (_| |/ /_//| |_| | | | | (_| | | | | | | | (__\__ \
\/    |_|  \___|_| |_| |_\/    |_|\__,_|_|\__,_/___,'  \__, |_| |_|\__,_|_| |_| |_|_|\___|___/
                                                       |___/                                  

~~~

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +//   Implementation of the Gauss-Seidel two step Updated Lagrangian Velocity-Pressure element
This is just curiosity, which is the main advantage of using a 3 step approach?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      rLeftHandSideMatrix.resize(LocalSize, LocalSize);
`rLeftHandSideMatrix.resize(LocalSize, LocalSize, false);` is much faster

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    rRightHandSideVector = ZeroVector(LocalSize);
use noalias, much faster

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      rRightHandSideVector.resize(LocalSize);
`(Localsize, false)`

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    if (schemeOrder == 2)
as far as I've understood, this if is always triggered... Why putting it?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      const ShapeFunctionsType &N = row(NContainer, g);
`r_N` according to style criterion

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      double OldPressure = 0.0;
should be snake_case: `old_pressure` since it is a local variable

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +          for (SizeType d = 0; d < TDim; ++d)
the for's should be:
~~~c++
for (----) {
    (code)
}
~~~
According to style

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +        array_1d<double, 3> &rTemp = rGeom[i].FastGetSolutionStepValue(FRACT_VEL);
snake case

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +  // void TwoStepUpdatedLagrangianVPImplicitElement<2>::ComputeCompleteTangentTerm(ElementalVariables &rElementalVariables,
this commented block is necessary?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +        double Mij = Weight / Coeff;
can be `const double` ? snake case also

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    // ElementalVariables rElementalVariables;
remove commented

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    rLeftHandSideMatrix = ZeroMatrix(NumNodes, NumNodes);
noalias

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    rRightHandSideVector = ZeroVector(NumNodes);
noalias

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      rRightHandSideVector.resize(NumNodes);
resize(Num, false)

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      // MatrixType BulkMatrixConsistent = ZeroMatrix(NumNodes, NumNodes);
remove commented code?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      // this->GetOutwardsUnitNormalForTwoPoints(NormalVector, 1, 2, 0);
more commented

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      // KRATOS_WATCH("1st oder AccA= ");
remove kratos watch ?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      // noalias(AccA) = timeFactor * (rGeom[1].FastGetSolutionStepValue(VELOCITY, 0) - rGeom[1].FastGetSolutionStepValue(VELOCITY, 1)) - rGeom[1].FastGetSolutionStepValue(ACCELERATION, 1);
IDEM

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +      std::cout << "... ComputeBulkMatrixLump TO IMPLEMENT" << std::endl;
not better a `KRATOS_ERROR`?

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    // double timeScale = 0.5 * (ElemSize / (2 * MeanVelocity) + DeltaTime);
idem

2021-07-15 07:59 UTC, AlejandroCornejo commented on applications/PfemFluidDynamicsApplication/custom_elements/three_step_updated_lagrangian_element.cpp
> +    //     for (SizeType d = 0; d < TDim; ++d)
👯 idem

2021-07-16 06:40 UTC, AlejandroCornejo approved these changes
good, are you planning to add a test of the new elements?

2021-07-16 06:43 UTC, AFranci commented
> good, are you planning to add a test of the new elements?

yes, for sure.. now it is still under development. As soon as I have it finished, I will add a test and make the element accessible from the GiD interface!

2021-07-16 06:43 UTC, merged