[Structural] allow usage of SubModelPart for ComputingModelPart
KratosMultiphysics/Kratos pull request #9139
Opened 2021-09-21 09:03 UTC by philbucher

This PR allows to use a SubModelPart as the ComputingModelPart in the Structural Solvers.

I thought some days about this and agree with the reasoning in #9130 about this being a valid usecase.

This solution is minimally intrusive, as suggested by @pablobecker. Ofc this is not mutually exclusive with the other solutions proposed in #9130

@pablobecker if this solution looks good to you, can you please test it with your usecase and if possible also add a small test?

closes #9130 

**Note**: This has nothing to do with the nasty ComputingModelPart that we had in the past (which was awkwardly constructed by creating a separate SubModelPart based on a list of SubModelPart-Names)
This PR allows to pass an EXISTING (aka defined in e.g. the mdpa) SubModelPart to the Strategy & B&S instead of the RootModelPart

2021-09-21 09:25 UTC, loumalouomega approved these changes
Ok from my side

2021-09-21 11:46 UTC, pablobecker commented
let me check if this works for us

2021-09-29 10:54 UTC, philbucher commented
ping @pablobecker

2021-09-29 12:07 UTC, rubenzorrilla commented
I wonder if we should implement this in the base `python_solver.py`. This would be a first step towards the standarization of the computing model part behavior.

2021-09-29 12:20 UTC, philbucher commented
> I wonder if we should implement this in the base `python_solver.py`. This would be a first step towards the standarization of the computing model part behavior.

No, the `ComputingModelPart` is an implementational detail of solvers that use only one ModelPart. It is only in the public interface for historical reasons

2021-09-29 12:46 UTC, rubenzorrilla commented
> > I wonder if we should implement this in the base `python_solver.py`. This would be a first step towards the standarization of the computing model part behavior.
> 
> No, the `ComputingModelPart` is an implementational detail of solvers that use only one ModelPart. It is only in the public interface for historical reasons

This might solve problems when doing volumetric coupling but might also be misleading when doing interface coupling. So yours is a fair argument. My point was that the behavior proposed in here is in my opinion the most common one, so we might want to adopt it as default to avoid copying and pasting it in all the derived solvers.

2021-09-29 13:44 UTC, philbucher commented
> This might solve problems when doing volumetric coupling but might also be misleading when doing interface coupling.

how is this related? I don't understand

> My point was that the behavior proposed in here is in my opinion the most common one, so we might want to adopt it as default to avoid copying and pasting it in all the derived solvers.

Not sure. In fact I only know two solvers where this can be used: Structural and ConDiff, all other solvers use other solutions for this. E.g. MPM, DEM, FSI, CoSim use multiple ModelParts, Fluid creates a custom SubModelPart, ...

2021-09-29 14:06 UTC, rubenzorrilla commented
My point was that in some cases we create the computing model part only because historical or preprocessing issues, and, in some cases it is possible to get rid of it (see the recent `ConvectionDiffusionApplication` case). Ideally, I'd like to only override this when it is strictly necessary (e.g. FSI).

In any case I was just pointing this out. Of course this discussion is out of the scope of this PR (lets ignore my comment for the moment).

2021-10-18 15:26 UTC, philbucher commented
ping @pablobecker

2021-11-26 09:54 UTC, philbucher commented
ping @pablobecker @KratosMultiphysics/altair is this still under review?
Otherwise I would merge it, I think it is a good enhancement

2021-11-26 14:26 UTC, pablobecker commented
Hi Phil, 
sorry, forgot to get back to this one.
I looks ok to me, with this change the system would be solved only on the ComputingModelPart only, which is what I needed.
However , if I recall correctly @pooyan-dadvand told me (while talking, so I cant search it now) that there could be some issues if implemented like this. Would you mind waiting till monday to merge this, so that he can take a look? (he's off today)
thank you

2021-11-26 15:47 UTC, philbucher commented
@pablobecker sure let me know :)

2021-11-29 14:37 UTC, pooyan-dadvand requested changes
I don't remember what was my concern about this...

2021-11-29 14:37 UTC, pooyan-dadvand commented on applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py
> +            computing_model_part_name = self.main_model_part.Name + "." + computing_sub_model_part_name
I would have used the complete path as compute model part and would only check if it is a sub of main model part rather than going only one step down

2021-11-29 15:17 UTC, philbucher commented on applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py
> +            computing_model_part_name = self.main_model_part.Name + "." + computing_sub_model_part_name
not sure I follow what you mean
You can already use now any SubSubSubSubSub...ModelPart
e.g. given you have the ModelPart hierarchy `Main.AA.BB.CC`
when setting `AA` then the `AA` SubModelPart will be used as ComputingMP
when setting `AA.BB` then the `BB` SubSubModelPart will be used.
when setting `AA.BB.CCC` then the `CC` SubSubSubModelPart will be used. And so on ...

The only thing that is enforced is that the ComputingMP is a Sub...ModelPart of the MainModelPart used by the solver

2021-11-29 15:29 UTC, pooyan-dadvand commented on applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py
> +            computing_model_part_name = self.main_model_part.Name + "." + computing_sub_model_part_name
Now I see. You are right!

2021-11-29 15:30 UTC, pooyan-dadvand approved these changes
:+1:

2021-11-29 15:33 UTC, merged