[Fluid][SDEM] Redefine manufactured solution
KratosMultiphysics/Kratos pull request #9168
Opened 2021-09-30 13:09 UTC by jgonzalezusua

**Description**
There are some objectives of this PR:

- Include the Drew's formulation for flows in porous media using the VMS framework.
- Implement Dallavalle's drag law to simulate dense-packed beds.
- Including more manufactured solutions: hyperbolic tangential and sinusoidal.
- Implement a new diffusion-based coarse graining function.

Please mark the PR with appropriate tags: 
- Applications
- Feature

**Changelog**
The changes made in this PR are the following:

- Implement two new elements using the Drew's formulation: `alternative_qs_vms_dem_coupled.cpp` and  `alternative_d_vms_dem_coupled.cpp`.
- Modify `bdf2_turbulent_schemeDEMCoupled.h` to update the residual projection before calculation and the subscale after it.
- Including a bool to project the body force depending on the type of model used (Drew or Jackson) in `binbased_DEM_fluid_coupled_mapping.cpp`.
- Changing the coarse graining function in `density_function_polynomial.h`, now its integral is equal to 1 and its derivatives in the boundaries are 0.
- Call to the particle instead of the node in the drag laws.
- Removing computation of the manufactured solution at each time step when they are not time dependant.

2021-09-30 13:54 UTC, rubenzorrilla requested changes
This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.

2021-09-30 13:59 UTC, jgonzalezusua commented
> This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.

It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.

2021-09-30 14:09 UTC, rubenzorrilla commented
> > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> 
> It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.

I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.

2021-09-30 14:14 UTC, jgonzalezusua commented
> > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > 
> > 
> > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> 
> I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.

The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.

2021-09-30 14:16 UTC, rubenzorrilla commented
> > > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > > 
> > > 
> > > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> > 
> > 
> > I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.
> 
> The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.

mmm... it is strange. The changes in the `FluidDynamicsApplication` must compile without the `SwimmingDEMApplication`. Otherwise there would be a dependency in the other way around.

2021-09-30 14:16 UTC, philbucher commented on applications/FluidDynamicsApplication/custom_elements/fluid_element.h
> +    virtual void GetFirstDerivativesVector(Vector& Values, int Step = 0) const override;
Please don’t add this, it is superfluous and clang format warns abt this
See https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html

2021-09-30 14:18 UTC, jgonzalezusua commented
> > > > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > > > 
> > > > 
> > > > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> > > 
> > > 
> > > I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.
> > 
> > 
> > The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.
> 
> mmm... it is strange. The changes in the `FluidDynamicsApplication` must compile without the `SwimmingDEMApplication`. Otherwise there would be a dependency in the other way around.

Which is true, the problem is in the SDEM application. Some tests need the new elements.

2021-09-30 14:25 UTC, rubenzorrilla commented
> > > > > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > > > > 
> > > > > 
> > > > > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> > > > 
> > > > 
> > > > I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.
> > > 
> > > 
> > > The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.
> > 
> > 
> > mmm... it is strange. The changes in the `FluidDynamicsApplication` must compile without the `SwimmingDEMApplication`. Otherwise there would be a dependency in the other way around.
> 
> Which is true, the problem is in the SDEM application. Some tests need the new elements.

But that's precisely my point.
1. We create an auxiliary PR with the `FluidDynamicsApplication` changes. This must contain the at least a cpp test for the new elements. Otherwise it is impossible to check if something gets broken without compiling the `SwimmingDEMApplication`.
2. We review & merge the PR in 1
3. Merging the `master` in `Redefine-manufactured-solution` branch
4. We review & merge this PR.

2021-09-30 14:27 UTC, jgonzalezusua commented
> > > > > > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > > > > > 
> > > > > > 
> > > > > > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> > > > > 
> > > > > 
> > > > > I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.
> > > > 
> > > > 
> > > > The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.
> > > 
> > > 
> > > mmm... it is strange. The changes in the `FluidDynamicsApplication` must compile without the `SwimmingDEMApplication`. Otherwise there would be a dependency in the other way around.
> > 
> > 
> > Which is true, the problem is in the SDEM application. Some tests need the new elements.
> 
> But that's precisely my point.
> 
> 1. We create an auxiliary PR with the `FluidDynamicsApplication` changes. This must contain the at least a cpp test for the new elements. Otherwise it is impossible to check if something gets broken without compiling the `SwimmingDEMApplication`.
> 2. We review & merge the PR in 1
> 3. Merging the `master` in `Redefine-manufactured-solution` branch
> 4. We review & merge this PR.

Ok, understood. I will do that.

2021-09-30 14:43 UTC, philbucher reviewed
There are many more of these virtual, I pointed it out only in one place

2021-09-30 14:45 UTC, jgonzalezusua commented
> There are many more of these virtual, I pointed it out only in one place

Ok, dont worry, I will work on that

2021-09-30 15:00 UTC, rubenzorrilla commented
> > > > > > > > This PR is too large to be reviewed. I'd suggest to, at least, separate the `FluidDynamicsApplication` changes from the `DEMApplication` ones.
> > > > > > > 
> > > > > > > 
> > > > > > > It is true that the PR is large, but as a fluid maintainer you can focus only on the FluidDynamicsApplications, most of the changes are related to the implementation of two new elements. The rest of the files can be reviewed by the DEM team.
> > > > > > 
> > > > > > 
> > > > > > I insist. In case something gets broken it would be very difficult and complex to backtrack the changes and eventually revert. Considering that it is straightforward to port the changes to from this branch to a new one (create a new branch, switch to it and do `git checkout Redefine-manufactured-solution my_fluid_file.cpp` for the files in the `FluidDynamicsApplication`) I'd appreciate doing the merge in such way. Then you just need to merge the master in here once the auxiliary PR is finished.
> > > > > 
> > > > > 
> > > > > The key problem is that I am working in the SwimmingDEMApplication which derives in part from the FluidDynamicsApplication. I need to merge the changes in the fluid application together with the rest of the PR.
> > > > 
> > > > 
> > > > mmm... it is strange. The changes in the `FluidDynamicsApplication` must compile without the `SwimmingDEMApplication`. Otherwise there would be a dependency in the other way around.
> > > 
> > > 
> > > Which is true, the problem is in the SDEM application. Some tests need the new elements.
> > 
> > 
> > But that's precisely my point.
> > 
> > 1. We create an auxiliary PR with the `FluidDynamicsApplication` changes. This must contain the at least a cpp test for the new elements. Otherwise it is impossible to check if something gets broken without compiling the `SwimmingDEMApplication`.
> > 2. We review & merge the PR in 1
> > 3. Merging the `master` in `Redefine-manufactured-solution` branch
> > 4. We review & merge this PR.
> 
> Ok, understood. I will do that.

Cool. Just let me know if you have any issue. Thanks!!! :rocket:

2021-10-05 16:19 UTC, rubenzorrilla approved these changes, later dismissed
No more concerns from the fluid side. I let the @KratosMultiphysics/dem guys to give the final approval.

2021-10-06 16:24 UTC, maceligueta approved these changes
No problems from my side

2021-10-06 16:24 UTC, maceligueta requested changes

2021-10-06 16:24 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_constitutive/drag_laws/chien_drag_law.cpp
> +        Geometry<Node<3> > r_geometry = p_particle->GetGeometry();
reference here?

2021-10-06 16:27 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +    double &r_nu = mViscosity;
why this alias? you could use mViscosity directly everywhere...

2021-10-06 16:28 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +    double &permeability = mPermeability;
why this alias?

2021-10-06 16:28 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +    double L = mLength;
Why alias?

2021-10-06 16:29 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/transient_spatial_dependant_porosity_solution_body_force_process.cpp
> +    double &permeability = mPermeability;
Alias (reference)

2021-10-07 08:34 UTC, jgonzalezusua commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +    double &r_nu = mViscosity;
Leftlover, I forgot to remove it

2021-10-07 15:36 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_hyperbolic_tangential_porosity_solution_and_body_force_process.cpp
> +    const double u_char = mUchar;
here too

2021-10-07 15:38 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_transient_body_force_process.cpp
>          const double x2 = it_node->Y();
These two could be a const reference instead of a copy, your call

2021-10-07 15:39 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_transient_body_force_process.cpp
> +
const if possible, not sure if you are changing these values

2021-10-07 15:39 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_transient_body_force_process.cpp
>          const double x2 = it_node->Y();
ref?

2021-10-07 15:40 UTC, maceligueta commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_sinusoidal_porosity_solution_and_body_force_process.cpp
> +        const double x2 = it_node->Y();
ref maybe

2021-10-07 15:41 UTC, maceligueta submitted a review, later dismissed
I am approving because my proposed changes do not affect performance, I think. It is your call to modify those lines and similar, or not.

2021-10-08 12:35 UTC, maceligueta submitted a review, later dismissed

2021-10-13 10:21 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_constitutive/drag_laws/dallavalle_drag_law.cpp
> +// Date: April 2021
Please, add a short comment metnioning the origin of the formulation (academic paper) along with any changes or errata corrections with respect to the original source.

2021-10-13 10:28 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_hyperbolic_tangential_porosity_solution_and_body_force_process.cpp
> +//    ' /   __| _` | __|  _ \   __|
Please, change the name of the process to something more exactly descriptive. Example: hyperbolic_tangent_porosity_solution_and_body_force_process.cpp
(I would skip the 'spatially_dependant' prefix, since it can be assumed to be virtually always)

2021-10-13 10:31 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +
Please add comments identifying the python code with which the hard-coded formulas where derived.

2021-10-13 10:35 UTC, jgonzalezusua commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_porosity_solution_and_body_force_process.cpp
> +
The python code is external from Kratos

2021-10-13 10:36 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_processes/spatial_dependant_sinusoidal_porosity_solution_and_body_force_process.cpp
> +//   _|\_\_|  \__,_|\__|\___/ ____/
same comment about referring the python code from which the formulas are derived

2021-10-13 10:40 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_utilities/binbased_DEM_fluid_coupled_mapping.cpp
> +    bool use_drew_model)
all these parameters should me moved to a Parameters object. For the future.

2021-10-13 10:50 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_utilities/custom_functions.h
> +    if (std::abs(vol) == 0.0){
I would prefer to leave it imprecise: it is not going to be exactly zero. Better to normalize the volume first by the size of the element cubed and then check with the epsilon. That is,
`if (std::abs(vol)/std::pow(h, 3) < std::numeric_limits<double>::epsilon())`
where
`const double h = CalculateDiameter(x0, y0, z0, x1, y1, z1, x2, y2, z2, x3, y3, z3)`
And where the diameter is easily computed as the maximum of the distances between pairs of points of the geometry.

2021-10-13 10:51 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_utilities/mollification/density_function_polynomial.h
> +        double weight = nodal_areas[i] * (m6 * radius_2 * radius_2 * radius_2 + m6*m2*radius_2 + m0);
use std::pow now that you are add it

2021-10-13 10:52 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/apply_spatial_dependant_hyperbolic_tangential_porosity_solution_and_body_force_process.py
> +# Importing the Kratos Library
the name of this process will be affected by the name changes above... There should be a better way, where you apply any 'solution_and_force' process from which the others derive. This can be left for the future too.

2021-10-13 10:53 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/fluid_fraction_test_analysis.py
> +        self.projector_post_process.WriteData(self.error_model_part, self.velocity_error_projected, self.pressure_error_projected, self.projection_type, self.model_type, self.subscale_type)
too long, take it to the next line

2021-10-13 10:55 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/hdf5_script.py
> +        self.spheres_model_part = spheres_model_part
This is too slow.. Please, predimension numpy arrays for this, do not append

2021-10-13 10:55 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/hdf5_script.py
> +                            names = ['id_particle', 'position_x', 'position_y', 'position_z', 'radius', 'drag_force_x', 'drag_force_y', 'drag_force_z', 'y', 'porosity', 'slip_velocity_x', 'slip_veloc
too long: use multiple lines

2021-10-13 10:55 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/hdf5_script.py
> +                            data = [self.id_particle, self.position_x, self.position_y, self.position_z, self.radius, self.drag_force_x, self.drag_force_y, self.drag_force_z, self.y, self.porosity, s
idem

2021-10-13 10:56 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/swimming_DEM_analysis.py
> +        return SDP.Counter(self.project_parameters["coupling"]["backward_coupling"]["backward_time_interval"].GetInt(), 1, self.project_parameters["coupling"]["coupling_level_type"].GetInt() > 1)
too long: take to next line

2021-10-13 10:58 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/variables_management.py
> +            self.coupling_fluid_vars += [SDEM.FLUID_FRACTION_OLDEST]
better use 'FLUID_FRACTION_OLD_2' or 'FLUID_FRACTION_OLD_OLD'

2021-10-13 10:59 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/tests/PorosityTestFactory.py
> +# Importing the Kratos Library
add brief explanation of what the test does

2021-10-15 14:46 UTC, jgonzalezusua commented on applications/SwimmingDEMApplication/python_scripts/hdf5_script.py
> +        self.spheres_model_part = spheres_model_part
This process was created to validate new drag force laws such as the Dallavalle's one. I think the performance of the `append` it is not important.

2021-10-15 15:05 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/python_scripts/hdf5_script.py
> +        self.spheres_model_part = spheres_model_part
Ok, but you must create a test for this Drag model in the future. When you do, please eliminate or modify this function.

2021-10-15 15:07 UTC, GuillermoCasas commented on applications/SwimmingDEMApplication/custom_constitutive/drag_laws/dallavalle_drag_law.cpp
> +// Date: April 2021
Please add author and year and check spelling

2021-10-15 15:17 UTC, GuillermoCasas submitted a review, later dismissed
Good job

2021-10-15 15:54 UTC, GuillermoCasas submitted a review, later dismissed

2021-10-15 16:28 UTC, ipouplana approved these changes

2021-10-15 17:23 UTC, merged