Temp bugfix, solved in the next PR
KratosMultiphysics/Kratos pull request #920
Opened 2017-10-27 09:50 UTC by philbucher

Fixes the problems in #915 

The test I uncommented is failing with the new processes, it was working with the deprecated ones.

I am trying to debug it, will most likely include it in another PR

the stuff uncommented in the cpp's is only needed for the composite laws which are anyway only added in #842

2017-10-28 17:56 UTC, RiccardoRossi commented
@loumalouomega can u take a look if it fixes #915 ?

2017-10-28 17:57 UTC, RiccardoRossi approved these changes
looks ok to me. Still i would like the green light of @loumalouomega

2017-10-29 21:05 UTC, RiccardoRossi commented
uff, i did some corrections and pushed a change. With that change all of the tests work in this branch.

2017-10-29 22:13 UTC, philbucher commented
Hi Riccardo 
It should fix #915, the tests on my machine passed in FullDebug

2017-10-30 09:19 UTC, loumalouomega requested changes

2017-10-30 09:19 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/tests/test_loading_conditions.py
> +<<<<<<< HEAD
Be careful, this is a conflict, remove it

2017-10-30 09:32 UTC, loumalouomega approved these changes

2017-10-30 09:44 UTC, loumalouomega requested changes
It doesn't compile

2017-10-30 09:44 UTC, loumalouomega commented
~~~
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_conditions/line_load_condition_2d.cpp: In member function ‘virtual void Kratos::LineLoadCondition2D::CalculateAll(Kratos::Condition::MatrixType&, Kratos::Condition::VectorType&, Kratos::ProcessInfo&, bool, bool)’:
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_conditions/line_load_condition_2d.cpp:228:38: error: ‘class Kratos::LineLoadCondition2D’ has no member named ‘CalculateAndAddWorkEquivalentNodalForcesLineLoad’
         if (this->HasRotDof()) this->CalculateAndAddWorkEquivalentNodalForcesLineLoad(gauss_load,rRightHandSideVector);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_conditions/line_load_condition_2d.cpp:228:87: error: ‘gauss_load’ was not declared in this scope
         if (this->HasRotDof()) this->CalculateAndAddWorkEquivalentNodalForcesLineLoad(gauss_load,rRightHandSideVector);
                                                                                       ^~~~~~~~~~
/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_conditions/line_load_condition_2d.cpp:228:87: note: suggested alternative: ‘getpayload’
         if (this->HasRotDof()) this->CalculateAndAddWorkEquivalentNodalForcesLineLoad(gauss_load,rRightHandSideVector);

~~~

2017-10-30 11:35 UTC, loumalouomega commented
@philbucher and @RiccardoRossi Travis can not compile too

2017-10-30 14:20 UTC, RiccardoRossi commented
ok, it passed now.

can u merge it? (if you agree)

2017-10-30 14:21 UTC, loumalouomega approved these changes

2017-10-30 14:21 UTC, loumalouomega commented
Ok

2017-10-30 14:21 UTC, merged