[Core] Extend triangle intersections
KratosMultiphysics/Kratos pull request #9217
Opened 2021-10-14 16:09 UTC by miguelmaso

**📝 Description**
My purpose is to extend the FindIntersectedGeometricalObjectsProcess to work with tretrahedras and lines. Those changes are enough. In addition, I have also extended it to quadrilaterals.

Some considerations:
- This PR could be shorter if  `intersection_utilities` is included in `Triangle3D3`, but ~~I've found a bug in `IntersectionUtilities::ComputeTriangleLineIntersection`. I should debug it deeper, but the link to the documentation is broken. That's why I've added the implementation in `Triangle3D3`. Moreover,~~ `HasIntersection` and `ComputeTriangleLineIntersection` are slightly different.
- The `OctreeBinary` has a lot of code duplication and dead code. I can make a fast PR with a clenaup proposal.

EDIT: there isn't any bug in `IntersectionUtilities::ComputeTriangleLineIntersection`, the point is that this function returns 2 for a co-planar line, which is evaluated to `true`. The algorithms are different. I can add some tests showing that behavior.

**🆕 Changelog**
- Extend the `Triangle3D3::HasIntersection` to lines and quadrilaterals.
- Add a new geometry type to the `OctreeBinary`

2021-10-15 10:16 UTC, philbucher commented on kratos/spatial_containers/octree_binary.h
> +        if (geometry_type == GeometryData::KratosGeometryType::Kratos_Line2D2 || geometry_type == GeometryData::KratosGeometryType::Kratos_Line3D2) { // Object is a line
maybe this fits better?
https://github.com/KratosMultiphysics/Kratos/blob/d42cfe13214a3fe701da9e65c7774a209ede836c/kratos/geometries/geometry_data.h#L90-L102

2021-10-15 10:41 UTC, miguelmaso commented on kratos/spatial_containers/octree_binary.h
> +        if (geometry_type == GeometryData::KratosGeometryType::Kratos_Line2D2 || geometry_type == GeometryData::KratosGeometryType::Kratos_Line3D2) { // Object is a line
not sure, I don't know what is the expected behavior with quadratic geometries.

It is better to use the `HasIntersection` method from the geometry. I have in mind to remove that, but in a separate PR:

> The `OctreeBinary` has a lot of code duplication and dead code. I can make a fast PR with a cleanup proposal.

2021-10-15 13:45 UTC, miguelmaso commented on kratos/spatial_containers/octree_binary.h
> +        if (geometry_type == GeometryData::KratosGeometryType::Kratos_Line2D2 || geometry_type == GeometryData::KratosGeometryType::Kratos_Line3D2) { // Object is a line
here #9219

2021-10-15 17:10 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        if (geometry_type == GeometryData::KratosGeometryType::Kratos_Line2D2 ||
Not sure if it makes sense to intersect a 2D geometry with a 3D one.

2021-10-15 17:10 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        else if(geometry_type == GeometryData::KratosGeometryType::Kratos_Triangle2D3 ||
Same comment.

2021-10-15 17:10 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        else if(geometry_type == GeometryData::KratosGeometryType::Kratos_Quadrilateral2D4 ||
Same comment.

2021-10-15 17:13 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
I just realized that creating and destroying geometries on the fly might be expensive. There is not an alternative way to do it right?

2021-10-15 17:14 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        const array_1d<double,3> vert2 = this->GetPoint(2);
```suggestion
        const array_1d<double,3>& r_vert0 = this->GetPoint(0);
        const array_1d<double,3>& r_vert1 = this->GetPoint(1);
        const array_1d<double,3>& r_vert2 = this->GetPoint(2);
```
Avoid the copies.

2021-10-15 17:17 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
Maybe you can use the `Plane` geometry which is much more lightweight.

2021-10-15 17:19 UTC, rubenzorrilla requested changes
This should be discussed in the @KratosMultiphysics/technical-committee. Maybe I'm wrong but as far as I remember, the `HasIntersection` intended behavior is to check intersection against another geometry of the same type. This would be a behavior change, which might affect very sensitive  algorithms.

2021-10-15 17:32 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
I think that should be a triangle. The function is accessing the vertices.

2021-10-19 08:17 UTC, RiccardoRossi commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
then this is VERY expensive :-(

2021-10-19 08:38 UTC, pooyan-dadvand commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
@KratosMultiphysics/technical-committee suggests that it would be better to move [this](https://github.com/KratosMultiphysics/Kratos/blob/5009962ec588c5ca48b2ac4b06a64a26bd087625/kratos/spatial_containers/octree_binary.h#L1343) implementation of the intersection to the intersection_utilities.h in core and changing the interface to take the 3 points instead of vector<Point> and use it here without generating auxiliary geometries.

2021-10-19 08:39 UTC, pooyan-dadvand commented on kratos/geometries/triangle_3d_3.h
> +            return LineTriangleOverlap(rThisGeometry);
Please call  [this function](https://github.com/KratosMultiphysics/Kratos/blob/5009962ec588c5ca48b2ac4b06a64a26bd087625/kratos/utilities/intersection_utilities.h#L100) instead of reimplementing it

2021-10-23 10:07 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +        if (geometry_type == GeometryData::KratosGeometryType::Kratos_Line2D2 ||
done, 2D geometry removed

2021-10-23 10:07 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +        else if(geometry_type == GeometryData::KratosGeometryType::Kratos_Triangle2D3 ||
done, 2D geometry removed

2021-10-23 10:07 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +        else if(geometry_type == GeometryData::KratosGeometryType::Kratos_Quadrilateral2D4 ||
done, 2D geometry removed

2021-10-23 10:08 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
done

2021-10-23 10:08 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +            return LineTriangleOverlap(rThisGeometry);
done

2021-10-23 10:15 UTC, miguelmaso commented on kratos/geometries/triangle_3d_3.h
> +            Triangle3D3 triangle_1 (rThisGeometry.pGetPoint(2), rThisGeometry.pGetPoint(3), rThisGeometry.pGetPoint(0));
Sorry, maybe it's a little bit confusing. In #9219 I've removed [this](https://github.com/KratosMultiphysics/Kratos/blob/5009962ec588c5ca48b2ac4b06a64a26bd087625/kratos/spatial_containers/octree_binary.h#L1343) implementation because it is duplicated code.
If you want, I can merge the branches to unify both PR.

2021-10-25 05:52 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        else return false;
```suggestion
        return result == 1 ? true : false;
```

2021-10-25 05:54 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        for (int i = 0; i < 3; i++)
```suggestion
        for (int i = 0; i < 3; ++i)
```
(very minor, most probably the compiler is changing it)

2021-10-25 05:56 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        if (ComputeIntervals(vp0, vp1, vp2, distances_2[0], distances_2[1], distances_2[2], a, b, c, x0, x1) == true)
```suggestion
        if (ComputeIntervals(vp0, vp1, vp2, distances_2[0], distances_2[1], distances_2[2], a, b, c, x0, x1))
```

2021-10-25 05:56 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        if (ComputeIntervals(up0, up1, up2, distances_1[0], distances_1[1], distances_1[2], d, e, f, y0, y1) == true)
```suggestion
        if (ComputeIntervals(up0, up1, up2, distances_1[0], distances_1[1], distances_1[2], d, e, f, y0, y1))

```

2021-10-25 05:58 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +        return true;
```suggestion
        return (isect1[1]<isect2[0] || isect2[1]<isect1[0]) ? false : true;
```

2021-10-25 06:00 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +		if (EdgeToTriangleEdgesCheck(i0, i1, this->GetPoint(2), this->GetPoint(0), rPoint1, rPoint2, rPoint3) == true) return true;
```suggestion
		if (EdgeToTriangleEdgesCheck(i0, i1, this->GetPoint(0), this->GetPoint(1), rPoint1, rPoint2, rPoint3)) return true;
		if (EdgeToTriangleEdgesCheck(i0, i1, this->GetPoint(1), this->GetPoint(2), rPoint1, rPoint2, rPoint3)) return true;
		if (EdgeToTriangleEdgesCheck(i0, i1, this->GetPoint(2), this->GetPoint(0), rPoint1, rPoint2, rPoint3)) return true;

```

2021-10-25 06:02 UTC, rubenzorrilla commented on kratos/geometries/triangle_3d_3.h
> +				if (e <= 0.0 && e >= f) return true;
```suggestion
                        if (f > 0.0) {
                            if (e >= 0.0 && e <= f) return true;
                        } else {
                            if (e <= 0.0 && e >= f) return true;
```
(minor indentation aesthetic)

2021-10-25 06:05 UTC, rubenzorrilla submitted a review, later dismissed
Aside of the minor suggestions I think this is ready to go in. I'd @loumalouomega 's suggested improvements in a separate PR.

2021-10-25 12:19 UTC, rubenzorrilla approved these changes

2021-10-25 21:34 UTC, merged