TPL Changes (Triangle/Tetgen)
KratosMultiphysics/Kratos pull request #9231
Opened 2021-10-19 10:15 UTC by roigcarlo

**📝 Description**
This PR wards some utilities from Kratos that depens on TPL libraries under their appropriate flags. 
I updated the install doc to also reflect those changes.

In detail what this does is:
- Changes the `DownloadLib.cmake` script so you can select the destination. It should be backwards compatible in case you use it in altar. Please @pooyan-dadvand take a quick look to confirm it does not break anything on your side.
- Added `USE_TRIANGLE_NONFREE_TPL`. If set to false (default, we can discuss about this) this will disable the following. As discussed in #9158 this changes should be temporal until we replace triangle in the core. @loumalouomega I have been very wary cutting files, if you see that less is needed please feel free to change ( specially the delaunator utilities part):
  - trigen_pfem_refine.h
  - trigen_pfem_refine_vms.h
  - trigen_pfem_refine_segment.h
  - trigen_glass_forming
  - trigen_droplet_refine.h
  - trigen_cdt.h 
  - class DelaunatorUtilities
  - class ExactMortarMapper
  - class ExactMortarSegmentationUtilities
  - class SimpleMortarMapperProcess
  - class CadTessellationModeler
  - Associated tests.
- Added additional flags to controls the way tetgen is obtained. In this order it checks for: 
  - `USE_TETGEN_NON_FREE_TPL_PATH=` for a local path in your system
  - `USE_TETGEN_NON_FREE_TPL_URL=` for a copy on the internet. This is tested with the official tetgen packages.
  - If all the above fails / is not present and `USE_TETGEN_NON_FREE_TPL` is set to `ON` it will try to find a installed copy in the system.

I flag this a draft as I understand there will be changes.
@maceligueta I tested with tetgen 1.5 and 1.6 and the meshing does not work do the changes in the `deinitialize()` function in tetgen. Since I have no available copy of 1.4 I have been unable to fully test it. It would be of  if you can take a look or give me a source for tetgen 1.4.

**🆕 Changelog**
- Added additional TPL flags to Kratos
- Warded code that makes use of TPL

2021-10-19 10:36 UTC, roigcarlo commented on CMakeLists.txt
> +    add_definitions( -DUSE_TETGEN_NONFREE_TPL )
Btw, I am not aware of the use of `TETGEN143` and `TETLIBRARY`. They do not seem to be used inside Kratos or Tetgen.

Can someone clarify what they are / why are needed?

2021-10-19 12:21 UTC, loumalouomega reviewed
For me is OK

2021-10-19 12:41 UTC, armingeiser commented on INSTALL.md
> +[Triangle](http://www.cs.cmu.edu/~quake/triangle.html) is a library for delaunay triangulation. We provide some utilities in Kratos that depend on this library. The flags related with Triangl are the
```suggestion
[Triangle](http://www.cs.cmu.edu/~quake/triangle.html) is a library for delaunay triangulation. We provide some utilities in Kratos that depend on this library. The flags related with Triangle are the following:
```

2021-10-19 12:41 UTC, armingeiser commented on INSTALL.md
> +Please note that **Kratos will NEVER DISTRIBUTE, RELEASE or COMPILE** with these libraries unless explicitly specified, and the use of these libraries may add aditinal restrictions on top of BSD.
```suggestion
Please note that **Kratos will NEVER DISTRIBUTE, RELEASE or COMPILE** with these libraries unless explicitly specified, and the use of these libraries may add additional restrictions on top of BSD.
```

2021-10-19 12:41 UTC, armingeiser commented on INSTALL.md
> +(Tetgen)[http://wias-berlin.de/software/tetgen/] is a library to generate tethrahedal mehses. We provide some utilities that can make use of tetgen. The flags related with Tetgen are the following:
```suggestion
(Tetgen)[http://wias-berlin.de/software/tetgen/] is a library to generate tetrahedral meshes. We provide some utilities that can make use of tetgen. The flags related with Tetgen are the following:
```

2021-10-21 12:19 UTC, loumalouomega requested changes
Blocking until change in contact is reverted

2021-10-21 12:19 UTC, loumalouomega commented on applications/ContactStructuralMechanicsApplication/CMakeLists.txt
> +if(${USE_TRIANGLE_NONFREE_TPL} MATCHES ON )
The contact does not require Triangle, why do you do this?

2021-10-21 12:20 UTC, loumalouomega commented on applications/ContactStructuralMechanicsApplication/CMakeLists.txt
> +if(${USE_TRIANGLE_NONFREE_TPL} MATCHES ON )
It is optional and not used by default

2021-10-21 12:55 UTC, roigcarlo commented on applications/ContactStructuralMechanicsApplication/CMakeLists.txt
> +if(${USE_TRIANGLE_NONFREE_TPL} MATCHES ON )
Most of the application needs processes from the core that include triangle (to be honest, mainly the mortar one) I tried disabling one by one but then the app becomes empty :S

2021-10-21 12:57 UTC, loumalouomega commented on applications/ContactStructuralMechanicsApplication/CMakeLists.txt
> +if(${USE_TRIANGLE_NONFREE_TPL} MATCHES ON )
You should add the preprocessor machos to the includes and calls of the library, and add an error otherwise, none of the tests of the contact uses triangle, do you want me to fix this?

2021-10-21 15:34 UTC, loumalouomega submitted a review, later dismissed
I release my block

2021-10-21 20:01 UTC, loumalouomega commented
@roigcarlo it fails in Windows, and it is related with the CAD modeler (@tteschemacher once this PR is merged I will open a new one with an alternative delaunator, and we will activate again your modeller)

2021-10-25 08:12 UTC, roigcarlo commented on INSTALL.md
> +#### Triangle
Duplicated:

```suggestion
```

2021-10-25 08:35 UTC, loumalouomega requested changes
We should merge #9254 first

2021-10-26 15:59 UTC, loumalouomega submitted a review, later dismissed
Okay now

2021-11-02 15:32 UTC, maceligueta commented
Any news on this matter? The current status was very helpful to work across different computers, as it was quite easy to compile all the libraries both in Linux and Windows. It would be great if we could merge asap.

2021-11-02 15:35 UTC, roigcarlo commented
Ok, we can merge if you need it.

2021-11-02 15:35 UTC, maceligueta approved these changes

2021-11-02 15:35 UTC, merged