Bug in ShapeFunctionsIntegrationPointsGradients for line elements
KratosMultiphysics/Kratos pull request #9242
Opened 2021-10-20 18:43 UTC by Vahid-Galavi

**📝 Description**
Bug in ShapeFunctionsIntegrationPointsGradients. Related to #9144.

2021-10-21 07:20 UTC, miguelmaso reviewed
Thanks! Can you merge or test with #9143 to see if it passes the test?

2021-10-22 09:25 UTC, rubenzorrilla commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
```suggestion
            if(rResult[pnt].size1() != (*this).size() ||  rResult[pnt].size2() != this->LocalSpaceDimension())
                rResult[pnt].resize( (*this).size(), this->LocalSpaceDimension(), false );
```
I think that changing `WorkingSpaceDimension` by `size` in the array size1 check is correct. However, as far as I understand, size2 must be the local size. If I'm not wrong changing it to working space dimension would work for "solid"-type geometries but for "beam or shell"-type ones we would be allocating more memory than required, something that might turn into a mismatch in the subsequent array multiplications.

2021-10-22 09:40 UTC, Vahid-Galavi commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
I think the result of DN_Dx should be in working space. We already have DN_De which is the gradient of shape functions in local space.

Here this is calculated: DN_Dx = DN_De x JacobianInverse 

In which DN_De has size of (geom.size x LocalSpaceDimension) and JacobianInverse has (LocalSpaceDimension x workingSpace). Therefore the result (DN_Dx) will have the size of (geom.size x workingSpace)

2021-10-22 10:57 UTC, miguelmaso commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
I agree with @Vahid-Galavi

2021-10-22 11:05 UTC, rubenzorrilla commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
Maybe I'm missing something but wouldn't this mean that for a line 2D you'll have a gradient X and gradient Y as working space dimension is 2.

2021-10-22 14:20 UTC, miguelmaso commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
For a line 2D, in DN_De I expect one derivative, and in DN_Dx I'm expecting two derivatives (X and Y).
Finally, if the line is in a 3D space, then I expect three derivatives in DN_Dx.

2021-10-22 18:46 UTC, Vahid-Galavi commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
> Maybe I'm missing something but wouldn't this mean that for a line 2D you'll have a gradient X and gradient Y as working space dimension is 2.

Yes, then the results will be DN_Dx and DN_Dy.

2021-10-22 18:46 UTC, Vahid-Galavi commented on kratos/geometries/geometry.h
> +                rResult[pnt].resize( (*this).size(), this->WorkingSpaceDimension(), false );
> For a line 2D, in DN_De I expect one derivative, and in DN_Dx I'm expecting two derivatives (X and Y). Finally, if the line is in a 3D space, then I expect three derivatives in DN_Dx.

Yes, exactly.

2021-10-26 08:45 UTC, RiccardoRossi requested changes
blocking as the proposed solution only hides the problem

2021-10-29 11:54 UTC, closed without merging