Shell q4thk initial strain test
KratosMultiphysics/Kratos pull request #9337
Opened 2021-11-12 20:44 UTC by clazaro

**📝 Description**
Adding a test of initial strains in a Q4 thick shell element.

**🆕 Changelog**
Added test files into StructuralMechanicsApplication/tests/InitialStateElasticity/
Added the corresponding class in structural_mechanics_test_factory.py

I didn't add the test into test_StructuralMechanicsApplication.py as I wasn't sure if it has to be included into the smallSuite or the nightSuite.

2021-11-12 20:45 UTC, clazaro commented
Apologies for the previous failed (closed) PRs...
Now I got it!

2021-11-12 22:17 UTC, loumalouomega requested changes
Thanks, add to test_StructuralMechanicsApplication.py, otherwise will not be computed in CI

2021-11-12 22:17 UTC, loumalouomega commented on applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py
> +class InitialStrainShellQ4ThickTest(StructuralMechanicsTestFactory):
I think the test is still missing in test_StructuralMechanicsApplication.py (maybe is added automatically, last I checked it wasn't)

2021-11-13 08:29 UTC, clazaro commented
@loumalouomega, added

2021-11-13 09:28 UTC, loumalouomega approved these changes
Okidoki

2021-11-14 20:21 UTC, philbucher reviewed
minor but important comment

2021-11-14 20:21 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/InitialStateElasticity/initial_strain_shell_Q4_thick_test_parameters.json
> +        "_print_output_process" : [{
the underscore syntax is not reliable (in terms of it works in some cases and not in others) and is from a time before we could have comments in the json

Hence I would comment this block. Commenting works same as in C++

What happens here is that this process still gets executed and hence renders the test useless as it constantly writes new reference results

2021-11-14 20:21 UTC, philbucher commented on applications/StructuralMechanicsApplication/tests/InitialStateElasticity/initial_strain_shell_Q4_thick_test_parameters.json
> +    "_output_processes" : {
same

2021-11-15 09:02 UTC, philbucher approved these changes

2021-11-15 09:02 UTC, clazaro commented
Done

2021-11-17 12:39 UTC, merged