[TopOpt] First draft for reactivation
KratosMultiphysics/Kratos pull request #9460
Opened 2021-12-16 19:56 UTC by PhiHo-eng

**Topology Optimization**
The topology optimization application in Kratos has been reactivated, linked with the structural mechanics application and extended. [I carried this work under the supervision of @e-dub at unibz]

**Changes in the new Topology Optimization Application**
The following has been done:
- Change solving application from SolidMechanicsApplication to StructuralMechanicsApplication
- Update with Pybind11
- Density filtering
- Heaviside projection in the density filter
- Update of the filtering function (now undependent of the Young's modulus)
- MMA and GCMMA as optimization algorithms (original code in external libraries)
- Reactivation of the smoothing function and the STL file as product of the post processing

2021-12-17 08:52 UTC, rubenzorrilla requested changes
I've quickly browsed the PR and there are some changes in the `scripts` folder that shouldn't be there. Besides. There is a `run_TopOpt.py` script in the repo main folder that must be there neither.

2021-12-17 09:14 UTC, armingeiser requested changes
Thanks for reviving the topology optimization app. Before reviewing in detail i have a few general comments:

- please remove all the examples from this PR:
   - there is an "Examples" repo made for storing those
   - instead create one small test case (e.g. MBB cantilever) with <<1000 nodes. 
   - ideally you set it up as a test case that compares the resulting topology (e.g. comparing the density distribution after the optimization with some reference values. 
- as Ruben has said, there are some files changed/added in folders outside of the application, please revert those changes. 
- Minor cosmetics: ev. you can add a small gif of a topology optimization and a convergence graph to the PR description

Once these things are done, the number of changed files (currently 97) should go down significantly, making the review easier.

2021-12-17 09:14 UTC, armingeiser commented on applications/ShapeOptimizationApplication/custom_python/add_custom_utilities_to_python.cpp
> -#include "custom_utilities/damping/direction_damping_utilities.h"
There should be no changes made to ShapeOptimizationApplication, i guess something went wrong when you merged.

2021-12-17 09:14 UTC, armingeiser commented on applications/TopologyOptimizationApplication/custom_elements/comparison_utilities.h
> +	//in principal stresses:
please clean such commented code parts

2021-12-17 09:14 UTC, armingeiser commented on applications/TopologyOptimizationApplication/examples/00_Small_Cantilever_Hexahedral_Mini/README.md
> +
This example (the mdpa) is too large for the main repo, there is a dedicated Examples repository where such large "use-case" examples should be created.

2021-12-17 09:14 UTC, armingeiser commented on applications/TopologyOptimizationApplication/examples/00_Small_Cantilever_Hexahedral_Mini/run_TopOpt.py
> +import OptimizationParameters as opt_parameters
i suggest to store the opt settings also as a json file, like it is done in the rest of Kratos

2021-12-17 09:14 UTC, armingeiser commented on applications/TopologyOptimizationApplication/examples/00_Small_Cantilever_Hexahedral_Mini/run_TopOpt_PostProcessing.py
> +IOUtilities().WriteSurfaceAsSTLFile("smoothed_design_00_Cantilever.stl",extracted_surface_model_part)
the resulting stl file seems to be commited, should definitely not be there.

2021-12-17 11:20 UTC, philbucher requested changes
**Since this is a very large PR I strongly recommend the following:**
Split up the PR into smaller ones, this way you will get a better review and also it will get merged much faster!

First I would create an empty application with the [ApplicationGenerator](https://github.com/KratosMultiphysics/Kratos/tree/master/kratos/python_scripts/application_generator) (=> `python3 createApplication.py TopologyOptimizationApplication`) and add it to the repo in an initial PR 
(then you will also get the latest updates which were done to e.g. `CMakeLists.txt`)
=> this way it can get merged super fast and you will already profit that if sth gets changed in master, your app will also receive the changes

Then afterwards I recommend adding your implementation in smaller chunks so that we can review it easier. Ofc this is a little more effort for you at first, but in the long run this will be faster AND you will get a more detailed review from us with suggestions on how to improve the code

2021-12-21 12:42 UTC, armingeiser commented on applications/TopologyOptimizationApplication/custom_elements/solid_mechanics_math_utilities.h
> +#if !defined(KRATOS_SOLID_MECHANICS_MATH_UTILITIES_H_INCLUDED)
Do you still need this? Please remove all functions /files that are not needed.

2021-12-21 12:56 UTC, armingeiser commented on applications/TopologyOptimizationApplication/tests/test.txt
> +
leftover

2022-03-06 14:50 UTC, closed without merging