Adding sparse matrix transposes
KratosMultiphysics/Kratos pull request #9701
Opened 2022-02-23 11:35 UTC by RiccardoRossi

**📝 Description**
adding matrix transpose

Please mark the PR with appropriate tags: 
feature

**🆕 Changelog**
adding the possibility to generate the transpose of a matrix

2022-02-23 11:57 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +		bool move_to_backend=false; //important!
Tabs!!
```suggestion
        bool move_to_backend=false; //important!
```

2022-02-23 11:57 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +		auto offdiag_global_index2 = rA.GetOffDiagonalIndex2DataInGlobalNumbering();
```suggestion
        auto offdiag_global_index2 = rA.GetOffDiagonalIndex2DataInGlobalNumbering();
```
Tabs!

2022-02-23 11:57 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +		return pAt;
```suggestion
        return pAt;
```
tabs!

2022-02-23 11:57 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +	}
```suggestion
    }
```
tabs

2022-02-23 11:58 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
>  		return pAconverted;
```suggestion
        return pAconverted;
```
tabs!

2022-02-23 11:58 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +	}
```suggestion
    }	
```
more tabs!

2022-02-23 11:59 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +	static typename DistributedCsrMatrix<TDataType, TIndexType>::Pointer Transpose(
```suggestion
    static typename DistributedCsrMatrix<TDataType, TIndexType>::Pointer Transpose(
```
more tabs

2022-02-23 11:59 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +			const DistributedCsrMatrix<TDataType, TIndexType>& rA
```suggestion
        const DistributedCsrMatrix<TDataType, TIndexType>& rA
```
tabs!

2022-02-23 11:59 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +			)
```suggestion
        )	
```
More tabs!

2022-02-23 12:00 UTC, loumalouomega commented on kratos/utilities/amgcl_csr_conversion_utilities.h
> +	static typename CsrMatrix<TDataType, TIndexType>::Pointer Transpose(
```suggestion
    static typename CsrMatrix<TDataType, TIndexType>::Pointer Transpose(
```

2022-02-23 12:00 UTC, loumalouomega commented on kratos/utilities/amgcl_csr_conversion_utilities.h
> +			CsrMatrix<TDataType, TIndexType>& rA
```suggestion
        CsrMatrix<TDataType, TIndexType>& rA
```

2022-02-23 12:00 UTC, loumalouomega commented on kratos/utilities/amgcl_csr_conversion_utilities.h
> +			)
```suggestion
        )	
```

2022-02-23 12:02 UTC, loumalouomega requested changes
Missing const?

2022-02-23 12:02 UTC, loumalouomega commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +        bool move_to_backend=false; //important!
Any const here?

2022-02-23 12:02 UTC, loumalouomega commented on kratos/utilities/amgcl_csr_conversion_utilities.h
> +        auto pAamgcl = ConvertToAmgcl<TDataType,TIndexType>(rA);
const?

2022-02-23 12:02 UTC, loumalouomega commented on kratos/mpi/tests/test_distributed_sparse_matrices.py
> +
```suggestion
```

2022-02-23 14:41 UTC, RiccardoRossi commented on kratos/mpi/utilities/amgcl_distributed_csr_conversion_utilities.h
> +        bool move_to_backend=false; //important!
it makes no harm so i'll add it

2022-02-23 14:44 UTC, RiccardoRossi commented on kratos/mpi/tests/test_distributed_sparse_matrices.py
> +
done

2022-02-23 14:50 UTC, loumalouomega approved these changes

2022-02-25 11:53 UTC, merged

2022-02-25 12:20 UTC, philbucher commented on kratos/tests/test_sparse_matrices.py
> +            self.assertEqual(y[i], y2[i], 1e-14)
there is also `assertVectorAlmostEqual` :)

https://github.com/KratosMultiphysics/Kratos/blob/6d6d5b943ded5c524753fa6807633312665a3e50/kratos/python_scripts/KratosUnittest.py#L76