[Core] Fixing uninitialized Dx in block builder and solver
KratosMultiphysics/Kratos pull request #9728
Opened 2022-02-28 20:40 UTC by pooyan-dadvand

**📝 Description**
The Dx was uninitialized in `SystemSolveWithPhysics` and valgrind correctly detected it.

**🆕 Changelog**
Move the SetToZero call outside of the if to include all branches

2022-03-01 09:11 UTC, loumalouomega commented on kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h
> +        TSparseSpace::SetToZero(Dx);
```suggestion
        // Initialize the solution vector
        TSparseSpace::SetToZero(Dx);

```

2022-03-01 09:11 UTC, loumalouomega approved these changes, later dismissed

2022-03-01 11:46 UTC, RiccardoRossi requested changes
the change should not be done here, but rather on line 

447

https://github.com/KratosMultiphysics/Kratos/pull/9728/files#diff-668533ef54116b8368300eb04251244aa7d2f8e668bb97653e64f4582b95342dR447

otherwise you would be resetting it twice (and once after the application of Dirichlet) in the case in which you have no MPCs

2022-03-01 15:43 UTC, pooyan-dadvand commented
> the change should not be done here, but rather on line
> 
> 447
> 
> https://github.com/KratosMultiphysics/Kratos/pull/9728/files#diff-668533ef54116b8368300eb04251244aa7d2f8e668bb97653e64f4582b95342dR447
> 
> otherwise you would be resetting it twice (and once after the application of Dirichlet) in the case in which you have no MPCs

You are right! Changed in the last commit

2022-03-02 11:18 UTC, RiccardoRossi approved these changes

2022-03-02 13:48 UTC, merged