Improving sp rom finite strain cl
KratosMultiphysics/Kratos pull request #9731
Opened 2022-03-01 13:16 UTC by AlejandroCornejo

**📝 Description**
In this PR I'm generalizing the parallel rule of mixtures and the serial/parallel rule of mixtures to be used consistently in finite strains, together with the TL or the UL elements.

Minor improvements of the hyperelastic laws.

2022-03-01 13:22 UTC, loumalouomega requested changes
Some comments

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/hyper_elastic_isotropic_kirchhoff_3d.cpp
> +    if(r_flags.IsNot( ConstitutiveLaw::USE_ELEMENT_PROVIDED_STRAIN )) {
uyuyuyy

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/hyper_elastic_isotropic_kirchhoff_3d.cpp
> +    Matrix stress_matrix(3, 3);
Bounded?

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// All the strains must be the same, therefore we can just simply compute the strain in the first layer
Tabs (affects all tabs)
```suggestion
    // All the strains must be the same, therefore we can just simply compute the strain in the first layer
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// Get Values to compute the constitutive law:
```suggestion
    // Get Values to compute the constitutive law:
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// Get Values to compute the constitutive law:
```suggestion
    // Get Values to compute the constitutive law:
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// All the strains must be the same, therefore we can just simply compute the strain in the first layer
```suggestion
    // All the strains must be the same, therefore we can just simply compute the strain in the first layer
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// Get Values to compute the constitutive law:
```suggestion
    // Get Values to compute the constitutive law:
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// All the strains must be the same, therefore we can just simply compute the strain in the first layer
```suggestion
    // All the strains must be the same, therefore we can just simply compute the strain in the first layer
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// Get Values to compute the constitutive law:
```suggestion
    // Get Values to compute the constitutive law:
```

2022-03-01 13:22 UTC, loumalouomega commented on applications/ConstitutiveLawsApplication/custom_constitutive/rule_of_mixtures_law.cpp
> +	// All the strains must be the same, therefore we can just simply compute the strain in the first layer
```suggestion
    // All the strains must be the same, therefore we can just simply compute the strain in the first layer
```

2022-03-01 13:32 UTC, AlejandroCornejo commented on applications/ConstitutiveLawsApplication/custom_constitutive/hyper_elastic_isotropic_kirchhoff_3d.cpp
> +    Matrix stress_matrix(3, 3);
unfortunately it cannot be because of the `ContraVariantPushForward` method...

2022-03-02 07:45 UTC, AlejandroCornejo commented
@SergioJimenezReyes can you approve? :) tests are passing

2022-03-02 08:40 UTC, loumalouomega approved these changes

2022-03-02 08:40 UTC, merged